go/common/cbor/codec.go

In order for us to get a better handle on what the maximum message size
limit should be set to, it is probably the easiest to just add metrics
for it, and run some realistic workloads.
Part of #2213.

go/common/cbor: Add `oasis_codec_size` metrics

---

client/src/rpc/client.rs
go/grpc/enclaverpc/enclaverpc.proto
go/keymanager/client/client.go
go/oasis-node/cmd/node/node.go
go/storage/client/client.go
go/worker/common/enclaverpc/enclaverpc.go
go/worker/keymanager/grpc.go
go/worker/keymanager/init.go
go/worker/keymanager/policy.go
go/worker/keymanager/worker.go
runtime/src/dispatcher.rs
runtime/src/rpc/demux.rs
runtime/src/rpc/dispatcher.rs
runtime/src/rpc/types.rs

Add access control to the key manager

---

.buildkite/pipeline.yml
.buildkite/rust/cargo_audit.sh
Cargo.lock
client/Cargo.toml
runtime/Cargo.toml

ci: add cargo audit step

---

go/staking/tests/tester.go
go/tendermint/apps/staking/staking.go

go/staking: Fix incorrect delegation share dilution

---

go/storage/client/client.go

It is possible to do batch verification of signatures, but it would be
rather complicated while wanting to also wait for F+1 successes.  As
network delay is likely to dominate here, explicitly note that signature
verifications will be done serially.
Basically, #1821 outweighs doing batch verification here.  I wish I figured this out before writing a branch with batch verification support, but so it goes.

go/storage/client: Cleanups, clarify a comment

---

go/common/node/address.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/validator.go
go/worker/common/worker.go

I think it will be easier to review these separately, so I extracted them from my #2300 PR.

Miscellaneous improvements

---

go/go.mod
go/go.sum

go: Update tendermint to 0.32.7

---

go/scheduler/api/api.go
go/staking/api/api.go
go/staking/api/rewards.go
go/tendermint/apps/scheduler/scheduler.go
go/tendermint/apps/staking/genesis.go
go/tendermint/apps/staking/staking.go
go/tendermint/apps/staking/state/state.go
go/tendermint/apps/staking/state/state_test.go

It was stated in the incentive design that we would reward accounts for having escrowed stake.
```
hook onEpochChange():
for a in accounts:
a.escrowed += amountEligibleStake(a) * rewardRate
butLessOverTime()
```
blocks #2265 
depends #2303

Distribute staking rewards

---

go/oasis-node/cmd/debug/byzantine/tendermint.go
go/roothash/api/api.go
go/roothash/tendermint/tendermint.go
go/tendermint/apps/roothash/query.go
go/tendermint/apps/roothash/roothash.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go
go/worker/common/worker.go
go/worker/merge/committee/node.go
go/worker/txnscheduler/init.go

https://github.com/oasislabs/oasis-core/pull/2309#discussion_r342196981
use RoundTimeout from genesis on all places

go/roothash: use RoundTimeout from genesis

---

docker/testing/Dockerfile

https://github.com/xd009642/tarpaulin/issues/190 appears to be fixed in 0.9.1

docker: update tarpaulin version

---

go/staking/api/api.go
go/staking/tests/debug_stake.go
go/staking/tests/tester.go
go/tendermint/apps/staking/transactions.go

go/staking: Add minimum delegation amount

---

go/beacon/api/api.go
go/consensus/genesis/genesis.go
go/consensus/tendermint/tendermint.go
go/consensus/tendermint/tests/genesis_testnode.go
go/epochtime/api/api.go
go/genesis/api/api.go
go/keymanager/api/api.go
go/oasis-node/cmd/genesis/genesis.go
go/registry/api/api.go
go/roothash/api/api.go
go/scheduler/api/api.go
go/staking/api/api.go
go/worker/txnscheduler/algorithm/batching/batching.go

Add sanity checks for the genesis state

---

go/oasis-node/cmd/node/node.go

go/oasis-node: Fix segfault in Cleanup

---

go/consensus/tendermint/apps/scheduler/genesis.go
go/consensus/tendermint/apps/scheduler/query.go
go/consensus/tendermint/scheduler/scheduler.go
go/oasis-node/node_test.go
go/scheduler/api/api.go

scheduler: Bugfix and additional query

---

go/oasis-node/cmd/registry/entity/entity.go

I modeled this as closely as possible to the `stake` subcommand but I hacked it together quickly cause I found this was a pain point for joining the testnet. See the section here: https://github.com/oasislabs/docs/blob/9428add3df027ba1ab3d7a96013eed895a20fa8d/src/operators/joining-the-testnet.md#registering-you-entity

Write signed registry txs to disk

---

README.md

I just triggered the first fetch of the documentation, so it's still updating

readme: add godoc badge

---

go/consensus/tendermint/apps/registry/state/state.go

go/consensus/tendermint/apps/registry: Remove node status

---

go/consensus/tendermint/abci/gas.go
go/consensus/tendermint/abci/gas_test.go
go/consensus/tendermint/apps/registry/registry.go
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/staking/transactions.go
go/keymanager/client/client.go
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/debug/byzantine/registry.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/entity.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/gas_fees.go
go/oasis-test-runner/scenario/e2e/roothash_messages.go
go/registry/api/api.go
go/registry/tests/tester.go
go/staking/api/api.go
go/worker/registration/worker.go

Based on #2399 
Fixes #2378 
TODO

Registry gas fees

---

docs/bigint.md
docs/consensus/staking.md
docs/consensus/transactions.md
docs/crypto.md
docs/encoding.md
go/.codecov.yml
go/Makefile
go/common/crypto/signature/signer.go
go/staking/gen_vectors/main.go
go/staking/gen_vectors/testvectors.go

staking: Basic docs and message test vectors

---

.buildkite/pipeline.yml
go/go.mod
go/go.sum

go: Bump cbor to v1.3.2

---

go/consensus/tendermint/apps/registry/state/state.go
go/consensus/tendermint/apps/registry/transactions.go
go/registry/api/api.go
go/registry/tests/tester.go

go/registry: Optimize check for duplicate keys

---

go/consensus/tendermint/apps/staking/transactions.go
go/staking/api/api.go

go/staking: Add params for disabling transfers and delegation

---

.github/workflows/release.yml
.gitignore
.goreleaser.yml
Makefile
common.mk
go/Makefile
go/common/version/version.go
go/oasis-node/cmd/root.go
go/storage/mkvs/urkel/interop/cmd/root.go

Automate build and release process for Oasis Core

---

common.mk

Compute the next version based on the latest tag of the `origin` remote instead of relying on the local `master` branch being the source-of-truth.

Makefile: Make automatic version computation more robust

---

common.mk

Link to the appropriate Change Log for the release and to Operator Docs.

Makefile: Update GitHub release's text

---

.changelog/2537.trivial.md
go/worker/keymanager/worker.go
keymanager-runtime/src/policy.rs
runtime/src/common/crypto/signature.rs
runtime/src/common/sgx/egetkey.rs
runtime/src/common/sgx/mod.rs
runtime/src/common/sgx/seal.rs

Generally useful things from #2534.

runtime: Extract common sealing code

---

.changelog/2558.bugfix.md
.changelog/2559.trivial.md
.github/workflows/ci.yml
Makefile
common.mk
go/consensus/tendermint/tendermint.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/oasis.go

Backports changes from #2558 and #2559.

Backports for 20.1.1 release

---

.changelog/2457.doc.md
.changelog/2565.doc.md
Makefile
docs/release-process.md
docs/versioning.md

Document Oasis Core's versioning scheme and release process

---

.changelog/2513.feature.md
go/common/namespace.go
go/consensus/tendermint/apps/registry/transactions.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/node_test.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/api/api.go
go/registry/api/runtime.go
go/registry/tests/tester.go

closes #2513
no additional info

go registry: for runtimes to whitelist node operators

---

.changelog/2593.trivial.md
Cargo.lock
client/Cargo.toml
client/src/lib.rs
client/src/transaction/api/storage.rs

Needed by `genesis` in https://github.com/oasislabs/oasis-runtime

client/src/transaction: add storage Apply gRPC method

---

.changelog/2595.trivial.md
.changelog/README.md
towncrier.toml

Discussions have shown that some changes that are primarily of interest to project's developers and maintainers are also Change Log worthy, so we should add a section dedicated to them.

changelog: Introduce "Internal changes" Change Log section

---

.changelog/2563.feature.md
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/oasis/cli/registry.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/registry_cli.go

closes #2563
no additional info. see issue

 go oasis-node: runtime node admission policy CLI 

---

.changelog/2624.breaking.md
go/consensus/tendermint/apps/scheduler/scheduler.go
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/proposing_rewards.go
go/consensus/tendermint/apps/staking/signing_rewards.go
go/genesis/genesis_test.go
go/oasis-node/cmd/genesis/genesis.go
go/scheduler/api/api.go
go/staking/api/api.go
go/staking/api/api_test.go
go/staking/api/sanity_check.go
go/staking/tests/debug/debug_stake.go
tests/fixture-data/gas-fees-runtimes/staking-genesis.json
tests/fixture-data/gas-fees/staking-genesis.json

closes #2624
no additional info

Rewards and fees consensus parameters

---

.changelog/2516.feature.md
go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/keymanager/transactions.go
go/keymanager/api/api.go
go/keymanager/api/policy_sgx.go
go/oasis-node/cmd/keymanager/keymanager.go
go/registry/api/api.go

go/keymanager: Support policy updates

---

.changelog/2588.breaking.md
go/common/crypto/signature/signature.go
go/common/node/address.go
go/common/node/address_test.go
go/genesis/genesis_test.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/cmd/stake/account.go
go/oasis-test-runner/oasis/cli/cli.go
go/oasis-test-runner/oasis/cli/registry.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/oasis-test-runner/scenario/e2e/stake_cli.go

Use base64-encoded IDs/public keys to unify CLI experience

---

go/consensus/tendermint/seed.go
go/consensus/tendermint/tendermint.go

The Tendermint genesis one is encountered in a dry run.
The seed one is speculative.

additional genesis signature check disablement

---

.changelog/1865.bugfix.md
go/storage/api/api.go
go/storage/api/root_cache.go
go/storage/client/client.go
go/storage/database/database.go
go/storage/mkvs/urkel/db/api/api.go

go/storage/client: Retry storage ops on specific errors

---

.changelog/2664.bugfix.md
.changelog/2667.trivial.md
go/consensus/tendermint/db/badger/badger.go
go/consensus/tendermint/db/tests/tester.go

when we run off the end of a range iteration
but now I need to try rewriting the whole badger iterator to make sure I understand it

go tendermint badger: don't scan whole keyspace

---

.changelog/2607.feature.md
go/common/persistent/persistent.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/tendermint.go
go/control/api/api.go
go/control/api/grpc.go
go/control/control.go
go/oasis-node/cmd/control/control.go
go/oasis-node/cmd/debug/byzantine/tendermint.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/log.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/oasis-test-runner/scenario/e2e/upgrade_cancel.go
go/oasis-test-runner/test-runner.go
go/upgrade/api/api.go
go/upgrade/dummy.go
go/upgrade/migrations/dummy.go
go/upgrade/migrations/migrations.go
go/upgrade/upgrade.go
go/worker/registration/worker.go

Fixes #2547 
Closes #2465 
Closes #2466 
Closes #2467

Upgrade mechanism

---

.buildkite/longtests.pipeline.yml
go/Makefile

Forgot to change this in #2709.

ci: Fix txsource test name

---

.buildkite/code.pipeline.yml
.buildkite/scripts/merge_coverage.sh
.buildkite/scripts/test_e2e.sh
.changelog/2644.internal.md

ci: merge e2e coverage per job

---

.changelog/2731.trivial.md
go/consensus/tendermint/apps/keymanager/transactions.go
go/keymanager/api/api.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/keymanager.go

it took me a few seconds to figure out why grepping for similar tokens wasn't working

Rename manger to manager

---

.changelog/2753.breaking.md
go/common/errors/errors.go
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/apps/staking/transactions_test.go
go/staking/api/api.go

We expect not to need this feature.

Remove locked accounts

---

.changelog/2760.internal.md
go/consensus/tendermint/apps/supplementarysanity/checks.go
go/staking/api/sanity_check.go

go/staking/api: Add more details to sanity check errors

---

.changelog/2773.feature.md
go/oasis-node/cmd/debug/txsource/workload/delegation.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/debug/txsource/workload/transfer.go
go/oasis-node/cmd/debug/txsource/workload/workload.go

- adds staking.Burn transactions to the transfer workload
- extracts repeated "estimateGas, fund caller, sign tx, submit tx" action into a helper function

transfer workload include burns

---

.changelog/2776.internal.md
go/Makefile

Allow running Go unit tests and node tests independently

---

.changelog/2766.feature.md
go/consensus/tendermint/apps/staking/query.go
go/consensus/tendermint/staking/staking.go
go/oasis-node/cmd/debug/txsource/workload/commission.go
go/oasis-node/cmd/debug/txsource/workload/workload.go
go/oasis-test-runner/scenario/e2e/txsource.go
go/staking/api/api.go
go/staking/api/commission.go
go/staking/api/grpc.go
tests/fixture-data/txsource/staking-genesis.json

Changing commission schedule workload, part of: #2506
TODO:

go/txsource: commission schedule amendments workload

---

.buildkite/code.pipeline.yml
.changelog/2777.breaking.md
go/consensus/tendermint/apps/staking/genesis.go
go/consensus/tendermint/apps/supplementarysanity/checks.go
go/genesis/genesis_test.go
go/oasis-node/cmd/stake/stake.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/dump_restore.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/halt_restore.go
go/oasis-test-runner/test-runner.go
go/staking/api/api.go
go/staking/api/sanity_check.go
tests/fixture-data/gas-fees/staking-genesis.json

Also adds a dump-restore version of the gas-fees test.

go/staking: include LastBlockFees in genesis

---

.changelog/2761.breaking.md
go/consensus/genesis/genesis.go
go/consensus/tendermint/abci/gas.go
go/consensus/tendermint/abci/gas_test.go
go/consensus/tendermint/abci/mux.go
go/oasis-node/cmd/debug/txsource/workload/oversized.go
go/oasis-node/cmd/debug/txsource/workload/parallel.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go

go/consensus: Introduce gas cost based on tx size

---

.changelog/2798.trivial.md
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go

We know how much should be disbursed in this test. This adds a check for that known amount.

e2e: check actual fee disbursement

---

.changelog/2815.internal.1.md
.changelog/2815.internal.2.md
go/consensus/tendermint/tendermint.go
go/go.mod
go/go.sum
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/txsource.go

Uses: https://github.com/oasislabs/tendermint/tree/v0.32.8-oasis3

go/consensus/tendermint: support DebugUnsafeReplayRecoverCorruptedWAL

---

.github/workflows/ci-reproducibility.yml

Fix ci-reproducibility workflow

---

.changelog/2830.internal.md
tests/fixture-data/txsource/staking-genesis.json

Forgot adding it in: https://github.com/oasislabs/oasis-core/pull/2815

tests/fixture/txsources: add initial balance for validator-3

---

.changelog/2849.internal.md
go/oasis-test-runner/scenario/e2e/txsource.go

I remembered we don't actually change the seed :grin:

go/oasis-test-runner/txsource: Generate a new random seed on each run

---

.changelog/2866.internal.md
go/consensus/tendermint/tendermint.go
go/oasis-net-runner/fixtures/fixtures.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/sentry.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/gas_fees_runtimes.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/identity_cli.go
go/oasis-test-runner/scenario/e2e/txsource.go
go/oasis-test-runner/scenario/remotesigner/basic.go
go/oasis-test-runner/scenario/scenario.go
tests/fixture-data/net-runner/default.json

oasis-test-runner: Test consensus pruning

---

.changelog/2868.breaking.md
go/common/version/version.go
go/consensus/api/api.go
go/consensus/tendermint/apps/scheduler/genesis.go
go/consensus/tendermint/apps/scheduler/query.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/consensus/tendermint/apps/scheduler/scheduler_test.go
go/consensus/tendermint/apps/scheduler/state/state.go
go/consensus/tendermint/tendermint.go
go/genesis/api/sanity_check.go
go/scheduler/api/api.go
go/scheduler/tests/tester.go

Now here's something we want to experiment with: validator voting power proportional to entity stake.

go consensus: stake weighted voting

---

runtime/src/storage/mkvs/mod.rs
runtime/src/transaction/context.rs

This is a dependency of oasislabs/oasis-runtime#991.

Trivial changes for custom dispatchers

---

.changelog/2892.bugfix.md
go/consensus/tendermint/apps/scheduler/genesis.go
go/scheduler/api/api.go
go/scheduler/api/api_test.go

we'll need this to fit under tendermint's maximum total voting power limit

go scheduler: increase tokens per voting power

---

.changelog/2896.feature.md
go/extra/stats/cmd/stats.go

here's the implementation of the new availability score v3 for May

go stats: new availability v3 formula

---

.changelog/2944.feature.md
go/Makefile
go/consensus/tendermint/staking/staking.go
go/staking/api/api.go
go/staking/api/grpc.go
go/staking/tests/tester.go

staking: Add WatchEvents

---

.changelog/3000.bugfix.md
go/worker/compute/merge/committee/node.go

worker/compute: Retry local dispatch between workers

---

.changelog/3015.feature.md
go/oasis-node/cmd/identity/identity.go
go/oasis-test-runner/scenario/e2e/identity_cli.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3015

go/identity/cli: Add show TLS pubkey commands

---

.buildkite/pipeline.sh
.changelog/3015.feature.md
.changelog/3023.bugfix.md
.changelog/3024.bugfix.md
go/oasis-node/cmd/identity/identity.go
go/oasis-test-runner/scenario/e2e/identity_cli.go
go/runtime/host/sandbox/sandbox.go
go/runtime/host/tests/tester.go
runtime/src/dispatcher.rs
runtime/src/protocol.rs

Backports include:
- https://github.com/oasisprotocol/oasis-core/pull/3022
- https://github.com/oasisprotocol/oasis-core/pull/3023
- https://github.com/oasisprotocol/oasis-core/pull/3024
- https://github.com/oasisprotocol/oasis-core/pull/3028

[BACKPORTS] for 20.8.1

---

.changelog/3032.bugfix.md
go/consensus/tendermint/tendermint.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/early_query.go

go/consensus/tendermint: Properly handle no committed blocks

---

.changelog/3005.doc.md
.changelog/3042.doc.md
docs/consensus/staking.md
go/staking/api/api.go
go/staking/api/commission.go

docs: Add the Accounts section of the Staking docs

---

.changelog/3043.internal.md
go/oasis-test-runner/scenario/e2e/debond.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/early_query.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/identity_cli.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/oasis-test-runner/scenario/e2e/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
go/oasis-test-runner/scenario/e2e/runtime/gas_fees.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_replicate.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_restart.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/late_start.go
go/oasis-test-runner/scenario/e2e/runtime/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/runtime/node_shutdown.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_prune.go
go/oasis-test-runner/scenario/e2e/runtime/sentry.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/oasis-test-runner/scenario/e2e/upgrade_cancel.go
go/oasis-test-runner/test-runner.go

Clean up E2E tests

---

.buildkite/code.pipeline.yml
.changelog/3051.internal.md
go/oasis-test-runner/cmd/root.go

ci: Only run runtime tests when testing SGX

---

.changelog/2978.doc.md
docs/mkvs.md
docs/runtime/index.md
docs/runtime/runtime-host-protocol.md

docs/runtime: Update the Runtime Host Protocol section

---

docs/consensus/scheduler.md

from https://github.com/oasisprotocol/oasis-core/pull/3068#pullrequestreview-440226214
> a description for how the validator committee is selected

docs: describe validator scheduling

---

.changelog/2924.doc.md
.changelog/2924.process.md
CONTRIBUTING.md
docs/adr/0000-architectural-decision-records.md
docs/adr/index.md
docs/adr/template.md
docs/index.md

Fixes #2924 
Introduce architectural decision records (ADRs) for keeping track of
architecture decisions in a transparent way.

ADR 0000: Architectural Decision Records

---

.changelog/3056.feature.md
go/common/crypto/signature/signers/ledger/ledger_signer.go
go/common/ledger/ledger.go
go/go.mod
go/go.sum

**On this PR**:
- Support for using Ledger Validator app for consensus role.

Ledger validator app support

---

.changelog/2179.feature.md
go/registry/api/api.go
go/registry/tests/tester.go

registry: Allow nodes to opt-in to more runtimes

---

.buildkite/longtests.pipeline.yml
.buildkite/scripts/daily_txsource.sh
.changelog/3090.internal.md

longtests: setup prometheus monitoring

---

.changelog/2186.internal.md
.changelog/3186.breaking.md
.changelog/3186.feature.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/api/genesis.go
go/consensus/tendermint/epochtime/epochtime.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/full/statesync.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/tests/evidence.go
go/consensus/tendermint/tests/genesis/genesis.go
go/genesis/api/sanity_check.go
go/genesis/genesis_test.go
go/go.mod
go/go.sum
go/oasis-node/cmd/debug/consim/mockchain.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
go/staking/tests/tester.go
go/storage/mkvs/commit.go
go/storage/mkvs/mkvs.go
go/storage/mkvs/tree_test.go

Also adds support for configurable initial height.

go/consensus/tendermint: Bump Tendermint Core to v0.34-rc4-oasis1

---

go/go.mod
go/go.sum

Update Badger version to v2.2007.1

---

.buildkite/longtests.pipeline.yml
.changelog/3209.bugfix.md
.changelog/3209.internal.1.md
.changelog/3209.internal.2.md
.changelog/3209.internal.3.md
go/common/grpc/errors.go
go/common/version/version.go
go/oasis-node/cmd/debug/txsource/txsource.go
go/oasis-node/cmd/debug/txsource/workload/commission.go
go/oasis-node/cmd/debug/txsource/workload/delegation.go
go/oasis-node/cmd/debug/txsource/workload/oversized.go
go/oasis-node/cmd/debug/txsource/workload/parallel.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/debug/txsource/workload/runtime.go
go/oasis-node/cmd/debug/txsource/workload/transfer.go
go/oasis-node/cmd/debug/txsource/workload/workload.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/registry/api/api.go
go/registry/tests/tester.go

* tests/txsource: Run queries workload against all nodes
* tests/txsource/queries: Verify state integrity
* go/registry: Correctly propagate lookup errors

tests/txsource: Run queries workload against all nodes

---

.changelog/3192.feature.md
go/consensus/api/api.go
go/consensus/tendermint/full/full.go
go/consensus/tests/tester.go

> cross reference [oasisprotocol/oasis-core-rosetta-gateway#40](https://github.com/oasisprotocol/oasis-core-rosetta-gateway/pull/40)
reopened from #3236

backport #3193

---

.changelog/3192.feature.md
CHANGELOG.md

changelog: Assemble changes for release 20.9.2

---

.changelog/3234.feature.md
docs/oasis-node/cli.md
go/consensus/tendermint/apps/scheduler/scheduler.go
go/control/api/api.go
go/control/control.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/node/control.go
go/oasis-node/cmd/node/node.go
go/roothash/api/commitment/pool.go
go/roothash/api/commitment/pool_test.go
go/roothash/tests/tester.go
go/scheduler/api/api.go
go/scheduler/tests/tester.go
go/worker/common/api/api.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go
go/worker/common/p2p/p2p.go
go/worker/common/worker.go
go/worker/storage/api/api.go
go/worker/storage/committee/node.go
go/worker/storage/worker.go

go/control: Add per-runtime status report

---

.changelog/3265.feature.1.md
.changelog/3265.feature.2.md
go/common/prettyprint/context.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/staking/api/commission.go
go/staking/api/commission_test.go
go/staking/api/prettyprint.go
go/staking/api/prettyprint_test.go

[BACKPORT/20.10.x] Pretty print commission schedule rates and rate bounds as enumerated lists

---

.changelog/3295.trivial.md
.github/dependabot.yml
Cargo.lock
client/Cargo.toml

rust: bump rusttracing crates

---

.changelog/3296.internal.md
.github/dependabot.yml
Cargo.lock
runtime/Cargo.toml

rust: bump snow from 0.6.2 to 0.7.1

---

.changelog/3312.doc.md
docs/consensus/genesis.md
docs/crypto.md

And try to clear the confusion between this hash and the SHA-1 or SHA-256 checksum of a genesis file.

docs: Document genesis document's hash

---

.changelog/3317.internal.md
go/consensus/tendermint/api/api.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/full/light.go
go/consensus/tendermint/full/statesync.go
go/consensus/tendermint/light/client.go
go/consensus/tendermint/registry/registry.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/staking/staking.go
go/consensus/tendermint/tests/evidence.go
go/go.mod
go/go.sum

go/consensus/tendermint: Bump Tendermint Core to v0.34-rc4-oasis3

---

.changelog/3241.internal.md
go/storage/mkvs/cache.go
go/storage/mkvs/checkpoint/checkpoint.go
go/storage/mkvs/checkpoint/checkpoint_test.go
go/storage/mkvs/checkpoint/chunk.go
go/storage/mkvs/checkpoint/restorer.go
go/storage/mkvs/commit.go
go/storage/mkvs/db/api/api.go
go/storage/mkvs/db/badger/badger.go
go/storage/mkvs/db/badger/badger_test.go
go/storage/mkvs/db/badger/metadata.go
go/storage/mkvs/interop/cmd/protocol_server.go
go/storage/mkvs/tree_test.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go
runtime/src/storage/mkvs/interop/rpc.rs

go/storage/mkvs: Add node tracking to chunk restore

---

.changelog/3307.trivial.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/fuzz/fuzz.go
go/oasis-node/cmd/debug/consim/mockchain.go
go/oasis-node/cmd/debug/dumpdb/dumpdb.go
go/worker/storage/committee/node.go
go/worker/storage/worker.go

go: Add checkpointer control options to storage worker and consensus

---

.changelog/3325.feature.md
go/runtime/client/watcher.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3325

go/runtime/client: remove unneeded P2P message republishing

---

.changelog/3276.breaking.md
go/staking/api/api.go
go/staking/api/slashing.go
go/staking/api/slashing_test.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3276

go: human readable slashing reasons

---

.changelog/3348.feature.md
go/consensus/api/api.go
go/consensus/tendermint/full/full.go
go/consensus/tests/tester.go

want this for https://github.com/oasisprotocol/oasis-core-rosetta-gateway/issues/57

go consensus: add last retained block information

---

.changelog/3348.feature.md
go/consensus/api/api.go
go/consensus/tendermint/full/full.go
go/consensus/tests/tester.go

backport #3348 to 20.11

---

.changelog/3264.bugfix.md
.changelog/3264.cfg.md
.changelog/3265.feature.1.md
.changelog/3265.feature.2.md
.changelog/3348.feature.md
CHANGELOG.md

I'm making a release so we can use these new features with the Rosetta gateway.

Assemble changes for release 20.10.1

---

.changelog/3333.internal.md
go/common/crypto/signature/signers/plugin/plugin.go
go/common/syscall/syscall_darwin.go
go/common/syscall/syscall_linux.go
go/oasis-node/cmd/common/isatty.go
go/oasis-test-runner/env/env.go

[BACKPORT/20.11.x] go: Update to build on macOS

---

.changelog/3354.internal.1.md
.changelog/3354.internal.2.md
go/runtime/committee/client.go
go/runtime/tagindexer/tagindexer.go
go/storage/api/context.go
go/storage/api/context_test.go
go/storage/client/client.go
go/worker/common/committee/runtime_host.go
go/worker/compute/executor/committee/batch.go

Prioritize nodes that signed storage receipts

---

.changelog/3284.doc.md
docs/adr/0004-runtime-governance.md
docs/adr/index.md

ADR 0004: Runtime Governance

---

.changelog/3439.doc.md
docs/adr/0007-improved-random-beacon.md
docs/adr/index.md

tldr; Read the paper and the branch

ADR-0007: Improved Random Beacon

---

.changelog/3339.doc.md
docs/adr/0005-runtime-compute-slashing.md
docs/adr/index.md

ADR 0005: Runtime Compute Node Slashing

---

go/runtime/nodes/runtime.go

Discovered in the daily tests.
Test run: https://buildkite.com/oasisprotocol/oasis-core-long-tests/builds/294#_

go/rutnime/nodes/RuntimeNodeLookup: Query for initial state

---

.changelog/3492.internal.md
Makefile
common.mk
docs/release-process.md

Handle cases where a new version was released and published off the `master` branch.

Make: Improve project version handling

---

.changelog/3423.doc.md
docs/adr/0006-consensus-governance.md
docs/adr/index.md

[Rendered](https://github.com/oasisprotocol/oasis-core/blob/kostko/docs/adr-consensus-governance/docs/adr/0006-consensus-governance.md)

ADR 0006: Consensus Governance

---

.changelog/3516.feature.md
go/consensus/tendermint/abci/mux.go
go/oasis-test-runner/scenario/e2e/upgrade.go

go/consensus/tendermint: Also dump state when shutting down for upgrade

---

.changelog/3534.bugfix.md
go/consensus/tendermint/full/full.go

backport #3534 to 20.12.x

---

.changelog/3396.breaking.md
go/common/version/version.go
go/consensus/tendermint/tests/evidence.go
go/go.mod
go/go.sum
go/oasis-node/cmd/root.go

go/consensus/tendermint: Bump Tendermint Core to v0.34.0-oasis1

---

.changelog/3538.bugfix.md
.changelog/3538.internal.md
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/oasis/cli/cli.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
go/storage/mkvs/checkpoint/checkpointer.go
go/storage/mkvs/checkpoint/checkpointer_test.go
go/worker/storage/committee/node.go

[BACKPORT/20.12.x] Fix storage sync after non-zero genesis

---

.changelog/3505.bugfix.md
.changelog/3506.internal.md
go/oasis-node/cmd/common/consensus/consensus.go
go/oasis-node/cmd/keymanager/keymanager.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/cmd/stake/account.go

[BACKPORT/20.12.x] Fix registration transaction signing with Ledger signer plugin

---

.changelog/3505.bugfix.md
.changelog/3506.internal.md
go/oasis-node/cmd/common/consensus/consensus.go
go/oasis-node/cmd/keymanager/keymanager.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/cmd/stake/account.go

Fix registration transaction signing with Ledger signer plugin

---

.changelog/3565.breaking.md
.changelog/3565.bugfix.md
.changelog/3565.feature.2.md
.changelog/3565.feature.3.md
.changelog/3565.feature.md
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/api/light.go
go/consensus/tendermint/apps/scheduler/query.go
go/consensus/tendermint/epochtime/epochtime.go
go/consensus/tendermint/epochtime_mock/epochtime_mock.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/full/light.go
go/consensus/tendermint/scheduler/scheduler.go
go/consensus/tendermint/seed/seed.go
go/consensus/tests/tester.go
go/epochtime/api/api.go
go/epochtime/tests/mock_tester.go
go/oasis-node/cmd/debug/consim/timesource.go
go/oasis-node/cmd/debug/txsource/workload/oversized.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/scheduler/api/api.go
go/scheduler/api/grpc.go
go/scheduler/tests/tester.go

Add ConsensusParameters methods for scheduler/epochtime

---

.changelog/3493.feature..md
go/oasis-node/cmd/stake/account.go
go/oasis-test-runner/scenario/e2e/stake_cli.go

go/oasis-node/cmd: Add oasis-node stake account validate_address cmd

---

go/oasis-node/cmd/debug/txsource/workload/governance.go

During the longterm tests with long restarts (and short epochs) a validator can get dropped out of committee during it's shutdown. Handle that case and just log errors when that happens in the governance workload.

go/e2e/workload-governance: handle validators dropping out of committee

---

.changelog/3630.internal.md
go/common/cbor/cbor.go
runtime/src/common/quantity.rs

* runtime/common/quantity: Implement Display trait
* go/common/cbor: Re-export Marshaler and Unmarshaler interfaces

Various minor updates

---

go/oasis-test-runner/scenario/e2e/runtime/txsource.go

go/oasis-test-runner/txsource: Also decrease MinPoolSize for storage

---

go/consensus/tendermint/apps/staking/genesis.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go

go/consensus: Make sure governance deposits are restored from genesis

---

.changelog/3669.internal.md
go/consensus/tendermint/abci/mux.go

go/consensus/tendermint/abci/mux: Reject early EstimateGas calls

---

.changelog/3662.feature.2.md
.changelog/3662.feature.md
.changelog/3662.internal.md
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/tests/tester.go
go/runtime/host/helpers.go
go/runtime/host/mock/mock.go
go/runtime/host/protocol/types.go
runtime/src/dispatcher.rs
runtime/src/protocol.rs
runtime/src/transaction/dispatcher.rs
runtime/src/types.rs

runtime: Add support for runtime queries

---

.changelog/3601.breaking.md
go/oasis-node/cmd/debug/txsource/workload/commission.go
go/staking/api/commission.go
go/staking/api/commission_test.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3601

go/staking: initial commission schedule

---

.changelog/3484.breaking.md
go/consensus/tendermint/apps/roothash/genesis.go
go/consensus/tendermint/apps/roothash/roothash.go
go/oasis-node/cmd/ias/auth_genesis.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3484

go/roothash/genesis: restore state from suspended runtimes

---

.changelog/3308.breaking.md
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/apps/staking/transactions_test.go
go/staking/api/api.go

go: Improve error message when delegating less than MinDelegationAmount

---

.changelog/3661.breaking.md
go/common/entity/entity.go
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/tests/genesis/genesis.go
go/genesis/genesis_test.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/oasis/entity.go
go/oasis-test-runner/oasis/validator.go
go/registry/api/api.go
go/registry/api/sanity_check.go
go/registry/tests/tester.go
go/worker/registration/worker.go

Remove support for entity-signed node registrations

---

go/worker/registration/worker.go

go/worker/registration: Check if node is whitelisted before registering

---

go/roothash/api/api.go
go/roothash/api/message/message.go

Here are some things I encountered scanning for API changes for our typescript SDK. See the individual commits.

Go API small fixes

---

.changelog/3728.bugfix.md
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go

go/cmd/fixgenesis: Add default beacon and governance parameters

---

.changelog/3781.breaking.md
go/consensus/tendermint/apps/governance/genesis_test.go
go/consensus/tendermint/apps/governance/governance_test.go
go/consensus/tendermint/apps/governance/state/state_test.go
go/consensus/tendermint/apps/governance/transactions_test.go
go/genesis/genesis_test.go
go/governance/api/api_test.go
go/governance/api/proposal_test.go
go/governance/gen_vectors/main.go
go/governance/tests/tester.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/upgrade/api/api.go
go/upgrade/api/api_test.go
go/upgrade/upgrade.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3770

go/upgrade/api: Version upgrade Descriptors

---

.changelog/3645.feature.md
.changelog/3771.bugfix.md
.changelog/3771.feature.md
go/consensus/tendermint/abci/mux.go
go/oasis-node/cmd/node/control.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_message.go
go/registry/api/runtime.go
go/runtime/registry/registry.go
go/runtime/scheduling/simple/txpool/orderedmap/ordered_map.go
go/runtime/scheduling/simple/txpool/tester.go
go/runtime/scheduling/tests/tester.go
go/runtime/transaction/batch.go
go/storage/client/client.go
go/worker/common/committee/node.go
go/worker/compute/executor/committee/batch.go
go/worker/compute/executor/committee/node.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go
go/worker/storage/service_external.go
runtime/src/common/quantity.rs
runtime/src/common/version.rs
runtime/src/consensus/roothash.rs
runtime/src/dispatcher.rs
runtime/src/transaction/context.rs
runtime/src/types.rs

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3645

go/worker/executor: Propose a new batch if there are message results

---

.changelog/3557.breaking.md
.changelog/3725.feature.1.md
.changelog/3725.feature.2.md
.changelog/3725.feature.3..md
go/common/prettyprint/quantity.go
go/common/prettyprint/quantity_test.go
go/oasis-node/cmd/stake/account.go
go/oasis-node/cmd/stake/allowances.go
go/oasis-node/cmd/stake/common.go
go/oasis-node/cmd/stake/delegations.go
go/oasis-node/cmd/stake/stake.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/staking/api/api.go
go/staking/api/token/prettyprint.go
go/staking/api/token/prettyprint_test.go

Closes #3557.
Example output for an account with nothing except some general balance:
```
$ oasis-node stake account info -a $ADDR --stake.account.address oasis1qqnhh0clvj978ym92rj07udfrku74yaluyz9e0la
Balance:
Total: 10000.000000001 ROSE
Available: 10000.000000001 ROSE
Nonce: 0
```
Example output for an account with a self-delegation:
```
$ oasis-node stake account info -a $ADDR --stake.account.address oasis1qqtcrdt33kxsvergtru8jm4umq8wf6tqlq3qq5zc
Balance:
Total: 11654.352017571 ROSE
Available: 425.337214176 ROSE
Active Delegations from this Account:
Total: 11229.014803395 ROSE
Delegations:
- To:     oasis1qqtcrdt33kxsvergtru8jm4umq8wf6tqlq3qq5zc (self)
Amount: 11229.014803395 ROSE (10000000000000 shares)
Active Delegations to this Account:
Total: 11229.014803395 ROSE (10000000000000 …
```

Enhance oasis-node stake account info CLI command's output

---

.changelog/3819.feature.md
go/staking/api/api.go

[BACKPORT/21.0.x] Improve pretty-print for Escrow/ReclaimEscrow transactions

---

.changelog/3820.bugfix.md
.changelog/3820.internal.1.md
.changelog/3820.internal.2.md
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/storage_node.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/storage/api/context.go
go/storage/client/client.go
go/storage/mkvs/db/badger/badger.go
go/storage/mkvs/db/badger/badger_test.go
go/worker/common/committee/node.go
go/worker/common/worker.go
go/worker/storage/committee/node.go
go/worker/storage/committee/utils.go

Storage fixes from master

---

.changelog/3830.bugfix.md
go/consensus/tendermint/abci/mux.go
go/storage/mkvs/checkpoint/checkpoint.go
go/storage/mkvs/checkpoint/checkpoint_test.go
go/storage/mkvs/checkpoint/restorer.go
go/storage/mkvs/db/badger/badger_test.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go

[BACKPORT/21.0.x] Checkpoint abort fixes

---

.changelog/3838.internal.md
go/worker/common/committee/node.go
go/worker/common/p2p/dispatch.go
go/worker/common/p2p/error/error.go

Iterate over all handlers on unhandled peer message

---

.buildkite/code.pipeline.yml
.changelog/3863.internal.1.md
.changelog/3863.internal.2.md
go/common/persistent/persistent.go
go/oasis-node/cmd/debug/storage/storage.go
go/oasis-test-runner/oasis/controller.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync_inconsistent.go
go/storage/mkvs/checkpoint/checkpointer.go
go/worker/storage/api/api.go
go/worker/storage/api/grpc.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go
go/worker/storage/service_internal.go
tests/clients/simple-keyvalue/src/main.rs

Verified to fail if #3830 isn't applied.

Add test for storage sync after messy/incorrect cleanup

---

.changelog/3889.bugfix.md
.changelog/3899.bugfix.md
go/worker/common/committee/node.go
go/worker/storage/committee/utils.go

[BACKPORT/21.1.x] Minor runtime worker fixes

---

.changelog/3903.breaking.md
.changelog/3908.feature.md
docs/setup/deploying-a-runtime.md
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/cmd/storage/storage.go
go/oasis-test-runner/oasis/cli/registry.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/oasis-test-runner/scenario/e2e/runtime/history_reindex.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
go/storage/mkvs/db/badger/rename.go
go/storage/mkvs/db/badger/rename_test.go

[BACKPORT/21.1.x] Runtime registration fixes, rename subcommand

---

go/Makefile

Fix go-fuzz builds

---

.changelog/3892.breaking.md
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/runtime/client/client.go
go/runtime/host/helpers.go
go/runtime/host/protocol/types.go
go/worker/compute/executor/committee/node.go
runtime/src/dispatcher.rs
runtime/src/transaction/context.rs
runtime/src/transaction/dispatcher.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/api/src/api.rs
tests/runtimes/simple-keyvalue/src/main.rs

runtime: Add epoch to ExecuteTx/CheckTx/Query requests

---

.changelog/3918.feature.md
.changelog/3918.internal.md
docs/consensus/staking.md
docs/crypto.md
go/Makefile
go/common/crypto/sakg/bip32.go
go/common/crypto/sakg/bip32_test.go
go/common/crypto/sakg/sakg.go
go/common/crypto/sakg/sakg_test.go
go/go.mod
go/go.sum
go/staking/gen_account_vectors/main.go

Implementation of [ADR 0008](https://github.com/oasisprotocol/oasis-core/pull/3656).

ADR 0008: Standard Account Key Generation implementation

---

.buildkite/benchmarks.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.yml

Here we go again, it seems that #3955 did not fix the issues after all :disappointed:.

ci: Disable incremental Rust builds due to compiler bugs

---

.changelog/3958.cfg.md
go/ias/init.go
go/ias/proxy/client/client.go
go/oasis-node/cmd/ias/proxy.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/ias.go

go/ias: Change client authentication configuration

---

.changelog/3960.internal.md
go/staking/gen_account_vectors/main.go

Using:
```
make -C go staking/gen_account_vectors_extended
```
one will now also get the test vector for [Trust Wallet Core's test mnemonic](https://github.com/trustwallet/wallet-core/blob/219b85286b6d042f9306402acefd33c08b2b3b66/swift/Tests/CoinAddressDerivationTests.swift#L13):
```json
... trimmed ...
{
"kind": "standard account key generation",
"bip39_mnemonic": "shoot island position soft burden budget tooth cruel issue economy destroy above",
"bip39_passphrase": "",
"bip39_seed": "577cd910aede2582668a741d476b45e7998e905a4286f701b87b25923501f9d4ea19513b460bcccbc069ebbe4327a59af3d6463045c4b6fa21a5e7004ccfcc3e",
"oasis_accounts": [
{
"bip32_path": "m/44'/474'/0'",
"private_key": "dc01d0c285df41e26e91530741a71352a118373b6e628e55c00930b02fdbd396345daa58a0f8404a85622055dce2ad1d79e2714877df3 …
```

go/staking/gen_account_vectors: Add Trust Wallet Core's test mnemonic

---

.changelog/3968.internal.md
Cargo.lock
client/Cargo.toml
client/src/transaction/client.rs
keymanager-client/Cargo.toml
runtime/Cargo.toml
tests/clients/simple-keyvalue-enc/Cargo.toml
tests/clients/simple-keyvalue-ops/Cargo.toml
tests/clients/simple-keyvalue/Cargo.toml
tests/clients/test-long-term/Cargo.toml

Bump grpcio to 0.9.0

---

.changelog/3827.feature.md
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/tendermint/roothash/roothash.go
go/oasis-node/cmd/debug/byzantine/roothash.go
go/oasis-node/cmd/node/control.go
go/oasis-node/cmd/node/node.go
go/oasis-node/node_test.go
go/roothash/api/api.go
go/roothash/api/grpc.go
go/roothash/metrics.go
go/roothash/tests/tester.go
go/runtime/client/client.go
go/runtime/client/submitter.go
go/runtime/registry/registry.go
go/runtime/tagindexer/tagindexer.go
go/staking/tests/tester.go
go/worker/common/committee/node.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/prune.go
go/worker/compute/executor/tests/tester.go
go/worker/storage/committee/node.go

go/roothash/api: Add gRPC service

---

.changelog/3894.feature.md
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_message.go
go/worker/compute/executor/committee/node.go

go/worker/compute: Propose block on runtime genesis

---

.changelog/3990.internal.md
Cargo.lock
runtime/Cargo.toml

runtime: Stop using the ring backend for snow

---

.changelog/3776.feature.md
go/oasis-node/cmd/common/common.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/runtime/host/host.go
go/runtime/host/protocol/connection.go
go/runtime/host/protocol/types.go
go/runtime/host/sandbox/sandbox.go
go/runtime/registry/config.go
runtime/src/protocol.rs
runtime/src/types.rs

Add support for local runtime-specific configuration

---

runtime/src/transaction/dispatcher.rs
runtime/src/types.rs

On `go` side this is already `transaction.Weight`

rename: CheckTxWeight -> TransactionWeight

---

.changelog/4009.bugfix.md
.changelog/4010.bugfix.2.md
.changelog/4010.bugfix.md
go/common/badger/helpers.go
go/common/badger/migrate.go
go/consensus/tendermint/abci/state.go
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/debug/beacon/beacon.go
go/storage/mkvs/checkpoint/checkpointer.go
go/storage/mkvs/checkpoint/checkpointer_test.go

Backports the following:
* #4009 
* #4010

[BACKPORT/21.2.x] Backport of multiple bugfixes

---

.changelog/4014.feature.md
go/consensus/tendermint/apps/staking/api.go
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/staking/staking.go
go/staking/api/api.go
go/staking/tests/tester.go

[BACKPORT/21.2.x] go/staking: Add DebondingStartEscrowEvent

---

.buildkite/code.pipeline.yml

CI improvements

---

.buildkite/code.pipeline.yml
.changelog/4024.feature.2.md
.changelog/4024.feature.3.md
.changelog/4024.feature.md
.changelog/4037.bugfix.md
.changelog/4037.cfg.md
.changelog/4040.feature.md
.changelog/4041.cfg.md
.changelog/4042.trivial.md
.github/workflows/ci-reproducibility.yml
.github/workflows/release-dev.yml
.github/workflows/release.yml
.goreleaser.yml
docker/development/Dockerfile
docs/setup/building.md
docs/setup/prerequisites.md
go/Makefile
go/common/badger/helpers.go
go/common/badger/migrate.go
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
runtime-loader/Cargo.toml
runtime-loader/bin/main.rs
runtime-loader/src/lib.rs

Backports the following:
- #4039
- #4037
- #4041
- #4040
- #4024
- #4042

[BACKPORT/21.2.x] Multiple dependency updates and fixes

---

.changelog/4025.cfg.md
.changelog/4025.feature.md
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/oasis.go
go/worker/common/p2p/init.go
go/worker/common/p2p/p2p.go

[BACKPORT/21.2.x]  #4025

---

.changelog/4059.bugfix.md
.changelog/4059.internal.md
go/common/backoff/backoff.go
go/consensus/api/submission.go
go/runtime/client/submitter.go
go/runtime/host/sandbox/sandbox.go
go/runtime/tagindexer/tagindexer.go
go/worker/beacon/worker.go
go/worker/common/p2p/dispatch.go
go/worker/common/p2p/peermgmt.go
go/worker/keymanager/worker.go
go/worker/registration/worker.go
go/worker/storage/committee/utils.go

go/runtime/host/sandbox: Prevent restart storm after 10m

---

.changelog/4059.bugfix.md
.changelog/4059.internal.md
.changelog/4061.bugfix.md
.changelog/4061.internal.md
go/common/backoff/backoff.go
go/consensus/api/submission.go
go/oasis-node/cmd/node/node.go
go/runtime/client/submitter.go
go/runtime/host/sandbox/sandbox.go
go/runtime/registry/registry.go
go/runtime/tagindexer/tagindexer.go
go/storage/client/client.go
go/storage/client/init.go
go/worker/beacon/worker.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go
go/worker/common/p2p/dispatch.go
go/worker/common/p2p/peermgmt.go
go/worker/compute/executor/committee/node.go
go/worker/keymanager/worker.go
go/worker/registration/worker.go
go/worker/storage/committee/utils.go

[BACKPORT/21.2.x] Multiple backports

---

.github/workflows/docker.yml
docker/development/Dockerfile
docs/setup/prerequisites.md

Also, simplify output variable setting in docker GitHub Actions workflow.

internal: Streamline and unify jemalloc build steps

---

.changelog/4111.bugfix.md
.changelog/4111.internal.md
go/runtime/host/sandbox/process/bwrap.go
go/worker/compute/executor/committee/node.go

 go/runtime/host/sandbox: Add deadline to bwrap pipes

---

.changelog/4101.internal.md
Cargo.lock
go/go.mod
go/go.sum
go/storage/mkvs/interop/cmd/db_json_rpc.go
go/storage/mkvs/interop/cmd/protocol_server.go
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/storage/mkvs/interop/protocol_server.rs
runtime/src/storage/mkvs/interop/rpc.rs

rust: Remove as much grpcio as possible

---

go/oasis-node/cmd/debug/txsource/workload/queries.go

Workload queries improvements:
- avoid iterating through all proposals if querying earliest height
- after the longtests are running for awhile there's a lot of proposals and iterating through and querying all votes takes some time, avoid this if we're querying earliest rounds, to reduce the chance of those getting pruned mid iteration (caused failure in https://buildkite.com/oasisprotocol/oasis-core-long-tests/builds/858#aeecc2e0-d50d-45cd-a910-422ce58ab7cb)
- avoid iterating through active proposals
- mostly duplicates the previous all-proposals iterations. Also in the long-epochs case, active proposals mostly match active proposals anyway.

workload/queries: minor improvements

---

.changelog/4079.trivial.md
go/common/address.go
go/common/node/address.go
go/worker/common/p2p/dispatch.go
go/worker/common/p2p/p2p.go

go/worker/common/p2p: Prefer returning "globally reachable" addresses

---

.changelog/4174.internal.md
.github/dependabot.yml
Cargo.lock
runtime/Cargo.toml
runtime/src/storage/mkvs/cache/lru_cache.rs

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3245

rust: update intrusive-collections to 0.9.2

---

.changelog/4176.internal.md
docker/development/Dockerfile
docs/setup/prerequisites.md
go/.golangci.yml
go/Makefile
go/common/grpc/cbor.go
go/common/grpc/errors_test.go
go/common/grpc/testing/ping.go
go/common/grpc/wrapper_test.go
go/consensus/api/transaction/transaction_test.go
go/consensus/tendermint/api/api.go
go/keymanager/api/grpc.go
go/oasis-node/cmd/common/metrics/net.go
go/registry/api/runtime.go
go/runtime/history/history_test.go
go/runtime/history/prune.go
go/runtime/host/host.go
go/runtime/host/mock/mock.go
go/runtime/host/protocol/connection.go
go/runtime/host/protocol/types.go
go/runtime/tagindexer/backend.go
go/storage/mkvs/db/badger/migrate_test.go
go/storage/mkvs/interop/fixtures/consensus_mock.go
go/storage/mkvs/syncer/merge.go
go/storage/mkvs/syncer/proof.go
go/upgrade/migrations/dummy.go

go: update gofumpt to 0.1.1

---

.changelog/4180.feature.md
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/upgrade/migrations/consensus_parameters.go

[stable/21.2.x] upgrade/migrations: consensus parameters upgrade handler

---

.changelog/4192.feature.md
go/oasis-node/cmd/common/common.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/ias.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/seed.go
go/oasis-test-runner/oasis/sentry.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go

Backports https://github.com/oasisprotocol/oasis-core/pull/4193

[BACKPORT/21.2.x] prevent startup when RLIMIT_NOFILE is too low

---

.buildkite/code.pipeline.yml
.buildkite/rust/coverage.sh
.changelog/4197.internal.md
docker/testing/Dockerfile

Last part of https://github.com/oasisprotocol/oasis-core/issues/3629

rust: bump tarpaulin to 0.18.0

---

.changelog/4070.internal.md
go/consensus/tendermint/apps/governance/governance.go
go/upgrade/api/api.go
go/upgrade/dummy.go
go/upgrade/upgrade.go

go/consensus/tendermint/apps/governance: Ensure upgrade is in progress

---

.buildkite/rust/coverage.sh
.changelog/4222.breaking.md
go/beacon/tests/tester.go
go/consensus/tendermint/apps/governance/governance.go
go/consensus/tendermint/apps/scheduler/genesis.go
go/consensus/tendermint/apps/scheduler/query.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/consensus/tendermint/tests/evidence.go
go/consensus/tendermint/tests/genesis/genesis.go
go/genesis/genesis_test.go
go/governance/tests/tester.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-node/cmd/node/node.go
go/oasis-node/node_test.go
go/registry/tests/tester.go
go/roothash/tests/tester.go
go/scheduler/api/api.go
go/scheduler/tests/tester.go
go/staking/tests/tester.go
go/storage/client/tests/tests.go
go/storage/database/database_test.go
go/storage/tests/tester.go
go/worker/compute/executor/tests/tester.go
go/worker/storage/crashing_test.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4215

go/scheduler: remove debug static validators option

---

.changelog/4223.internal.md
Makefile
go/consensus/tendermint/tests/evidence.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/validator_equivocation.go
go/staking/tests/tester.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4223

go/tests/e2e: validator-equivocation test scenario

---

.changelog/4242.breaking.md
Cargo.lock
keymanager-api-common/Cargo.toml
keymanager-api-common/src/api.rs
keymanager-client/src/mock.rs
keymanager-lib/src/kdf.rs

keymanager-api-common: Implement Zeroize for secret types

---

.changelog/4289.bugfix.md
.changelog/4290.bugfix.md
.changelog/4292.bugfix.md
go/common/identity/identity.go
go/common/identity/identity_test.go
go/storage/api/grpc.go
go/worker/storage/committee/node.go

Backports the following:
* #4289 
* #4290 
* #4292

[BACKPORT/21.3.x] Multiple fixes

---

go/common/version/version.go
go/common/version/version_test.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/runtime.go

[BACKPORT/21.3.x] test-runner: Read runtime version from fixture

---

.changelog/4387.bugfix.1.md
.changelog/4387.bugfix.2.md
go/runtime/client/client.go
go/storage/mkvs/checkpoint/checkpointer.go
go/worker/storage/committee/node.go

[BACKPORT/21.3.x] go/worker/storage: Checkpoint correct round on consensus checkpoint

---

.changelog/4327.doc.md
docs/adr/0011-incoming-runtime-messages.md
docs/adr/index.md

[Rendered](https://github.com/oasisprotocol/oasis-core/blob/kostko/docs/adr-rt-incoming-msgs/docs/adr/0011-incoming-runtime-messages.md)

ADR 0011: Incoming Runtime Messages

---

.changelog/4090.breaking.md
.changelog/4212.breaking.md
.changelog/4241.feature.md
go/common/node/node.go
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/seed/seed.go
go/oasis-node/cmd/consensus/consensus.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/api/runtime.go
go/worker/registration/worker.go

go: Various small improvements from the backlog

---

.changelog/4437.breaking.md
go/consensus/tendermint/apps/staking/transactions.go
go/staking/api/api.go
go/staking/tests/tester.go

Part of: https://github.com/oasisprotocol/oasis-core/issues/4402

go/staking: include debond end time in debonding events

---

.changelog/4439.bugfix.md
Cargo.lock
runtime/Cargo.toml

deps: Switch to the upstream jsonrpc import

---

.changelog/4439.bugfix.md
Cargo.lock
runtime/Cargo.toml

[BACKPORT/21.3.x] deps: Switch to the upstream jsonrpc import

---

.changelog/4438.feature.md
go/oasis-test-runner/scenario/e2e/runtime/keymanager_restart.go
go/runtime/client/host.go
go/runtime/host/host.go
go/runtime/host/mock/mock.go
go/runtime/host/protocol/connection.go
go/runtime/host/protocol/connection_test.go
go/runtime/host/protocol/types.go
go/runtime/host/sandbox/sandbox.go
go/runtime/registry/host.go
go/runtime/scheduling/api/api.go
go/runtime/scheduling/simple/simple.go
go/runtime/scheduling/simple/txpool/api/api.go
go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
go/runtime/scheduling/simple/txpool/tester.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/runtime_host.go
go/worker/compute/executor/committee/state.go
runtime/src/config.rs
runtime/src/dispatcher.rs
runtime/src/protocol.rs
runtime/src/transaction/dispatcher.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

[BACKPORT/21.3.x] Add support for runtime schedule control

---

.changelog/4453.bugfix.md
go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go

[BACKPORT/21.3.x] go/runtime/scheduling: Attempt to continue scheduling

---

.changelog/4456.breaking.md
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/apps/staking/transactions_test.go
go/genesis/genesis_test.go
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
go/staking/api/api.go
go/staking/tests/state.go

cross reference: https://oasisprotocol.clickup.com/t/1zfn2hb

 go/staking: add minimum transfer amount 

---

.changelog/4436.feature.md
.changelog/4524.feature.md
go/worker/common/api/api.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go

go/worker/common: Report locally supported runtime host versions

---

.changelog/4548.bugfix.md
go/oasis-node/cmd/ias/auth_registry.go
go/oasis-node/cmd/ias/proxy.go

go/oasis-node/cmd/ias: Refresh runtimes on every epoch

---

.changelog/4580.bugfix.md
.changelog/4580.feature.md
go/oasis-node/cmd/control/control.go
go/oasis-test-runner/scenario/e2e/runtime/node_shutdown.go
go/worker/registration/worker.go

[BACKPORT/22.0.x] go/worker/registration: Clear deregister flag when deregistered

---

.changelog/4596.feature.md
go/go.mod
go/go.sum
go/oasis-node/cmd/control/control.go
go/oasis-node/cmd/control/runtime_stats.go

This is a cleaned up version of the command in the tools repository.
Fixes #4425

go/oasis-node/cmd/control: Add runtime-stats

---

.changelog/4588.feature.md
go/oasis-node/cmd/node/unsafe_reset.go
go/oasis-test-runner/oasis/cli/cli.go

stable/21.3.x backport #4588

---

.changelog/4588.feature.md
go/oasis-node/cmd/node/unsafe_reset.go
go/oasis-test-runner/oasis/cli/cli.go

stable/22.0.x backport #4588

---

.buildkite/go/build.sh
.changelog/4598.internal.md

ci: show dirtiness after regenerating protos

---

.buildkite/go/build.sh
.changelog/4598.internal.md

just wondering if what I'm seeing locally is the same as we see on CI
backport of #4598

backport 21.3.x - ci: show dirtiness after regenerating protos

---

.buildkite/go/build.sh
.changelog/4598.internal.md

backport 22.0.x - ci: show dirtiness after regenerating protos

---

.changelog/4602.internal.md
go/common/crypto/signature/batch_verification.go
go/common/crypto/signature/batch_verification_test.go
go/common/crypto/signature/signature.go
go/consensus/api/transaction/transaction.go

go/common/crypto/signature: Add batch verification goodies

---

.changelog/4640.bugfix.md
.changelog/4640.feature.md
Cargo.lock
go/runtime/txpool/txpool.go
go/worker/common/p2p/rpc/client.go
go/worker/common/p2p/txsync/client.go
go/worker/common/p2p/txsync/protocol.go
go/worker/compute/executor/committee/batch.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/transactions.go
keymanager-client/Cargo.toml
keymanager-lib/Cargo.toml
runtime-loader/Cargo.toml
runtime/Cargo.toml
runtime/src/config.rs
runtime/src/dispatcher.rs
tools/Cargo.toml

[BACKPORT/22.1.x] go/worker/compute: Improve proposed transaction handling

---

.changelog/4653.trivial.md
go/consensus/api/transaction/transaction.go

go/consensus/api/transactions: Fix OpenRawTransactions

---

.changelog/4539.feature.md
.changelog/4571.bugfix.md
go/consensus/api/api.go
go/consensus/api/submission.go
go/consensus/api/transaction/transaction.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/common.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/full/light.go
go/consensus/tendermint/full/services.go
go/consensus/tendermint/seed/seed.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/runtime/archive_api.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/upgrade/upgrade.go
go/worker/registration/worker.go

Backport of: https://github.com/oasisprotocol/oasis-core/pull/4571
Tested the archive mode on the dryrun.

[BACKPORT/21.3.x]: Add archive mode support

---

.changelog/4662.bugfix.md
go/oasis-node/cmd/common/genesis/staking.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/worker/registration/worker.go

Backports https://github.com/oasisprotocol/oasis-core/pull/4662

[BACKPORT/22.1.x]: worker/registration: fix waiting for deregister event

---

.changelog/4678.feature.md
go/oasis-test-runner/scenario/e2e/runtime/trust_root.go
go/runtime/host/helpers.go
go/runtime/host/mock/mock.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/trust.go

[BACKPORT/22.1.x] go/worker/compute: Ensure trust root is verified before registering

---

.buildkite/go/nancy_audit.sh
.changelog/4754.internal.md
.changelog/4776.bugfix.md
docker/development/Dockerfile
go/.nancy-ignore
go/go.mod
go/go.sum
go/oasis-node/cmd/node/node.go
go/worker/storage/worker.go

Quick fix for archive nodes on 21.3.x

[BACKPORT:21.3.x]: archive: disable storage sync for archive nodes

---

go/common/crypto/signature/signers/remote/grpc.go
go/oasis-node/cmd/common/signer/signer.go

[BACKPORT/22.1.x] common/crypto/signature/signers/remote: Support AF_LOCAL

---

.changelog/4799.internal.md
go/consensus/tendermint/apps/scheduler/debug_force.go
go/consensus/tendermint/apps/scheduler/shuffle.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/scheduler/api/api.go

Non-breaking test part of #4798.

go/oasis-test-runner/byzantine: Add primary+backup liveness test

---

.changelog/4822.bugfix.2.md
.changelog/4822.bugfix.md
go/registry/api/api.go
go/registry/api/api_test.go
go/registry/api/runtime.go
go/registry/api/runtime_test.go

This was already fixed in (recent) 22.1.x releases.

fix nil deference bugs and add tests

---

.changelog/4844.internal.md
go/common/sgx/sigstruct/sigstruct.go
go/common/sgx/sigstruct/sigstruct_test.go
go/runtime/bundle/bundle.go
go/runtime/bundle/bundle_test.go

Backport https://github.com/oasisprotocol/oasis-core/pull/4844

[BACKPORT/22.1.x] go/common/sgx/sigstruct: Add support for offline signing

---

.changelog/4867.bugfix.md
.punch_version.py
CHANGELOG.md

changelog: Assemble changes for 22.1.10 release

---

.changelog/4935.doc.md
docs/development-setup/prerequisites.md

...based on my recent experience building from source.

Update documentation about prerequisites for building

---

.changelog/4755.breaking.md
go/common/crypto/signature/signature.go
go/consensus/tendermint/apps/staking/transactions.go
go/staking/api/address_internal.go
go/staking/api/address_test.go
go/staking/api/api.go
go/staking/api/sanity_check.go
go/staking/tests/tester.go

Yet another PR that can rot for months in "don't want to fork the 22.x branch yet" purgatory.
* ~Migration~
Implements #4755

staking: Add a burn address

---

.changelog/5005.bugfix.1.md
.changelog/5005.bugfix.2.md
.changelog/5005.bugfix.3.md
.changelog/5005.bugfix.4.md
go/storage/mkvs/checkpoint/checkpointer.go
go/worker/common/committee/node.go
go/worker/common/p2p/rpc/client.go
go/worker/common/p2p/rpc/peermgmt.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go

[BACKPORT/22.2.x] Fix storage sync from non-empty genesis and p2p multi call dispatch

---

.changelog/5007.bugfix.1.md
.changelog/5007.bugfix.2.md
go/worker/common/p2p/rpc/client.go

Backport of https://github.com/oasisprotocol/oasis-core/pull/5007

[BACKPORT/22.2.x] go/p2p/rpc: Fix peer grading and memory leaks in RPC multi calls

---

.changelog/5011.feature.md
go/consensus/tendermint/apps/staking/state/state.go

 [BACKPORT/22.2.x] go tendermint staking: reduce DelegationsTo scanning

---

.changelog/5038.breaking.md
go/common/sgx/pcs/quote.go
go/common/sgx/pcs/quote_test.go
go/common/sgx/pcs/tcb.go
runtime/src/common/sgx/pcs.rs

Use PCS quote policy to blackist FMSPCs.

go/common/sgx/pcs: Add support for blacklisting FMSPCs

---

.changelog/5049.feature.md
.changelog/5053.bugfix.md
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/registry/api/api.go
go/registry/api/runtime.go
go/registry/api/runtime_test.go
go/upgrade/migrations/consensus_v62.go
go/worker/compute/executor/committee/node.go
runtime/src/consensus/tendermint/verifier/mod.rs

[BACKPORT/22.2.x] Multiple backports

---

.changelog/5102.breaking.1.md
.changelog/5102.breaking.2.md
.changelog/5102.feature.md
go/consensus/tendermint/apps/roothash/slashing_test.go
go/consensus/tendermint/apps/staking/messages.go
go/consensus/tendermint/apps/staking/query.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/apps/staking/transactions_test.go
go/consensus/tendermint/apps/supplementarysanity/checks.go
go/consensus/tendermint/staking/staking.go
go/genesis/genesis_test.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/scenario/e2e/consensus_parameter_upgrade.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/staking/api/api.go
go/staking/api/commission.go
go/staking/api/commission_test.go
go/staking/api/grpc.go
go/staking/api/sanity_check.go

go/staking: Add MinCommissionRate parameter

---

.buildkite/pipeline.sh
.changelog/5146.internal.md
.changelog/5148.bugfix.md
.changelog/5149.internal.md
Cargo.lock
runtime/Cargo.toml
runtime/src/common/mod.rs
runtime/src/common/process.rs
runtime/src/common/sgx/mod.rs
runtime/src/common/sgx/pcs.rs
runtime/src/consensus/tendermint/verifier/mod.rs
runtime/src/consensus/tendermint/verifier/store/lru.rs
runtime/src/dispatcher.rs

Backports of the following:
* #5146
* #5148 
* #5149 
* #5150

[BACKPORT/22.2.x] Multiple verifier-related backports

---

.changelog/5155.trivial.md
Makefile

Fix build documentation typo

---

.changelog/5161.bugfix.md
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/p2p.go
go/worker/compute/executor/committee/proposals.go
go/worker/compute/executor/committee/state.go

[BACKPORT/22.2.x] go/worker/compute: Do not drop valid proposals

---

go/config/config.go
go/genesis/config/config.go
go/genesis/file/file.go
go/oasis-node/cmd/common/consensus/consensus.go
go/oasis-node/cmd/debug/byzantine/node.go
go/oasis-node/cmd/debug/txsource/txsource.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/debug/txsource/workload/workload.go
go/oasis-node/cmd/node/flags.go
go/oasis-node/node_test.go
go/oasis-test-runner/oasis/network.go

* tests/workload/registration: Increase iteration timeout
* go/config: Move genesis file path to configuration file

Multiple minor fixes

---

.changelog/5200.feature.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/full.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore_nonmock.go

[BACKPORT/22.2.x] Move halt epoch from genesis to node-local configuration

---

.changelog/5188.feature.md
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
go/registry/api/api.go
go/registry/api/runtime.go
go/registry/api/runtime_test.go
go/runtime/config/config.go
go/runtime/host/host.go
go/runtime/host/mock/mock.go
go/runtime/host/multi/multi.go
go/runtime/host/sandbox/sandbox.go
go/runtime/registry/host.go
go/worker/common/committee/node.go
go/worker/compute/executor/committee/node.go
go/worker/keymanager/worker.go

go/runtime: Reduce downtime for TEE runtime upgrades

---

.buildkite/benchmarks.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.yml
.buildkite/pipeline.sh
.changelog/5224.internal.md
.github/workflows/docker.yml
Cargo.lock
Makefile
docker/Makefile
docker/oasis-core-ci/Dockerfile
docs/development-setup/building.md
docs/development-setup/prerequisites.md

[BACKPORT/22.2.x] docker: Switch to ghcr.io for container registry

---

go/roothash/api/commitment/pool.go
go/roothash/api/commitment/pool_test.go

Fixes an issue introduced in #5261.

go/roothash: Wait for proposer commit in discrepancy resolution

---

.changelog/5287.breaking.md
.changelog/5287.trivial.md
go/upgrade/upgrade.go

Minor fixes that were found during code review.

go/upgrade: Fix upgrade manager

---

go/oasis-test-runner/scenario/e2e/runtime/trust_root_change.go

Waiting time of 25 blocks was sometimes not enough for a compute worker to start a runtime. Extending to 1 minute. Locally, a compute worker needed approx. 30 seconds to start a runtime.

go/oasis-test-runner: Extend waiting time in trust root change scenario

---

.buildkite/scripts/daily_txsource.sh

Fix a bug introduced in #5304.

ci: Fix long E2E test timeout

---

.buildkite/scripts/test_upgrade.sh
go/oasis-node/cmd/debug/txsource/workload/registration.go
tests/upgrade/post/go.mod
tests/upgrade/post/go.sum

* tests: Increase iteration timeout in registry txsource workload
* ci: Use Go version from oasis-core-dev Docker image

Multiple test-related fixes

---

go/roothash/api/liveness.go
go/worker/common/api/api.go
go/worker/common/committee/node.go

[BACKPORT/23.0.x] 5402

---

.changelog/5442.bugfix.md
go/runtime/host/protocol/connection.go
go/runtime/host/sgx/sgx.go

[BACKPORT/23.0.x] 5442

---

.changelog/5446.bugfix.2.md
.changelog/5446.bugfix.md
.changelog/5447.bugfix.2.md
.changelog/5447.bugfix.md
.changelog/5448.bugfix.md
.changelog/5450.bugfix.md
.changelog/5453.bugfix.md
.changelog/5456.bugfix.2.md
.changelog/5456.bugfix.md
go/consensus/cometbft/apps/roothash/transactions.go
go/p2p/discovery/bootstrap/client.go
go/p2p/host.go
go/p2p/rpc/client.go
go/p2p/rpc/nop.go
go/runtime/host/host.go
go/runtime/host/mock/mock.go
go/runtime/host/multi/multi.go
go/runtime/host/sandbox/sandbox.go
go/runtime/registry/host.go
go/runtime/txpool/txpool.go
go/worker/compute/executor/committee/node.go
go/worker/registration/worker.go
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/client.rs

Backports:
- #5446
- #5447
- #5448
- #5450
- #5453
- #5456
Skipped: 
- 5449
- 5451
- 5452

[BACKPORT/23.0.x] Multiple backports

---

runtime/src/consensus/state/roothash.rs

https://github.com/oasisprotocol/oasis-core/pull/5460

[BACKPORT/23.0.x] 5460

---

.changelog/5466.bugfix.md
.changelog/5466.cfg.md
go/consensus/api/light.go
go/consensus/cometbft/abci/prune.go
go/consensus/cometbft/cometbft.go
go/consensus/cometbft/config/config.go
go/consensus/cometbft/full/full.go
go/consensus/cometbft/light/api/light.go
go/consensus/cometbft/light/internal.go
go/consensus/cometbft/light/p2p/p2p.go
go/consensus/cometbft/light/service.go
go/consensus/p2p/light/server.go
go/oasis-node/cmd/node/node.go

[BACKPORT/23.0.x] go/consensus/cometbft/light: Try multiple sources when fetching blocks

---

.changelog/5472.bugfix.md
go/governance/api/api.go
go/governance/api/api_test.go

Old:
```
Method: governance.SubmitProposal
Body:
(invalid)
```
New:
```
Method: governance.SubmitProposal
Body:
Change Parameters:
Module: staking
Changes:
- Parameter: upgrade_cancel_min_epoch_diff
Value: 15
```

governance: Fix PrettyPrint for ChangeParametersProposal

---

.changelog/5465.internal.md
.changelog/5467.feature.md
.changelog/5472.bugfix.md
go/common/sgx/pcs/http.go
go/common/sgx/pcs/pcs.go
go/common/sgx/pcs/quote.go
go/common/sgx/pcs/tcb.go
go/consensus/cometbft/apps/roothash/query.go
go/consensus/cometbft/roothash/roothash.go
go/governance/api/api.go
go/governance/api/api_test.go
go/ias/http/http.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/oasis/network.go
go/roothash/api/api.go
go/roothash/api/grpc.go
go/runtime/host/sgx/ecdsa.go

- https://github.com/oasisprotocol/oasis-core/pull/5465
- contains a minor fix in the ias/pcs http clients
- https://github.com/oasisprotocol/oasis-core/pull/5467
- https://github.com/oasisprotocol/oasis-core/pull/5472

[BACKPORT/23.0.x] 5465 5467 5472

---

go/runtime/registry/host.go

rhp: Revert Eden fix

---

.changelog/5509.doc.md
LICENSE-docs
README.md

See https://github.com/oasisprotocol/docs/pull/440

docs: License the documentation under CC BY 4.0

---

.changelog/5510.bugfix.md
go/go.mod
go/go.sum
go/oasis-node/cmd/common/metrics/disk.go

[BACKPORT/23.0.x] 5510

---

.changelog/5592.feature.md
secret-sharing/src/lib.rs
secret-sharing/src/vss/lagrange/mod.rs
secret-sharing/src/vss/lagrange/multiplier.rs
secret-sharing/src/vss/lagrange/naive.rs
secret-sharing/src/vss/lagrange/optimized.rs
secret-sharing/src/vss/mod.rs
secret-sharing/src/vss/polynomial/univariate.rs

I guess the multiplier could be optimized if we didn't clone so much.

secret-sharing/src/vss: Add Lagrange interpolation

---

go/storage/mkvs/db/pathbadger/pathbadger.go

We need to commit the sequence number for the pending (non-finalized) root early on. Otherwise a crash could result in the root being committed but its sequence number is not known so finalization would fail.
The issue was discovered by our long-term E2E tests.

go/storage/mkvs/db/pathbadger: Record sequence number early

---

.changelog/5804.internal.md
go/common/sgx/common_test.go
go/common/sgx/ias/avr.go
go/common/sgx/pcs/quote.go
go/common/sgx/quote/quote.go
go/common/sgx/quote/quote_test.go

go/common/sgx: Make quote policy YAML serializable

---

.changelog/5820.feature.md
go/oasis-node/cmd/control/control.go
go/oasis-node/cmd/identity/identity.go

go/oasis-node: Add identity show-address subcommand

---

.changelog/5909.bugfix.md
runtime/src/consensus/tendermint/verifier/store/state.rs

[BACKPORT/24.3.x] runtime: Do not persist updated trusted state for TDX

---

.changelog/5909.bugfix.md
.changelog/5951.internal.md
.punch_version.py
CHANGELOG.md

https://github.com/oasisprotocol/oasis-core/pull/5912 and https://github.com/oasisprotocol/oasis-core/pull/5952

changelog: Assemble changes for 24.3.1 release

---

.changelog/6024.internal.md
go/runtime/host/sandbox/sandbox.go

go/runtime/host: Introduce a runtime watchdog

---

go/runtime/host/sandbox/sandbox.go

Removing `context.Background()`.

go/runtime/host/sandbox: Add ctx to manager method

---

.changelog/6123.cfg.md
go/runtime/config/config.go
go/runtime/config/config_test.go
go/runtime/host/tdx/qemu.go

go/runtime: Add support for simple per-component networking

---

.changelog/6070.cfg.md
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/scenario/e2e/consensus_prune.go
go/oasis-test-runner/scenario/e2e/runtime/helpers_runtime.go
go/oasis-test-runner/scenario/e2e/runtime/history_reindex.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_governance.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_message.go
go/oasis-test-runner/scenario/e2e/scenario.go
go/runtime/config/config.go
go/runtime/history/indexer.go
go/runtime/registry/registry.go

Improve e2e history reindex test

---

.changelog/6159.cfg.1.md
.changelog/6159.cfg.2.md
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/keymanager.go
go/runtime/bundle/registry.go
go/runtime/config/config.go
go/runtime/host/provisioner/provisioner.go
go/runtime/host/sandbox/host.go
go/runtime/host/sandbox/provisioner.go
go/runtime/host/tdx/cid_pool.go
go/runtime/host/tdx/cid_pool_test.go
go/runtime/host/tdx/qemu.go

go/runtime: Add configurable CID pool

---

go/consensus/cometbft/apps/keymanager/keymanager.go

remove duplicate package imports

chore: remove duplicate package imports

---

.github/workflows/release-dev.yml
.github/workflows/release.yml
.goreleaser.yml
common.mk

ci: Bump goreleaser to 2.9.0

---

go/common/cache/lru/lru_test.go
go/common/dynlib/cache.go
go/common/quantity/quantity.go
go/common/sync/sync_test.go

Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor: use a more modern writing style

---

.changelog/6194.bugfix.md
go/common/sgx/pcs/http.go
go/common/sgx/pcs/pcs.go
go/common/sgx/pcs/service.go
go/common/sgx/pcs/tcb.go

go/common/sgx/pcs: Add support for specific TCB data evaluation numbers

---

go/worker/common/committee/runtime_host.go

make function comment match function name

chore: make function comment match function name

---

go/oasis-node/cmd/keymanager/keymanager.go
go/runtime/host/sandbox/host.go

fix some function names in comment

chore: fix some function names in comment

---

go/common/sgx/pcs/cache.go
go/common/sgx/pcs/cache_test.go
go/common/sgx/pcs/service.go

go/common/sgx: Also cache TCB evaluation data numbers

---

go/beacon/api/vrf.go
go/common/grpc/service.go
go/common/grpc/testing/ping.go
go/governance/api/sanity_check.go
go/p2p/error/error.go
go/staking/api/api.go
go/staking/api/token/prettyprint.go
go/storage/mkvs/node/node.go
go/worker/storage/p2p/sync/protocol.go

fix some minor issues in the comments

chore: fix some minor issues in the comments

---

go/worker/keymanager/churp.go

1. **invalid handoff interval**
The test was flaky because if the submission manager received a status update before confirmation that the submission transaction was included in a block, it would cancel the submission. This led to a retry, even though the context had already been canceled. Retrying the submission overwrote the previously chosen bivariate polynomial, whose verification matrix had already been submitted in the initial transaction. As a result, other nodes were unable to perform proactivization, since the bivariate share could not be derived, as the polynomial no longer matched. As a result, the handoff failed.
This is similar to the attack where a compromised node registers using one polynomial, deletes enclave's local storage, generates another polynomial and derives …

go/oasis-test-runner: Fix flaky CHURP test
