oasisprotocol/oasis-core

go/common/version/version.go
go/tendermint/abci/context.go
go/tendermint/abci/mux.go
go/tendermint/abci/timer.go
go/tendermint/abci/timer_test.go
go/tendermint/apps/beacon/beacon.go
go/tendermint/apps/epochtime_mock/epochtime_mock.go
go/tendermint/apps/keymanager/keymanager.go
go/tendermint/apps/registry/registry.go
go/tendermint/apps/roothash/roothash.go
go/tendermint/apps/scheduler/scheduler.go
go/tendermint/apps/staking/staking.go

Simplifies ABCI timers and transaction execution.

go/tendermint: ABCI interface cleanup

---

.buildkite/pipeline.yml
docker/testing/Dockerfile

- 0.9 seems to have increased the number of segfaults in tests.
- don't fail build if coverage fails

.buildkite/rust-coverage: tarpaulin revert to 0.8.7

---

go/grpc/registry/entity.proto
go/registry/api/api.go
go/registry/grpc.go
go/registry/tendermint/tendermint.go
go/registry/tests/tester.go

Fix for #1947.
This PR:
* removes `GetNodeTransport` function from registry API
* removes `GetNodesForEntity` function from registry API

go/registry: remove obsolete GetNodeTransport API function

---

go/common/node/address.go
go/common/node/address_test.go

~In hindsight the split into IPv4 and IPv6 ranges was not necessary so i'm ok with reverting that part.~ reverted
However the `"::ffff:0:0/96",      // RFC 4291: IPv4-mapped Address` had to be removed as go converts IP4-mapped IPv6 addresses to IPv4 addresses automatically. So that range basically matched all IPv4 addresses.

go/common/node: fix address IsRoutable

---

go/Makefile

This removes filesystem paths from the resulting binary for determinism
regardless of how the host filesystem is setup.  Note that the extended
behavior of this flag is a Go 1.13.x-ism.
Part of #64.

go/Makefile: Set `-trimpath`

---

go/common/crypto/mrae/api/api.go
go/common/crypto/mrae/api/api_test.go
go/common/crypto/signature/signature.go
go/common/crypto/signature/signers/file/file_signer.go
go/common/crypto/signature/signers/memory/memory_signer.go
go/common/node/node_test.go
go/go.mod
go/go.sum
go/registry/api/runtime_test.go

This should force everything to use our ed25519 and x25519.

go: Use a faster ed25519 implementation

---

go/tendermint/apps/staking/genesis.go
go/tendermint/apps/staking/state.go

we should export this, right?
and for Go no to help developers find uses of a struct they're modifying, yuck.

go tendermint staking: export acceptable transfer peers

---

go/common/version/version.go
go/epochtime/tendermint_mock/tendermint_mock.go
go/keymanager/tendermint/tendermint.go
go/oasis-node/cmd/debug/byzantine/scheduler.go
go/registry/tendermint/tendermint.go
go/roothash/tendermint/tendermint.go
go/scheduler/tendermint/tendermint.go
go/staking/tendermint/tendermint.go
go/tendermint/abci/context.go
go/tendermint/abci/mux.go
go/tendermint/api/api.go
go/tendermint/apps/beacon/api.go
go/tendermint/apps/beacon/beacon.go
go/tendermint/apps/epochtime_mock/api.go
go/tendermint/apps/epochtime_mock/epochtime_mock.go
go/tendermint/apps/keymanager/api.go
go/tendermint/apps/keymanager/genesis.go
go/tendermint/apps/keymanager/keymanager.go
go/tendermint/apps/registry/api.go
go/tendermint/apps/registry/genesis.go
go/tendermint/apps/registry/registry.go
go/tendermint/apps/roothash/api.go
go/tendermint/apps/roothash/roothash.go
go/tendermint/apps/scheduler/api.go
go/tendermint/apps/scheduler/scheduler.go
go/tendermint/apps/staking/api.go
go/tendermint/apps/staking/staking.go
go/tendermint/apps/staking/state.go

Use tendermint ABCI events "properly", instead of retrofitting something that resembles the old tag system onto the new API.
Fixes #1853

go/tendermint/abci: Drink the ABCI event flavor-aid

---

go/tendermint/apps/beacon/beacon.go
go/tendermint/apps/beacon/query.go
go/tendermint/apps/beacon/state/state.go
go/tendermint/apps/epochtime_mock/epochtime_mock.go
go/tendermint/apps/keymanager/genesis.go
go/tendermint/apps/keymanager/keymanager.go
go/tendermint/apps/keymanager/query.go
go/tendermint/apps/keymanager/state/state.go
go/tendermint/apps/registry/genesis.go
go/tendermint/apps/registry/query.go
go/tendermint/apps/registry/registry.go
go/tendermint/apps/registry/state/state.go
go/tendermint/apps/roothash/query.go
go/tendermint/apps/roothash/roothash.go
go/tendermint/apps/roothash/state/round.go
go/tendermint/apps/roothash/state/state.go
go/tendermint/apps/scheduler/query.go
go/tendermint/apps/scheduler/scheduler.go
go/tendermint/apps/scheduler/state/state.go
go/tendermint/apps/staking/api.go
go/tendermint/apps/staking/genesis.go
go/tendermint/apps/staking/query.go
go/tendermint/apps/staking/staking.go
go/tendermint/apps/staking/state/cache.go
go/tendermint/apps/staking/state/state.go

This makes it easier to use application state without import cycles.

go/tendermint/apps: Move state to its own module

---

.buildkite/rust/common.sh
README.md
docker/deployment/build_context.sh
go/common/sgx/ias/avr.go
go/common/sgx/ias/avr_test.go
go/common/sgx/ias/ias.go
go/common/sgx/ias/quote.go
go/common/sgx/ias/quote_test.go
go/ias/ias.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/steps.go
go/oasis-node/cmd/debug/byzantine/steps_test.go
go/oasis-test-runner/oasis/args.go
runtime/src/common/sgx/avr.rs
runtime/src/lib.rs

PR for https://github.com/oasislabs/ekiden/issues/2181
This PR:
- adds `OASIS_UNSAFE_ALLOW_DEBUG_ENCLAVES` env variable at compile time which checks AVR attributes Debug flag in rust,
- adds `ias.debug.allow_debug_enclaves` runtime switch for worker which checks AVR attributes Debug flag in go,
- if debug enclaves are not allowed, they are dropped; similarly, if debug enclaves are allowed, production enclaves are dropped.

runtime: check AVR quote for debug bit

---

go/common/crypto/signature/signature.go
go/roothash/api/block/header.go
go/roothash/api/commitment/compute.go
go/roothash/api/commitment/pool.go
go/tendermint/abci/mux.go

Not to be content with the ~2x perf increase we already have over using the runtime library's verify, we can do better since our ed25519 implementation has a Bos-Coster based batch verify.
Fixes #1351.

Use the optimized ed25519 batch verify where applicable

---

go/common/consensus/consensus.go
go/common/crypto/signature/signer.go
go/common/crypto/signature/signers/file/file_signer.go
go/common/crypto/signature/signers/memory/memory_signer.go
go/common/identity/identity.go
go/common/identity/identity_test.go
go/common/node/node.go
go/common/version/version.go
go/grpc/common/common.proto
go/oasis-node/cmd/debug/byzantine/registry.go
go/oasis-node/cmd/debug/byzantine/steps.go
go/oasis-node/cmd/node/node.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/seed.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/dump_restore.go
go/registry/api/api.go
go/tendermint/api/api.go
go/tendermint/apps/scheduler/scheduler.go
go/tendermint/genesis_single.go
go/tendermint/service/service.go
go/tendermint/tendermint.go
go/worker/registration/registration.go

This makes tendermint use it's own Ed25519 key that will never use `ContextSign`, and forces every other key to only use `ContextSign`.
Yes, Ed25519ph/ctx is better.  Yes, I'm still mad about it.  Yes, this breaks everything.  If node operators complain, then they get what they deserve since they're the ones that complained about the plans to use Ed25519ph.
As a unfortunate side-effect, the validator election logs will refer to nodes by their consensus key and not their ID key, because this saves ABCI queries.
In this context, "breaking" also means, "every single node descriptor needs to be regenerated with the new code".
Fixes #2307

Use a distinct Ed25519 key for all tendermint operations

---

go/oasis-node/cmd/genesis/genesis.go
go/staking/api/api.go
go/staking/grpc.go
go/staking/tests/tester.go
go/tendermint/apps/staking/genesis.go
go/tendermint/apps/staking/staking.go
go/tendermint/apps/staking/state/state.go

We'll need this for rewards, so that we can increase the value of the escrow shares that aren't undergoing debonding.
blocks #2288
cc #2290, which also changes slashing to take a fraction. That PR uses a single shared denominator, which is fine.

split escrow between normal tokens and tokens undergoing debonding

---

go/common/crypto/signature/signature.go
go/common/crypto/signature/signer.go
go/common/crypto/signature/signers/file/file_signer.go
go/common/crypto/signature/signers/memory/memory_signer.go
go/common/entity/entity.go
go/common/node/node.go
go/common/sgx/ias/grpc.go
go/common/version/version.go
go/keymanager/api/api.go
go/keymanager/api/policy_sgx.go
go/oasis-node/cmd/keymanager/keymanager.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/registry/api/api.go
go/registry/api/runtime.go
go/registry/api/status.go
go/roothash/api/commitment/compute.go
go/roothash/api/commitment/merge.go
go/roothash/api/commitment/txnscheduler.go
go/staking/api/api.go
go/storage/api/api.go
go/worker/common/p2p/crypto.go
keymanager-runtime/api/src/api.rs
keymanager-runtime/api/src/lib.rs
runtime/src/common/roothash.rs
runtime/src/common/version.rs
runtime/src/rak.rs

Breaking because every single signature ever made is now invalid.
Fixes #2311
Fixes #2318

go/common/crypto/signature: Increase domain separation context length

---

go/common/consensus/consensus.go
go/oasis-node/cmd/genesis/genesis.go
go/tendermint/abci/mux.go

To avoid trivial DoS attacks against the consensus layer, enforce an
upper bound on the maximum transaction size (default: 32 KiB).  At a
future date, this limit can either be made more fine-grained, or the
limit can be adjusted as required.
Inspired by #2022.

go/tendermint/abci: Enforce a maximum transaction size limit

---

go/common/consensus/consensus.go
go/common/node/address.go
go/common/node/address_test.go
go/common/node/node.go
go/grpc/common/common.proto
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/oasis/validator.go
go/registry/api/api.go
go/tendermint/api/api.go
go/tendermint/tendermint.go

Splitting this off from #2300 since it is a self-contained change and having it separate should make it easier to review.

Generalize ConsensusInfo's addresses

---

go/common/crypto/signature/signer.go
go/oasis-test-runner/oasis/seed.go
go/tendermint/crypto/signature.go
go/tendermint/crypto/signature_test.go
go/tendermint/seed.go
go/tendermint/tendermint.go

Not all Signer implementations should provide `UnsafeBytes`, so remove
it from the base interface.  This also switches the seed node to use the
`Identity.ConsensusSigner` instead of `Identity.NodeSigner` for it's
keys.

go/common/crypto/signature: Move `UnsafeBytes`

---

.buildkite/go/build.sh
.buildkite/go/test_and_coverage.sh
.buildkite/pipeline.yml
.buildkite/scripts/download_e2e_test_artifacts.sh
.buildkite/scripts/test_e2e.sh
.buildkite/scripts/upload_coverage.sh
go/.gitignore
go/Makefile
go/oasis-node/cmd/root.go
go/oasis-node/integrationrunner/integration_test.go
go/oasis-node/integrationrunner/utils.go
go/oasis-node/main.go
scripts/build-run-e2e-cov.sh
scripts/integrationrunner-wrapper.sh

add a test that runs the node, so that we can get coverage in integration tests
somehow codecov doesn't merge the coverage files correctly, so add a step to merge them ourselves

experimental e2e coverage hacks

---

go/common/crypto/signature/signer.go
go/common/crypto/signature/signers/file/file_signer.go
go/common/crypto/signature/signers/memory/memory_signer.go
go/go.mod
go/go.sum
go/oasis-test-runner/oasis/seed.go
go/oasis-test-runner/oasis/validator.go
go/tendermint/crypto/priv_val.go
go/tendermint/crypto/signature.go
go/tendermint/seed.go
go/tendermint/tendermint.go

This deprecates all non-context signatures, and forces tendermint to use
our ad-hoc construct via extensions provided with our fork.
Additionally, the tendermint node identity key is now the oasis node
identity key, and the old ConsensusSigner is only used for validator
signatures (proposals/votes).
Fixes #2332

go/tendermint: Use our domain-separation signature scheme

---

.buildkite/pipeline.yml
.buildkite/scripts/test_e2e.sh

tests: Make E2E test coverage computation optional

---

go/tendermint/apps/registry/registry.go
go/tendermint/apps/registry/state/state.go
go/tendermint/apps/staking/state/cache.go

To prevent entities from spamming the registry with node registrations,
limit node registrations by a check against the entity's staking
balance.
`numNodes * lowestNonZeroThreshold < balance` should be sufficiently
forgiving, and will prevent the worst of the abuse.  The lowest
threshold is used because entities registering more nodes isn't a
problem, until it gets excessive.
Fixes #2338

go/tendermint/apps/registry: Limit node registrations by stake

---

go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/oasis/validator.go

Fixes #2341.
This should enable provisioning consensus nodes as before (i.e. without having a pre-provisioned identity).

go/oasis-node/cmd/registry/node: Make consensus address' ID@ optional

---

README.md

Otherwise, the badge shows the last build's status on any branch.

ci: Scope Buildkite build status badge to the master branch

---

go/oasis-node/integrationrunner/integration_test.go

blocks #2344
there's no option to disable messages from the test framework

go oasis-node: close stdout before test framework prints junk

---

go/go.mod
go/go.sum

I made a really stupid mistake in the ed25519 code that required a minor
fix.  This pulls in the new ed25519 and tendermint versions.

go: Bump the ed25519 and tendermint dependencies

---

go/oasis-node/cmd/genesis/genesis.go
go/scheduler/api/api.go
go/tendermint/apps/scheduler/genesis.go
go/tendermint/apps/scheduler/scheduler.go
go/tendermint/apps/staking/state/cache.go
go/tendermint/tests/genesis_testnode.go

Change the placeholder election algorithms to something more in-line with what is actually designed.

go/tendermint/apps/scheduler: Change the election behavior

---

go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/oasis.go
go/scheduler/api/api.go
go/tendermint/apps/scheduler/genesis.go
go/tendermint/apps/scheduler/scheduler.go
go/tendermint/tests/genesis_testnode.go

Meetings happened when I was asleep, so change the algorithm to a
sensible version of what was decided on.
Validators are now picked, 1 per entity (at random if multiple candiates
ran by a single entity are available), in order of decending stake, up
to the maximum number of validators.
Unlike the previous version of this where eligibility was also
restricted to the top-N entities by stake, this election algorithm will
continue to go down the entity list if required in an attempt to fill
out the validator set.
Incentives are now "any entity that is running a validator at the time
of the election, that meets the minimum stake threshold", rather than
being restricted to "top-N" as well.
Note: The "1 per entity" limit is configurable.  If more are allowed,
then each entity (in descending …

go/tendermint/apps/scheduler: Change validator elections again

---

go/consensus/genesis/genesis.go
go/consensus/tendermint/abci/context.go
go/consensus/tendermint/abci/gas.go
go/consensus/tendermint/abci/gas_test.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/apps/staking/state/gas.go
go/consensus/tendermint/tendermint.go
go/consensus/tendermint/tests/genesis_testnode.go
go/oasis-node/cmd/genesis/genesis.go

Fixes #2367 
This adds MaxBlockSize, MaxBlockGas and MaxEvidenceAge and makes the
Tendermint consensus backend use these instead of the default config.
The genesis document generation utility is updated to use the same
defaults as previously.

Add more consensus parameters

---

go/consensus/tendermint/apps/scheduler/scheduler.go

More meetings.  There apparently was a miscommunication, and only
entities that actually get validators elected should be eligible for
rewards.

go/consensus/tendermint/apps/scheduler: Change the validator incentives

---

go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/common/grpc/grpc.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-node/cmd/stake/account.go
go/oasis-node/cmd/stake/stake.go
go/oasis-test-runner/scenario/e2e/common.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/oasis-test-runner/test-runner.go
go/staking/api/api.go

PR for https://github.com/oasislabs/oasis-core/issues/2275
This PR:
- adds new `stake` e2e test based on basic test,
- adds e2e tests for `oasis-node` commands `stake list`, `stake account info`, `stake account gen_transfer`, `stake account gen_burn`, `stake account gen_escrow`, `stake account gen_reclaim_escrow`, and `stake account submit`,
- adds `runCommandWithOutput()` helper to `oasis-test-runner` which executes external command and returns its stdout/stderr for further parsing (e.g. for reading list of stake accounts).
For documentation on stake management, see https://github.com/oasislabs/docs/pull/105.

oasis-node stake tests and docs

---

go/common/crypto/signature/signer.go
go/common/crypto/signature/signer_test.go
go/consensus/tendermint/apps/roothash/genesis.go
go/consensus/tendermint/tests/genesis_testnode.go
go/genesis/file/file.go
go/genesis/tests/tests.go
go/oasis-node/cmd/debug/byzantine/tendermint.go
go/oasis-node/cmd/node/node.go
go/oasis-node/cmd/stake/account.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/halt_restore.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/roothash/api/api.go
go/roothash/api/block/block.go
go/roothash/api/commitment/compute.go
go/roothash/api/commitment/merge.go
go/roothash/api/commitment/pool_test.go
go/roothash/api/commitment/txnscheduler.go
go/staking/api/api.go
go/staking/tests/tendermint.go
go/storage/api/api.go
go/storage/mkvs/urkel/interop/cmd/protocol_server.go
go/storage/tests/tester.go

Fixes #2364 
Note: This is a BREAKING change as it changes the signing contexts. It also makes some contexts dependent on the value of ChainID as specified in the genesis file so specific statements can no longer be mixed between different chains.
Note: This changes the invocations for generating staking transactions as the genesis file must now be passed as an argument (see E2E tests) in order to extract the ChainID.

Enable domain separation by ChainID for specific contexts

---

go/consensus/tendermint/apps/registry/genesis.go
go/oasis-node/cmd/genesis/genesis.go
go/registry/api/api.go

go/registry/api: Allow deployments without a KM operator

---

go/common/crypto/signature/signature.go
go/common/node/node_test.go
go/common/version/version.go
go/registry/api/api.go
go/registry/tests/tester.go

Fixes #2379 
Note: This is a BREAKING change as it makes some existing serialized state invalid.

go/common/crypto/signature: Fail when unmarshaling nil keys

---

go/consensus/tendermint/tendermint.go
go/oasis-test-runner/oasis/args.go

This should correctly match Tendermint's `private_peer_ids` configuration option.
In addition, convert the IDs to lowercase to ensure Tendermint's case sensitive string comparison will check ID equality correctly.
Closes #2387.

go/consensus/tendermint: Change private_peer config to private_peer_id

---

go/consensus/tendermint/apps/roothash/roothash.go
go/oasis-node/cmd/common/grpc/grpc.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/validator.go
runtime/src/transaction/dispatcher.rs
runtime/src/transaction/types.rs

This is why we can't have nice things.
In retrospect, clearly marked foot+gun options are still foot+gun
options.  While the loss of convenience sucks, don't allow exposing the
internal gRPC service over TCP/IP at all.

oasis-node: Deprecate `grpc.debug.port`

---

.buildkite/pipeline.yml
docker/development/Dockerfile
docker/testing/Dockerfile

don't fail when coverage data is corrupted.
also install gocovmerge in the container

ci: put coverage aside

---

.buildkite/pipeline.yml

from #2396, we shouldn't have to install this in the pipeline anymore

ci: clean up remaining tool installation

---

go/common/version/version.go
go/consensus/tendermint/apps/staking/api.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/staking/staking.go
go/genesis/api/api.go
go/grpc/staking/staking.proto
go/oasis-node/cmd/stake/account.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/staking/api/api.go
go/staking/api/commission.go
go/staking/api/commission_test.go
go/staking/api/rewards.go
go/staking/client/client.go
go/staking/grpc.go
tests/fixture-data/stake-cli/staking-genesis.json

it was said that rewards should have some portion split off as "commission" and paid to the node operator, i.e., the entity that owns the node. that's the account where we keep the escrow pools.
it was said that one should only be able to change the commission rate once per some interval. that interval is modeled in the consensus parameter CommissionRateChangeInterval.
it was said that one should have to post a future bound on the commission rate. this distance into the future is modeled in the consensus parameter CommissionRateBoundLead.
each entity's schedule of commission rates and bounds are represented in a CommissionSchedule structure in the account's new `.Escrow.CommissionSchedule` field.
there's a new transaction where an entity can amend its own commission rate and bound …

Staking commission

---

README.md

- Require GNU Make.
- Reword `protoc-gen-go` instructions and add installation instructions when one didn't/can't add `$GOPATH/bin` to the `$PATH`.

README: Improve development and building instructions

---

Makefile
README.md

I find myself frequently going to the README.md to find the right parameters to run the docker container used for development.
I thought it was worth adding this to the Makefile and sharing the change.
Note: There is an old existing issue with the container. Files created inside the container are using the root user id, so later they are not easy to access/delete. This is something that could be fixed by creating the right user ids inside the docker container. This is anyway unrelated to the this and can be fixed later.

Add development docker to Makefile

---

tests/clients/simple-keyvalue/src/main.rs
tests/runtimes/simple-keyvalue/api/src/api.rs
tests/runtimes/simple-keyvalue/src/main.rs

This reverts commit 8f8ea0b22f29d6b763ad751b1a5d8f533b6f62b6.
for #2405
we can't run this test as part of the simple-keyvalue client. the simple-keyvalue client is meant to work under committee changes in the middle of the test (although we should have been more careful that we consistently exercise that).
if we really want to support this, please reinstate this test in a scenario with a fixed compute committee.

Revert "tests: Test the untrusted local storage"

---

go/common/mkdir.go

Also say what permissions and which owner is expected.

go/common/mkdir: add more verbose permission errors

---

Makefile

This PR includes two changes:
- `shell` was missing because the command executed inside a makefile.
- Adds `--rm` so the container is removed on exit. Otherwise, the name remains registered

Makefile docker-shell improvements

---

go/consensus/tendermint/tests/genesis/genesis.go
go/genesis/api/api_test.go
go/oasis-node/cmd/genesis/genesis.go
go/registry/api/api.go
go/registry/api/runtime.go
go/roothash/tests/tester.go
go/staking/api/api.go
go/staking/tests/debug/debug_stake.go
go/staking/tests/tester.go

Part of #1633.
Closes #2358.
This PR adds tests for the functionality implemented in PR #2365, as well as a few new sanity checks.
It also adds self-delegation for the test entity.

Add tests for genesis sanity checks

---

go/common/node/node.go
go/common/version/version.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/registry.go
go/oasis-node/cmd/node/node.go
go/registry/api/api.go
go/registry/tests/tester.go
go/worker/common/p2p/p2p.go
go/worker/compute/worker.go
go/worker/keymanager/init.go
go/worker/keymanager/worker.go
go/worker/merge/worker.go
go/worker/registration/worker.go
go/worker/storage/worker.go
go/worker/txnscheduler/worker.go

Fixes: https://github.com/oasislabs/oasis-core/issues/2400
Changes: 
- `committee.Certificate` & `p2p.ID` are now both required fields in registry (note: this will likely break Genesis SanityCheck on a dump in existing deployments where validators have an invalid P2P ID by default - to mitigate this: should probably allow invalid P2P keys for the next few versions in Genesis)
- optional node addresses are now validated as well in the registry (before addresses were only validated if required)
- registration worker no longer registers with committee addresses unless role requires it, and provides all required IDs

registry validation consistency

---

go/Makefile
go/common/version/version.go
go/oasis-node/cmd/root.go

When talking to node operators I noticed some of them used an older version of `oasis-node` binary. This PR runs `git rev-parse HEAD` during compilation and appends this information to the oasis node's version. Running `oasis-node --version` will now produce:
```
oa@matevz-oa:~/oasis-core/go$ oasis-node/oasis-node --version
Software version: 0.2.0-alpha+d8c21ad1
Runtime protocol version: 0.9.0
Consensus protocol version: 0.18.0
Committee protocol version: 0.6.0
Tendermint core version: 0.32.7
ABCI library version: 0.16.1
```

oasis-node/cmd: append git HEAD commit to oasis-node version

---

go/oasis-node/cmd/identity/identity.go
go/oasis-node/cmd/root.go
go/oasis-test-runner/scenario/e2e/identity_cli.go
go/oasis-test-runner/test-runner.go

Fixes: https://github.com/oasislabs/oasis-core/issues/2413
Usage:
```
oasis-node/oasis-node identity init --datadir /tmp/test
Generated identity files in: /tmp/test
```

go/cmd/identity: add command for generating node identity keys

---

go/oasis-test-runner/log/handlers.go
go/oasis-test-runner/log/log.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/ias.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/log.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/seed.go
go/oasis-test-runner/oasis/sentry.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/byzantine.go
go/oasis-test-runner/scenario/e2e/gas_fees.go
go/oasis-test-runner/scenario/e2e/roothash_messages.go
go/oasis-test-runner/scenario/e2e/sentry.go

This PR:
- Implements log watcher handler factories which makes it easy for each node to get its own set log watcher handlers.
- Enables specifying different log watcher handler factories for each node.
TODO:
Closes #2355.
Closes #2356.

oasis-test-runner: Log watcher fixes and improvements

---

go/common/version/version.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/apps/beacon/query.go
go/consensus/tendermint/apps/epochtime_mock/query.go
go/consensus/tendermint/apps/keymanager/query.go
go/consensus/tendermint/apps/registry/query.go
go/consensus/tendermint/apps/roothash/query.go
go/consensus/tendermint/apps/scheduler/query.go
go/consensus/tendermint/apps/staking/query.go
go/consensus/tendermint/tendermint.go
go/worker/common/worker.go

PR for https://github.com/oasislabs/oasis-core/issues/2122:
* Moves `InitChain()` calls to applications from `BeginBlock()` of mux to `InitChain()` where it should be.
* Temporarily stores the events emitted during `InitChain()` and prepends them to `BeginBlock` events during the first `BeginBlock()` call in mux.
* Replaces immutable state calls with `NewMutableState(abciCtx.State())` in `QueryAt()` functions when called from `InitChain`.

abci: move calling InitChain on apps from BeginBlock to mux InitChain

---

go/common/crypto/signature/signer.go
go/common/crypto/signature/signer_test.go
go/consensus/tendermint/seed.go
go/consensus/tendermint/tendermint.go
go/genesis/api/api.go
go/genesis/api/api_test.go
go/genesis/tests/tests.go
go/oasis-node/cmd/common/consensus/consensus.go
go/oasis-node/cmd/debug/byzantine/tendermint.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/oasis.go
go/staking/gen_vectors/main.go

Fixes #2410 
This is a BREAKING change as it invalidates all signatures that require chain domain separation (e.g., transactions) and also changes the consensus ChainID.

Use genesis document hash instead of ChainID for chain domain separation

---

go/oasis-net-runner/cmd/root.go

This was missed when the debug feature-gating was added and it breaks
the test runner that internally loads the genesis file and does other
operations on test keys.

go/oasis-net-runner: Always set the feature-gate flag

---

go/common/version/version.go
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/signing_rewards.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/consensus/tendermint/apps/staking/votes.go
go/genesis/api/api_test.go
go/scheduler/api/api.go
go/staking/api/api.go

blocks #2434
Give entities a reward on their staked amount when they sign 3/4 of the blocks of an epoch.
Relies on the property that an entity can have at most one node on the validator committee.
In this implementation, the staking mux app counts up how many blocks are created and how many each entity is seen signing. At the end of an epoch, we check which entities meet the 3/4 threshold and add rewards and reset the count.

go staking: reward for signing blocks

---

go/consensus/tendermint/apps/registry/transactions.go
go/registry/api/api.go
go/registry/tests/tester.go

go/registry: Reject node registrations with duplicate keys

---

.buildkite/go/lint.sh
.buildkite/pipeline.yml
Makefile
common.mk
go/Makefile

This will make integrating release tooling easier since it makes information such as version info and linker flags available from all Makefiles.

Reorganize Makefiles

---

.buildkite/pipeline.yml
.buildkite/scripts/merge_coverage.sh
.buildkite/scripts/test_e2e.sh
go/common/crypto/hash/hash.go
go/common/namespace.go

Fixes #2476
* ~buildkite: Add more useful artifacts for certain tests.~ (Too spammy)

 Hash should be base64 encoded in JSON

---

go/sentry/api/grpc.go

Checked other clients as well, seems like all others are fine.
TODO:

go/sentry/grpc: fix GetConsensusAddresses client method

---

common.mk

If `make go` is called from project's root directory, then the `common.mk` file gets included twice, meaning `export GOLDFLAGS += foo` would recursively add `foo` to the `GOLDFLAGS` variable.

Makefile: Only set GOLDFLAGS if it doesn't exist yet

---

go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/common/flags/flags.go
go/oasis-node/cmd/node/node.go
go/oasis-node/cmd/node/unsafe_reset.go
go/oasis-node/cmd/root.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/dump_restore.go
go/oasis-test-runner/scenario/e2e/halt_restore.go

Fixes: #2435
As it probably can be deduced from the name, this sub-command will
reset the node back to a freshly provisioned state (preserving any
key material if it exists).
The `-n` (`--dry_run`) flag will go through the process without actually
removing state, so that it is possible to preview the results of
executing the command.
Usage: `oasis-node unsafe-reset --datadir=/path/to/datadir`

go/oasis-node: Add the `unsafe-reset` sub-command

---

go/oasis-node/cmd/common/consensus/consensus.go
go/oasis-node/cmd/debug/storage/export.go
go/oasis-node/cmd/debug/storage/storage.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/scenario/e2e/dump_restore.go
go/storage/init.go

Fixes #1845
Replaces #1847
Mostly straight forward, instead of CBOR I ended up settling on JSON.  I doubt we will need to use this tool all that often anyway.

go/oasis-node/cmd/debug/storage: Add the `export` sub-command

---

go/Makefile

There's no need to print the entire `go build` line with all the
flags and everything.

Makefile: Reduce noise

---

.changelog/1845.feature.md
.changelog/2377.removal.md
.changelog/2435.feature.md
.changelog/2482.feature.md
.changelog/2484.bugfix.md
.changelog/2492.removal.md
.changelog/README.md
.changelog/template.md.j2
.github/workflows/ci.yml
CHANGELOG.md
CONTRIBUTING.md
towncrier.toml

Add CHANGELOG.md and use towncrier for automatic assembly

---

.changelog/2245.feature.md
.changelog/2246.feature.md
go/Makefile
go/common/fuzz/fuzz.go
go/consensus/tendermint/abci/mux_mock.go
go/consensus/tendermint/fuzz/.gitignore
go/consensus/tendermint/fuzz/fuzz.go
go/consensus/tendermint/fuzz/gencorpus/main.go
go/go.mod
go/go.sum
go/storage/fuzz/.gitignore
go/storage/fuzz/fuzz.go
go/storage/fuzz/gencorpus/main.go

Add fuzzing for transaction methods

---

.changelog/2498.feature.md
go/consensus/tendermint/apps/staking/transactions.go
go/staking/api/api.go

ostensibly for faucet purposes while we run the rest of the network with transfers disabled, this lets us identify a whitelist of accounts from which we allow transfers when otherwise transfers are disabled.
cc #2481

go staking: undisable transfers for some senders

---

.changelog/2503.trivial.md
go/consensus/tendermint/apps/staking/transactions_test.go

it was desired that we have tests for this transfer permissions engine

go staking: add isTransferPermitted tests

---

.changelog/2426.breaking.md
Cargo.lock
go/consensus/tendermint/apps/roothash/genesis.go
go/consensus/tendermint/apps/roothash/roothash.go
go/genesis/tests/tester.go
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/debug/storage/export.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/halt_restore.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/api/api.go
go/registry/api/runtime.go
go/registry/tests/tester.go
go/roothash/api/api.go
keymanager-runtime/api/Cargo.toml
keymanager-runtime/api/src/api.rs
keymanager-runtime/api/src/lib.rs
runtime/src/common/bytes.rs
runtime/src/common/mod.rs
runtime/src/common/registry.rs

PR for #2426:
- replaces `roothash.Genesis.Blocks` with map storing `api.RuntimeGenesis` objects,
- adds `RuntimeGenesis.Round` and `--runtime.genesis.round` flag,
- on `InitChain()` generates runtime genesis block using `RuntimeGenesis` instead of block,
- replaces `RuntimeGenesis.StorageReceipt` with `StorageReceipts` i.e. one receipt per storage node,
- adds sanity checks for `RuntimeGenesis` including `StorageSignatures` verification of `StateRoot` and tests for it,
- adds `RuntimeGenesis` struct to rust,
- adds base64 serialization/deserialization of `Bytes` in rust.

roothash/api: rename Genesis.Blocks -> RuntimeStates

---

.buildkite/longtests.pipeline.yml
.changelog/2505.trivial.md
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/common.go
go/oasis-test-runner/scenario/e2e/keymanager_restart.go
go/oasis-test-runner/scenario/e2e/txsource.go
go/oasis-test-runner/test-runner.go
scripts/run-e2e-txsource.sh
scripts/txsource-wrapper.sh

This adds short versions of the txsource e2e tests for use in regular CI tests. Adding these to the regular CI tests is supposed to keep the system from rotting.
The run-e2e-txsource.sh script is removed. Use .buildkite/scripts/test_e2e.sh with `-t txsource-transfer` instead.

txsource: short runner

---

.changelog/2507.trivial.md
go/oasis-test-runner/scenario/e2e/txsource.go
scripts/txsource-wrapper.sh

We need this to support the test coverage hacks in integration tests.

scripts: unhardcode node binary in txsource wrapper

---

.changelog/2511.trivial.md
.changelog/README.md

The `breaking` type was introduced in #2499.

changelog: Update README for the new breaking type

---

.changelog/2528.trivial.md
go/roothash/tests/tester.go
go/worker/txnscheduler/tests/tester.go

There's been intermittent failures on certain systems (read: my laptop)
in some tests for a while, that have recently gotten worse.
This adds a helper `MustTransitionEpoch` that monitors the roothash
backend for a block in the requested epoch, that can be called after
the force advancing the epoch with the mock backend, to ensure that the
roothash's view of the world is caught up enough where required.

go/oasis-node: Reduce node test flakiness on certain systems

---

.changelog/2459.breaking.md
go/consensus/tendermint/apps/keymanager/genesis.go
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/registry/state/state.go
go/consensus/tendermint/apps/registry/transactions.go
go/registry/api/api.go
go/registry/tests/tester.go

PR for #2459:
- adds a check whether key manager ID of the newly registered runtime points to a valid key manager in the registry.

add key manager ID check

---

.gitignore
.punch_config.py
Makefile
common.mk

Closes #2523. Closes #2512.
Note, documentation on installing the [Punch](https://punch.readthedocs.io/) utility for computing the next version will come as part of #2457.

More release automation

---

.changelog/2542.bugfix.md
go/runtime/client/client.go
tests/clients/simple-keyvalue/src/main.rs

Fixes #2531 
The crash reported in the above issue is actually result of two separate problems, both of which should be fixed by this PR:
* The runtime client endpoint should return empty sequences instead of nil as serde doesn't know how to decode a `NULL` when the expected type is a sequence.
* The simple-keyvalue client used a hardcoded round number in the query (`3`) which can easily be incorrect due to the time at which the client is called.

Fix simple-keyvalue-client crash

---

.buildkite/deploy.pipeline.yml
.buildkite/longtests.pipeline.yml
.buildkite/pipeline.yml
.changelog/2543.trivial.md

since /tmp will be put on /tmpfs on ci hosts, artifacts should be persisted through /var/tmp

ci: persist build artifacts in /var/tmp

---

.changelog/2502.feature.md
go/oasis-node/node_test.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/compute.go
go/registry/api/api.go
go/worker/txnscheduler/api/api.go
go/worker/txnscheduler/committee/node.go
go/worker/txnscheduler/init.go
go/worker/txnscheduler/worker.go

Use CheckTx in transaction scheduler

---

.changelog/2458.trivial.md
.changelog/2537.trivial.md
Makefile
common.mk

Makefile: Add tag-next-release target

---

.changelog/2538.feature.md
go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/registry/transactions.go
go/keymanager/api/api.go
go/registry/api/api.go

Based on #2504 
Fixes #2538 
This is a performance optimization to avoid loading a list of all registered
runtimes into memory in cases when only a specific runtime is actually needed.

go/consensus/tendermint/apps: Avoid loading all registered runtimes

---

.changelog/2529.breaking.md
.changelog/2529.feature.1.md
.changelog/2529.feature.2.md
go/Makefile
go/common/version/version.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/runtime_dynamic.go
go/oasis-test-runner/scenario/e2e/runtime_prune.go
go/oasis-test-runner/test-runner.go
go/registry/api/runtime.go
go/worker/common/host/protocol/types.go
go/worker/common/host/sandboxed.go
go/worker/common/host/sandboxed_test.go
runtime/src/common/version.rs
runtime/src/init.rs
runtime/src/lib.rs
runtime/src/protocol.rs
runtime/src/types.rs
tests/clients/simple-keyvalue/src/main.rs
tests/runtimes/simple-keyvalue/api/src/api.rs
tests/runtimes/simple-keyvalue/src/main.rs

PR for https://github.com/oasislabs/oasis-core/issues/2519 and https://github.com/oasislabs/oasis-core/issues/1062:
- adds `RuntimeID` field to `WorkerInfoRequest`,
- adds `runtime_id` to runtime `Protocol`
- adds check to simple-keyvalue client that remote `runtime_id` equals the CLI passed one,
- adds new `multiple-runtimes` e2e test which spins up 2 runtimes on each compute node with shared runtime binary,
- adds `make force-test` rule to go/ for running *all* tests without taking caching into account,
- adds sorting scenarios alphabetically when calling `oasis-test-runner list`.

host/protocol: add RuntimeID to WorkerInfoRequest and use it

---

.changelog/2559.trivial.md
.github/workflows/ci.yml
Makefile
common.mk

This will allow back-porting fixes from an upcoming release and prepare a stable/bugfix release with versions of the form `YY.MINOR.MICRO`.
The workflow will look like (e.g. for a `20.1.1` release):
```
git checkout -b stable/20.1.x v20.1
git push -u origin stable/20.1.x
git checkout -b tjanez/stable/20.1.x/backport-foo
... backport foo change...
git push -u origin tjanez/stable/20.1.x/backport-foo
... create a pull request against the stable/20.1.x branch and merge it...
... create other pull requests and merge them (if necessary) ...
... once ready to prepare a minor release ...
git checkout -b tjanez/stable/20.1.x/changelog-20.1.1
RELEASE_BRANCH=stable/20.1.x NEXT_VERSION=20.1.1 make changelog
git push -u origin tjanez/stable/20.1.x/changelog-20.1.1
... create a pull request against …
```

Release tooling improvements

---

.changelog/2107.breaking.md
go/common/node/node.go
go/consensus/tendermint/apps/beacon/beacon.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/merge.go
go/oasis-node/cmd/debug/byzantine/scheduler.go
go/oasis-node/cmd/debug/byzantine/scheduler_test.go
go/oasis-node/cmd/node/node.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-node/node_test.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/oasis_test.go
go/oasis-test-runner/scenario/e2e/byzantine.go
go/oasis-test-runner/scenario/e2e/runtime_dynamic.go
go/registry/api/api.go
go/registry/tests/tester.go
go/worker/compute/init.go
go/worker/computeenable/init.go
go/worker/merge/init.go
go/worker/merge/worker.go
go/worker/txnscheduler/init.go
go/worker/txnscheduler/worker.go

We're removing the separation among registering nodes for the compute, merge, and transaction scheduler roles. You now have to register for and enable all or none of these roles, under a new, broadened, and confusing--you're welcome--term "compute."
non-changelog data:
- the `.enabled` flag is moved to its own package, `computeenable`. this is because there are dependencies leading toward the merge worker package, but that would be a weird place to put the compute enable flag.
- a backwards incompatible change is made to the on-chain representation of registered nodes, and no migration is provided. you're welcome.
closes #2107

go node: unite compute, merge, and transaction scheduler roles

---

.changelog/2545.trivial.1.md
.changelog/2545.trivial.2.md
go/common/grpc/grpc.go
go/common/node/node.go
go/common/node/node_test.go
go/oasis-test-runner/scenario/e2e/basic.go
go/oasis-test-runner/scenario/e2e/runtime_dynamic.go
go/worker/common/host/interface.go
go/worker/common/host/mock.go
go/worker/common/host/sandboxed.go
go/worker/common/host/sandboxed_test.go
go/worker/common/runtime_host.go
go/worker/executor/committee/node.go
go/worker/executor/worker.go
go/worker/keymanager/init.go
go/worker/keymanager/worker.go
go/worker/merge/committee/node.go
go/worker/merge/worker.go
go/worker/registration/worker.go
go/worker/storage/committee/node.go
go/worker/storage/worker.go
go/worker/txnscheduler/committee/node.go
go/worker/txnscheduler/worker.go

See #1794 
This replaces the previous mechanism which was implemented twice, first
to receive the CapabilityTEE and second to receive the runtime version.
The new mechanism is based on events so that the caller is able to get
notified when changes occur (e.g., on restarts).

go/worker/common/host: Emit events on (re)starts/failures

---

.changelog/2566.bugfix.md
go/extra/stats/cmd/stats.go

go/extra/stats: handle nil-votes and non-registered nodes

---

.changelog/2567.bugfix.md
go/oasis-node/cmd/stake/stake.go

go/oasis-node: Include account ID in `stake list -v` cmd

---

.changelog/2362.breaking.md
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/sentry.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go
go/worker/common/config.go
go/worker/common/configparser/configparser.go
go/worker/registration/worker.go
go/worker/sentry/worker.go

Fixes: #2362 
This changes the sentry configuration to:
- on sentry node:
- single flag:  `--tendermint.sentry.upstream_address` 
- on upstream node:
- `--worker.registration.sentry.address`, `--worker.registration.sentry.cert_fiile` (for querying addresses at registration time)
-  `--tendermint.disable_peer_exchange` 
One regression to the previous sentry setup is that the upstream node no longer sets "tendermint.persistent_peers" to sentry nodes. I think this is fine, since in any real sentry node setup, the sentry nodes are the only nodes connecting to the upstream node, so not sure if setting persistent peers is/was really needed/useful. Let me know what others think.
Also updated the E2E tests so that nodes behind sentries do not connect to the seed node, since currently the sentry …

go/sentry: simplify tm sentry flags

---

keymanager-runtime/src/main.rs

It seems we forgot to change this in #2529.

keymanager-runtime: Use dynamically assigned runtime ID

---

.changelog/2546.breaking.md
go/Makefile
go/common/version/version.go
go/consensus/tendermint/abci/context.go
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/scheduler_test.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/node_test.go
go/registry/api/runtime.go
go/registry/tests/tester.go
go/roothash/api/block/block.go
go/roothash/api/block/header.go
go/roothash/api/block/header_test.go
go/roothash/api/commitment/pool.go
go/roothash/api/commitment/pool_test.go
go/roothash/tests/tester.go
go/runtime/client/watcher.go
go/runtime/transaction/transaction.go
go/runtime/transaction/transaction_test.go
go/scheduler/api/api.go
go/scheduler/tests/tester.go
go/worker/common/committee/group.go
runtime/src/common/roothash.rs
runtime/src/transaction/tree.rs

PR for #2527:
- adds `KindInvalid` to `RuntimeKind` enum,
- adds `KindInvalid` to `CommitteeKind` enum,
- adds `ContextInvalid` to `ContextType` enum,
- adds `HeaderInvalid` to `HeaderType` enum,
- adds `Invalid` to `artifactType` enum both in go and rust,
- in `CommitteeKind` enum renames `KindExecutor` -> `KindComputeExecutor`, `KindTransactionScheduler` -> `KindComputeTxnScheduler`, and `KindMerge` -> `KindComputeMerge`.

enum checks

---

.changelog/2580.breaking.md
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/supplementarysanity/checks.go
go/genesis/api/api.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/oasis.go
go/registry/api/api.go

Node expirations being unbound is likely a bad idea.  This adds a
consensus parameter that limits the maximum lifespan of a node
registration, to a pre-defined number of epochs (default 5).
Additionally the genesis document sanity checker is now capable of
detecting if genesis node descriptors have invalid expirations.
Fixes #2580

go/registry: Add `ConsensusParams.MaxNodeExpiration`

---

.changelog/2586.bugfix.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/apps/staking/state/gas.go
go/consensus/tendermint/tendermint.go

A validator node should always accept own transactions (signed by the node's
identity key) regardless of the configured gas price.

go/consensus/tendermint: Always accept own transactions

---

.changelog/2571.bugfix.md
.changelog/2590.internal.md
.github/workflows/ci-lint.yml
.github/workflows/ci-reproducibility.yml
.github/workflows/release.yml
.goreleaser.yml
README.md
common.mk

Fixes #2571.
An example of how the new reproducibility workflow reports error: https://github.com/oasislabs/oasis-core/runs/405500021.

Fix GoReleaser oasis-node build reproducibility issue

---

.changelog/2058.breaking.md
.changelog/2598.bugfix.md
.changelog/2599.breaking.md
go/common/crypto/signature/signature.go
go/common/crypto/signature/signers/memory/memory_signer.go
go/common/crypto/tls/cert.go
go/common/identity/identity.go
go/common/identity/identity_test.go
go/common/node/node.go
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/registry/registry.go
go/consensus/tendermint/apps/registry/state/state.go
go/consensus/tendermint/apps/registry/transactions.go
go/genesis/tests/tester.go
go/oasis-node/cmd/debug/byzantine/registry.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/api/api.go
go/registry/api/sanity_check.go
go/registry/tests/tester.go
go/worker/registration/worker.go

Fixes #2058
Fixes #2598
Fixes #2599

registry: bug fixes

---

.changelog/2594.breaking.md
go/consensus/tendermint/tests/genesis/genesis.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/entity.go
go/registry/api/api.go
go/registry/api/sanity_check.go
go/worker/registration/worker.go

This feature is mostly useful for testing and should not be used in
production, basically ever.
Note: Breaking if anyone happens to use said feature.
Fixes #2594

go/registry: Disallow entity signed node registrations

---

go/oasis-node/cmd/genesis/genesis.go
keymanager-runtime/src/main.rs
runtime/src/common/roothash.rs

Trivial follow-up of https://github.com/oasislabs/oasis-runtime/pull/958:
* fixes comments in `runtime/common` and `genesis init` command for providing roothash runtime states file,
* fixes unused compilation warnings in keymanager-runtime.

trivial: fix some comments, warnings

---

.changelog/2589.internal.md
go/common/grpc/policy/policy.go
go/consensus/tendermint/tests/evidence.go
go/consensus/tendermint/tests/genesis/genesis.go
go/genesis/genesis_test.go
go/genesis/tests/helpers.go
go/keymanager/api/api.go
go/keymanager/api/grpc.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/oasis.go
go/registry/api/api.go
go/registry/api/sanity_check.go
go/roothash/api/commitment/pool_test.go
go/runtime/enclaverpc/api/api.go
go/storage/mkvs/urkel/interop/cmd/protocol_server.go
go/storage/tests/tester.go

go/genesis: Fix genesis tests and registry sanity checks

---

.changelog/2611.bugfix.md
go/storage/mkvs/urkel/node/node.go

PR for https://github.com/oasislabs/oasis-core/issues/2611:
- instead of storing a reference to external data, properly copy it to the node.

go/storage/mkvs/urkel: fix invalid memory access when unmarshalling

---

.changelog/2614.feature.md
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/supplementarysanity/checks.go
go/oasis-node/cmd/debug/debug.go
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
go/registry/api/api.go
go/registry/api/sanity_check.go

> Crawling in my skin
> These wounds, they will not heal

go/registry: Handle the old and busted node descriptor envelope

---

.changelog/2620.feature.md
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go

The node.RolesMask bit definitons have changed since the last major
release deployed to the wild, so support migrating things by rewriting
the node descriptor.
Note: This assumes that signature validation in InitChain is disabled.

go/oasis-node/cmd/debug/fixgenesis: Support migrating Node.Roles

---

.changelog/2628.bugfix.md
go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/keymanager/state/state.go
go/keymanager/api/api.go

This fixes panics in keymanager client if key manager doesn't exist.

go/tendermint/keymanager: error Status() if keymanager doesn't exist

---

.changelog/2438.trivial.md
go/oasis-node/cmd/common/grpc/grpc.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/ias.go
go/oasis-test-runner/scenario/e2e/txsource.go

PR for https://github.com/oasislabs/oasis-core/issues/2438:
* introduces new `--wait` flag which explicitly waits for gRPC address to become available,
* automatically prepends a `unix:` prefix, if the address is a local file name and prints a warning message.

go/cmd: add explicit --wait flag, prepend unix: if user forgets it

---

.changelog/2627.bugfix.md
go/consensus/tendermint/apps/registry/registry.go
go/consensus/tendermint/apps/staking/slashing.go
go/consensus/tendermint/apps/staking/slashing_test.go
go/consensus/tendermint/apps/staking/staking.go

Based on #2630 
Fixes #2627 
TODO

go/consensus/tendermint/apps/staking: Fix epochtime overflow

---

.changelog/2625.breaking.md
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/proposing_rewards.go
go/consensus/tendermint/apps/staking/signing_rewards.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/votes.go
go/staking/api/api.go

- a larger portion of the fees
- an additional reward

Special rewards for block proposer

---

.changelog/2634.breaking.md
go/consensus/tendermint/abci/state.go

from https://github.com/oasislabs/oasis-core/pull/2625#discussion_r373370431
We've been using `blockHeight+1` for getting the epoch time except for on blockHeight=1. The hypothesis in this PR is that we don't need that special case.

go tendermint: mux offset block height consistently

---

.changelog/2639.bugfix.md
go/oasis-node/cmd/registry/runtime/runtime.go

`vipper.IsSet` always returns true if key was bound to a PFlag. Also did check, and this is the only place where we're using `viper.IsSet`.
Apparently could also use:
```
flag := cmd.Flags().Lookup("flag-name")
if flag == nil || !flag.Changed {
continue
}
```
but this seems clearer?

go/cmd/registry/runtime: fix provisioning a runtime without keymanager

---

go/oasis-node/cmd/debug/control/control.go
go/oasis-node/cmd/debug/debug.go

Closes: #2622
Mostly taken back from: https://github.com/oasislabs/oasis-core/commit/b1bd66e0899e0a2c728337e31bc73aabb9f17d9e
At this time this is still needed for oasis-runtime e2e tests: https://github.com/oasislabs/oasis-runtime/blob/master/.buildkite/scripts/test_e2e.sh and benchmarks.

cmd/debug/control: debug set-epoch/wait-nodes commands

---

.changelog/2643.bugfix.md
go/consensus/tendermint/apps/registry/transactions.go
go/registry/api/api.go

`rt.Genesis.StateRoot.IsEmpty` check should only be done when registering (otherwise `supplementarysanity` checks are failing)

registry/api/sanitycheck: move genesis stateroot check into registration

---

.buildkite/pipeline.yml

temoporary, until: https://github.com/oasislabs/oasis-core/issues/2644

.buildkite/pipeline: require large agents for coverage step

---

.changelog/2508.feature.md
.changelog/2649.breaking.md
.changelog/2649.bugfix.md
go/oasis-node/cmd/control/control.go
go/oasis-node/cmd/debug/tendermint/tendermint.go
go/oasis-node/cmd/identity/identity.go
go/oasis-node/cmd/identity/tendermint/tendermint.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/scenario/e2e/identity_cli.go
go/oasis-test-runner/scenario/e2e/registry_cli.go

Among other things, closes #2508.

Various CLI improvements

---

.changelog/2646.breaking.md
go/consensus/tendermint/tendermint.go

Fixes #2597
TODO: Update sentry node config doc: https://docs.oasis.dev/operators/sentry-node.html#configuring-the-oasis-sentry-node

go/consensus/tendermint: Expose more P2P config params

---

.changelog/2647.breaking.md
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/proposing_rewards.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/genesis/genesis_test.go
go/oasis-node/cmd/genesis/genesis.go
go/staking/api/api.go
go/staking/api/api_test.go
go/staking/api/sanity_check.go
go/staking/tests/debug/debug_stake.go
tests/fixture-data/gas-fees-runtimes/staking-genesis.json
tests/fixture-data/gas-fees/staking-genesis.json

- go staking: new fee distribution
- go staking: adjust block proposing staking reward by included signatures

staking: more reward for more signatures

---

go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go

registry doc was coming out empty due to this

go oasis-node: use references to update genesis doc

---

.changelog/2652.bugfix.md
go/consensus/tendermint/seed.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
go/registry/api/api.go

For the purpose of migration.
Predictably, disabling this sort of thing is error prone. :/

go: Disable additional signature verification for migration

---

.changelog/2615.bugfix.md
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/supplementarysanity/checks.go
go/consensus/tendermint/seed.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
go/registry/api/api.go
go/registry/api/sanity_check.go

Now that the migration has hopefully been done, re-enable all of the
signature verification that was disabled for the sake of allowing for
migration.
Fixes #2615

go: Re-enable signature verification disabled for migration

---

.changelog/2406.breaking.md
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/registry/registry.go
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/tests/genesis/genesis.go
go/genesis/genesis_test.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/oasis-test-runner/scenario/e2e/runtime_dynamic.go
go/registry/api/api.go
go/registry/api/sanity_check.go

See #2406 
Fixes #2445 (together with #2642)

go/registry: Enable non-genesis runtime registrations by default

---

.changelog/.markdownlint.yml
.changelog/2406.breaking.md
.changelog/2572.internal.md
.changelog/2638.breaking.md
.changelog/2642.breaking.1.md
.changelog/2642.breaking.2.md
.changelog/2647.breaking.md
.changelog/2662.internal.1.md
.changelog/2662.internal.2.md
.changelog/README.md
.github/workflows/ci-lint.yml
.markdownlint.yml
CHANGELOG.md
CONTRIBUTING.md
Makefile
README.md
common.mk
docs/bigint.md
docs/consensus/staking.md
docs/consensus/transactions.md
docs/encoding.md
docs/release-process.md
docs/runtime-id.md
go/extra/README.md
go/extra/stats/README.md
tests/fixture-data/txsource/README.md

Add markdownlint

---

.changelog/2670.internal.md
go/common/crypto/signature/signer.go
go/common/crypto/signature/signers/file/file_signer.go
go/consensus/tendermint/crypto/signature.go
go/consensus/tendermint/crypto/signature_test.go
go/consensus/tendermint/seed.go
go/consensus/tendermint/tendermint.go

No, that's German for "The UnsafeSigner, The"

go/consensus/tendermint: Don't use `UnsafeSigner`

---

go/consensus/tendermint/db/badger/badger.go
go/consensus/tendermint/db/tests/tester.go

Here's an alternate implementation.
- Responsibility for correct seeking is moved down to BadgerDB.
- Responsibility for caching keys and values is moved up or down.
- Bounds checking is moved to Valid.
- Methods now don't call Close internally. Remember to call it yourself and don't abuse Valid.

go tendermint db: restructure badger iterator

---

.changelog/2671.bugfix.md
go/staking/api/sanity_check.go

Detect when a (debonding) delegation is specified for a nonexisting account and report an appropriate error.

go/staking/api: Fix genesis sanity check for nonexisting accounts

---

.changelog/2673.trivial.md
Makefile

This is a workaround needed to avoid recompilations in newer cargo nightly
builds.
See https://github.com/oasislabs/oasis-core/issues/2579 for more details.

Makefile: build-runtimes explicitly set target-dir

---

.changelog/2650.breaking.md
.changelog/2650.internal.1.md
.changelog/2650.internal.2.md
go/common/version/version.go
go/control/debug.go
go/epochtime/api/api.go
go/oasis-node/cmd/node/node.go
go/oasis-node/node_test.go
go/oasis-test-runner/scenario/e2e/multiple_runtimes.go
go/runtime/client/client.go
go/runtime/client/watcher.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go
go/worker/common/worker.go
go/worker/compute/executor/committee/node.go
go/worker/compute/merge/committee/node.go
go/worker/compute/txnscheduler/api/api.go
go/worker/compute/txnscheduler/committee/node.go
go/worker/compute/txnscheduler/service.go
go/worker/compute/txnscheduler/tests/tester.go
go/worker/keymanager/worker.go
go/worker/storage/committee/node.go

PR for #1062: 
- runtime/client: add expectedEpochNumber parameter to SubmitTx call,
- txnscheduler/committee/node: check whether expectedEpochNumber matches the local one,
- executor/node, merge/node: abort, if state change detected,
- e2e/multiple-runtimes:
- reduce all group sizes to 1 with no backups,
- use epochTime mock,
- add new numComputeWorkers parameter,
- cmd/node/node.go, common/commmittee/node.go, common/worker.go, runtime/client/client.go, worker/common/committee/group.go: access `RootHash`, `Scheduler`, `Beacon`, `KeyManager`, `EpochTime`, and `Registry` fields indirectly using `consensus` member.

send expected epoch along when calling SubmitTx

---

.changelog/2672.breaking.md
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/apps/staking/transactions_test.go
go/staking/api/api.go

With this, we'll be able to set up special accounts in the genesis document where they're not permitted to transfer staking tokens until a the specified epoch time. They can still delegate during that time.

go staking: add per-account lockup

---

Makefile

Also using env var setting for consistency, as `cargo elf2sgxs` doesn't support the `--target-dir` flag

Makefile: set correct target-dir for elf2sgxs

---

.changelog/2554.bugfix.md
go/consensus/tendermint/seed.go

for record keeping: we put these bandaids on the seed node to skip over the unroutable nodes in the genesis document

"unfatalize"

---

.buildkite/pipeline.yml
.buildkite/scripts/skip_if_only_docs_changes.sh
.changelog/2573.internal.md

in this PR, we skip some heavy Go and Rust builds and tests when changes are only in docs
blocks #2573 
test: https://github.com/oasislabs/oasis-core/pull/2682

ci: skip some steps for non-code changes

---

.changelog/2693.feature.md
go/extra/stats/cmd/stats.go

sample output:
```
$ ./go/extra/stats/stats entity-signatures --address unix:../testnet/quest-c/serverdir/node/internal.sock --start-block 0 --end-block 100 --top-n 100
|Rank |Entity ID                                                       |Nodes |Signatures| Proposals|
-----------------------------------------------------------------------------------------------------
|1    |p6UuBtDdJQNJl513U7caGqALObw5obOgpQ6dwpgnlpI=                    |     1|       100|         2|
|2    |rUywd4hma3h5cmKGkeYskIRAdrxqw6OBPi6JfuCOWHs=                    |     1|       100|         2|
|3    |eTpIJnjpMlm+qEgsW76eWYNxsh2xwLdlbIPXjXAoYTQ=                    |     1|       100|         2|
|4    |5s7OfLEjIrePZ35UnkwrPQ7YVyzd5HAiddbWZKYLo5w=                    |     1|       100|         2|
|5 …
```

stats: figure out how many blocks they propose

---

.buildkite/pipeline.yml
.changelog/2695.internal.md
go/consensus/tendermint/abci/mux_mock.go
go/consensus/tendermint/apps/staking/proposing_rewards.go
go/consensus/tendermint/fuzz/fuzz.go
go/storage/fuzz/fuzz.go
go/storage/fuzz/gencorpus/main.go

Make build-fuzz work again, test it on CI

---

.changelog/2691.bugfix.md
.changelog/2691.internal.1.md
.changelog/2691.internal.2.md
go/oasis-node/cmd/debug/byzantine/executor.go
go/oasis-test-runner/scenario/e2e/storage_sync.go
go/runtime/transaction/transaction.go
go/storage/api/root_cache.go
go/storage/mkvs/urkel/checkpoint/chunk.go
go/storage/mkvs/urkel/commit.go
go/storage/mkvs/urkel/debug.go
go/storage/mkvs/urkel/insert.go
go/storage/mkvs/urkel/iterator.go
go/storage/mkvs/urkel/iterator_test.go
go/storage/mkvs/urkel/lookup.go
go/storage/mkvs/urkel/overlay.go
go/storage/mkvs/urkel/overlay_test.go
go/storage/mkvs/urkel/prefetch.go
go/storage/mkvs/urkel/remove.go
go/storage/mkvs/urkel/syncer_test.go
go/storage/mkvs/urkel/tree.go
go/storage/mkvs/urkel/urkel.go
go/storage/mkvs/urkel/urkel_test.go
runtime/src/storage/mkvs/urkel/tree/iterator.rs

Extracted from #2674 for easier review.
Contains a fix for an MKVS iterator bug.

MKVS fixes and improvements

---

.changelog/2698.bugfix.1.md
.changelog/2698.bugfix.2.md
.changelog/2698.internal.md
go/Makefile
go/storage/client/tests/tests.go
go/storage/mkvs/urkel/fuzz/.gitignore
go/storage/mkvs/urkel/fuzz/fuzz.go
go/storage/mkvs/urkel/fuzz/gencorpus/main.go
go/storage/mkvs/urkel/insert.go
go/storage/mkvs/urkel/node/key.go
go/storage/mkvs/urkel/node/key_test.go
go/storage/mkvs/urkel/remove.go
go/storage/mkvs/urkel/testdata/case-1.json
go/storage/mkvs/urkel/testdata/case-2.json
go/storage/mkvs/urkel/testdata/case-3.json
go/storage/mkvs/urkel/tests/fixture.go
go/storage/mkvs/urkel/urkel_test.go
runtime/src/storage/mkvs/urkel/tree/node.rs
runtime/src/storage/mkvs/urkel/tree/node_test.rs
runtime/src/storage/mkvs/urkel/tree/remove.rs

Adds fuzzers specifically for MKVS tree operations and fixes a bug found during fuzzing (added as unit test).

 go/storage/mkvs: Add MKVS fuzzing

---

.changelog/2697.internal.md
.changelog/README.md
.changelog/template.md.j2

Update the Change Log template to list multiple issues on separate lines.

changelog: Reference multiple issues/pull requests for a single entry

---

.changelog/2704.internal.md
.github/workflows/ci-reproducibility.yml

Almost none of the pull requests touches things that would break Go build reproducibility, so it makes more sense to only trigger the workflow for pushes to `master` and `stable/*` branches and on schedule, once every day.

github: Don't trigger ci-reproducibility workflow for pull requests

---

.changelog/2699.feature.md
go/extra/stats/cmd/stats.go

sample output:
```
$ ./go/extra/stats/stats entity-signatures --address unix:../testnet/quest-c/serverdir/node/internal.sock --start-block 100000 --end-block 120000 --top-n 100
|Rank |Entity ID                                                       |Nodes |Signatures| Proposals|Availability score|
------------------------------------------------------------------------------------------------------------------------
|1    |lWwiVpJ7SXBVoyQ5mDNmJsjB/oGAw6WzwK8Pj/FL3xM=                    |     1|     19845|       733|             56495|
|2    |/fgHhks5RMJ/W5ymnYCriSg73D+gkWFqH9CAfd1Xqo0=                    |     1|     19908|       587|             49258|
|3    |GwOSEEM/Lej8DrY1iQrX1zOvAkX2qk4/HWgS5jaHTb8=                    |     1|     19919|       503|             45069|
|4 …
```

availability ranking for next Quest phase

---

.buildkite/code-skip.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/pipeline.sh
.buildkite/rust/build_generic.sh
.buildkite/rust/build_runtime.sh
.buildkite/rust/test_generic.sh
.buildkite/scripts/download_e2e_test_artifacts.sh
.buildkite/scripts/test_e2e.sh
.changelog/2666.bugfix.md
.changelog/2702.internal.md
.changelog/2708.bugfix.md
Cargo.lock
Cargo.toml
Makefile
README.md
go/consensus/genesis/genesis.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/oasis-node/cmd/genesis/genesis.go
runtime/Cargo.toml
runtime/src/common/crypto/mrae/deoxysii.rs
runtime/src/common/sgx/avr.rs
runtime/src/rpc/session.rs

Backport of fix for #2708 (from #2709).
Also backports some fixes that are required for the new CI pipeline.

backport: go/consensus/tendermint: Properly cache consensus parameters

---

.changelog/2707.trivial.md
.github/workflows/ci-lint.yml

The next step, _Lint git commits_, needs access git's history so it can lint the relevant commits, otherwise it just lints all commits.
This is an alternative fix for #2707 and partially supersedes #2706.
Closes #2707.

github: Keep git history intact in Change Log fragment check

---

.changelog/2564.internal.md
.github/workflows/release.yml
common.mk

Also fix Make's `ENSURE_NO_CHANGELOG_FRAGMENTS` helper.
Closes #2564.

Bump GoReleaser to 0.127.0 and switch back to upstream

---

.changelog/2720.internal.md
go/consensus/tendermint/abci/mux.go

When CheckTx is disabled (for debug purposes only, e.g. in E2E tests), we still
need to periodically remove old transactions as otherwise the mempool will fill
up. Keep track of transactions were added and invalidate them when they expire.

go/consensus/tendermint: Expire txes when CheckTx is disabled

---

.changelog/2635.internal.md
go/common/cbor/cbor.go
go/common/grpc/service.go
go/go.mod
go/go.sum

go/common/cbor: Bump fxamacker/cbor to v2.2

---

.changelog/2706.trivial.md
Makefile
README.md

test PR for git lint problem
fixes #2707

readme: avoid tricky parsing of hard wrapped link

---

.changelog/2730.trivial.md
go/common/version/version.go
go/oasis-node/cmd/root.go

go/oasis-node: Add go toolchain info to `--version`

---

.changelog/2733.internal.md
Cargo.lock
runtime/Cargo.toml
runtime/src/common/crypto/hash.rs
runtime/src/common/crypto/mrae/deoxysii.rs
runtime/src/common/crypto/mrae/mod.rs
runtime/src/lib.rs
runtime/src/rak.rs
runtime/src/rpc/types.rs

As much as I like the concept of ring as a library, and the
implementation, the SGX support situation is rediculous, and we should
minimize the use of the library for cases where alternatives exist.
Part of #2683.

runtime: Remove the non-webpki/snow related uses of ring

---

.changelog/2732.bugfix.md
go/common/persistent/persistent.go
go/consensus/tendermint/db/badger/badger.go
go/runtime/history/db.go
go/runtime/localstorage/localstorage.go
go/storage/mkvs/urkel/db/badger/badger.go

Encountered corrupted badger value log file when running txsource tests with node restarts. Apparently badger is not at all resilient to crashes unless the truncate option is set on (which could result in data loss, but i think this should be safe as this means the crash happened while it was being written to the value log, so not yet committed). 
> {"caller":"node.go:741","err":"tendermint: failed to create node: tendermint/db/badger: failed to open database: During db.vlog.open: Value log truncate required to run DB. This might result in data loss","level":"error","module":"oasis-node","msg":"failed to start tendermint service","ts":"2020-02-27T09:42:18.599026044Z"}
This was also default behavior before an configuration option was added: https://github.com/dgraph-io/badger/pull/452 …

go/badger: enable truncate to recover from corrupted value log file

---

.changelog/2718.feature.md
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/api/submission.go
go/consensus/tendermint/apps/staking/auth.go
go/consensus/tendermint/tendermint.go
go/consensus/tests/tester.go
go/oasis-node/cmd/debug/txsource/txsource.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/debug/txsource/workload/workload.go
go/oasis-test-runner/scenario/e2e/txsource.go

- Adds registration txsource workloads (part of: https://github.com/oasislabs/oasis-core/issues/2506)
Currently runtime and entities only register at start and the workload then continuously registers nodes. Could update to also register new entities & runtimes during the run, if reviewers find it useful.
TODO:

registration workload

---

.changelog/2741.bugfix.md
go/oasis-net-runner/fixtures/default.go

The value of 16M was taken from the [the CLI flags](https://github.com/oasislabs/oasis-core/blob/master/go/oasis-node/cmd/registry/runtime/runtime.go#L525)

Increase scheduler max batch size

---

.changelog/2742.bugfix.md
go/common/version/version.go

Not all sources of semvers provide three fields. For instance, [runtime.Version()](https://golang.org/pkg/runtime/#Version) will return only major and minor when it's part of a release build ([usage](https://golang.org/pkg/runtime/#Version)). This fixes oasis-node startup issues.

Increase leniency of semver parsing

---

.changelog/2690.breaking.md
go/oasis-node/cmd/stake/account.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/stake_cli.go

go/oasis-node/cmd/stake: Use stake.shares flag in gen_reclaim_escrow tx

---

.changelog/2739.feature.md
.changelog/2740.feature.md
go/consensus/tendermint/apps/registry/query.go
go/consensus/tendermint/apps/scheduler/query.go
go/consensus/tendermint/apps/staking/query.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/staking/staking.go
go/scheduler/api/api.go
go/scheduler/tests/tester.go
go/staking/api/api.go
go/staking/api/grpc.go

Notes:
* The new Delegations call mimics the existing DebondingDelegations call, and requires specifying the delegator ID.

go: Various requested gRPC API additions.

---

.buildkite/scripts/daily_txsource.sh
.changelog/2744.feature.md
go/oasis-node/cmd/debug/txsource/txsource.go
go/oasis-node/cmd/debug/txsource/workload/oversized.go
go/oasis-node/cmd/debug/txsource/workload/parallel.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/debug/txsource/workload/runtimeplaceholder.go
go/oasis-node/cmd/debug/txsource/workload/transfer.go
go/oasis-node/cmd/debug/txsource/workload/workload.go
go/oasis-test-runner/scenario/e2e/txsource.go
tests/fixture-data/txsource/README.md
tests/fixture-data/txsource/staking-genesis.json

txsource: funding of accounts, fees

---

.changelog/2749.feature.md
Cargo.lock
keymanager-runtime/src/main.rs
runtime/Cargo.toml
runtime/src/dispatcher.rs
runtime/src/init.rs
runtime/src/lib.rs
runtime/src/transaction/dispatcher.rs
tests/runtimes/simple-keyvalue/src/main.rs

Allow runtimes to have a custom dispatcher

---

.changelog/2747.feature.md
go/oasis-test-runner/scenario/e2e/debond.go
go/oasis-test-runner/test-runner.go
tests/fixture-data/debond/staking-genesis.json

Here's an e2e test scenario that exercises debonding delegation records from the genesis document.

e2e tests: test debonding entries from genesis

---

.changelog/2756.bugfix.md
go/consensus/tendermint/apps/staking/state/state.go

Split out from: https://github.com/oasislabs/oasis-core/pull/2752 (unit test will be added there)
cc @peterjgilbert

staking/state: fix DelegationsFor queries

---

.changelog/2763.bugfix.md
go/staking/api/commission.go
go/staking/api/commission_test.go

The validation check would panic whenever the number of bound steps was greater than `rate_steps + 2`.

staking/api/commission: fix possible panic in validation check

---

.changelog/2674.feature.md
go/go.mod
go/go.sum
go/storage/api/api.go
go/storage/database/database.go
go/storage/database/database_test.go
go/storage/metrics.go
go/storage/mkvs/urkel/cache.go
go/storage/mkvs/urkel/checkpoint/checkpoint_test.go
go/storage/mkvs/urkel/checkpoint/chunk.go
go/storage/mkvs/urkel/commit.go
go/storage/mkvs/urkel/db/api/api.go
go/storage/mkvs/urkel/db/badger/badger.go
go/storage/mkvs/urkel/db/badger/helpers.go
go/storage/mkvs/urkel/db/badger/metadata.go
go/storage/mkvs/urkel/urkel_test.go
go/worker/storage/committee/node.go

Extracted from #2674
Fixes #2736 
By restricting how Prune behaves (it can now only remove the earliest round) we
can leverage Badger's managed mode to have it manage versions for us. This
avoids the need to track node lifetimes separately.

go/storage/mkvs: Use Badger to manage versions

---

.changelog/2745.doc.md
.changelog/README.md
README.md
docs/release-process.md

Mostly a clarification on how to set up Rust and take advantage of the newly added `rust-toolchain` file which rustup uses to download and install the correct version of the Rust toolchain automatically.

Smaller docs improvements

---

.buildkite/longtests.pipeline.yml
.buildkite/scripts/daily_txsource.sh
.changelog/2774.trivial.md

Longtests pipeline doesn't build rust code in debug mode resulting in tests not working in CI. While at it, also parallelize the build similarly as in code pipeline.
Note: this was not noticeable before #2759 as none of the txsource/workloads tested runtime level transactions.

buildkite/longtests: build rust code with debug flags

---

.changelog/2783.bugfix.md
.changelog/2783.internal.1.md
.changelog/2783.internal.2.md
go/oasis-node/cmd/debug/txsource/txsource.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-node/cmd/debug/txsource/workload/workload.go
go/runtime/client/client.go
go/storage/client/client.go

Contains fixes for issues discovered during long-term testing of #2674 which are also present in master.

Various fixes

---

.changelog/2787.internal.md
go/oasis-node/cmd/debug/txsource/workload/queries.go

To test things like: https://github.com/oasislabs/oasis-core/pull/2786
Probably shouldn't have removed this from the initial queries PR in the first place :-)

txsource/queries: increase the odds of querying the latest height

---

.changelog/2786.bugfix.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/tendermint.go

Do not let Tendermint determine the latest height as that completely ignores
ABCI processing so it can return a block for which local state does not yet
exist.

go/consensus/tendermint: Use our notion of latest height

---

.changelog/2790.trivial.md
go/common/ledger/ledger.go

Oasis was added as index 474 in the SLIP-0044 registry: https://github.com/satoshilabs/slips/pull/861

go/common/ledger: Update Oasis SLIP-0044 index

---

.changelog/2705.internal.md
.gitignore
Cargo.lock
client/src/lib.rs
client/src/rpc/client.rs
client/src/transaction/block_watcher.rs
client/src/transaction/client.rs
keymanager-api-common/Cargo.toml
keymanager-api-common/src/lib.rs
keymanager-client/src/lib.rs
keymanager-lib/src/lib.rs
keymanager-runtime/api/Cargo.toml
keymanager-runtime/api/src/lib.rs
keymanager-runtime/src/main.rs
runtime/Cargo.toml
runtime/fuzz/mkvs_node.rs
runtime/fuzz/mkvs_proof.rs
runtime/src/storage/mkvs/urkel/mod.rs
runtime/src/storage/mkvs/urkel/sync/proof.rs

Fixes #2705 
Also removes `extern crate` declarations which are not needed anymore.

runtime: Add hongfuzz fuzzing targets

---

.changelog/2793.trivial.md
README.md

Runtime allocation scheme changed in https://github.com/oasislabs/oasis-core/commit/b2ef06d38ad3b82b63d0792301c5fa0cf4228949

Fix runtime instructions in readme

---

.changelog/2789.trivial.md
go/common/crypto/signature/signature.go
go/common/crypto/tls/cert.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/apps/keymanager/genesis.go
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/staking/genesis.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/tendermint.go

- nil pointer dereferences in processing genesis document
- unused beacon reference
- imports spacing convention
- new cert and private key import/export without going out to file

Changes from fuzzing that we could keep

---

.changelog/2794.breaking.md
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/gas.go
go/genesis/genesis_test.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/staking/api/api.go
go/staking/api/api_test.go
go/staking/api/sanity_check.go
go/staking/tests/debug/debug_stake.go
tests/fixture-data/gas-fees-runtimes/staking-genesis.json
tests/fixture-data/gas-fees/staking-genesis.json
tests/fixture-data/txsource/staking-genesis.json

We should give more to the previous block proposer, which is the block that first ran the transactions that paid the fees in the `LastBlockFees`. Currently they only get paid as a voter.
The fee for block $h$ is split into $k$ portions, where $k$ is the number of validators at block $h$, one for each of those validators.
Each portion is split by constant weights into a _proposer share_, a _voter share_, and a _next proposer share_.
At the end of block $h$, pay the proposer share of all portions to the proposer of block $h$.
At the beginning of block $h+1$, for each portion where its validator's vote is included in block $h+1$, pay the voter share to the validator and pay the next proposer share to the proposer of block $h+1$.
In `.staking.params`:
- Changed: `fee_split_*` is renamed to …

go staking: three-way fee split

---

.changelog/2795.bugfix.md
go/roothash/api/history.go
go/runtime/client/client.go
go/runtime/client/tests/tester.go
go/runtime/history/history.go
go/runtime/history/history_test.go

Using history for all GetBlock requests prevents the case where the latest
block would already be available but not yet in history, leading to
inconsistent results compared to querying by specific block number.

go/runtime/client: use history for GetBlock(latest)

---

.changelog/2796.feature.md
.changelog/2796.internal.md
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/tests/tester.go

Another option would be adding support for querying "earliest" round to the runtime client (which could also include runtime pruning), not sure which option we prefer.

go/txsource/queries: get runtime earliest round from runtime state

---

.changelog/2802.bugfix.md
go/consensus/api/transaction/gas.go
go/consensus/api/transaction/gas_test.go

switch to more concise `FromUint64`

 go consensus: shorten gas import

---

.changelog/2809.bugfix.md
.changelog/2810.bugfix.md
go/consensus/tendermint/apps/staking/genesis.go
go/oasis-node/cmd/debug/txsource/workload/commission.go
go/staking/api/commission.go

go/staking: Use uint16 for limits in CommissionScheduleRules

---

.changelog/2819.internal.md
go/extra/stats/cmd/stats.go

As per https://docs.oasis.dev/operators/the-quest-rules.html#types-of-challenges, the availability score formula has changed from `Blocks Signed + 50 x Blocks Proposed` to `Blocks Signed + 50 x Blocks Proposed in Round 0`.

go/extra/stats: Update availability formula

---

.changelog/2684.feature.md
go/common/crypto/signature/signer.go
go/common/crypto/signature/signers/composite/composite_signer.go
go/common/crypto/signature/signers/composite/composite_signer_test.go
go/common/crypto/signature/signers/memory/memory_signer.go
go/oasis-node/cmd/common/signer/signer.go
go/oasis-node/cmd/common/signer/signer_test.go

This adds a composite signer factory that can aggregate multiple signer
factories.  This could be used (for example), to use multiple signer
backends simultaneously, depending on the key role.
Eg: The P2P link signer could use a local file, while the consensus
signer can be backed by a remote HSM.
Fixes 2684.

go/common/crypto/signature/signer/composite: Initial import

---

.changelog/2780.process.md
.github/workflows/release.yml
.gitignore
.goreleaser.yml
Makefile

Fixes #2780 
The current solution for including Rust artifacts does not seem the best to me, but Goreleaser is slightly awkward. I tested this by running `make release`, probably I also need to change the release workflow to include the Rust compiler.
TODO

Include oasis-core-runtime-loader and oasis-net-runner in releases

---

.changelog/2778.feature.md
go/consensus/tendermint/apps/staking/api.go
go/consensus/tendermint/registry/registry.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/service/service.go
go/consensus/tendermint/staking/staking.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/registry/api/api.go
go/registry/api/grpc.go
go/registry/tests/tester.go
go/roothash/api/api.go
go/roothash/tests/tester.go
go/staking/api/api.go
go/staking/api/grpc.go
go/staking/tests/tester.go

Add `GetEvents` to backends

---

.changelog/2844.breaking.md
Cargo.lock
go/common/grpc/policy/policy.go
go/common/grpc/proxy/proxy.go
go/common/grpc/service.go
go/common/grpc/testing/ping.go
go/keymanager/api/grpc.go
go/keymanager/client/client.go
go/oasis-node/cmd/node/node.go
go/runtime/client/api/grpc.go
go/runtime/committee/client.go
go/runtime/enclaverpc/api/api.go
go/runtime/enclaverpc/api/grpc.go
go/storage/api/grpc.go
go/worker/keymanager/init.go
go/worker/keymanager/policy.go
go/worker/sentry/grpc/worker.go
keymanager-api-common/src/api.rs
keymanager-client/src/client.rs
tests/clients/simple-keyvalue-enc/Cargo.toml
tests/clients/simple-keyvalue-enc/src/main.rs
tests/clients/simple-keyvalue-ops/Cargo.toml
tests/clients/simple-keyvalue-ops/src/main.rs
tests/clients/simple-keyvalue/Cargo.toml
tests/clients/test-long-term/Cargo.toml
tests/clients/test-long-term/src/main.rs
tests/runtimes/simple-keyvalue/src/main.rs

* go/runtime/enclaverpc: Refactor gRPC endpoint routing
Previously each endpoint required its own gRPC service. But since all EnclaveRPC
requests already include an "endpoint" field, it is better to use that for
routing requests.
This commit adds a new enclaverpc.Endpoint interface that is used as an endpoint
descriptor. All endpoints must be registered in advance (e.g., during init). It
also changes the key manager EnclaveRPC support to use the new API.
Since it changes the gRPC service name this BREAKS the committee gRPC protocol.
* tests/clients/simple-keyvalue-enc: Test the key manager client via gRPC
Previously we only tested the runtime transport for the key manager so this adds
a test that also tests the gRPC transport.

Key manager EnclaveRPC fixes

---

.changelog/2767.internal.md
go/staking/tests/debug/debug_stake.go
go/staking/tests/tester.go

Extracted from #2748.
Introduce `stakingTestsState` that holds the current state of staking tests.
Since staking tests are run as part of `TestNode` tests which spin up a real node, subsequent tests are run in a modified (i.e. non-genesis) state.
This change enables the staking implementation tests (`StakingImplementationTest`, `StakingClientImplementationTests`) to use a new `stakingTestsState` that is initialized to the current staking state.
Remove `testInitialEnv()` since it has become tautological.
Extract remaining useful checks from the removed `testInitialEnv()`:
- `testThresholds()`,
- `testLastBlockFees()`.

go/staking/tests: Add escrow and delegations to debug genesis state

---

.changelog/2853.bugfix.md
go/common/crypto/mrae/deoxysii/asymmetric.go

Following 73aacaa73d7116a6be0443e70f2d10d0c7a4b76e, this should also use
the correct hash algorithm for the KDF.

go/common/crypto/mrae/deoxysii: Use SHA512/256 for the KDF

---

.changelog/2855.feature.md
go/consensus/tendermint/tendermint.go

Expose new p2p config options  which were added in tendermint 0.33

tendermint unconditional peers

---

.changelog/2856.bugfix.md
go/extra/stats/cmd/stats.go

Fixes: #2854 
Instead of separately querying for entities and nodes, we can get Entity IDs
from nodes directly.
This change also fixes a case that previous variant missed: node that was
removed from entity list of nodes, but has not yet expired.
TODO:

go/extra/stats: fix & simplify node-entity mapping

---

.changelog/2856.bugfix.md
go/extra/stats/cmd/stats.go

Backports: https://github.com/oasislabs/oasis-core/pull/2856
Instead of separately querying for entities and nodes, we can get Entity IDs
from nodes directly.
This change also fixes a case that previous variant missed: node that was
removed from entity list of nodes, but has not yet expired.

[BACKPORT] go/extra/stats: fix & simplify node-entity mapping

---

go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/keymanager/transactions.go
go/consensus/tendermint/keymanager/keymanager.go
go/keymanager/api/policy_sgx.go
go/oasis-node/cmd/keymanager/keymanager.go
go/oasis-test-runner/oasis/cli/cli.go
go/oasis-test-runner/oasis/cli/keymanager.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/runtime_dynamic.go

go/oasis-test-runner: Test dynamic KM runtime registration

---

.changelog/2858.bugfix.md
go/extra/stats/cmd/stats.go

If we encounter a signature for a node that is not yet being tracked, we should query for it's info on the previous height, as that's the block at which the vote was made.
Tested on blocks 0-69488 questnet.

go/extra/stats: fix heights at which missing nodes should be queried

---

.changelog/2858.bugfix.md
go/extra/stats/cmd/stats.go

https://github.com/oasislabs/oasis-core/pull/2858
Tested on blocks 0-69488 questnet.

[BACKPORT] go/extra/stats: fix heights at which missing nodes should be queried

---

.changelog/2872.bugfix.md
client/src/rpc/client.rs
client/src/rpc/mod.rs
client/src/rpc/transport.rs
runtime/src/rak.rs

Previously the EnclaveRPC client did not change the session identifier on reset, resulting in unnecessary round-trips during a transport error. The EnclaveRPC client now changes the session identifier and the code now includes unit tests for the EnclaveRPC client (and demux).

client/rpc: Change session identifier on reset, add unit tests

---

.changelog/2873.feature.md
go/consensus/tendermint/tendermint.go
go/oasis-test-runner/scenario/e2e/late_start.go
go/oasis-test-runner/test-runner.go

Fixes: https://github.com/oasislabs/oasis-core/issues/2861
Sync-worker relies on Tendermint fast-sync to determine if the node is still
catching up. This PR adds aditional condition that the latest block is not
older than 1 minute. This prevents cases where node stops fast-syincing
before it has actually caught up.
TODO:

go/consensus/tendermint: sync-worker additionally check block timestamps

---

.changelog/2876.bugfix.md
.changelog/2876.internal.1.md
.changelog/2876.internal.2.md
go/common/pubsub/pubsub.go
go/common/pubsub/pubsub_test.go
go/consensus/tendermint/epochtime/epochtime.go
go/consensus/tendermint/epochtime_mock/epochtime_mock.go
go/consensus/tendermint/keymanager/keymanager.go
go/consensus/tendermint/registry/registry.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/scheduler/scheduler.go
go/epochtime/api/api.go
go/epochtime/tests/mock_tester.go
go/oasis-node/cmd/debug/consim/timesource.go
go/runtime/committee/nodes.go
go/worker/registration/worker.go

Fixes: #2862
Pubsub framework is extended to support subscriptions based on bounded
ring channels. Bounded subscriptions are used in the new epochtime
WatchLatestEpoch method. The method is similar to the existing WatchEpochs
method, with the change that unread epochs get overridden with latest
epoch.
Registration worker is changed to use the WatchLatestEpoch method to
prevent trying to register for old epochs in case the worker falls
behind.
XXX: any other places where using a ring channel (e.g. skipping past/outdated channel items) would be preferable?

go/epochtime: add WatchLatestEpoch method

---

.buildkite/scripts/daily_txsource.sh

Recent merge of #2687 broke daily long-term txsource tests due to the test being renamed.

ci: Fix daily txsource test runner

---

.changelog/2843.breaking.6.md
.changelog/2843.bugfix.1.md
.changelog/2843.bugfix.2.md
.changelog/2843.bugfix.3.md
.changelog/2843.feature.4.md
.changelog/2843.feature.5.md
go/consensus/tendermint/keymanager/keymanager.go
go/keymanager/api/api.go
go/keymanager/api/grpc.go
go/keymanager/client/client.go
go/oasis-net-runner/fixtures/default.go
go/oasis-net-runner/fixtures/fixtures_test.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/oasis/controller.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/keymanager_replicate.go
go/oasis-test-runner/scenario/e2e/runtime.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/oasis-test-runner/scenario/e2e/upgrade_cancel.go
go/worker/common/runtime_host.go
go/worker/keymanager/handler.go
go/worker/keymanager/init.go
go/worker/keymanager/watcher.go
go/worker/keymanager/worker.go
keymanager-lib/src/kdf.rs
tests/fixture-data/net-runner/default.json

go/oasis-test-runner/oasis: Add a keymanager replication test

---

.changelog/2885.bugfix.md
go/oasis-test-runner/scenario/e2e/keymanager_replicate.go
go/runtime/committee/client.go

Fixes #2885 
Previously the round-robin node selection policy would randomize the order on
every update ignoring the currently picked node. This would cause the current
node to flip on each update causing problems with EnclaveRPC which is stateful.
The fix makes the round-robin node selection policy attempt to restore the
currently picked node on each update. This means that in case the node is still
in the node list, it will not change.

go/runtime/committee: Restore previously picked node in RR selection

---

.changelog/2748.bugfix.md
.changelog/2748.internal.md
go/consensus/tendermint/apps/supplementarysanity/checks.go
go/genesis/api/sanity_check.go
go/registry/api/api.go
go/registry/api/sanity_check.go

Extract and generalize registry's staking sanity checks in `go/consensus/tendermint/apps/supplementarysanity.checkStakeClaims()` and move them to `go/registry/api.SanityCheckStake()` function.
Augment the checks to check if an entity has enough stake for all stake claims in the Genesis document to prevent panics at oasis-node start-up due to entities not having enough stake in the escrow to satisfy all their stake claims.
Example panic when an entity doesn't have enough stake to be registered:
```
panic: mux: InitChain: fatal error in application: '200_registry': registry: genesis entity registration failure: staking: insufficient stake
goroutine 1 [running]:
github.com/oasislabs/oasis-core/go/consensus/tendermint/abci.(*abciMux).InitChain(0xc0001f64b0, 0x0, 0xed5d4d490, 0x0, …
```

Add sanity check for registered entities' stake

---

.changelog/2440.feature.1.md
.changelog/2440.feature.2.md
.changelog/2881.breaking.md
go/common/node/node.go
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/api/light.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/full.go
go/consensus/tendermint/tendermint.go
go/consensus/tests/tester.go
go/go.mod
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/runtime.go
go/storage/mkvs/checkpoint/checkpoint.go
go/storage/mkvs/checkpoint/checkpoint_test.go
go/storage/mkvs/checkpoint/file.go
go/storage/mkvs/checkpoint/restorer.go
go/worker/consensusrpc/worker.go

Initial implementation of #2440, required for #2880.
TODO

Basic consensus light client support

---

.changelog/2826.internal.md
go/go.mod
go/go.sum
go/runtime/committee/client.go

go/runtime/committee: Don't close gRPC connections on connection refresh

---

.changelog/2898.trivial.md
go/oasis-node/cmd/common/metrics/metrics.go

Workaround for https://github.com/prometheus/pushgateway/issues/344
Prometheus push gateway rejects labels with empty values (e.g. when SGX is not used `tee_hardware` label is empty). This PR removes labels with empty values before sending them to push gateway.

metrics: Ignore labels with empty values

---

.buildkite/code.pipeline.yml
.buildkite/scripts/sgx_ias_tests.sh
.buildkite/scripts/test_e2e.sh
.changelog/2883.bugfix.md
.changelog/2883.feature.md
.changelog/2883.internal.md
go/common/sgx/ias/avr.go
go/ias/http/http.go
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/ias/proxy.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/ias.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/runtime.go
go/oasis-test-runner/scenario/e2e/runtime_dynamic.go
runtime/src/common/sgx/avr.rs
tests/fixture-data/net-runner/default.json

Fixes: #1733
TODO:
- no more client certs, but client authentication is done with an API key
- new statuses: `SW_HARDENING_NEEDED` & `CONFIGURATION_AND_SW_HARDENING_NEEDED`
- advisories moved from response headers into actual report

go/oasis-test-runner: add support for running tests with non-mock IAS

---

.buildkite/code.pipeline.yml
.changelog/2900.internal.md

This actually the error we hit when an agent is killed while a docker job is running, so retry it: https://buildkite.com/oasislabs/oasis-core-ci/builds/3755#67e54104-47e9-44cb-8c31-2e1218d6b51c

.buildkite: retry exit status '125'

---

.changelog/2908.feature.md
go/extra/stats/cmd/stats.go

we don't use the "Rank" column from the stats program because it's wrong on ties. we probably still can't use it directly because we often need to combine it across upgrades. but here's some logic to give ties the same rank.

go stats: give ties the same rank

---

.changelog/2909.bugfix.md
go/common/crypto/signature/signature.go
go/consensus/tendermint/apps/staking/api.go
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/state/gas.go
go/consensus/tendermint/apps/staking/state/state.go
go/staking/api/api.go
go/staking/tests/tester.go

Fixes #2909.
Staking events are now generated when disbursing fees and rewards.
There are two new special account IDs -- `CommonPoolAccountID` and
`FeeAccumulatorAccountID` (both defined in `go/staking/api/api.go`),
which are used only in events to signify the common pool and the fee
accumulator respectively.
These account IDs are invalid by design to prevent misusing them
anywhere else.

staking: Emit events when disbursing fees and rewards

---

.changelog/2581.feature.md
go/common/entity/entity.go
go/common/node/node.go
go/consensus/tendermint/apps/keymanager/genesis.go
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/registry/state/state_test.go
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/staking/slashing_test.go
go/genesis/genesis_test.go
go/oasis-node/cmd/debug/byzantine/registry.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/node_test.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/api/api.go
go/registry/api/runtime.go
go/registry/api/sanity_check.go
go/registry/tests/tester.go
go/roothash/api/commitment/pool_test.go
go/worker/registration/worker.go

Fixes #2581 
This introduces a DescriptorVersion field to all entity, node and runtime
descriptors to support future updates and handling of legacy descriptors at
genesis.
All new registrations only accept the latest version while initializing from
genesis is also allowed with an older version to support a dump/restore upgrade.

Version signed entity, node and runtime descriptors

---

.changelog/2902.feature.1.md
.changelog/2902.feature.2.md
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/tendermint/tendermint.go
go/consensus/tests/tester.go
go/control/api/api.go
go/control/api/grpc.go
go/control/control.go

Closes #2902.
* consensus: Add GetStatus method to API
A new `GetStatus` method has been added to the consensus API.
It returns useful information about the latest block, the genesis
block, and the node itself.
* control: Add GetStatus method to API
A new `GetStatus` method has been added to the control API.
It returns the software version and the status of the consensus layer.

{consensus,control}: Add GetStatus method to API

---

go/consensus/tendermint/tendermint.go
go/consensus/tests/tester.go

This PR fixes the `GenesisHeight` in `GetStatus`, so that it always returns 1 as the genesis height.

consensus: Fix GenesisHeight in GetStatus

---

.buildkite/benchmarks.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.yml
.buildkite/scripts/download_e2e_test_artifacts.sh
.changelog/2517.bugfix.md
.changelog/2517.feature.md
Cargo.lock
Cargo.toml
Makefile
go/oasis-net-runner/fixtures/default.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/keymanager_upgrade.go
go/oasis-test-runner/scenario/e2e/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/runtime.go
go/worker/keymanager/init.go
go/worker/keymanager/worker.go
tests/fixture-data/net-runner/default.json
tests/runtimes/simple-keymanager-upgrade/Cargo.toml
tests/runtimes/simple-keymanager-upgrade/src/api.rs
tests/runtimes/simple-keymanager-upgrade/src/lib.rs
tests/runtimes/simple-keymanager-upgrade/src/main.rs

Closes: #2517 
TODO:
- will be handled in a separate PR

KM upgrade E2E test

---

.changelog/2359.feature.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/abci/state/state.go
go/consensus/tendermint/api/state.go
go/consensus/tendermint/apps/beacon/query.go
go/consensus/tendermint/apps/beacon/state/state.go
go/consensus/tendermint/apps/epochtime_mock/query.go
go/consensus/tendermint/apps/epochtime_mock/state.go
go/consensus/tendermint/apps/keymanager/query.go
go/consensus/tendermint/apps/keymanager/state/state.go
go/consensus/tendermint/apps/registry/query.go
go/consensus/tendermint/apps/registry/state/state.go
go/consensus/tendermint/apps/roothash/query.go
go/consensus/tendermint/apps/roothash/state/state.go
go/consensus/tendermint/apps/scheduler/query.go
go/consensus/tendermint/apps/scheduler/state/state.go
go/consensus/tendermint/apps/staking/query.go
go/consensus/tendermint/apps/staking/state/state.go
go/oasis-node/cmd/debug/debug.go
go/oasis-node/cmd/debug/dumpdb/dumpdb.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/scenario/e2e/dump_restore.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/runtime.go
go/storage/api/api.go
go/storage/database/database.go
go/storage/mkvs/db/api/api.go
go/storage/mkvs/db/badger/badger.go

go/oasis-node: Add the `debug dumpdb` command

---

.changelog/2929.bugfix.md
go/common/crypto/signature/signature.go
go/common/keyformat/hashed.go
go/common/keyformat/hashed_test.go
go/common/keyformat/key_format.go
go/consensus/tendermint/abci/timer.go
go/consensus/tendermint/apps/keymanager/state/state.go
go/consensus/tendermint/apps/registry/genesis.go
go/consensus/tendermint/apps/registry/state/state.go
go/consensus/tendermint/apps/roothash/state/state.go
go/consensus/tendermint/apps/scheduler/state/state.go

Add support for hashed key elements and hash some of the key elements.
Staking state is omitted as it will not be needed once we do #2928 (as all account identifiers will already be hashed then).

go/common/keyformat: Add support for hashed key elements

---

.buildkite/code.pipeline.yml
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/query.go
go/consensus/tendermint/apps/staking/state/state.go
go/oasis-test-runner/scenario/e2e/debond.go
go/staking/api/sanity_check.go
tests/fixture-data/debond/staking-genesis.json

When testing the backported staking events for 20.6.1, kostko found a few events that I missed, so I added them in this PR.

staking: Add missing events

---

.changelog/2945.bugfix.md
go/consensus/tendermint/apps/staking/state/state.go
go/staking/api/sanity_check.go

Version 20.6.1 introduced an additional sanity check for account identifier
validity, but this actually breaks some existing deployments. This revert makes
the checks consistent with 20.6 behavior.

[20.6.x] go/staking: Relax account identifier sanity check added in 20.6.1

---

.changelog/2942.trivial.md
go/staking/api/api.go
go/staking/api/commission.go

A non-breaking change that omits some empty fields from staking account state.

go/staking: Omit some more empty fields from account state

---

.changelog/2936.bugfix.1.md
.changelog/2936.feature.1.md
docs/oasis-node/metrics.md
docs/oasis-node/metrics.md.tpl
go/oasis-node/cmd/common/metrics/metrics.go

* ~investigate mystery crashes~
Fixes #2936

metrics: Fix prometheus push issues

---

.changelog/2949.bugfix.md
.changelog/2950.bugfix.md
go/oasis-node/cmd/common/signer/signer.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/entity.go

Fixes #2949
Fixes #2950 
This may require updates to the operator docs after 20.7 is released as `--signer` has been renamed to `--signer.backend`.

go/oasis-node: Signer configuration fixes

---

.changelog/2897.internal.md
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/env/env.go
go/oasis-test-runner/env/env_test.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/identity_cli.go
go/oasis-test-runner/scenario/e2e/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/oasis-test-runner/scenario/e2e/restore_previous.go
go/oasis-test-runner/scenario/e2e/runtime.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/oasis-test-runner/scenario/e2e/upgrade_cancel.go
go/oasis-test-runner/scenario/remotesigner/basic.go
go/oasis-test-runner/scenario/remotesigner/remotesigner.go
go/oasis-test-runner/scenario/scenario.go

oasis-test-runner: Use explicit flagsets for scenario parameters

---

.changelog/2919.bugfix.md
client/src/rpc/client.rs
go/oasis-test-runner/scenario/e2e/keymanager_upgrade.go
go/runtime/host/protocol/connection.go
go/runtime/host/protocol/types.go
go/runtime/host/tests/tester.go
go/worker/common/committee/runtime_host.go
go/worker/common/runtime_host.go
go/worker/compute/executor/committee/node.go
go/worker/compute/txnscheduler/committee/node.go
go/worker/keymanager/worker.go
keymanager-client/src/client.rs
runtime/src/dispatcher.rs
runtime/src/protocol.rs
runtime/src/rpc/dispatcher.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

Fixes: #2919
This will also require (minor) changes to the oasis-runtime (updating the initalizer with the keymanager-update handle)

notify runtimes of its key manager policy updates

---

.changelog/2948.feature.md
go/common/crypto/signature/signature.go
go/common/crypto/signature/signer_test.go
go/consensus/genesis/genesis.go
go/consensus/tendermint/tendermint.go
go/genesis/api/sanity_check.go
go/registry/api/sanity_check.go

go/consensus/genesis: Add a public key blacklist

---

.changelog/2966.bugfix.md
go/oasis-node/cmd/node/node.go

Missed this in #2964 :disappointed:

go/oasis-node: Don't bypass Stop in newNode failure handler

---

.buildkite/code.pipeline.yml
.changelog/2969.internal.md

Apparently jobs that hit the time-out limit exit with status `-1`  and get automatically retried (which we actually don't want). Haven't seen any other job fail with `-1` (agents getting killed appears to be `125`) so i think it's fine just not retrying these.

ci: don't retry timeout jobs

---

.changelog/2967.bugfix.md
go/runtime/host/sandbox/sandbox.go
go/worker/common/committee/runtime_host.go

Issue discovered in long-term tests.

go/runtime/host/sandbox: Retry Call in case the runtime is not yet ready

---

.buildkite/benchmarks.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.yml
.buildkite/pipeline.sh
.changelog/295.internal.md
.github/workflows/docker.yml
docker/Makefile
docker/development/Dockerfile
docker/testing/Dockerfile

ci: Automatically rebuild development/CI Docker images

---

.changelog/2844.feature.md
keymanager-api-common/src/api.rs
keymanager-client/src/client.rs
keymanager-client/src/lib.rs
keymanager-client/src/mock.rs
keymanager-lib/src/kdf.rs
keymanager-lib/src/methods.rs
tests/clients/simple-keyvalue-enc/src/main.rs
tests/runtimes/simple-keyvalue/src/main.rs

Each runtime does not neccecarily have a notion for contracts, so the
key manager now operates in terms of `KeyPairId`s that identify a given
`KeyPair`.
Fixes #2844.

keymanager: Rename APIs referencing "contracts"

---

.changelog/2983.bugfix.md
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/state/gas.go
go/staking/tests/tester.go

If fees were set to 0, staking events related to the fee accumulator
would still get emitted with zero amounts, which is pointless.
This fix affects only events related to the internal fee accumulator
and common pool accounts, manual transfers with 0 as the amount will
still get emitted.

staking: Don't emit zero-amount staking events

---

.changelog/2989.internal.md
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/storage.go

we currently append seeds twice in these two places, instead of only in case when not using sentries (see bellow, not visible in the PR diff)

test/e2e/sentry: don't set seed node for nodes running with sentries

---

.changelog/2993.process.md
docs/release-process.md

Currently we create a stable release branch only once we need to backport some
changes. This PR changes the release process to create the stable branch when
creating a new release. This will ensure CI jobs hooked to stable/ branches,
such as building a release tagged CI docker image will be run for every
release.
NOTE: this could probably be automated within the `tag-next-release` make step (with an additional check to only run this when creating a new release and not when backporting), but I'm afraid i'm not enough of a makefile enthusiast to tackle that :/ - can open an issue though.

release-process: create a stable branch when preparing a new release

---

.changelog/2994.trivial.md
Cargo.lock
runtime/Cargo.toml
runtime/src/common/sgx/avr.rs
runtime/src/lib.rs

While there was nothing really all that wrong with pem-iterator,
the only reason why the pem crate wasn't being used was because
nostd used to be mandatory.  Since that is no longer a requirement
switching crates removes a overcomplicated helper function.

runtime/src/common/sgx: Use the `pem` crate instead of `pem-iterator`

---

.changelog/2992.breaking.md
go/common/entity/entity.go
go/common/node/node.go
go/registry/api/runtime.go
go/upgrade/migrations/dummy.go
tests/fixture-data/consim/genesis.json

We forgot to do this earlier, v0 descriptors should not be allowed anywhere in 20.8.

Disallow v0 entity/node/runtime descriptors

---

.changelog/2995.breaking.md
docs/consensus/registry.md
go/common/quantity/quantity.go
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/registry/transactions_test.go
go/consensus/tendermint/apps/staking/state/accumulator.go
go/consensus/tendermint/apps/staking/state/accumulator_test.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/oasis/cli/registry.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/api/api.go
go/registry/api/runtime.go
go/registry/api/sanity_check.go
go/registry/tests/tester.go
go/staking/api/api.go
go/staking/api/api_test.go
go/upgrade/migrations/dummy.go
tests/fixture-data/consim/genesis.json
tests/fixture-data/debond/staking-genesis.json
tests/fixture-data/net-runner/default.json
tests/fixture-data/runtime-dynamic/staking-genesis.json
tests/fixture-data/stake-cli/staking-genesis.json

registry: Add runtime-specific staking thresholds

---

.changelog/3011.bugfix.md
go/oasis-node/cmd/registry/node/node.go

go/oasis-node: Support non-file signers in registry node init

---

.changelog/1807.feature.md
go/common/crypto/signature/signature.go
go/keymanager/client/client.go
go/roothash/api/commitment/executor.go
go/roothash/api/commitment/merge.go
go/worker/compute/executor/committee/fault.go
go/worker/compute/executor/committee/fault_test.go
go/worker/compute/executor/committee/node.go

worker/compute/executor: Independently submit commit in case of faults

---

.buildkite/pipeline.sh
.changelog/3016.breaking.md
.changelog/3016.internal.md
go/oasis-node/cmd/stake/account.go
go/oasis-node/cmd/stake/stake.go

Change `oasis-node stake list --verbose` CLI command's output to not list all accounts' information as a single-line JSON string but rather output each account's JSON string on a separate line.
This is consistent with the verbose outputs of the `oasis-node registry entity list` and `oasis-node registry node list` CLI commands.

go/oasis-node/cmd/stake: Make list command's verbose output consistent

---

.changelog/3003.feature.md
go/oasis-node/cmd/stake/stake.go
go/oasis-test-runner/scenario/e2e/stake_cli.go

Add a CLI command for converting entities' ids to their staking account addresses

---

.changelog/3023.bugfix.md
go/runtime/host/tests/tester.go
runtime/src/dispatcher.rs
runtime/src/protocol.rs

Ideally this should be caught by: 
https://github.com/oasisprotocol/oasis-core/blob/b7b2c4201e91d06fb5f5bae84e35a3af51444926/go/runtime/host/tests/tester.go#L180-L196
But the problem is that the `Abort` request makes it to the dispatcher before the first iteration of the dispatch loop, therefore the request is handled before the dispatcher is stuck in the `recv` loop. 
Updated the test to do another abort which also handles the case where dispatcher is stuck in the `recv` loop.

runtime/dispatcher: Break recv loop on abort request

---

.changelog/3024.bugfix.md
go/runtime/host/sandbox/sandbox.go

The data race existed because the cancel function that is referenced inside a
goroutine waiting for initialization to complete was unintentionally
overwritten.

go/runtime/host/sandbox: Fix possible data race

---

.buildkite/pipeline.sh

Currently we used the branch name without replaced slashes in `check_docker_ci_image_tag_exists` (which leads to pipeline failure on `stable/` branches).
The only other place where `docker_tag` is set is within `pr_and_docker_changes` (which i believe should not ever contain slashes).

ci: fix branch to docker image tag in pipline.sh

---

.changelog/3030.internal.md
go/common/encoding/bech32/bech32.go
go/go.mod

The github.com/tendermint/tendermint/libs/bech32 module has been removed in
later Tendermint Core versions. As it only contained a small helper, we just
copy it over.

go/common/encoding/bech32: Replace to-be-removed dependency

---

.changelog/3035.bugfix.md
go/runtime/committee/client.go

Reduces the gRPC backoff MaxDelay in committee client. Committee nodes are expected to be available and this timeout is more in line with timeouts we use in the clients using these connections (e.g. storage client retries for 15 secs). 
This was causing spurious `runtime_dynamic` E2E test failures, where the nodes are restarted in the test. In case the storage node restart took to long, the connection retry delay got greater than the retry timeout in storage client, causing failures.

runtime/committee/client: reduce gRPC max backoff timeout

---

.buildkite/code.pipeline.yml
.changelog/3036.internal.md

Apparently jobs that timeout exit with status `255` and those shouldn't be automatically retried.
As noted before (https://github.com/oasisprotocol/oasis-core/pull/2900) `125` is actually the only error we want to automatically retry.

ci: don't automatically retry timed out jobs

---

.changelog/3038.breaking.md
.changelog/3038.feature.1.md
.changelog/3038.feature.2.md
.changelog/3038.feature.3.md
go/consensus/api/api.go
go/consensus/tendermint/tendermint.go
go/control/api/api.go
go/control/control.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-node/cmd/node/control.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/scenario/e2e/early_query.go
go/oasis-test-runner/scenario/e2e/node_shutdown.go
go/registry/api/api.go
go/worker/registration/worker.go

* go/registry: Make TLS address required for RoleConsensusRPC
* go/control: Add registration status to node status
This updates the response returned by the `GetStatus` method exposed by the
node controller service to include a `Registration` field that contains
information about the node's current registration.
* go/consensus: Add IsValidator to reported node status
* go/control: Add identity status to node status
This updates the response returned by the `GetStatus` method exposed by the
node controller service to include an `Identity` field that contains
information about the public keys used to identify a node in different
contexts.

Update TLSAddressRequiredRoles and update node control API

---

.changelog/2880.breaking.md
go/consensus/genesis/genesis.go
go/consensus/tendermint/abci/state.go
go/genesis/genesis_test.go
go/oasis-node/cmd/genesis/genesis.go
go/storage/mkvs/checkpoint/checkpointer.go
go/worker/storage/committee/node.go

Part of #2880, extracted from #2882.

go/consensus: Enable periodic state checkpoints

---

.changelog/3044.internal.md
go/oasis-test-runner/cmd/cmp/cmp.go
go/oasis-test-runner/cmd/common/common.go
go/oasis-test-runner/cmd/root.go

List all available scenarios if command was invoked with a particular scenario that was not found.
For example, running `.buildkite/scripts/test_e2e.sh --test storage-sync` where `storage-sync` scenario doesn't exist, now returns:
```
+ WORKDIR=/home/tadej/Oasis/oasis-core
+ runtime_target=default
+ [[ '' == \i\n\t\e\l\-\s\g\x ]]
+ [[ '' != '' ]]
+ node_binary=/home/tadej/Oasis/oasis-core/go/oasis-node/oasis-node
+ test_runner_binary=/home/tadej/Oasis/oasis-core/go/oasis-test-runner/oasis-test-runner
+ [[ '' != '' ]]
+ ias_mock=true
+ set +x
+ /home/tadej/Oasis/oasis-core/go/oasis-test-runner/oasis-test-runner --basedir.no_cleanup --e2e.node.binary /home/tadej/Oasis/oasis-core/go/oasis-node/oasis-node --e2e/runtime.client.binary_dir /home/tadej/Oasis/oasis-core/target/default/debug …
```

go/oasis-test-runner: List all available scenarios

---

.changelog/2020.breaking.md
go/common/cbor/cbor.go
go/common/cbor/cbor_test.go
go/go.mod
go/go.sum

go/common/cbor: Reject CBOR blobs with unknown fields

---

.changelog/3049.internal.1.md
.changelog/3049.internal.2.md
go/worker/common/committee/node.go
go/worker/compute/executor/committee/batch.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/state.go
go/worker/compute/merge/committee/node.go

* go/worker/compute/executor: Defer fetching the batch from storage
There is no need to attempt to fetch the batch immediately, we can defer it to
when we actually need to start processing the batch. This makes fetching not
block P2P dispatch.
* go/worker/compute/merge: Defer finalization attempt
There is no need for the finalization attempt to block handling of an incoming
commitment as any errors from that are not propagated. This avoids blocking
P2P relaying as well.
* go/worker/common: Treat unknown P2P message type as a permanent error

go/worker: Defer various processing

---

.changelog/3050.feature.md
go/common/crypto/signature/signers/ledger/ledger_signer.go
go/go.mod

Make Ledger signer return a more descriptive error message when a user rejects a transaction on the Ledger device.
For example, previously, the returned error was:
```
ts=2020-06-25T10:26:59.930888297Z level=error module=cmd/common/consensus caller=consensus.go:107 msg="failed to sign transaction" err="[APDU_CODE_COMMAND_NOT_ALLOWED] Command not allowed (no current EF)"
```
Now, it is:
```
ts=2020-06-25T10:27:24.693936203Z level=error module=cmd/common/consensus caller=consensus.go:107 msg="failed to sign transaction" err="transaction was rejected on Ledger device"
```

go/common/crypto/signature/signers/ledger: Descriptive error on user reject

---

.changelog/3065.breaking.md
go/consensus/tendermint/apps/staking/state/state_test.go
go/staking/api/rewards.go

The denominator turned out not to be fine enough. This PR increases it. To keep the same reward rate, the numerators from the genesis block would need to be increased too. cc @bennetyee

go staking: increase reward amount denominator

---

docs/consensus/scheduler.md

fixes #3057
Adds a section on how voting power is computed to the Consensus Scheduler doc.

docs: add voting power description

---

.changelog/2961.feature.md
.changelog/3067.breaking.md
go/consensus/tendermint/apps/registry/query.go
go/consensus/tendermint/registry/registry.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/registry/api/api.go
go/registry/api/grpc.go
go/registry/tests/tester.go
go/worker/common/p2p/peermgmt.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/2961

go/registry/api: Add `GetNodeByConsensusAddress` method

---

.changelog/3075.bugfix.md
go/worker/common/p2p/error/error.go

Context cancellation errors should not count as permanent for P2P dispatch as
the cancelled context may be due to the round advancing in which case dispatch
should actually be retried.

go/worker/common/p2p: Don't treat context cancellation as permanent

---

.changelog/2723.feature.md
go/oasis-node/cmd/common/consensus/consensus.go
go/oasis-node/cmd/consensus/consensus.go
go/oasis-test-runner/oasis/cli/consensus.go
go/oasis-test-runner/scenario/e2e/stake_cli.go

fixes #2723 
> We just need to expose it via CLI.
in fact this is made even easier now that the command is further exposed over consensus ClientBackend
~~doesn't exactly live up to the original request though, because you'd still have to set a gas and sign it first before you would run the signed transaction through this file~~

go/oasis-node: add consensus estimate_gas

---

.changelog/3047.feature.md
.changelog/3073.breaking.2.md
.changelog/3073.breaking.3.md
.changelog/3073.breaking.4.md
.changelog/3073.breaking.md
go/common/errors/errors.go
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/api/transaction/results/results.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/apps/roothash/api.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/transactions.go
go/consensus/tendermint/registry/registry.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/staking/staking.go
go/consensus/tendermint/tendermint.go
go/consensus/tests/tester.go
go/go.mod
go/go.sum
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/scenario/e2e/early_query.go
go/registry/api/api.go
go/registry/tests/tester.go
go/roothash/api/api.go
go/roothash/tests/tester.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3047

go/consensus/api: Add `GetTransactionsWithResults` method

---

.changelog/3077.feature.md
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/api/light.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/full.go
go/consensus/tendermint/tendermint.go
go/consensus/tests/tester.go

Fixes #3077 
Nodes configured as consensus RPC services workers now expose read-only
access to consensus state via the usual MKVS ReadSyncer interface, allowing
light clients to remotely query state while transparently verifying proofs.
TODO

go/consensus: Expose read-only state via light client interface

---

.changelog/3087.feature.1.md
.changelog/3087.feature.2.md
go/oasis-node/cmd/stake/account.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/staking/api/api.go
go/staking/api/commission.go

Example of previous `oasis-node stake account info` CLI command output:
```json
{"general":{"balance":"601492490765","nonce":8},"escrow":{"active":{"balance":"11242384816640","total_shares":"10000000000000"},"debonding":{"balance":"0","total_shares":"0"},"commission_schedule":{"rates":[{"start":16,"rate":"50000"}],"bounds":[{"start":16,"rate_min":"0","rate_max":"100000"}]},"stake_accumulator":{"claims":{"registry.RegisterEntity":[{"global":"entity"}]}}}}
```
Example of the new `oasis-node stake account info` CLI command output:
```text
General Account:
Balance: 601492490765
Nonce:   8
Escrow Account:
Active:
Balance:      11242384816640
Total Shares: 10000000000000
Debonding:
Balance:      0
Total Shares: 0
Commission Schedule:
Rates:
- Start: epoch 16
Rate:  50 %
Rate Bounds:
- Start: …
```

Implement PrettyPrinter for various staking types and use it in stake CLI

---

.changelog/3088.feature.md
docs/oasis-node/metrics.md
go/worker/storage/committee/node.go

Add round sync metrics to storage worker

---

.changelog/3097.process.md
Makefile
common.mk
docs/release-process.md

Remind to bump protocol versions before release

---

.changelog/3105.bugfix.md
go/oasis-node/cmd/node/unsafe_reset.go

See: https://github.com/oasisprotocol/oasis-core/blob/ec03a8ec565e53f48e7f0a8bfffcd63932443b60/go/oasis-node/cmd/node/unsafe_reset.go#L47-L48

oasis-node/cmd/unsafe-reset: fix globs for runtime files

---

.changelog/3103.internal.md
go/oasis-test-runner/cmd/root.go

Prevent oasis-test-runner to match too many scenarios for a given scenario name regex by ensuring the given scenario name regex matches the whole scenario name.
For example, previously, using
```
oasis-test-runner --test a [... other arguments ...]
```
would match and run all the following scenarios:
```
e2e/runtime/runtime-dynamic
e2e/runtime/keymanager-replication
e2e/gas-fees/staking
e2e/runtime/byzantine/executor-straggler
e2e/runtime/gas-fees/runtimes
e2e/node-upgrade
e2e/runtime/keymanager-upgrade
e2e/runtime/runtime-upgrade
e2e/gas-fees/staking-dump-restore
e2e/early-query
e2e/stake-cli
e2e/runtime/byzantine/merge-honest
e2e/runtime/storage-sync
remote-signer/basic
e2e/runtime/byzantine/merge-wrong
e2e/runtime/byzantine/merge-straggler
e2e/runtime/byzantine/executor-honest …
```

go/oasis-test-runner/cmd: Limit scenario name regex matching

---

.changelog/3106.internal.md
go/oasis-test-runner/scenario/e2e/runtime/late_start.go

Note: not overriding `Clone` in a scenario that embeds a different scenario actually causes embedded scenario test to be run (since `Clone` returns the embedded "parent" scenario).
Did check all other test scenarios and all do override the `Clone()` method.

go/tests/e2e: add missing Clone() override to late-start

---

.changelog/3104.bugfix.md
go/oasis-test-runner/cmd/root.go

go/oasis-test-runner/cmd: Sort scenarios for correct parallel execution

---

.changelog/3093.feature.md
go/consensus/tendermint/apps/registry/query.go
go/consensus/tendermint/registry/registry.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/api/api.go
go/registry/api/grpc.go
go/registry/tests/tester.go

Fixes: #3093
TODO:
- actually cannot reporduce this in the runtime dynamic test (or locally anymore), so it might have worked fine even before (even if the node fast-syncs it still get's all the events during fast syncing so it does get notified of the suspended runtimes). Nevertheless this change is still useful.

go/registry: Add support for querying suspended runtimes

---

.changelog/3113.breaking.md
go/oasis-node/cmd/common/flags/flags.go
go/oasis-node/cmd/stake/account.go
go/oasis-node/cmd/stake/stake.go

As mentioned https://github.com/oasisprotocol/oasis-core/pull/3111#discussion_r456003315, the retry functionality is not needed since the staking client waits for a response from the gRPC server.

go/oasis-node/cmd: Remove retry functionality from staking CLI commands

---

.changelog/3091.internal.md
go/consensus/tendermint/api/api.go
go/consensus/tendermint/api/api_test.go
go/consensus/tendermint/apps/epochtime_mock/epochtime_mock.go
go/consensus/tendermint/apps/roothash/api.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/transactions.go
go/consensus/tendermint/beacon/beacon.go
go/consensus/tendermint/epochtime/epochtime.go
go/consensus/tendermint/epochtime_mock/epochtime_mock.go
go/consensus/tendermint/keymanager/keymanager.go
go/consensus/tendermint/registry/registry.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/scheduler/scheduler.go
go/consensus/tendermint/seed.go
go/consensus/tendermint/service/service.go
go/consensus/tendermint/services.go
go/consensus/tendermint/staking/staking.go
go/consensus/tendermint/tendermint.go
go/epochtime/api/api.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/scheduler.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
go/roothash/api/api.go
go/scheduler/api/api.go
go/storage/client/client.go

go/consensus/tendermint: Refactor internal event handling

---

.changelog/3037.feature.1.md
.changelog/3037.feature.2.md
.changelog/3111.breaking.md
go/common/crypto/signature/signature.go
go/common/entity/entity.go
go/common/node/node.go
go/common/prettyprint/prettyprint.go
go/consensus/api/transaction/transaction.go
go/genesis/tests/helpers.go
go/oasis-node/cmd/consensus/consensus.go
go/oasis-node/cmd/stake/account.go
go/oasis-node/cmd/stake/stake.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/registry/api/runtime.go
go/staking/api/api.go
go/staking/api/commission.go
go/staking/api/prettyprint.go
go/staking/api/prettyprint_test.go

Closes #3037.
Example outputs of update `oasis-node stake` CLI commands:
```
[tadej@toronto staking-docs-network]$ oasis-node-dev stake info -a $ADDR
Token's ticker symbol: AMBER
Token's value base-10 exponent: 9
Total supply: AMBER 10000000000.0
Common pool: AMBER 7999217230.11968289
Last block fees: AMBER 0.0
Staking threshold (entity): AMBER 100.0
Staking threshold (node-validator): AMBER 100.0
Staking threshold (node-compute): AMBER 100.0
Staking threshold (node-storage): AMBER 100.0
Staking threshold (node-keymanager): AMBER 100.0
Staking threshold (runtime-compute): AMBER 100.0
Staking threshold (runtime-keymanager): AMBER 100.0
```
```
[tadej@toronto staking-docs-network]$ oasis-node-dev stake account info   -a $ADDR   --stake.account.address …
```

Enable pretty-printers to print stake amounts in tokens

---

.changelog/3117.bugfix.md
go/oasis-node/cmd/common/common.go

Instead of using an entity populated with the zero values and a manually
filled in public key, use the entity constructor that can fill in
sensible values for things like the version.
Rescued from #3094

go/oasis-node/cmd/common: ExportEntity should use the entity ctor

---

.buildkite/code.pipeline.yml
.buildkite/scripts/download_e2e_test_artifacts.sh
.buildkite/scripts/test_e2e.sh
.changelog/3120.feature.1.md
common.mk
go/.gitignore
go/.golangci.yml
go/Makefile
go/common/crypto/signature/signers/plugin/plugin.go
go/oasis-node/cmd/common/signer/signer.go
go/oasis-node/cmd/common/signer/signer_test.go
go/oasis-test-runner/cmd/common/common.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/scenario/pluginsigner/basic.go
go/oasis-test-runner/scenario/pluginsigner/example_signer_plugin/main.go
go/oasis-test-runner/scenario/pluginsigner/pluginsigner.go
go/oasis-test-runner/scenario/remotesigner/basic.go
go/oasis-test-runner/scenario/signer/signer.go
go/oasis-test-runner/test-runner.go

Bloating the repository with a ton of different HSM (etc) signing backends doesn't make sense, and is a maintenance burden.  Use the runtime's built-in DLSO support to be able to separate out the non-esssential implementations.
After merge:
* Move the ledger implementation off into a separate repository (https://github.com/oasisprotocol/oasis-core-ledger/issues/13)
* Remove the integrated ledger signer implementation.
* Remove the ledger oasis-node sub command.
Notes:
* The plugin loader enforces (rather strictly) that the package versions of plugins are the same as what the loading application was built with.  This will require everything be built with `-trimpath`, but we should be doing that already anyway.  See https://github.com/golang/go/issues/27751 for more information.
* This is …

go/common/crypto/signature: Add and use the plugin backed signer

---

.changelog/3119.internal.md
go/common/cbor/versioned.go
go/common/cbor/versioned_test.go
go/common/entity/entity.go
go/common/node/node.go
go/consensus/tendermint/apps/registry/state/state_test.go
go/consensus/tendermint/apps/registry/transactions_test.go
go/consensus/tendermint/apps/staking/slashing_test.go
go/genesis/genesis_test.go
go/oasis-node/cmd/debug/byzantine/registry.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/node_test.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/api/runtime.go
go/registry/gen_vectors/main.go
go/registry/tests/tester.go
go/roothash/api/commitment/pool_test.go
go/upgrade/migrations/dummy.go
go/worker/registration/worker.go

go: Use `cbor.Versioned` for descriptor versioning

---

.buildkite/benchmarks.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/go/upload_artifacts.sh
.buildkite/longtests.pipeline.yml
.changelog/3125.internal.md

Extracted from https://github.com/oasisprotocol/oasis-core/pull/3124 since otherwise the next longtest run will fail.

ci: extract go artifacts upload code into a script

---

.changelog/3101.breaking.md
go/consensus/tendermint/seed.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/identity/tendermint/tendermint.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/seed.go
go/oasis-test-runner/oasis/sentry.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go

Fixes #3101 
Previously the Tendermint consensus backend used the node's identity key for
Tendermint P2P connections. This has now been changed to use the node's P2P
key instead as that can be made ephemeral in the future.

go/consensus/tendermint: Use P2P key for Tendermint P2P

---

.buildkite/code.pipeline.yml
.changelog/3124.bugfix.md
.changelog/3124.internal.md
go/consensus/tendermint/roothash/roothash.go
go/oasis-node/cmd/debug/txsource/workload/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
tests/fixture-data/txsource/staking-genesis.json

TODO:
Fixes:
* .buildkite/longtests.pipeline.yml missing new artifact: extracted into: #3125
* go/consensus/tendermint/roothash: ignore non tracked runtimes when reindexing

go/e2e/txsource: periodically restart runtime nodes

---

.changelog/3127.bugfix.md
.changelog/3127.internal.md
go/consensus/tendermint/abci/prune.go
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/api/state.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/tendermint.go
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/debug/dumpdb/dumpdb.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/log.go
go/oasis-test-runner/scenario/e2e/runtime/history_reindex.go
go/oasis-test-runner/scenario/e2e/runtime/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/roothash/api/api.go
tests/fixture-data/net-runner/default.json

* makes roothash reindexing aware of pruning
* adds a e2e/test scenario that triggers reindexing (with prunning)
TODO:

 go/tendermint/roothash: Skip pruned heights when reindexing

---

.changelog/3133.bugfix.md
go/oasis-node/cmd/debug/byzantine/p2p.go
go/worker/common/committee/group.go
go/worker/common/p2p/dispatch.go

If the message's group version indicates that the message is stale and an
authorization check fails, treat the error as permanent as a stale message will
never become valid.

go/worker/common: Treat stale unauthorized peer error as permanent

---

.changelog/2213.bugfix.md
.changelog/3139.bugfix.md
docs/runtime/runtime-host-protocol.md
go/common/cbor/codec.go
go/runtime/transaction/transaction.go
go/runtime/transaction/transaction_test.go
go/worker/compute/executor/committee/batch.go
go/worker/compute/executor/committee/node.go
runtime/src/protocol.rs

Fixes #2213
Message size is reduced based on benchmark metrics where messages never exceeded 3 MiB even with large batches.
Also enforces maximum batch sizes at compute nodes.

runtime: Reduce maximum RHP message size

---

.buildkite/go/upload_artifacts.sh
.buildkite/scripts/download_e2e_test_artifacts.sh
.buildkite/scripts/test_e2e.sh
.changelog/3120.feature.1.md
go/.gitignore
go/Makefile
go/common/crypto/signature/signers/plugin/interface.go
go/common/crypto/signature/signers/plugin/plugin.go
go/common/crypto/signature/signers/plugin/rpc.go
go/go.mod
go/go.sum
go/oasis-node/cmd/common/signer/signer.go
go/oasis-node/main.go
go/oasis-remote-signer/main.go
go/oasis-test-runner/scenario/pluginsigner/basic.go
go/oasis-test-runner/scenario/pluginsigner/example_signer_plugin/main.go
go/oasis-test-runner/scenario/pluginsigner/pluginsigner.go
go/oasis-test-runner/test-runner.go

The Go runtime library's `plugin` is a steaming pile of shit.  Switch
to something that lets people write plugins that live in a separate
module, that import sub-packages from the module that is loading the
plugin.

go/common/crypto/signature/signers/plugin: Rewrite

---

.changelog/3136.doc.md
docs/adr/0001-tm-multi-root-apphash.md

Currently the Tendermint ABCI application hash is equal to the consensus state
root for a specific height. In order to allow additional uses, like proving to
light clients that specific events have been emitted in a block, we should make
the application hash be derivable from potentially different kinds of roots.

ADR 0001: Multiple Roots Under the Tendermint Application Hash

---

.changelog/3146.breaking.md
go/consensus/tendermint/apps/registry/transactions.go
go/genesis/genesis_test.go
go/registry/api/api.go
go/registry/tests/tester.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3146

go/registry: Require SGX for non-test keymanager runtimes

---

.changelog/3152.feature.md
go/consensus/api/api.go
go/consensus/api/base.go
go/consensus/api/grpc.go
go/consensus/api/light.go
go/consensus/tendermint/full/light.go
go/consensus/tests/tester.go

Fixes #3152 
The new method allows submitting a transaction without waiting for it to be
included in a block.

go/consensus: Add SubmitTxNoWait method

---

.changelog/2871.feature.md
.changelog/3157.feature.md
go/common/prettyprint/context.go
go/consensus/api/transaction/transaction.go
go/oasis-node/cmd/consensus/consensus.go
go/oasis-node/cmd/stake/account.go

Show Genesis document's hash when generating staking transactions with `oasis-node stake account gen_*` CLI commands, e.g.:
```
You are about to sign the following transaction:
Nonce:  1
Fee:    2000 (gas limit: 1000, gas price: 2)
Method: staking.AddEscrow
Body:
Account: oasis1qpl4axynedmdrrgrg7dpw3yxc4a8crevr5dkuksl
Amount:  AMBER 208.0
Other info:
Genesis document's hash: 0b9ddeaa80431ff3718f928e654e4b64cbd3f956d69d64e9c923e30766706a11
You may need to review the transaction on your device if you use a hardware-based signer plugin...
```
And when showing transactions' pretty prints with the `oasis-node consensus show_tx` CLI command, e.g.:
```
Hash: 144bf255028a13ec03c2c19879658a97de44e32adb9750690ac2579a4df81518
Signer: l+cuboPsOeuY1+kYlROrpmKgiiELmXSw9xl0WEg8cWE=
(signature: …
```

go/oasis-node/cmd: Show Genesis document's hash when displaying transactions

---

.changelog/3142.internal.md
go/go.mod
go/go.sum
go/storage/mkvs/db/badger/badger.go

TODO:
- looks much better during compaction & also fixes cpu spikes at node restarts (there was a bug with badger vlog replay that replayed all vlogs)

go/badger: bump badger version

---

.changelog/3161.bugfix.md
go/consensus/tendermint/full/full.go
go/oasis-node/cmd/common/metrics/metrics.go
go/registry/metrics.go
go/runtime/host/protocol/connection.go

Runtime events are also triggered when a runtime is resumed, however we never subtract a runtime being suspended.

go/registry/metrics: Runtimes metrics: query for runtimes

---

.changelog/3160.bugfix.md
go/storage/mkvs/checkpoint/checkpoint.go
go/storage/mkvs/checkpoint/checkpoint_test.go
go/storage/mkvs/checkpoint/checkpointer.go
go/storage/mkvs/checkpoint/checkpointer_test.go
go/storage/mkvs/checkpoint/file.go

When all root checkpoints are removed for a specific version, the version dir
itself should also be removed.

go/storage/mkvs/checkpoint: Remove empty version directories

---

.changelog/3169.feature.md
go/consensus/api/api.go
go/consensus/api/base.go
go/consensus/api/grpc.go
go/consensus/api/light.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/light/client.go
go/consensus/tendermint/tests/evidence.go
go/consensus/tests/tester.go

Fixes #3169 
This allows light clients to submit evidence of Byzantine behavior.

go/consensus: Move SubmitEvidence to LightClientBackend

---

.changelog/3162.feature.md
go/worker/keymanager/worker.go

Fixes:
>Maybe it would be better to make sure that the key manager worker (not only the enclave) ignores any runtimes which are not in the policy document but are trying to use the key manager? This would make the key manager reject requests one layer earlier.
TODO:
- can do in future if needed

go/worker/keymanager: Ignore runtimes not in policy document

---

.changelog/3173.bugfix.md
go/consensus/tendermint/abci/prune.go
go/storage/mkvs/db/api/api.go
go/storage/mkvs/db/badger/badger.go

Otherwise a crash can cause the state database to be rolled back to a version
that has already been discarded from Tendermint's state stores which would
prevent replay on restart.
Discovered during long-term tests.

go/consensus/tendermint: Sync state database before discarding versions

---

.changelog/3151.feature.md
.changelog/3167.feature.1.md
.changelog/3167.feature.2.md
go/common/prettyprint/context.go
go/consensus/api/transaction/gas.go
go/consensus/api/transaction/transaction.go
go/genesis/genesis_test.go
go/oasis-node/cmd/consensus/consensus.go
go/oasis-node/cmd/stake/account.go
go/oasis-node/cmd/stake/stake.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/staking/api/api.go
go/staking/api/prettyprint.go
go/staking/api/prettyprint_test.go
go/staking/api/sanity_check.go
go/staking/api/token/prettyprint.go
go/staking/api/token/prettyprint_test.go
go/staking/api/token/token.go

An example of the new output:
```
You are about to sign the following transaction:
Nonce:  7
Fee:
Amount: AMBER 0.000002
Gas limit: 1000
(gas price: AMBER 0.000000002 per gas unit)
Method: staking.Transfer
Body:
To:     oasis1qr3jc2yfhszpyy0daha2l9xjlkrxnzas0uaje4t3
Amount: AMBER 170.0
Other info:
Genesis document's hash: da80e19432de40911469314ee5aa02ee9ea5e5518b01b0b1eb3a13e526a8e3ca
```
TODO:
Closes https://github.com/oasisprotocol/oasis-core/issues/3151.

 Pretty print transaction's gas amount in token units

---

.changelog/3182.internal.md
go/go.mod
go/go.sum

Note: only diff to the commit we were using before is the added changelog.

go/badger: bump to 20.07.0

---

.changelog/3178.bugfix.md
go/genesis/api/sanity_check.go
go/genesis/genesis_test.go

Fixes #3178 
Previously the genesis document sanity check rejected genesis documents with
future timestamps which made it awkward to prepare the node in advance. Since
the only supported consensus backend (Tendermint) can handle future
timestamps by delaying the consensus process, allow such genesis documents.

go/genesis: Remove time sanity check

---

.changelog/3187.feature.md
go/consensus/api/api.go
go/consensus/api/base.go
go/consensus/api/grpc.go
go/consensus/tendermint/full/full.go
go/consensus/tests/tester.go

Fixes #3187 
The new method allows the caller to query the current set of transactions in
the mempool (e.g., known transactions which have not yet been included in a
block).

go/consensus: Add the GetUnconfirmedTransactions method

---

.changelog/3194.internal.md
go/oasis-test-runner/scenario/e2e/consensus_state_sync.go

Instead of terminating the validator-to-be-synced immediately and restarting
it later, do not even start it. Early stopping could result in state that
prevents proper state sync later.

go/oasis-test-runner: Fix e2e/consensus-state-sync scenario

---

.changelog/3080.breaking.md
go/consensus/tendermint/staking/staking.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/staking/api/api.go
go/staking/api/grpc.go
go/staking/tests/tester.go

Fixes #3080 
The separate WatchTransfers/Burns/Escrows methods provided less information
than the more general WatchEvents, namely they were missing the height and tx
hash. There is no good reason to maintain both as the individual methods can
be easily replaced with WatchEvents.

go/staking: Remove WatchTransfers/Burns/Escrows in favor of WatchEvents

---

.changelog/3204.breaking.md
go/common/cbor/versioned.go
go/genesis/genesis_test.go
go/go.mod
go/go.sum

This should result in some smaller payloads as omitempty should work better for
our use cases now.

go/common/cbor: Bump fxamacker/cbor to 58b1cf4afc2b

---

.changelog/3213.trivial.md
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/state/state.go
go/consensus/tendermint/apps/supplementarysanity/checks.go
go/roothash/tests/tester.go

go/consensus/tendermint/apps/roothash: Clear timeout in emitEmptyBlock

---

.changelog/3214.internal.md
go/roothash/tests/tester.go

Extracted from: https://github.com/oasisprotocol/oasis-core/pull/3212

go/roothash/tester: fix flaky RoundTimeoutWithEpochTransition

---

.changelog/3215.bugfix.md
go/oasis-node/cmd/registry/entity/entity.go

Fixes #3215 
The "registry entity init" subcommand previously always performed a check
whether an entity already exists. It did that by creating an additional signer
factory to perform this check.
Some signers assign exclusive access to an underlying resource (e.g., HSM) to
the given factory. In that case, all operations on the second signer factory
would fail. Thus we now omit the existing entity check for non-file signers.

go/oasis-node: Omit existing entity check for non-file signers

---

.changelog/3215.bugfix.md
go/oasis-node/cmd/registry/entity/entity.go

The "registry entity init" subcommand previously always performed a check
whether an entity already exists. It did that by creating an additional signer
factory to perform this check.
Some signers assign exclusive access to an underlying resource (e.g., HSM) to
the given factory. In that case, all operations on the second signer factory
would fail. Thus we now omit the existing entity check for non-file signers.

[BACKPORT/20.9.x] go/oasis-node: Omit existing entity check for non-file signers

---

.changelog/3203.bugfix.md
go/runtime/scheduling/api/api.go
go/runtime/scheduling/init.go
go/runtime/scheduling/simple/incoming_queue.go
go/runtime/scheduling/simple/simple.go
go/runtime/scheduling/simple/simple_test.go
go/runtime/scheduling/tests/tester.go
go/worker/compute/executor/committee/node.go

go/worker/executor: update scheduling parameters on runtime updates

---

.changelog/3197.internal.1.md
go/common/crypto/signature/signers/remote/grpc.go
go/common/grpc/credentials.go
go/common/grpc/policy/policy_test.go
go/common/grpc/proxy/proxy_test.go
go/ias/proxy/client/client.go

See #3197 
While we only ever use public key pinning for authenticating TLS connections,
some places still used the regular TLS config with a single certificate in
the certificate pool. This causes failures on Go 1.15+ due to CommonName
checks being deprecated, even if we never used hostnames for authentication.
This changes all cases to use our explicit public key pinning credentials for
gRPC connections.

go: Explicitly use public key pinning for certificate verification

---

.changelog/3225.breaking.md
.changelog/3225.cfg.md
.changelog/3225.feature.md
go/common/crypto/signature/signer.go
go/common/crypto/signature/signer_test.go
go/oasis-node/cmd/common/signer/signer.go
go/oasis-node/cmd/common/signer/signer_test.go

The `--signer.composite.backends` CLI flag previously accepted integer-indexed Signer roles, e.g:
```
--signer.composite.backends 1:file,2:file,3:file,4:plugin
```
Now, it only accepts descriptive string names for Signer roles, e.g.:
```
--signer.composite.backends entity:file,node:file,p2p:file,consensus:plugin
```

go/common/crypto/signature: Use descriptive names for Signer roles 

---

.changelog/3230.bugfix.md
go/extra/stats/cmd/root.go
go/oasis-net-runner/cmd/root.go
go/oasis-node/cmd/root.go
go/oasis-remote-signer/cmd/root.go

Previously, `Execute()` called `nodeCommon.EarlyLogAndExit()` if there was an error running `rootCmd.Execute()` which in turn printed the error to stderr.
The error message is printed to stdout via [github.com/spf13/cobra's `ExecuteC()`](https://github.com/spf13/cobra/blob/a684a6d7f5e37385d954dd3b5a14fc6912c6ab9d/command.go#L959-L963) already, so this resulted in the same error message being printed twice.
This is an expansion of f5f906b3c076290d20ea6cbd298ce548c2000513 which fixed this behavior for `go/oasis-test-runner/cmd`.
Closes #3048.

go: Fix CLI tools to not print error messages twice

---

.github/workflows/ci-reproducibility.yml

This matches the behavior from actions/download-artifact@v1 (ref: https://github.com/actions/download-artifact#compatibility-between-v1-and-v2)

ci/ci-reproducibility: fix output path

---

.changelog/3249.breaking.md
.changelog/3249.internal.md
docs/release-process.md
docs/versioning.md
go/common/version/version.go
runtime/src/common/version.rs

Also, document how to include protocol versions in the Change Log.

Bump protocol versions to 1.0.0 in preparation for the Mainnet

---

.changelog/3253.bugfix.md
.changelog/3253.internal.md
go/runtime/committee/nodes.go
go/storage/api/api.go
go/storage/client/client.go
go/storage/client/init.go
go/storage/metrics.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go
go/worker/compute/executor/committee/node.go
go/worker/storage/committee/node.go

Previously the runtime worker(s) used the common storage client which was not
synced with any particular committee version. This could cause an executor
node to use a stale storage node for storing updates.
TODO

go/worker/common: Use group-synced storage client

---

.buildkite/code.pipeline.yml
.changelog/3181.internal.md
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/log.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/registry/api/runtime.go
go/runtime/committee/committee.go
go/storage/api/grpc.go
go/storage/client/init.go
go/storage/mkvs/checkpoint/checkpoint.go
go/storage/mkvs/checkpoint/restorer.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go
go/worker/storage/worker.go

go/worker/storage: Add initial sync from checkpoints

---

.changelog/3260.internal.md
.github/dependabot.yml
Cargo.lock
keymanager-lib/Cargo.toml
keymanager-lib/src/policy.rs
runtime/Cargo.toml
runtime/src/common/crypto/hash.rs
runtime/src/common/crypto/mrae/deoxysii.rs
runtime/src/common/sgx/egetkey.rs

rust update tiny-keccak, hmac, sha2 dependencies

---

docs/setup/prerequisites.md

Here is how it looks like before this change:

docs: Fix wrong indentation of Ubuntu system packages install command

---

.changelog/3265.feature.1.md
.changelog/3265.feature.2.md
go/common/prettyprint/context.go
go/oasis-test-runner/scenario/e2e/stake_cli.go
go/staking/api/commission.go
go/staking/api/commission_test.go
go/staking/api/prettyprint.go
go/staking/api/prettyprint_test.go

Example of an old pretty print:
```
You are about to sign the following transaction:
Nonce:  0
Fee:
Amount: AMBER 0.000002
Gas limit: 1000
(gas price: AMBER 0.000000002 per gas unit)
Method: staking.AmendCommissionSchedule
Body:
Amendment:
Rates:
- Start: epoch 32
Rate:  50.0%
- Start: epoch 40
Rate:  40.0%
- Start: epoch 48
Rate:  30.0%
- Start: epoch 56
Rate:  25.0%
- Start: epoch 64
Rate:  20.0%
Rate Bounds:
- Start:        epoch 32
Minimum Rate: 10.0%
Maximum Rate: 50.0%
- Start:        epoch 64
Minimum Rate: 10.0%
Maximum Rate: 30.0%
Other info:
Genesis document's hash: d7aff9a80cf626fb49585a37c8f8e0ec99bccdec1c93c93d566accdccdb58bef
```
Same example with the new pretty print:
```
You are about to sign the following transaction:
Nonce:  0
Fee:
Amount: AMBER 0.000002
Gas limit: 1000 …
```

Pretty print commission schedule rates and rate bounds as enumerated lists

---

.changelog/3272.trivial.md
codecov.yml

Since `extra` is for packages that are not directly part of oasis-core it makes sense skipping those for coverage checks.
Noticed when the coverage increased after removing `extra/stats`: https://github.com/oasisprotocol/oasis-core/pull/3270

ci/codecov: ignore go/extra code coverage

---

.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.yml
.changelog/3264.bugfix.md
.changelog/3264.cfg.md
go/runtime/client/watcher.go
go/worker/common/p2p/init.go
go/worker/common/p2p/p2p.go

Backport of https://github.com/oasisprotocol/oasis-core/pull/3264.

[BACKPORT/20.10.x] go/worker/p2p: configurable libp2p buffer sizes

---

.changelog/3275.feature.md
go/runtime/client/tests/tester.go
go/worker/common/p2p/p2p.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3275

go/worker/p2p: Use hash of the message payload as message ID

---

.changelog/3274.feature.md
Cargo.lock
go/common/cache/lru/lru.go
go/common/cache/lru/lru_test.go
go/oasis-node/cmd/debug/txsource/workload/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_restart.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
go/runtime/client/tests/tester.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/state.go
go/worker/compute/executor/init.go
go/worker/compute/executor/tests/tester.go
go/worker/compute/executor/worker.go
tests/clients/simple-keyvalue-enc/Cargo.toml
tests/clients/simple-keyvalue-enc/src/main.rs
tests/clients/simple-keyvalue-ops/Cargo.toml
tests/clients/simple-keyvalue-ops/src/main.rs
tests/clients/simple-keyvalue/Cargo.toml
tests/clients/simple-keyvalue/src/main.rs
tests/clients/test-long-term/Cargo.toml
tests/clients/test-long-term/src/main.rs
tests/runtimes/simple-keyvalue/api/src/api.rs
tests/runtimes/simple-keyvalue/api/src/lib.rs
tests/runtimes/simple-keyvalue/src/main.rs

go/worker/executor: cache of last seen runtime transactions

---

.changelog/2757.feature.md
.changelog/3278.internal.md
docs/consensus/genesis.md
docs/index.md
docs/toc.md
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/genesis_file.go

Update `oasis-node genesis init` and `oasis-node genesis dump` CLI commands to create pretty-printed JSON files that represent the Oasis' *canonical* Genesis file format.
This  _canonical_ form enables simple state patching with the standard Unix tools (i.e. `diff`/`patch`).
Closes #2757.

Introduce the canonical form of Genesis files

---

.changelog/3286.bugfix.md
go/worker/registration/worker.go

Fixes #3286 
This avoids some cases of failed node registration transactions when the entity
under which the node is being registered does not actually exist.

go/worker/registration: Verify entity exists before node registration

---

.changelog/3289.bugfix.md
go/runtime/host/protocol/connection.go

go/runtime/host/protocol: Add write timeouts

---

.changelog/3298.doc.md
.changelog/3298.feature.md
docs/oasis-node/cli.md
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/scenario/e2e/genesis_file.go

Partially extracted from #3290.

go/oasis-node/cmd/genesis: Add check for canonical form to check command & Docs

---

.changelog/3300.bugfix.md
go/worker/compute/executor/committee/node.go

`BackupWorker` also doesn't follow transactions and processed batches so should also reset the queue in that case. 
Not sure how i missed this in: https://github.com/oasisprotocol/oasis-core/pull/3300

go/worker/executor: clear tx queue before becoming a worker

---

.changelog/3223.internal.md
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/debond.go
go/oasis-test-runner/scenario/e2e/runtime/gas_fees.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_restart.go
go/oasis-test-runner/scenario/e2e/runtime/node_shutdown.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/oasis-test-runner/scenario/e2e/test_accounts.go
go/oasis-test-runner/scenario/e2e/upgrade.go

txsource: Shut down nodes for longer period of time

---

.changelog/3303.bugfix.md
go/consensus/tendermint/full/full.go
go/oasis-node/cmd/node/node.go

go/oasis-node: Start internal gRPC server before consensus backend

---

.changelog/3313.internal.md
common.mk

Omit node operator link from release notes

---

.changelog/3319.bugfix.md
go/worker/common/p2p/dispatch.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3318

go/worker/p2p: Skip peer authentication for our own messages

---

.changelog/3320.bugfix.md
go/worker/compute/executor/committee/node.go

Don't unnecessarily hold the lock during external requests to storage nodes, as those can take long time. 
Issue discovered in the daily tests with long restarts, when the storage node is taken offline, these requests can take up to 15 sec to timeout.

go/worker/executor: don't hold the lock during storage requests

---

.changelog/3329.trivial.md
.changelog/3330.bugfix.md
go/storage/mkvs/checkpoint/checkpoint_test.go
go/storage/mkvs/db/badger/badger.go
go/worker/storage/committee/checkpoint_sync.go

Fixes #3329 
Fixes #3330 
* go/worker/storage: Abort multipart insert after failed finalize
Make sure to abort the multipart insert after a failed finalize operation as
otherwise all normal batch operations will continue to fail.
* go/storage/mkvs: Fix Finalize after checkpoint restore

Storage checkpoint restore related fixes

---

.changelog/3302.internal.md
go/common/grpc/errors.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go

- don't fail on `EOF` on `GetTransactionsWithResults`
- enable `TendermintRecoverCorruptedWAL` also for non-validators since the upstream recovery doesn't seem to work all that well

queries workload eof

---

.changelog/3338.internal.md
go/oasis-node/cmd/debug/txsource/workload/queries.go

A `QueryTxs` in the daily E2E tests will fail in case it's done for a height for which active storage nodes are missing historical state due to restoring from snapshots (https://github.com/oasisprotocol/oasis-core/issues/3337). Note: for this to happen also the `storage-0` needs to not be in the committee for the epoch (since `storage-0` is never restarted it has all the state), and the other storage node (which likely has the state) is down (e.g. due to just being restarted), therefore this should happen rarely.
This makes the E2E test not fail in those cases.

go/e2e/workload-queries: allow historical `QueryTxs` to fail few times

---

.changelog/3333.internal.md
go/common/crypto/signature/signers/plugin/plugin.go
go/common/syscall/syscall_darwin.go
go/common/syscall/syscall_linux.go
go/oasis-node/cmd/common/isatty.go
go/oasis-test-runner/env/env.go

This PR factors out some OS-specific syscall parameters for conditional compilation.
_This does not change the fact that **macOS is not officially supported by oasis-core**._

go: update to build on macOS

---

.changelog/3340.internal.md
go/.nancy-ignore

Should be fixed now: https://github.com/sonatype-nexus-community/nancy/issues/189

go/nancy: remove fixed 'golang.org/x/net' false positive ignores

---

.changelog/3341.internal.md
go/.nancy-ignore
go/go.mod
go/go.sum

With updated `nancy` (done in https://github.com/oasisprotocol/oasis-core/pull/3283) we now use `go list -json -m all` to get the list of dependencies, which does correctly take `replace` directive into account. Therefore we can now replace the vulnerable etcd and remove the CVE ignores.

go/dependencies/etcd: update etcd with replace directive

---

.changelog/3342.trivial.md
go/worker/compute/executor/committee/node.go

Currently (since https://github.com/oasisprotocol/oasis-core/pull/3320) this check is made after a node publishes a message, instead this check should be made before node publishes a message to prevent proposing another batch after node starts processing a batch.
Note that `p2p.Publish` is async so this shouldn't increase the time the CrossNode.Lock is held by much.

go/executor/node: check if we are in correct state before publishing a message

---

.changelog/3327.doc.md
.changelog/3327.internal.1.md
.changelog/3327.internal.2.md
.changelog/3327.internal.3.md
.changelog/3327.internal.4.md
.changelog/3327.internal.5.md
.github/workflows/release.yml
.goreleaser.yml
.punch_config.py
.punch_version.py
Makefile
common.mk
docs/release-process.md
towncrier.toml

Among other things, this should get rid of the:
```
/bin/bash: punch: command not found error
```
error message when running Make targets without having the Punch utility installed.

Refactor release tooling

---

go/go.mod
go/go.sum

Includes https://github.com/tendermint/tendermint/pull/5412.
TODO

go/consensus/tendermint: Bump Tendermint Core to v0.34-rc4-oasis4

---

.changelog/3347.bugfix.md
go/worker/common/committee/group.go

Discovered while testing: https://github.com/oasisprotocol/oasis-core/pull/3322
Note: in the other place where we compute current version (runtime client) we already handle this case correctly.

go/worker/common/committee: group version should be the epoch block

---

.changelog/3311.breaking.md
go/common/version/version.go
go/common/version/version_test.go
go/worker/common/p2p/dispatch.go
go/worker/common/p2p/p2p.go

Fixes: #3311
Note: used `MajorMinor()` since we also used that for runtime-host protocol.
This is a breaking `RuntimeCommitteeProtocol` change.

p2p topic ids: include chain ID and remove patch version

---

.changelog/3348.feature.md
go/consensus/api/api.go
go/consensus/tendermint/full/full.go
go/consensus/tests/tester.go

cross reference https://github.com/oasisprotocol/oasis-core-rosetta-gateway/issues/57

backport #3348 to 20.10

---

.changelog/3369.internal.md
go/consensus/tendermint/abci/mux.go
go/oasis-test-runner/oasis/log.go
go/oasis-test-runner/scenario/e2e/consensus_state_sync.go

Previous "fix" (see #3194) actually made the test silently skip actually performing state sync because it used the wrong validator index.

go/oasis-test-runner: Fix e2e/consensus-state-sync scenario (take two)

---

.changelog/3372.internal.md
go/common/grpc/errors_test.go
go/oasis-node/cmd/debug/txsource/workload/queries.go

Working fix from: #3302 , now with tests

go/e2e/queries: correctly ignore UnexpectedEOF errors

---

.changelog/3378.bugfix.md
go/worker/common/p2p/peermgmt.go

Previously we only removed peers and updated existing peers from the received node list - therefore a node restarting in the middle of an epoch did not actually connect to all of the nodes until the next epoch transition (it only connected to the nodes that did an update mid-epoch - which triggered a `WatchNodes` event).
Discovered while testing #3322

go/worker/p2p: Include new peers from received node list

---

.changelog/3379.bugfix.md
go/consensus/tendermint/registry/registry.go
go/registry/api/api.go

Related to: https://github.com/oasisprotocol/oasis-core/pull/3378
Discovered when testing: https://github.com/oasisprotocol/oasis-core/pull/3322

go/registry.WatchNodeList: return current node list upon subscription

---

.changelog/3360.breaking.1.md
.changelog/3360.breaking.2.md
.changelog/3360.doc.md
.changelog/3360.feature.md
docs/index.md
docs/toc.md
docs/versioning.md
go/common/version/version.go
go/common/version/version_test.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/api/genesis.go
go/consensus/tendermint/full/statesync.go
go/consensus/tendermint/seed/seed.go
go/consensus/tendermint/tests/genesis/genesis.go
go/runtime/host/protocol/connection.go
go/worker/common/p2p/p2p.go
runtime/src/common/version.rs

Since we bumped the protocol versions to version 1.0.0 with the release of Oasis Core 20.10, we also need to modify how we compare and detect backward-incompatible changes to follow SemVer 2.0.0 rules.
From now onwards, only a change in a protocol's major version signifies a backward-incompatible change.
NOTE: The change in this PR would require a major bump in runtime committee protocol's version, but since it was already bumped in #3346, we don't need to bump it again.

Compare protocol versions according to SemVer 2.0.0

---

.changelog/3390.internal.md
go/go.mod
go/go.sum
go/worker/common/p2p/error/error.go
go/worker/common/p2p/error/error_test.go

Out upstream patch was accepted and released so the `EnsurePermanent` workaround can be simplified to only special case the `context.Canceled` method.

go/backoff: Update `cenkalti/backoff` to 4.1.0

---

.changelog/3393.trivial.md
go/runtime/scheduling/simple/incoming_queue.go
go/worker/compute/executor/committee/node.go

Minor change to the executor worker handling of retrying P2P Tx errors: 
- retry & relay Tx messages if CheckTx error is not actually permanent (e.g. errors due to runtime being not ready)
- QueueTx failures should generally be retried and relayed  (unless it's a duplicate transaction errors then it should be just relayed)

go/worker/executor: Relay transaction that fail to be enqueued

---

.changelog/3391.breaking.md
.changelog/3391.internal.md
go/common/version/version.go
go/consensus/tendermint/apps/roothash/roothash.go
go/oasis-node/cmd/debug/byzantine/executor.go
go/roothash/api/commitment/commitment.go
go/roothash/api/commitment/executor.go
go/roothash/api/commitment/executor_test.go
go/roothash/api/commitment/pool.go
go/roothash/api/commitment/pool_test.go
go/roothash/tests/tester.go
go/runtime/host/mock/mock.go
go/worker/compute/executor/committee/node.go
runtime/src/common/roothash.rs
runtime/src/dispatcher.rs

The E2E tests with increased epoch times (#3322) discovered a failure edge case that can happen if the storage committee becomes unavailable after proposer already proposes a batch, but before any of the nodes submit a commitment. In that case the nodes currently abort the processing and wait for a round failure. Since there is no submitted commitments the round failure only happens at the next epoch transition.
This PR adds support for failure indicating commitments (which were first proposed as part of the [ADR 0005](https://github.com/oasisprotocol/oasis-core/blob/cbf413b788e3fd0a0bc20b8193cc3570f99880b9/docs/adr/0005-runtime-compute-slashing.md)), which solve the above mentioned issue since compute nodes can now submit a failure indicating commitment and with it trigger a round …

failure indicating commitments

---

.changelog/3241.internal.md
.changelog/3307.trivial.md
.changelog/3329.trivial.md
.changelog/3330.bugfix.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/fuzz/fuzz.go
go/oasis-node/cmd/debug/consim/mockchain.go
go/oasis-node/cmd/debug/dumpdb/dumpdb.go
go/storage/mkvs/cache.go
go/storage/mkvs/checkpoint/checkpoint.go
go/storage/mkvs/checkpoint/checkpoint_test.go
go/storage/mkvs/checkpoint/chunk.go
go/storage/mkvs/checkpoint/restorer.go
go/storage/mkvs/commit.go
go/storage/mkvs/db/api/api.go
go/storage/mkvs/db/badger/badger.go
go/storage/mkvs/db/badger/badger_test.go
go/storage/mkvs/db/badger/metadata.go
go/storage/mkvs/interop/cmd/protocol_server.go
go/storage/mkvs/tree_test.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go
go/worker/storage/worker.go
runtime/src/storage/mkvs/interop/rpc.rs

Backports the following fixes related to storage node checkpoint sync:
* #3285 
* #3326
* #3331

[BACKPORT/20.11.x] Storage checkpoint fixes

---

.changelog/3416.internal.md
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/oasis.go

This adds the ability to change the initial block height at genesis time to something other than 1.

Add ability to set initial block height at genesis

---

.changelog/3416.internal.md
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/oasis.go

Backport of https://github.com/oasisprotocol/oasis-core/pull/3416.

[BACKPORT/20.11.x] Add ability to set initial block height at genesis

---

.changelog/3317.internal.md
.changelog/3396.breaking.md
go/consensus/genesis/genesis.go
go/consensus/tendermint/api/genesis.go
go/genesis/genesis_test.go
go/go.mod
go/go.sum
go/oasis-node/cmd/genesis/genesis.go

go/consensus/tendermint: Bump Tendermint Core to v0.34-rc5-oasis1

---

.changelog/3424.bugfix.md
go/storage/client/client.go

Fixes https://github.com/oasisprotocol/oasis-core/issues/3424 (and a flaky e2e storage_sync test)

storage/client: Retry NodeNotFound errors

---

.changelog/3432.bugfix.md
go/worker/common/committee/group.go

Fixes nil ptr defer that can happen if the executor node tries to publish a message before it's synced

go/worker/common/committee: check if active epoch exists

---

.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.sh
.buildkite/longtests.pipeline.yml
.buildkite/scripts/daily_txsource.sh
.changelog/3301.internal.md
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/oasis-test-runner/scenario/e2e/test_accounts.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3301
This enables configuring epochtime length for the daily txsource test run. 
To setup a daily run with longer epochs, setup another schedule in the existing pipeline and configure the epoch interval via the `LONGTESTS_EPOCHTIME_INTERVAL` env var.
TODO:
```
buildkite-agent pipeline upload .buildkite/longtests.pipeline.yml -> .buildkite/longtests.pipeline.sh
```

ci: Setup daily longterm tests with longer epoch periods

---

.changelog/3404.internal.md
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go

e2e/runtime/runtime-upgrade: Wait for old compute nodes to expire

---

.changelog/3412.bugfix.md
.changelog/3443.bugfix.md
.changelog/3443.cfg.md
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/scenario/e2e/runtime/client_expire.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/runtime/client/api/api.go
go/runtime/client/client.go
go/runtime/client/watcher.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3412
- runtime client remembers failed roothash blocks and rechecks them on every new received block
- additionally transactions that do not succeed in 1500 blocks are considered failed and client drops them
- as a future improvement should the client also support `SubmitTxNoWait` operation (opened https://github.com/oasisprotocol/oasis-core/issues/3444)

go/runtime/client: Recheck failed blocks and implement max tx age

---

.changelog/3460.bugfix.md
Cargo.lock
runtime-loader/Cargo.toml

https://rustsec.org/advisories/RUSTSEC-2020-0059

rust: bump futures to 0.3.7

---

.changelog/3470.breaking.md
go/common/version/version.go

Since https://github.com/oasisprotocol/oasis-core/pull/3360 has been merged, we stated that from now onwards, only a change in a protocol's major version signifies a backward-incompatible change.
The change in https://github.com/oasisprotocol/oasis-core/pull/3458/ is a breaking change, hence we should bump the consensus protocol's major version.

go/common/version: Bump consensus protocol version to 2.0.0

---

.changelog/3477.bugfix.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/epochtime/api/api.go
go/genesis/api/sanity_check.go
go/genesis/genesis_test.go

[BACKPORT/20.12.x] go/genesis: Fix epoch-based sanity checks

---

.changelog/3477.breaking.md
.changelog/3477.bugfix.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/epochtime/api/api.go
go/genesis/api/sanity_check.go
go/genesis/genesis_test.go

go/genesis: Fix epoch-based sanity checks

---

.changelog/3480.bugfix.md
go/storage/mkvs/checkpoint/checkpointer.go
go/storage/mkvs/checkpoint/checkpointer_test.go

go/storage/mkvs/checkpoint: Fix handling of non-zero earliest version

---

.changelog/3454.feature.md
go/common/node/node.go
go/keymanager/client/client.go
go/oasis-node/node_test.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync_from_registered.go
go/runtime/committee/committee.go
go/runtime/nodes/grpc/grpc.go
go/runtime/nodes/nodes.go
go/runtime/nodes/nodes_test.go
go/runtime/nodes/runtime.go
go/runtime/nodes/runtime_test.go
go/runtime/nodes/versioned.go
go/runtime/nodes/vresioned.go
go/storage/api/api.go
go/storage/api/context.go
go/storage/api/context_test.go
go/storage/client/client.go
go/storage/client/init.go
go/worker/common/committee/accessctl.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go
go/worker/compute/executor/committee/node.go
go/worker/keymanager/watcher.go
go/worker/keymanager/worker.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go

Fixes: #3454
Done:
- now in `runtime/nodes/node.go`
- supports both `Versioned` (suitable for watching committees) and non-`Versioned`  mode (e.g. suitable for watching all registered nodes for a runtime)

go/storage: Sync from all registered nodes for runtime

---

go/worker/storage/committee/node.go

Added trivial fragment to make ci pass, as this fixes something that is not in any previous releases, so a changelog would be just confusing.

go/worker/storage: Fix possible nilptr deref in storage sync

---

go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
tests/runtimes/simple-keyvalue/src/main.rs

We do the same for non-encrypted versions already.

tests/simple-keyvalue: Handle check-only for encrypted ops

---

.changelog/3497.bugfix.md
go/common/sgx/common.go
go/common/sgx/ias/quote.go
go/storage/mkvs/node/depth.go

Note that in practice these will never currently be triggered as the
caller always checks the overall size before calling the more specific
UnmarshalBinary method.

go: Add missing size checks in UnmarshalBinary

---

.changelog/3452.feature.md
go/oasis-test-runner/scenario/e2e/runtime/late_start.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/runtime/client/api/api.go
go/runtime/client/client.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3452

go/runtime/client: Reject transactions before node completes initial sync

---

.github/dependabot.yml

Otherwise the dependabot will keep opening PRs (and rebasing those), hogging CI resources.
This is the issue tracking these outdated libs: https://github.com/oasisprotocol/oasis-core/issues/3245

dependabot: ignore tokio updates until it is manually updated

---

.changelog/3481.bugfix.md
go/consensus/tendermint/full/full.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/early_query.go

go/consensus/tendermint: Fix early GetStatus with initial height > 1

---

.buildkite/code.pipeline.yml
.changelog/3374.internal.md

ci: Make build-fuzz failures fatal now that upstream is fixed

---

.changelog/3522.internal.md
.github/workflows/release.yml

The deprecated `set-env` workflow command used stdout to communicate with a GitHub Action Runner which poses a security issue with workflows that log untrusted data to stdout.
For more details, see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.

github: Replace deprecated set-env command with environment file

---

.changelog/3349.internal.md
.changelog/3364.internal.md
.changelog/3365.internal.md
.changelog/3367.internal.md
.changelog/3405.internal.md
.github/workflows/ci-lint.yml
.github/workflows/ci-reproducibility.yml
.github/workflows/release.yml

The old versions of GitHub Actions that we use rely on `set-env` and `add-path` workflow commands were deprecated and disabled on November 16th.
For more details, see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.

[BACKPORT/20.12.x] Bump GitHub Actions' versions

---

.changelog/3525.bugfix.md
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/worker/storage/committee/node.go

Fixes #3525 
When a storage database from one network is used in a new network (e.g. when
the consensus layer did a dump/restore upgrade) properly handle the case where
there were additional rounds after the runtime has stopped (e.g., due to epoch
transitions).

go/worker/storage: Fill in additional versions when restoring state

---

.changelog/3534.bugfix.md
go/consensus/tendermint/full/full.go

Otherwise we won't have `t.node` available.

go tendermint: status peers and validator only after started

---

.changelog/3538.bugfix.md
.changelog/3538.internal.md
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/oasis/cli/cli.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
go/storage/mkvs/checkpoint/checkpointer.go
go/storage/mkvs/checkpoint/checkpointer_test.go
go/worker/storage/committee/node.go

* go/storage/mkvs/checkpoint: Add initial version parameter
Previously if the local database contained a version earlier than the genesis
version, the checkpointer would attempt to create a new checkpoint at that
earlier version (and fail). Now the version is clamped at the initial version.
* go/worker/storage: Force checkpoint sync when replication is needed
Previously a freshly initialized storage node with no genesis state would fall
back to incremental sync even though there was no chance of that succeeding.

Fix storage sync after non-zero genesis

---

.changelog/3545.bugfix.md
go/consensus/tendermint/apps/roothash/roothash.go
go/roothash/api/commitment/pool.go
go/roothash/api/commitment/pool_test.go

A subtle bug introduced in #3448 and discovered by daily long-term tests.

go/roothash/api/commitment: Return proposer commit in DR

---

.changelog/3546.feature.md
go/common/version/version.go
go/common/version/version_test.go

[BACKPORT/20.12.x] go/common/version: Add ConvertGoModulesVersion() function

---

.changelog/3546.feature.md
go/common/version/version.go
go/common/version/version_test.go

It can be used to convert a Go Modules compatible version defined in [ADR 0002] (i.e. a Go Modules compatible Git tag without the `go/` prefix) to the canonical Oasis Core version.
[ADR 0002]: https://github.com/oasisprotocol/oasis-core/blob/master/docs/adr/0002-go-modules-compatible-git-tags.md

go/common/version: Add ConvertGoModulesVersion() function

---

.github/workflows/release.yml

This is no longer needed and should also enable the next release to be built with the latest 1.15.x version.
This reverts commit 73a3acbc28b00f90f76e53977cfa0acdc3eb905a.

github: Unpin Go version in the release workflow

---

.changelog/3556.internal.md
go/oasis-node/cmd/common/common.go
go/oasis-node/cmd/common/consensus/consensus.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-node/cmd/registry/runtime/runtime.go

Replace `LoadEntity()` helper with `LoadEntitySigner()` that requires no arguments and loads the entity directory and obtains the signer backend by itself.
Remove entity directory loading boilerplate code by using this new helper.

go/oasis-node/cmd/common: Add LoadEntitySigner() helper

---

.changelog/3559.feature.md
go/oasis-node/cmd/stake/account.go
go/oasis-test-runner/scenario/e2e/stake_cli.go

It can be used to get a staking account's current nonce.

go/oasis-node/cmd: Add oasis-node stake account nonce CLI command

---

.changelog/3568.internal.md
go/oasis-node/cmd/debug/txsource/workload/workload.go

Sometimes it can take up to two minutes for a transaction to get included in a
block due to high load.
(This was masked before #3511 as submission was retried on all errors.)

go/oasis-node/txsource: Increase submission timeout

---

.changelog/3569.bugfix.md
go/runtime/scheduling/api/api.go
go/runtime/scheduling/simple/simple.go
go/runtime/scheduling/simple/txpool/orderedmap/ordered_map.go
go/runtime/scheduling/simple/txpool/tester.go
go/runtime/scheduling/tests/tester.go
go/worker/compute/executor/committee/node.go

Previously the scheduler would push batches to the consumer (e.g. compute
node) which makes no sense as the consumer knows when it's ready to accept
new batches. This changes the model so that the consumer pulls batches from
the scheduler.

go/runtime/scheduling: Consumer should pull from scheduler

---

.changelog/3593.internal.md
go/oasis-node/cmd/debug/txsource/workload/queries.go

There seems to be a bug in the queries workload event validation which fails in case two same events are emitted -- which seems like a perfectly valid thing that can happen now with a single transaction performing runtime message execution emitting events.
Discovered during long-term tests.

go/oasis-node/txsource: Fix event validation in queries workload

---

.changelog/3594.bugfix.md
go/consensus/tendermint/roothash/roothash.go
go/roothash/api/api.go

Only commit the block in case it was not already committed during reindex. This
can happen when reindexing after a crash (e.g., the before_index crash point)
since the initial height at which the reindex happens does not necessarily
contain a round finalization event so reindexing up to height-1 doesn't help.
Discovered during long-term tests.

go/consensus/tendermint/roothash: Fix latest block reindexing

---

.changelog/3604.internal.2.md
.changelog/3604.internal.md
Cargo.lock
runtime/src/storage/mkvs/mod.rs

Trivial MKVS trait impl needed by the ParaTime SDK.

runtime/storage/mkvs: Add MKVS impl for &mut T

---

.changelog/3603.internal.md
docs/adr/0006-consensus-governance.md
go/consensus/tendermint/apps/governance/query.go
go/consensus/tendermint/apps/governance/transactions.go
go/consensus/tendermint/governance/governance.go
go/governance/api/api.go
go/governance/api/grpc.go
go/governance/api/proposal.go
go/governance/tests/tester.go
go/oasis-node/cmd/debug/txsource/txsource.go
go/oasis-node/cmd/debug/txsource/workload/commission.go
go/oasis-node/cmd/debug/txsource/workload/delegation.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-node/cmd/debug/txsource/workload/oversized.go
go/oasis-node/cmd/debug/txsource/workload/parallel.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/debug/txsource/workload/runtime.go
go/oasis-node/cmd/debug/txsource/workload/transfer.go
go/oasis-node/cmd/debug/txsource/workload/workload.go
go/oasis-node/cmd/governance/governance.go
go/oasis-test-runner/scenario/e2e/debond.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/oasis-test-runner/scenario/e2e/test_accounts.go

- Adds the governance workload. Governance workload does the following:
- continuously submits proposals (both upgrade & cancel pending upgrade)
- votes for proposals (makes sure some proposals get rejected and some pass) 
- cancels any pending upgrades (via submitting a proposal and making sure it passes) `UpgradeCancelMinEpochDiff` before execution, to ensure no upgrades actually happen during the txsource test. In future we could/should probably also support this in the txsource test. 
- queries workload is updated with governance queries
- use multiple entities for txsrouce validators
TODO:

go/oasis-test-runner: governance workload

---

.changelog/3618.internal.md
go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go

This should help with the governance-upgrade test flakiness where the runtime client request would be sent before the compute nodes were ready (related to: https://github.com/oasisprotocol/oasis-core/pull/3599 as compute nodes take a bit more time to get initialized after a restart now).

go/e2e/governance-upgrade: wait for compute nodes to be ready

---

.changelog/3579.breaking.md
go/common/version/version.go
go/common/version/version_test.go
go/consensus/tendermint/apps/governance/genesis_test.go
go/consensus/tendermint/apps/governance/governance_test.go
go/consensus/tendermint/apps/governance/state/state_test.go
go/consensus/tendermint/apps/governance/transactions_test.go
go/consensus/tests/tester.go
go/control/api/api.go
go/control/api/grpc.go
go/control/control.go
go/genesis/genesis_test.go
go/governance/api/api_test.go
go/governance/gen_vectors/main.go
go/governance/tests/tester.go
go/oasis-node/cmd/control/control.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/oasis-test-runner/scenario/e2e/upgrade_cancel.go
go/upgrade/api/api.go
go/upgrade/api/api_test.go
go/upgrade/dummy.go
go/upgrade/upgrade.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3579
TODO:
NOTE: this also introduces a minor change the governance submit proposal transaction format (see governance/gen_vectors change).

go/upgrade: use ProtocolVersions as internal upgrade identifier

---

.changelog/3633.breaking.md
.changelog/3633.internal.md
client/src/enclave_rpc/api/enclaverpc.rs
client/src/enclave_rpc/client.rs
client/src/enclave_rpc/transport.rs
client/src/transaction/api/client.rs
client/src/transaction/client.rs
keymanager-api-common/src/api.rs
keymanager-client/src/client.rs
keymanager-lib/src/context.rs
keymanager-lib/src/kdf.rs
keymanager-lib/src/policy.rs
runtime/src/common/mod.rs
runtime/src/common/runtime.rs
runtime/src/dispatcher.rs
runtime/src/protocol.rs
runtime/src/types.rs
tests/clients/simple-keyvalue-enc/src/main.rs
tests/clients/simple-keyvalue-ops/src/main.rs
tests/clients/simple-keyvalue/src/main.rs
tests/clients/test-long-term/src/main.rs
tests/runtimes/simple-keyvalue/src/main.rs

* runtime: Remove common::runtime::RuntimeId
The Go API has been using Namespace for a while so this makes it
consistent in the Rust runtime as well.
* runtime: Validate block namespace against runtime ID

runtime: Use Namespace for runtime id, validate block namespace

---

.changelog/3511.internal.md
.changelog/3604.internal.2.md
Cargo.lock

Backport Rust crate version bumps.

[BACKPORT/20.12.x] Bump arc-swap and smallvec

---

.changelog/3636.internal.md
go/oasis-test-runner/scenario/e2e/runtime/txsource.go

When restarts are enabled there can be one less node so we should make sure to
decrease the MinPoolSize in this case.

go/oasis-test-runner/txsource: Decrease MinPoolSize for restarts

---

.changelog/3646.breaking.1.md
.changelog/3646.breaking.2.md
go/consensus/tendermint/apps/staking/slashing.go
go/consensus/tendermint/apps/staking/slashing_test.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/consensus/tendermint/crypto/priv_val.go
go/consensus/tendermint/tests/evidence.go
go/staking/api/slashing.go
go/staking/api/slashing_test.go
go/staking/tests/debug/debug_stake.go
go/staking/tests/tester.go

Extracted some general slashing changes from: https://github.com/oasisprotocol/oasis-core/pull/3640 (ADR-0005)
- rename `DoubleSigning`->`ConsensusEquivocation`
- change `SlashReason` type to `uint8`
- change `SlashEscrow` method to return slashed amount

slashing: rename DoubleSigning to ConsensusEquivocation

---

.changelog/3648.bugfix.md
go/consensus/api/api.go
go/consensus/tendermint/abci/mux.go
go/consensus/tests/tester.go

go/consensus/tendermint: Fix nil deref in EstimateGas

---

.changelog/3663.internal.md
tests/runtimes/simple-keyvalue/src/main.rs

This was responsible for some E2E test flakiness.

tests: Fix potential key clash in the confidential test KV runtime

---

.changelog/3156.breaking.md
go/consensus/tendermint/apps/staking/slashing.go
go/consensus/tendermint/apps/staking/slashing_test.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/state.go
go/staking/api/slashing.go

go/consensus/tendermint: Handle LIGHT_CLIENT_ATTACK evidence

---

.changelog/3675.internal.md
go/beacon/api/pvss.go
go/consensus/api/transaction/transaction.go
go/consensus/api/transaction/transaction_test.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/apps/beacon/backend_pvss.go
go/consensus/tendermint/apps/registry/state/state.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go

* go/consensus: Add support for method priority
* go/beacon: Make beacon methods critical and ignore tx authentication
There is no sense in handling transaction authentication and fees for beacon
methods which can only be invoked by the block proposer.
* e2e/runtime: Also configure intervals for PVSS backend
* go/beacon: Only allow a single beacon transaction per block

beacon: Transaction handling fixes

---

.changelog/3674.feature.md
go/common/crypto/pvss/pvss.go
go/common/crypto/pvss/pvss_test.go
go/common/crypto/pvss/s11n.go
go/common/identity/identity.go
go/common/node/node.go
go/go.mod
go/go.sum
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/tests/tester.go
go/worker/registration/worker.go

To prepare for the future migration to a PVSS based beacon scheme, every
node should generate and register a elliptic curve point in advance of
the migration.  This commit selectively backports the required logic for
a hopefully smooth transition.
Fixes #3674

go/beacon: Backport the beacon key generation/registration

---

.changelog/3611.breaking.md
go/common/node/node.go
go/common/sgx/common.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/genesis/genesis_test.go
go/oasis-node/cmd/debug/byzantine/steps_test.go
go/oasis-node/cmd/ias/auth.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/oasis/cli/registry.go
go/oasis-test-runner/oasis/runtime.go
go/registry/api/api.go
go/registry/api/runtime.go
go/registry/tests/tester.go

go/scheduler: Check runtime versions for node eligibility

---

.changelog/3640.breaking.md
docs/adr/0005-runtime-compute-slashing.md
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/slashing.go
go/consensus/tendermint/apps/roothash/slashing_test.go
go/consensus/tendermint/apps/roothash/state/state.go
go/consensus/tendermint/apps/roothash/state/state_test.go
go/consensus/tendermint/apps/roothash/transactions.go
go/consensus/tendermint/apps/roothash/transactions_test.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/genesis/genesis_test.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/oasis/cli/registry.go
go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
go/registry/api/runtime.go
go/registry/tests/tester.go
go/roothash/api/api.go
go/roothash/api/api_test.go
go/roothash/api/commitment/pool.go
go/roothash/api/commitment/txnscheduler.go
go/roothash/tests/tester.go
go/staking/api/slashing.go
go/staking/api/slashing_test.go
go/staking/tests/tester.go

runtime node slashing (ADR 0005)

---

.changelog/3666.internal.md
go/beacon/api/api.go
go/beacon/api/grpc.go
go/beacon/tests/tester.go
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/tendermint/beacon/beacon.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/seed/seed.go
go/consensus/tests/tester.go
go/oasis-node/cmd/debug/byzantine/node.go
go/oasis-node/cmd/debug/consim/timesource.go
go/oasis-node/cmd/debug/txsource/workload/commission.go
go/oasis-node/cmd/debug/txsource/workload/delegation.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-node/cmd/debug/txsource/workload/runtime.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/controller.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
go/oasis-test-runner/scenario/e2e/seed_api.go
go/worker/registration/worker.go
go/worker/upgrade/worker.go

beacon: Add a minimal gRPC service
This moves the following calls to the new beacon gRPC service:
* `Consensus.GetEpoch`
* `Consensus.WaitEpoch`
* `Consensus.BeaconConsensusParameters` -> `Beacon.ConsensusParameters`
At some point someone that cares can move the `SetEpoch` call from the debug endpoint, and add support for streams.
Fixes #3666

beacon: Add a minimal gRPC service

---

.changelog/3704.trivial.md
Cargo.lock

Fixes https://rustsec.org/advisories/RUSTSEC-2021-0023

rust: update rand_core to 0.6.2

---

.changelog/3643.breaking.md
go/common/crypto/signature/signer.go
go/common/crypto/signature/signer_test.go
go/common/namespace.go
go/consensus/tendermint/apps/roothash/transactions.go
go/consensus/tendermint/apps/roothash/transactions_test.go
go/oasis-node/cmd/debug/byzantine/beacon.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/executor.go
go/oasis-node/cmd/debug/byzantine/node.go
go/oasis-node/cmd/debug/byzantine/steps.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/scenario/e2e/byzantine_beacon.go
go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
go/roothash/api/api.go
go/roothash/api/api_test.go
go/roothash/api/commitment/executor.go
go/roothash/api/commitment/pool.go
go/roothash/api/commitment/pool_test.go
go/roothash/api/commitment/txnscheduler.go
go/roothash/tests/tester.go
go/worker/common/committee/group.go
go/worker/compute/executor/committee/node.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3643

go/roothash: runtime domain separation in executor commitments

---

.changelog/3696.feature.md
go/common/accessctl/accessctl.go
go/common/accessctl/accessctl_test.go
go/common/grpc/service.go
go/common/node/node.go
go/oasis-node/cmd/debug/storage/export.go
go/oasis-node/node_test.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/scenario/e2e/runtime/sentry.go
go/registry/tests/tester.go
go/runtime/registry/registry.go
go/storage/api/grpc.go
go/storage/client/init.go
go/storage/client/tests/tests.go
go/worker/storage/committee/node.go
go/worker/storage/committee/policy.go
go/worker/storage/init.go
go/worker/storage/worker.go

Getting checkpoints and diffs is now allowed for any connecting node,
which eliminates a race condition and initialization difficulty in the
storage committee node startup.
State access is made gated but optionally public as before, depending on
command line parameters.
Closes #3562

go/worker/storage: Add StorageRPC role and change access policy

---

.changelog/3524.bugfix.md
go/oasis-test-runner/scenario/e2e/runtime/node_shutdown.go
go/worker/registration/worker.go

In cases where the registration worker was started with a dummy
goroutine that just waits for the service to stop, deregistration
requests would hang, because the dummy wasn't watching the
deregistration channel.
Closes #3524

go/worker/registration: Fix RequestShutdown for nodes with no registration

---

.changelog/3722.internal.1.md
.changelog/3722.internal.md
.github/workflows/ci-lint.yml
Makefile
common.mk
go/Makefile

- Remove `build-go` target's non-standard `go` alias.
- Add `lint-go-mod-tidy` target.

Make: Unify with Oasis Core Ledger and Rosetta Gateway repos

---

LICENSE

this came up when we were adding a license to oasis-sdk in https://github.com/oasisprotocol/oasis-sdk/pull/6
here's an example of another project that came to the same conclusion: https://github.com/kubernetes/kubernetes/pull/65

restore template in license

---

.changelog/3641.breaking.md
.changelog/3717.breaking.md
go/consensus/tendermint/api/context.go
go/consensus/tendermint/api/context_test.go
go/consensus/tendermint/apps/roothash/messages.go
go/consensus/tendermint/apps/roothash/transactions_test.go
go/consensus/tendermint/apps/staking/genesis.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/apps/staking/transactions_test.go
go/oasis-node/cmd/debug/txsource/workload/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/roothash/api/message/message.go
go/roothash/api/message/message_test.go
go/staking/api/api.go
go/staking/api/api_test.go
runtime/src/consensus/roothash.rs
runtime/src/consensus/staking.rs
tests/clients/simple-keyvalue-enc/src/main.rs
tests/clients/simple-keyvalue-ops/src/main.rs
tests/clients/simple-keyvalue/src/main.rs
tests/clients/test-long-term/src/main.rs
tests/runtimes/simple-keyvalue/api/src/api.rs
tests/runtimes/simple-keyvalue/api/src/lib.rs
tests/runtimes/simple-keyvalue/src/main.rs

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3641
TODO:

Add AddEscrow and ReclaimEscrow runtime messages

---

.changelog/3539.breaking.md
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/registry/transactions_test.go
go/registry/api/api.go
go/registry/api/api_test.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3539

go/registry: Allow more updates to expired nodes

---

.changelog/3440.feature.md
go/common/keyformat/hashed_test.go
go/common/keyformat/key_format.go
go/runtime/transaction/transaction.go
go/runtime/transaction/transaction_test.go
go/worker/storage/service_external.go

go/worker/storage: Add validation for IO roots in Apply operations

---

.changelog/3719.internal.1.md
.changelog/3719.internal.2.md
go/oasis-net-runner/fixtures/default.go
go/oasis-node/cmd/common/pprof/pprof.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/oasis/sentry.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/genesis_file.go
go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/late_start.go
go/oasis-test-runner/scenario/e2e/runtime/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_governance.go
go/oasis-test-runner/scenario/e2e/runtime/sentry.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/oasis-test-runner/scenario/e2e/upgrade_cancel.go

Daily longterm tests have been failing since validator-0 was falling behind the rest of the network due to the supplementary-sanity checker. This moves the supplementary-sanity checker to a new (client-1) node, which can fall behind without affecting rest of the network.
Also increase the timeout between governance workload iterations, as currently the amount of proposals was quickly pilling up over time (and both queries-workload and sanity-checker, go through all (even expired) proposal and votes).
TODO:

go/oasis-test-runner: configurable sanitychecker

---

.changelog/3444.feature.md
go/oasis-test-runner/scenario/e2e/runtime/client_expire.go
go/oasis-test-runner/scenario/e2e/runtime/late_start.go
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/submitter.go
go/runtime/client/tests/tester.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3444
TODO:

go/runtime/client: add SubmitTxNoWait method

---

.changelog/3743.feature.md
go/consensus/api/api.go
go/consensus/tendermint/full/full.go

go/control/GetStatus: include the latest epoch

---

.changelog/3757.internal.md
go/runtime/nodes/grpc/grpc.go
go/storage/client/client.go
go/worker/common/config.go

Tweak some grpc timeouts. Before, the default storage commit timeout was less than `grpcBackoffMaxDelay` which made the storage commit request retries ineffective whenever the max delay was reached (e.g. first few requests after a storage node was restarted).
Discovered in longterm tests.

go/nodes/grpc: tweak backoff timeouts

---

go/common/entity/entity.go
go/common/entity/entity_test.go

This PR adds a custom deserializer to the `Entity` struct that can handle both v1 and v2 descriptors.

go/common/entity: Fix backward compatibility

---

go/common/crypto/pvss/s11n.go
go/common/crypto/pvss/s11n_test.go

Fixes text unmarshaling of beacon point in jsons (used in cli outputs. e.g. `registry node list` or `control status`) from:
```
"beacon": {
"point": {}
},
```
to:
```
"beacon": {
"point": "BOwfi4VYUP2Qh87Lwq0Np9esST7cbReL11nIuRCRvsS45hm3XFG61qkBU8C6bVXT4FpUshZRjXagK5sO4MpFcXY="
},
```

pvss/point: implement encoding.Text{Un}Marshaler interfaces

---

.changelog/3177.bugfix.md
go/consensus/tendermint/api/genesis.go
go/consensus/tendermint/api/genesis_test.go

go/consensus: Include only top K validators at genesis time

---

go/consensus/tendermint/apps/governance/governance.go
go/consensus/tendermint/full/full.go

Fixes #3764 
Upgrader checks should run on every block so that any pending upgrade
descriptors are cleared after consensus upgrade is performed.

go/consensus/tendermint/governance: Move upgrader checks

---

.changelog/3763.bugfix.md
go/consensus/tendermint/api/genesis.go
go/consensus/tendermint/api/genesis_test.go

go/consensus: Exclude expired nodes from validator set at genesis time

---

.changelog/3768.bugfix.1.md
.changelog/3768.bugfix.2.md
.changelog/3768.bugfix.3.md
go/upgrade/api/api.go
go/upgrade/migrations/dummy.go
go/upgrade/migrations/migrations.go
go/upgrade/upgrade.go

Also changes:
- `PushStage(api.UpgradeStageStartup)` happens only after a successful stage completion
-  removes `RunningVersion`
- we already ensure that we are running upgrade-compatible version
- and i think switching the version mid-upgrade (e.g. fixing a migration bug after a failure) should be fine, as long as the version stays compatible 
- removes `SubmittingVersion`
-  this prevents changing binary while an upgrade is pending. This should be allowed - e.g. a compatible bugfix while an upgrade is pending.

go/upgrade: ensure upgrade handler exists

---

.buildkite/longtests.pipeline.yml

Longtests agents are now in the default queue, so that the agents can be used for normal CI, while no daily job is being run. The "daily=true" tag was added, so that the daily tests can target these agents.
Also as a test, the daily agents are now on ephemeral spot instances.

.buildkite/longtests: update buildkite agent tag

---

.changelog/3778.feature.2.md
.changelog/3778.feature.md
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/seed/seed.go
go/consensus/tests/tester.go
go/runtime/host/protocol/connection.go
go/runtime/host/protocol/types.go
go/runtime/registry/config.go
runtime/src/protocol.rs
runtime/src/types.rs

This adds a way for the runtime to be informed about the chain domain separation
context that the consensus layer is using. It can be used by the runtime to
perform domain separation for cryptographic signatures.

runtime: Provide consensus layer chain domain separation context

---

.changelog/3774.breaking.1.md
.changelog/3774.breaking.2.md
.changelog/3774.feature.1.md
.changelog/3774.feature.2.md
.changelog/3774.feature.3.md
.changelog/3774.feature.md
.changelog/3774.internal.2.md
.changelog/3774.internal.md
go/consensus/tendermint/apps/staking/query.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/staking/staking.go
go/consensus/tendermint/tests/genesis/genesis.go
go/genesis/genesis_test.go
go/governance/tests/tester.go
go/oasis-node/cmd/debug/txsource/workload/delegation.go
go/oasis-test-runner/scenario/e2e/test_accounts.go
go/roothash/tests/tester.go
go/staking/api/api.go
go/staking/api/grpc.go
go/staking/tests/accounts.go
go/staking/tests/state.go
go/staking/tests/tester.go

Additionally, refactor `go/staking/tests`:
- Move `go/staking/tests/debug` into `go/staking/tests` package.
- Generalize account handling and add delegations.
Extracted from #3725.

go/staking/api: Add new delegation querying methods

---

.changelog/3782.breaking.md
go/consensus/tendermint/apps/roothash/state/state.go
go/consensus/tendermint/apps/roothash/state/state_test.go

That makes it easier to construct proofs starting at the consensus state root
that prove what the state root of a specific runtime is. You can then chain
these proofs to prove something about runtime state.

go/consensus: Store runtime state roots in a single key

---

.changelog/3784.breaking.1.md
.changelog/3784.breaking.2.md
go/consensus/api/transaction/transaction.go
go/staking/api/token/prettyprint.go
go/staking/api/token/prettyprint_test.go

Additionally, change transaction's pretty-printer to transaction's method name and body before the rest.
Example output before this change for `oasis-node consensus show_tx` CLI command:
```
Hash: 36c5da997aed1065acd726a9358578ad94588efee9b60585cd1dcb0130894d19
Signer: 8E6DSXn0elXyIF9pYfoSg6+/LK9HeNONJia2rdD3Ozg=
(signature: cdqMW6aYDUJcYwxcKuC7eY6ycaYGxNQ4jxMdw9U9yxIgPTrkEGlzIQn7RdmaGbyyXc5S5/N1pKWEQsQbli7sBw==)
Content:
Nonce:  0
Fee:
Amount: ROSE 0.0
Gas limit: 2000
(gas price: ROSE 0.0 per gas unit)
Method: staking.Withdraw
Body:
From:   oasis1qzn7ztfjlc962yy5yz50zt6tedl60p0aw5n98s0k
Amount: ROSE 300.0
Other info:
Genesis document's hash: e2a76b23e48639d7e08c961af77aaf55498c90fd01b70ec996d8f1906869b0d1
```
Example output after this change for `oasis-node consensus show_tx` CLI …

Pretty-print: print token's symbol after the amount

---

.changelog/3783.feature.md
go/control/api/api.go
go/worker/registration/worker.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3783

go/control/api: Add node status to registration status response

---

go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go

Consensus not making progress while one validator is shutdown for 10 mins and another is being restarted (leaving 2 out of 4 validators up) is a common reason for failures, specially whenever the check interval got lined up with the restart.
Also bumps the queries timeout to be more in line with other timeouts across workloads.

go/tests/txsource: Bump liveness and queries timeouts

---

Cargo.lock
runtime/Cargo.toml

These two need to be bumped together.

runtime: Bump honggfuzz to 0.5.54, arbitrary to 1.0.0

---

.changelog/3791.bugfix.md
go/consensus/tendermint/roothash/roothash.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go

This fixes a case where a storage node would not register if restarted while synced and there were no new runtime rounds (e.g. the runtime is suspended).
Also updates the runtime-dynamic scenario to test this case.

go/roothash/reindexBlocks: return latest known round if no new rounds are reindexed

---

.changelog/3790.breaking.md
go/roothash/api/commitment/pool.go
go/roothash/api/commitment/pool_test.go

When the set of current commitments already determines the fate of the process
(e.g., when there is a discrepancy or a majority of votes indicate success),
proceed with the process instead of waiting for the remaining commitments.

go/roothash: Finish commitment processing early when possible

---

.changelog/3792.feature.1.md
.changelog/3792.feature.2.md
go/oasis-node/cmd/common/context/context.go
go/oasis-node/cmd/governance/governance.go
go/oasis-node/cmd/keymanager/keymanager.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/cmd/stake/account.go

Display amounts in tokens and display genesis document's hash when previewing transactions with various `oasis-node * gen_*` CLI commands.

go/oasis-node/cmd: Improve transaction preview when generating txns

---

.changelog/3800.feature.1.md
.changelog/3800.feature.2.md
.changelog/3800.feature.3.md
go/common/version/version.go
go/governance/api/api.go
go/governance/api/api_test.go
go/upgrade/api/api.go

Examples of various transaction pretty-prints:
```
Method: governance.SubmitProposal
Body:
Upgrade:
Handler: upgrade1
Target Version:
Consensus Protocol: 3.0.0
Runtime Host Protocol: 2.0.0
Runtime Committee Protocol: 2.0.0
Epoch: 3828
Nonce:  0
Fee:
Amount: 0.00003 ROSE
Gas limit: 2000
(gas price: 0.000000015 ROSE per gas unit)
```
```
Method: governance.SubmitProposal
Body:
Cancel Upgrade:
Proposal ID: 15
Nonce:  0
Fee:
Amount: 0.00003 ROSE
Gas limit: 2000
(gas price: 0.000000015 ROSE per gas unit)
```
```
Method: governance.CastVote
Body:
Proposal ID: 12
Vote:        yes
Nonce:  0
Fee:
Amount: 0.00003 ROSE
Gas limit: 2000
(gas price: 0.000000015 ROSE per gas unit)
```

go: Add pretty-printers for governance and upgrade types

---

.changelog/3801.bugfix.md
go/worker/compute/executor/committee/node.go

Also updates to use round context where appropriate (and fixes some cases where the roundCtx was accessed without the lock being held).

go/worker/executor: avoid holding lock while applying processed batch to storage

---

go/oasis-node/cmd/debug/txsource/workload/parallel.go

Same reasoning as in https://github.com/oasisprotocol/oasis-core/pull/3788
Last daily failure was due to this.

go/tests/txsource: Bump parallel workload timeout

---

.changelog/3794.feature.md
.changelog/3805.bugfix.md
go/oasis-net-runner/fixtures/default.go

oasis-net-runner: Fix runtime configuration in default fixture

---

.changelog/3819.feature.md
go/staking/api/api.go

Use more descriptive name for:
- `Escrow`'s destination account ("To" instead of "Account")
- `ReclaimEscrow`'s source account ("From" instead of "Account")

go/staking: Improve pretty-print for Escrow/ReclaimEscrow transactions

---

.changelog/3820.bugfix.md
.changelog/3820.internal.1.md
.changelog/3820.internal.2.md
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/storage_node.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/storage/api/context.go
go/storage/client/client.go
go/storage/mkvs/db/badger/badger.go
go/storage/mkvs/db/badger/badger_test.go
go/worker/common/committee/node.go
go/worker/common/worker.go
go/worker/storage/committee/node.go
go/worker/storage/committee/utils.go

Avoid database corruption in certain cases.

Fix storage worker

---

.changelog/3851.feature.md
go/upgrade/api/api.go
go/worker/compute/executor/init.go

go/upgrade: Add work-around for incorrect go-fuzz instrumentation.

go/worker/compute/executor: Enable schedule_check_tx.enabled by default

---

.changelog/3833.internal.md
go/consensus/tendermint/apps/staking/state/interop/interop.go
go/storage/mkvs/interop/cmd/protocol_server.go
go/storage/mkvs/interop/fixtures/consensus_mock.go
go/storage/mkvs/interop/fixtures/fixture.go
runtime/src/consensus/state/staking.rs
runtime/src/storage/mkvs/interop/mod.rs
runtime/src/storage/mkvs/interop/protocol_server.rs
runtime/src/storage/mkvs/mod.rs
runtime/src/storage/mkvs/sync/test.rs
runtime/src/storage/mkvs/tree/iterator.rs
runtime/src/storage/mkvs/tree/tree_test.rs

Implements interoperability tests for the rust consensus state wrappers.

Runtime consensus state interoperability tests

---

.changelog/3848.breaking.md
go/runtime/transaction/tags.go
runtime/src/dispatcher.rs
runtime/src/transaction/dispatcher.rs
runtime/src/transaction/tree.rs

Runtime: Add support for block tags (tags not emitted by a specific transaction).
Needed for: oasis-sdk#consensus-module (https://github.com/oasisprotocol/oasis-sdk/pull/92)

runtime: Support for block tags

---

.changelog/3875.internal.md
.github/workflows/release-dev.yml

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3875
Builds release artifacts and upload them as github action artifacts.

ci: build and upload release artifacts on every master merge

---

.changelog/3889.bugfix.md
go/worker/common/committee/node.go

Fixes #3889 
If a node first syncs consensus without any runtimes configured and a runtime
is configured later, the workers should wait for historic runtime block
reindexing to complete before continuing with initialization. Otherwise
historic block queries may fail and prevent the worker from operating
normally.

Runtime workers should wait for history reindex

---

.changelog/3903.breaking.md
docs/setup/deploying-a-runtime.md
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-test-runner/oasis/cli/registry.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/oasis-test-runner/scenario/e2e/runtime/history_reindex.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go

Closes: https://github.com/oasisprotocol/oasis-core/issues/3626
Update `gen_register` runtime command to accept runtime descriptor instead of messing with the arguments.
TODO:

go/cmd/registry: simplify register runtime command

---

.changelog/3914.feature.1.md
.changelog/3914.feature.2.md
go/oasis-net-runner/fixtures/default.go

Supports configuring multiple runtime in the default fixture

go/oasis-net-runner: support multiple runtimes in default fixture

---

Cargo.lock
runtime/Cargo.toml

Reverting as `untrusted 0.8.0` has been yanked, see https://github.com/briansmith/untrusted/issues/57.
This reverts commit f80896da9d99582735c3213aaabc5d3547623810.

Revert "rust: bump untrusted from 0.7.1 to 0.8.0"

---

.changelog/3829.feature.1.md
.changelog/3829.feature.2.md
go/common/crypto/mrae/api/api.go
go/common/crypto/mrae/api/api_test.go
go/common/crypto/signature/signature.go
go/common/crypto/signature/signer.go
go/common/crypto/signature/signers/file/file_signer.go
go/common/crypto/signature/signers/memory/memory_signer.go
go/common/crypto/slip10/slip10.go
go/common/crypto/slip10/slip10_test.go
go/go.mod
go/go.sum
go/oasis-test-runner/oasis/oasis_test.go

~~This should eventually carve out the cache into somewhere else (maybe as part of voi, it seems generally useful), so that the tendermint side can also use it.  But what is there is ok as an illustration of how this will work.~~

common/crypto/ed25519: Use curve25519-voi

---

.changelog/3945.internal.md
go/common/crypto/slip10/slip10.go
go/common/crypto/slip10/slip10_test.go

The SLIP-0010 spec, was updated after approximately 5 years to be
coherent, so support `S` that range from 128-bits to 512-bits, and
add in the formerly nonsensical test vector.

common/crypto/slip-10: Relax the seed-length check

---

.changelog/3939.breaking.md
.changelog/3944.breaking.md
docs/consensus/staking.md
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/consensus/tendermint/apps/staking/transactions.go
go/staking/api/api.go
go/staking/tests/tester.go

Fixes: #3939
Also fixed `Escrow` events emitted when disbursing rewards. I think explicitly emitting (transfer and self-escrow) events makes more sense?

{Add,Reclaim}EscrowEvent: include share amounts

---

.changelog/3946.internal.md
Cargo.lock
runtime/Cargo.toml
runtime/src/common/crypto/signature.rs

We currently use semantics that are close to ed25519-dalek's strict,
but we require using the cofactored verification equation.  Implementing
verification ourselves lets us alter the behavior in the future as
we see fit, though "Just use Ristretto".
TODO:

runtime/common/crypto/signature: Switch Ed25519 to our consensus flavor

---

.changelog/3948.trivial.md
runtime/src/common/cbor.rs

This PR exposes the `Error` type for easier conversion of an invalid argument found by the SDK.

runtime/core/common/cbor: expose Error type

---

.buildkite/benchmarks.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.yml

It seems that the recent version bumps are triggering Rust compiler bugs related to incremental compilation. [Suggestion from upstream is to disable incremental compilation.](https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html)
Also filed an issue upstream: https://github.com/rust-lang/rust/issues/85502
Unfortunately this will make CI times even longer.

ci: Disable incremental Rust builds due to compiler bugs

---

.changelog/3959.internal.md
go/oasis-node/cmd/debug/txsource/workload/governance.go

Found in daily longerm test (thanks @kostko)

workload/governance: fix case with multiple identical active proposals

---

go/staking/api/slashing.go

go/staking: Remove backwards compat in UnmarshalText

---

.changelog/3981.internal.md
Cargo.lock
runtime/Cargo.toml

Specify exact ring version in `Cargo.toml` as otherwise project depending on oasis-runtime (e.g. oasis-sdk), will need to manually lock `ring` to the exact version.

rust: specify ring version

---

.changelog/3812.feature.md
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/tests/tester.go

A new method called GetTransactions has been added to replace the now deprecated
GetTxs. The new method does not require the caller to pass the IO root as that
is an internal detail. This makes it consistent with the existing GetEvents API.
Users of GetTxs should migrate to GetTransactions as the former may be removed
in a future release.

go/runtime/client: Add GetTransactions method, deprecate GetTxs

---

.changelog/3891.doc.md
.changelog/3891.docs.md
.changelog/3993.doc.md
docs/release-process.md

Apparently, Git has a limitation where if branch named `b` exists, no branch named `b/something` can be created:
https://stackoverflow.com/a/22630664/1872673.
Hence, if branch named `stable/21.2.x` exists, one is unable to create a `stable/21.2.x/backport-foo` or `stable/21.2.x/changelog` branch.

docs: Avoid / in backport/changelog git branch names in Release Process

---

.changelog/3760.breaking.md
go/runtime/host/helpers.go
go/runtime/host/mock/mock.go
go/runtime/host/protocol/connection.go
go/runtime/host/protocol/types.go
go/runtime/scheduling/api/api.go
go/runtime/scheduling/init.go
go/runtime/scheduling/simple/simple.go
go/runtime/scheduling/simple/simple_test.go
go/runtime/scheduling/simple/txpool/api/api.go
go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
go/runtime/scheduling/simple/txpool/tester.go
go/runtime/scheduling/tests/tester.go
go/runtime/transaction/transaction.go
go/worker/compute/executor/committee/node.go
runtime/src/dispatcher.rs
runtime/src/protocol.rs
runtime/src/transaction/dispatcher.rs
runtime/src/types.rs

Fixes: https://github.com/oasisprotocol/oasis-core/issues/3974
See also: https://github.com/oasisprotocol/oasis-sdk/pull/146
Executor worker now queries `"internal.BatchWeightLimits"` runtime method to receive custom batch weight limits on every round.

worker/executor: support custom runtime batch weight limits
