.changelog/3897.feature.md
go/beacon/api/grpc.go
go/beacon/api/pvss.go
go/consensus/tendermint/beacon/beacon.go
go/go.mod
go/go.sum
go/oasis-node/cmd/debug/beacon/beacon.go
go/oasis-node/cmd/debug/byzantine/beacon.go
go/oasis-node/cmd/debug/debug.go
go/worker/beacon/worker.go

 Make current beacon status available via the CLI

---

.changelog/4009.bugfix.md
go/oasis-net-runner/fixtures/default.go

This fixes a behavior that was introduced in 3e6d8f911f509614361e9b4efae1e3a500b66c20 where if you set `fixture.default.setup_runtimes` to `false` it could generate an incorrect fixture when `fixture.default.runtime.binary` is set to its default value.

go/oasis-net-runner: Always honor fixture.default.setup_runtimes

---

.changelog/4010.bugfix.2.md
.changelog/4010.bugfix.md
go/common/badger/helpers.go
go/common/badger/migrate.go
go/consensus/tendermint/abci/state.go
go/oasis-node/cmd/debug/beacon/beacon.go
go/storage/mkvs/checkpoint/checkpointer.go
go/storage/mkvs/checkpoint/checkpointer_test.go

Previously the checkpointer would generate checkpoints in ascending order which
meant that it could generate many checkpoints only to garbage collect them in
the next step.

go/storage/mkvs/checkpoint: Checkpoint in descending order

---

.changelog/4014.feature.md
go/consensus/tendermint/apps/staking/api.go
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/staking/staking.go
go/staking/api/api.go
go/staking/tests/tester.go

This makes it easier to reason about the debonded amounts, both in shares and
in base units.

go/staking: Add DebondingStartEscrowEvent

---

docs/release-process.md

Prefixing branch names with the name of the current stable branch, e.g. `stable/21.2.x`, matches GitHub's protected branch rule and stable branch rules in GitHub Actions workflows, which is undesirable (e.g. no force-pushing changes to a PR, triggering of extended CI).

docs: Don't prefix backport branches with stable/* in Release Process

---

runtime/src/common/bytes.rs

This PR makes bytes types `Copy`,  which is useful for [`PublicKey`](https://nhynes.github.io/oasis_runtime_sdk/crypto/signature/ed25519/struct.PublicKey.html) in [`AuthProof`](https://nhynes.github.io/oasis_runtime_sdk/types/transaction/enum.AuthProof.html). It's a little easier to return a new `AuthProof` with an updated nonce than make the thing mutable with a lock.

runtime/core/common/bytes: impl Copy on bytes types

---

.changelog/4026.internal.md
go/go.mod
go/go.sum

The ldconfig that ships with newer glibc does something that it didn't when I originally wrote this library many years ago.

go: Bump the dynlib import

---

.changelog/4021.internal.md
Cargo.lock
Cargo.toml
runtime/Cargo.toml
runtime/src/common/sgx/avr.rs
runtime/src/lib.rs

It's German for "The Ring The".
This removes the webpki (and consequently) ring dependency by switching to manually verifying the IAS AVR certificate chain, and AVR signature.  It makes a number of assumptions about how IAS does things (that are part of the API specification), so it is probably ok, though if Intel ever decides to change this, we will be rather sad.
The unfortunate thing about this is that I personally like ring/webpki as far as libraries go for the most part, but, having to carry around a fork just to get SGX support due to a trivial patch not being merged is not worth the hassle.
Fixes #2683

runtime: Stop using webpki to verify the IAS cert chain

---

.changelog/4023.internal.md
runtime/src/storage/mkvs/interop/protocol_server.rs

The storage protocol server binary will now compile but just panic with
an error on launch, making it possible to compile the tests even without
the env var set.
Fixes #4023

runtime: Do not require `OASIS_STORAGE_PROTOCOL_SERVER_BINARY`

---

.changelog/4024.feature.2.md
.changelog/4024.feature.3.md
.changelog/4024.feature.md
go/oasis-net-runner/fixtures/default.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
runtime-loader/Cargo.toml
runtime-loader/bin/main.rs
runtime-loader/src/lib.rs

This PR:
* adds conditional compilation to the `oasis-core-runtime-loader`
* allows setting the provisioner through `oasis-net-runner` (to unconfined)
* allows running a net without a keymanager since `simple-keymanager` isn't fun to compile with musl

Enable development on macOS without docker

---

.changelog/4033.bugfix.md
.changelog/4033.internal.md
go/beacon/api/pvss.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/api/context.go
go/consensus/tendermint/apps/beacon/backend_pvss.go
go/consensus/tendermint/apps/governance/api.go
go/consensus/tendermint/apps/governance/governance.go
go/consensus/tendermint/apps/governance/transactions.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/consensus/tendermint/apps/staking/api.go
go/consensus/tendermint/apps/staking/fees.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/gas.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/beacon/beacon.go
go/consensus/tendermint/governance/governance.go
go/consensus/tendermint/staking/staking.go
go/governance/api/api.go
go/staking/api/api.go

[BACKPORT/21.2.x] go/consensus/tendermint/apps/staking: Fix emitted reward events

---

.changelog/4037.bugfix.md
go/common/badger/helpers.go
go/common/badger/migrate.go
go/oasis-node/cmd/node/node.go

Even though oasis-core always configures non-managed badger databases to keep
a single version of keys, some databases in the wild contain multiple versions
of the same key.
Skip migrating more than the latest version when migrating non-managed
badger databases.

badger/migration: keep only last version when migrating non-managed DB

---

.changelog/4040.feature.md
.github/workflows/ci-reproducibility.yml
.github/workflows/release-dev.yml
.github/workflows/release.yml
.goreleaser.yml
docker/development/Dockerfile
docs/setup/building.md
docs/setup/prerequisites.md
go/Makefile

TODO:
- tested release-dev workflow, for build binary, see the artifacts here: https://github.com/oasisprotocol/oasis-core/runs/2841426938
- ci run: https://buildkite.com/oasisprotocol/oasis-core-ci/builds/5277

build badgerdb using jemalloc

---

.changelog/4025.cfg.md
.changelog/4025.feature.md
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/oasis.go
go/worker/common/p2p/init.go
go/worker/common/p2p/p2p.go

Some updates useful for https://github.com/oasisprotocol/oasis-sdk/issues/96
- configurable libp2p gossipsub validator concurrences
- ~increase `runtime/src/dispatcher.rs` channel backlog size~
- support setting custom node arguments in oasis-runner fixtures

Updates useful for oasis-sdk#96

---

.changelog/4061.bugfix.md
.changelog/4061.internal.md
go/oasis-node/cmd/node/node.go
go/runtime/registry/registry.go
go/storage/client/client.go
go/storage/client/init.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go
go/worker/compute/executor/committee/node.go

Move committee storage to `Group` to make it available to all subworkers (instead of the executor worker having a specialized case) and change it so that it doesn't go through gRPC when communicating with the local node.

go/worker/common: Move committee storage to Group

---

.changelog/4072.bugfix.1.md
.changelog/4072.bugfix.2.md
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/node.go

[BACKPORT/21.2.x] go/worker/storage: Add missing timeout for operations

---

.changelog/4060.bugfix.md
go/consensus/tendermint/abci/prune.go
go/consensus/tendermint/full/full.go
go/oasis-test-runner/scenario/e2e/consensus_state_sync.go

Fixes #4060
Previously the reported version was incorrect when the node used state sync and
pruning was disabled.

go/consensus/tendermint: Fix last retained version query

---

.changelog/4060.bugfix.md
go/consensus/tendermint/abci/prune.go
go/consensus/tendermint/full/full.go
go/oasis-test-runner/scenario/e2e/consensus_state_sync.go

[BACKPORT/21.2.x] go/consensus/tendermint: Fix last retained version query

---

.changelog/4067.feature.md
go/common/errors/errors.go
go/common/errors/errors_test.go

This PR makes it possible to decode the actual error variant via `details` in the gRPC error response status.
re: https://github.com/oasisprotocol/oasis-sdk/pull/139/commits/860e4233b5b07b716177d1994f02f980fe93a0f0

go/common/errors: expose all grpc errors as coded

---

.changelog/4085.bugfix.md
go/consensus/tendermint/full/full.go

This should enable returning other useful `GetStatus()` info when failing to load the validator set for a given height.

consensus/tendermint: Handle validator fetching error in GetStatus()

---

.changelog/4093.bugfix.2.md
.changelog/4093.bugfix.md
go/storage/api/api.go
go/storage/api/mux.go
go/storage/api/mux_test.go
go/worker/common/committee/group.go
go/worker/storage/synced_storage.go

Previously the committee group could incorrectly use the synced version of the
local backend which could block operations.

go/worker/common: Always use naked local storage

---

.changelog/4095.internal.md
.github/workflows/ci-reproducibility.yml
.github/workflows/release-dev.yml
.github/workflows/release.yml
docker/development/Dockerfile
docs/setup/prerequisites.md

Also updated development docker image to ubuntu 20.04 so that we can use `ffile-prefix-map` (added in GCC 8)

ci: Make jemalloc builds reproducible

---

.changelog/4096.bugfix.md
go/storage/mkvs/checkpoint/checkpoint_test.go
go/storage/mkvs/checkpoint/chunk.go

[BACKPORT/21.2.x] go/storage/mkvs/checkpoint: Determine next offset correctly

---

.changelog/4107.bugfix.md
go/storage/api/mux.go
go/storage/api/mux_test.go
go/worker/common/committee/group.go
go/worker/compute/executor/committee/node.go

Previously storage commit could fail in case the node was both an executor and
a storage node but not in the storage committee.

[BACKPORT/21.2.x] go/worker/compute: Replicate input batch locally

---

.changelog/4110.bugfix.md
go/consensus/tendermint/apps/staking/proposing_rewards.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/votes.go

Not propagating the state unavailable error could lead to corruption when the
database becomes unavailable (e.g., due to running out of space or file
descriptors).

go/consensus/tendermint: Correctly propagate errors

---

.changelog/4110.bugfix.md
go/consensus/tendermint/apps/staking/proposing_rewards.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/votes.go

Not propagating the state unavailable error could lead to corruption when the
database becomes unavailable (e.g., due to running out of space or file
descriptors).

[BACKPORT/21.2.x] go/consensus/tendermint: Correctly propagate errors

---

.changelog/4117.internal.md
go/common/logging/logging.go
go/go.mod
go/go.sum

This is the only part of go-kit that we are using so it makes sense to switch
to the smaller package.

go/common/logging: Switch to go-kit/log module

---

.changelog/4111.bugfix.md
go/runtime/host/sandbox/process/bwrap.go

This prevents the constructor from blocking forever in case something is
wrong with the sandbox setup.

[BACKPORT/21.2.x] go/runtime/host/sandbox: Add deadline to bwrap pipes

---

Cargo.lock
runtime/Cargo.toml

Latest revision has prost-types bumped to 0.8.0 which addresses RUSTSEC-2021-0073.

bump tendermint to latest revision

---

.changelog/2548.feature.md
go/runtime/client/client.go
go/runtime/client/tests/tester.go
go/runtime/host/helpers.go
go/runtime/scheduling/simple/orderedmap/ordered_map.go
go/runtime/scheduling/simple/orderedmap/ordered_map_test.go
go/worker/compute/executor/committee/batch.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/init.go
go/worker/compute/executor/tests/tester.go
go/worker/compute/executor/worker.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/2548
TODO:

go/worker/executor: batch CheckTx transactions

---

.changelog/3983.feature.md
go/oasis-test-runner/scenario/e2e/runtime/runtime_message.go
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/tests/tester.go

The GetTxs method has been deprecated and removed. Users should migrate
to use GetTransactions instead.
Fixes #3983

go/runtime/client: Remove deprecated GetTxs method

---

.changelog/4154.internal.md
go/oasis-test-runner/scenario/e2e/runtime/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_governance.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_prune.go
tests/runtimes/simple-keyvalue/api/src/api.rs
tests/runtimes/simple-keyvalue/src/main.rs

Most daily-longtest errors come from the re-execution of simple-keyvalue transaction which happens due to runtime not enforcing nonces and worker nodes being continuously restarted/killed.
TODO:

runtime/simple-keyvalue: check nonces

---

.changelog/4155.internal.md
go/oasis-test-runner/scenario/e2e/runtime/client_expire.go
go/worker/storage/committee/checkpoint_sync.go

Alternative fix to https://github.com/oasisprotocol/oasis-core/pull/4152 
Not sure which one we prefer

storage/checkpoint_sync: add timeout for fetching checkpoints from nodes

---

go/oasis-node/cmd/debug/txsource/workload/queries.go

Once the state is really big (e.g. after ~11 hours in the below test run), the consensus queries iteration can take more than currently configured timeout of 2 minutes. (as it iterates through all accounts, proposals, proposals votes, active proposals...). 
Discovered in https://buildkite.com/oasisprotocol/oasis-core-long-tests/builds/850#_

workload/queries: bump consensus queries timeout

---

.changelog/4161.internal.md
go/oasis-node/cmd/debug/txsource/workload/runtime.go

Ensure `validateEvents` queries events for the correct round.
Reason for failure in https://buildkite.com/oasisprotocol/oasis-core-long-tests/builds/852

workload/runtime: ensure correct round for validating events

---

.changelog/4167.internal.md
go/registry/gen_vectors/main.go

Previously, register entity transactions with v1 entities were supposedly being generated, however, it turned they were not properly generated.
Inside the `testvectors.MakeTestVectorWithSigner()` call, `cbor.Unmarshal()` was being called which automatically converted a v1 entity to a v2 entity.
Hence, test vectors for register entity transactions with v1 entities lacked integrity with one portion of the test vector having a v1 entity and the other portion having a v2 entity.

go/registry/gen_vectors: Stop generating transactions for v1 entities

---

.buildkite/longtests.pipeline.yml

Increase the longtests timeout. The timeout was actually too low for the long epoch tests to pass, as it takes two epochs (~1.5 hours in the long epoch case)  before all nodes are registered and the workloads get started. The current timeout was less than the required 1.5 hours + 12 hours workload run, so the long epoch version did always timeout.

ci: bump longtests timeout

---

.changelog/4162.feature.md
go/oasis-node/cmd/debug/txsource/workload/runtime.go
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/submitter.go
go/runtime/client/tests/tester.go
go/runtime/host/mock/mock.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4162
Not sure if there's any other potentially useful metadata that could be included

runtime/client: SubmitTx variant that returns metadata

---

.changelog/4177.feature.md
.changelog/4177.internal.md
go/registry/api/api.go
go/registry/gen_vectors/main.go

Use the custom `DeregisterEntity` type as the `DeregisterEntity` transaction's body type instead of `nil` to allow all pretty-printing
functions to work correctly.
Also, add test vectors for `registry.DeregisterEntity` transactions.

go/registry/api: Add its own body type to MethodDeregisterEntity

---

.changelog/4179.internal.md
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/upgrade.go

This makes it easier to e2e-test upgrade handlers. (note in `master` there's currently only the dummy handler, so this doesn't add any tests here)
TODO:

go/oasis-test-runner: support for testing update handlers

---

.changelog/4182.internal.md
Cargo.lock
runtime/Cargo.toml

- Fixes RUSTSEC-2021-0072 audit check
- https://github.com/oasisprotocol/oasis-core/pull/4130

[BACKPORT/21.2.x] rust: RUSTSEC-2021-0072 backports

---

.changelog/4179.internal.md
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/upgrade.go

Backports https://github.com/oasisprotocol/oasis-core/pull/4179

[BACKPORT/21.2.x] go/oasis-test-runner: support for testing upgrade handlers

---

.changelog/4187.feature.md
go/consensus/tendermint/apps/roothash/query.go
go/consensus/tendermint/roothash/roothash.go
go/oasis-test-runner/oasis/controller.go
go/roothash/api/api.go
go/roothash/api/grpc.go
go/roothash/tests/tester.go
go/staking/api/api.go

Backports https://github.com/oasisprotocol/oasis-core/pull/4187

[BACPORT/21.2.x] go/roothash: adds ConsensusParameters method

---

.changelog/4167.internal.md
.changelog/4177.feature.md
.changelog/4177.internal.md
go/registry/api/api.go
go/registry/gen_vectors/main.go

[BACKPORT/21.2.x] go/registry: Update test vectors and add its own body type to MethodDeregisterEntity

---

.changelog/4192.breaking.md
go/oasis-node/cmd/common/common.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/ias.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/seed.go
go/oasis-test-runner/oasis/sentry.go
go/oasis-test-runner/oasis/storage.go
go/oasis-test-runner/oasis/validator.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4192

prevent startup when RLIMIT_NOFILE is too low

---

.changelog/4202.bugfix.md
go/runtime/client/client.go
go/runtime/client/tests/tester.go

Fixes #4202 
Make sure that the runtime is actually among the supported runtimes as
otherwise we will not be able to actually get any results back.

go/runtime/client: Fail SubmitTx early for unsupported runtimes

---

.changelog/4210.bugfix.md
go/roothash/api/history.go
go/runtime/client/client.go
go/runtime/client/tests/tester.go
go/runtime/history/history.go
go/runtime/history/history_test.go
go/runtime/host/mock/mock.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4206
TODO:

go/runtime: fix round in runtime query

---

.buildkite/rust/build_runtime.sh

Fixes https://buildkite.com/oasisprotocol/oasis-core-ci/builds/5982#c112f7e2-f008-4930-aab5-c0f72a67dce8

.buildkite/rust/build-runtime: use --locked flag in cargo install

---

.changelog/4231.breaking.md
go/runtime/client/client.go
go/runtime/host/helpers.go
go/runtime/host/protocol/types.go
go/worker/compute/executor/committee/node.go
runtime/src/dispatcher.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

Fixes #4231 
This allows transaction checks and queries to access the maximum number of
runtime messages that can be emitted per round. Previously this information
was only available in ExecuteTxBatch.

runtime: Add MaxMessages to CheckTxBatch and Query

---

.changelog/4237.feature.md
go/consensus/tendermint/abci/mux.go
go/upgrade/api/api.go
go/upgrade/upgrade.go

Fixes #4237 
Previously pending upgrade descriptors were only refreshed during governance
proposal execution or after finishing a state sync. This is changed so that the
MessageStateSyncCompleted message is also emitted after consensus initialization
on already synced nodes so pending upgrades get installed even in case state was
synced manually (out of band).

go/consensus/tendermint: Request state refresh on consensus init

---

.changelog/4243.feature.md
go/common/node/node.go
go/common/node/node_test.go

This will result in easy to understand `"roles"` fields in various CLI commands that output JSON.
For example,  instead of `oasis-node control status` showing:
```
{
... trimmed ...
"registration": {
"last_registration": "2021-09-02T13:25:53+02:00",
"descriptor": {
... trimmed ...
"roles": 24
},
... trimmed ...
}
```
it will show:
```
{
... trimmed ...
"registration": {
"last_registration": "2021-09-02T13:25:53+02:00",
"descriptor": {
... trimmed ...
"roles": "validator,consensus-rpc"
},
... trimmed ...
}
```

go/common/node: Add custom text (un)marshaler for RolesMask type

---

.changelog/4244.breaking.md
.changelog/4244.bugfix.md
client/src/enclave_rpc/client.rs
go/keymanager/client/api/api.go
go/oasis-node/cmd/node/node.go
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/host.go
go/runtime/registry/host.go
go/worker/common/committee/runtime_host.go
go/worker/keymanager/worker.go

Previously runtimes hosted on client nodes were not able to issue EnclaveRPC
requests as the endpoint was not implemented in the handler. This unifies the
handler implementations between the client and compute nodes and makes sure that
key manager requests are possible (of course client nodes will only be able to
request public keys).
Also removes the EnclaveRPC client interface as the idea is to go through runtime
queries (as the SDK now supports using the key manager). Note that the client part
of EnclaveRPC transport was already removed when doing the gRPC refactor.

 go/runtime: Add key manager EnclaveRPC support to client runtime hosts

---

.changelog/4239.bugfix.md
go/common/identity/identity.go
go/common/identity/identity_test.go

go/common/identity: Refresh sentry TLS certificates

---

.changelog/4065.bugfix.md
go/governance/gen_vectors/main.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/upgrade/api/api.go
go/upgrade/migrations/migrations.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4065

go/upgrade: validate migration handler name on registration

---

.changelog/4183.feature.md
go/control/api/api.go
go/roothash/api/api.go
go/roothash/api/block/block.go
go/roothash/api/block/header.go
go/roothash/api/block/header_test.go
go/roothash/tests/tester.go

This enables prettier Oasis Node's `control status` CLI command's output for runtimes' `latest_time` field and matches the format of consensus' `latest_time` field.

go/roothash/api/block: Use custom TimeStamp type for block's header

---

.changelog/4265.internal.md
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go

Removes the not anymore relevant migration from old genesis from the `fixgenesis` command.

go/fixgenesis: remove the not anymore relevant migration

---

.changelog/4266.feature.1.md
.changelog/4266.feature.2.md
.changelog/4266.internal.md
go/common/entity/entity.go
go/oasis-node/cmd/common/consensus/consensus.go
go/oasis-node/cmd/common/json.go
go/oasis-node/cmd/control/control.go
go/oasis-node/cmd/debug/beacon/beacon.go
go/oasis-node/cmd/debug/dumpdb/dumpdb.go
go/oasis-node/cmd/governance/governance.go
go/oasis-node/cmd/keymanager/keymanager.go
go/oasis-node/cmd/registry/entity/entity.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-node/cmd/registry/runtime/runtime.go
go/oasis-node/cmd/stake/stake.go
go/oasis-test-runner/scenario/e2e/registry_cli.go

Add `PrettyJSONMarshal()` helper to unify how things are outputted to JSON.

go/oasis-node/cmd: Use pretty-printed variant when outputting JSON

---

.changelog/4278.internal.1.md
.changelog/4278.internal.2.md
.changelog/4278.internal.3.md
Cargo.lock
client/Cargo.toml
keymanager-api-common/Cargo.toml
keymanager-client/Cargo.toml
keymanager-lib/Cargo.toml
runtime/Cargo.toml
tests/runtimes/simple-keyvalue/Cargo.toml

Also bumps `base64ct` and `crypto-bigint` due to build warnings about old versions being yanked from registry.

bump oasis-cbor to 0.2.0

---

.changelog/4282.internal.md
Cargo.lock

It fixes  RUSTSEC-2021-0115:
https://rustsec.org/advisories/RUSTSEC-2021-0115.

rust: bump zeroize_derive to 1.2.0

---

.changelog/4281.breaking.md
.changelog/4281.doc.md
.changelog/4281.feature.2.md
.changelog/4281.feature.md
docs/oasis-node/cli.md
go/common/crypto/hash/hash.go
go/consensus/api/api.go
go/consensus/tendermint/api/api.go
go/oasis-test-runner/scenario/e2e/consensus_state_sync.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
go/oasis-test-runner/scenario/e2e/runtime/trust_root.go

Also change the type of `Status`' hash-related field (`LatestHash`, `GenesisHash`, `LastRetainedHash`) to the [common `Hash` type](  https://pkg.go.dev/github.com/oasisprotocol/oasis-core/go/common/crypto/hash#Hash
).
This will make all hash-related fields in the `"consensus"` part of `oasis-node control status`'s output use hex-encoding rather than Base64-encoding.
It follows a similar change for textual representation of runtime IDs and runtime state roots which was done in #4279.
The motivation for this change is to unify:
- Consensus hash representation (which used Base64-encoding previously) with runtime state root hash representation (which uses hex-encoding since #4279).
- `oasis-node control status`'s block hash representation with OASIS SCAN's and Oasis Monitor's representations …

go/consensus/api: Change Block's Hash field type to common Hash type

---

.changelog/4290.bugfix.md
go/worker/storage/committee/node.go

go/worker/storage: Fix potential memory leak through context

---

.changelog/4292.bugfix.md
go/storage/api/grpc.go

Exposed by fix for memory leak in #4290, the `receiveWriteLogIterator` did not handle context cancellation correctly and instead spinned forever.
Also see #4263.

go/storage/api: Handle context cancellation in receiveWriteLogIterator

---

.changelog/4334.feature.md
go/control/api/api.go
go/oasis-node/cmd/node/control.go
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/tests/tester.go

This allows clients to query what is the earliest runtime round that the
give node is storing.

go/runtime/client: Add last retained round query

---

.changelog/4334.feature.md
go/control/api/api.go
go/oasis-node/cmd/node/control.go
go/runtime/client/api/api.go
go/runtime/client/api/grpc.go
go/runtime/client/client.go
go/runtime/client/tests/tester.go

This allows clients to query what is the earliest runtime round that the
give node is storing.

[BACKPORT/21.3.x] go/runtime/client: Add last retained round query

---

.changelog/4340.bugfix.md
go/staking/api/api.go
go/staking/api/api_test.go

[BACKPORT/21.3.x] go/staking: Fix incorrect non-existence check

---

.changelog/4345.bugfix.md
go/runtime/history/prune.go

[BACKPORT/21.3.x] go/runtime/history: Limit batch size when pruning rounds

---

.changelog/4351.bugfix.md
go/consensus/tendermint/roothash/roothash.go

In case multiple runtimes were being tracked, the indexing process could
incorrectly set the last indexed round which could make it skip to index a
round.

go/consensus/tendermint/roothash: Only index the correct runtime

---

.changelog/4351.bugfix.md
go/consensus/tendermint/roothash/roothash.go

[BACKPORT/21.3.x] go/consensus/tendermint/roothash: Only index the correct runtime

---

.changelog/4333.feature.md
go/runtime/host/sgx/sgx.go

go/runtime/host/sgx: Autodetect SGX device name

---

.changelog/4333.feature.md
go/runtime/host/sgx/sgx.go

[BACKPORT/21.3.x] go/runtime/host/sgx: Autodetect SGX device name

---

go/common/version/version.go
go/common/version/version_test.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/runtime.go

Fixes #4343:
- adds `version` field of type `version.Version` to runtime fixture and config structs
- fixes converting versions from `uint64`, if component values are greater than 255

test-runner: Read runtime version from fixture

---

.cargo/audit.toml
.changelog/4366.bugfix.md
go/common/version/version.go
go/common/version/version_test.go

Semver parsing behavior changed in https://github.com/oasisprotocol/oasis-core/issues/4343 was too strict. This hotfix changes parsing of versions so that only `major` component is required whereas `minor` and `patch` are optional and any remaining components are ignored.

oasis-node: Make semver parsing less strict

---

.cargo/audit.toml
.changelog/4366.bugfix.md
go/common/version/version.go
go/common/version/version_test.go

[BACKPORT/21.3.x] oasis-node: Make semver parsing less strict

---

.changelog/4381.bugfix.md
go/storage/mkvs/db/badger/check.go

In case the state root did not change, a write log is empty and so the
sanity check should not require that it exists.

go/storage/mkvs: Don't fail sanity check for equal roots

---

.changelog/4386.bugfix.md
runtime/src/dispatcher.rs

A panic during transaction/local RPC/policy dispatch signals a serious problem
so it should be propagated and the runtime should crash to force state reset.

runtime: Propagate panics during transaction/local RPC/policy dispatch

---

.changelog/4395.internal.md
go/oasis-node/cmd/debug/txsource/workload/runtime.go

Since the VRF-based scheduler was introduced the compute nodes only become
eligible for election in the third epoch after genesis.

tests/workload/runtime: Wait for 3rd epoch for compute nodes to be up

---

.changelog/3986.internal.md
go/go.mod
go/go.sum

It was just released and it includes what we were using anyway. Just need to make sure it doesn't break anything.

go: Bump fxamacker/cbor to v2.3.0

---

.changelog/4055.cfg.1.md
.changelog/4055.internal.2.md
go/common/node/node.go
go/common/sgx/common.go
go/genesis/genesis_test.go
go/oasis-node/cmd/debug/byzantine/steps_test.go
go/oasis-node/cmd/ias/auth.go
go/oasis-test-runner/oasis/runtime.go
go/registry/api/api.go
go/registry/tests/tester.go
runtime/src/common/sgx/avr.rs
runtime/src/lib.rs

*  [x] runtime: Change OASIS_STRICT_AVR_VERIFY to OASIS_UNSAFE_LAX_AVR_VERFIY
Yes I had to move the `Constraints` field definition to the node package, because it doesn't belong in our IAS support code, and there will be an import loop otherwise.

runtime: Enclave quote status related cleanups/improvements

---

.changelog/4397.bugfix.md
go/storage/client/client.go

[BACKPORT/21.3.x] go/storage/client: Catch GetDiff errors early

---

.changelog/4392.doc.md
docs/adr/0012-runtime-message-results.md
docs/adr/index.md

[Rendered](https://github.com/oasisprotocol/oasis-core/blob/ptrus/adr/runtime-message-results/docs/adr/0012-runtime-message-results.md)

ADR-0012: Runtime message results

---

.changelog/4403.bugfix.md
go/worker/storage/committee/node.go

Previously, when a node was syncing from genesis, it would try to fetch all unapplied rounds before applying them.
This could mean trying to fetch 100k+ rounds before applying them.
In combination with failing to fetch rounds and random retrying, this could make the syncing process unbearably slow.

go/worker/storage: Limit number of rounds to fetch before applying them

---

.changelog/4403.bugfix.md
go/worker/storage/committee/node.go

[BACKPORT/21.3.x] go/worker/storage: Limit number of rounds to fetch before applying them

---

.changelog/4411.bugfix.md
Cargo.lock
go/storage/api/metrics.go
go/worker/storage/init.go
keymanager-client/Cargo.toml
keymanager-lib/Cargo.toml
runtime/Cargo.toml

[BACKPORT/21.3.x] go/storage/api: Make metrics wrapper return proper types

---

.changelog/4316.breaking.md
go/consensus/tendermint/apps/roothash/api.go
go/consensus/tendermint/apps/roothash/genesis.go
go/consensus/tendermint/apps/roothash/messages.go
go/consensus/tendermint/apps/roothash/query.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/slashing.go
go/consensus/tendermint/apps/roothash/slashing_test.go
go/consensus/tendermint/apps/roothash/state/state.go
go/consensus/tendermint/apps/roothash/transactions.go
go/consensus/tendermint/roothash/roothash.go
go/roothash/api/api.go
go/roothash/api/grpc.go
go/roothash/tests/tester.go
go/worker/compute/executor/committee/node.go

Fixes #4316 
Based on #4308 
Previously last normal round results were only available as events at the height
where the runtime block was emitted. This caused problems when consensus state
sync was used as that block may not be available. Last rounds results are now
persisted in consensus state so they remain always available.

go/roothash: Persist last round results in consensus state

---

.changelog/4426.internal.md
go/consensus/tendermint/api/context.go
go/consensus/tendermint/api/context_test.go
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/roothash/messages.go
go/storage/mkvs/overlay.go

The old way of doing checkpoints is removed as the new transaction
context supports nesting and event isolation.

go/consensus/tendermint/api: Add transaction context

---

.changelog/4309.breaking.md
go/consensus/tendermint/apps/governance/genesis_test.go
go/consensus/tendermint/apps/governance/governance.go
go/consensus/tendermint/apps/governance/governance_test.go
go/consensus/tendermint/apps/governance/transactions_test.go
go/consensus/tendermint/tests/genesis/genesis.go
go/genesis/genesis_test.go
go/governance/api/api.go
go/governance/api/proposal.go
go/governance/api/proposal_test.go
go/governance/api/sanity_check.go
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go

This replaces the old quorum + threshold based governance proposal
verification with a single unified threshold that the precentage of
yes votes in terms of total voting power (greater than or equal to).
The fixgenesis conversion logic will convert the existing parameters
to a stake threshold of 68%.
Fixes #4309.

go/governance: Replace quorum/threshold with stakeThreshold

---

.changelog/4429.bugfix.md
go/runtime/transaction/transaction.go
go/runtime/transaction/transaction_test.go

Previously when runtime transactions were queried via a GetTransactions call,
they were returned ordered by transaction hash instead of in execution order.

go/runtime/transaction: Return transactions in batch order when queried

---

.changelog/4429.bugfix.md
go/runtime/transaction/transaction.go
go/runtime/transaction/transaction_test.go

[BACKPORT/21.3.x] go/runtime/transaction: Return transactions in batch order when queried

---

.changelog/4431.feature.md
go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
go/runtime/scheduling/simple/txpool/tester.go

[BACKPORT/21.3.x] go/runtime/scheduling: Allow a higher priority tx even if queue full

---

.changelog/4386.bugfix.md
runtime/src/dispatcher.rs

Backport of #4386 (forgot to do it earlier).

[BACKPORT/21.3.x] runtime: Propagate panics during transaction/local RPC/policy dispatch

---

.changelog/4438.feature.md
go/oasis-test-runner/scenario/e2e/runtime/keymanager_restart.go
go/runtime/host/host.go
go/runtime/host/mock/mock.go
go/runtime/host/protocol/connection.go
go/runtime/host/protocol/connection_test.go
go/runtime/host/protocol/types.go
go/runtime/host/sandbox/sandbox.go
go/runtime/registry/host.go
go/runtime/scheduling/api/api.go
go/runtime/scheduling/simple/simple.go
go/runtime/scheduling/simple/txpool/api/api.go
go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
go/runtime/scheduling/simple/txpool/tester.go
go/runtime/txpool/txpool.go
go/worker/common/committee/runtime_host.go
go/worker/compute/executor/committee/batch.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/state.go
runtime/src/config.rs
runtime/src/dispatcher.rs
runtime/src/protocol.rs
runtime/src/transaction/dispatcher.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

Based on #4415.
Also adds functionality needed for #4436.
TODO

Add support for runtime schedule control

---

.changelog/4470.breaking.md
go/consensus/tendermint/apps/roothash/liveness.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/slashing.go
go/consensus/tendermint/apps/scheduler/api/api.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/consensus/tendermint/apps/scheduler/scheduler_test.go
go/consensus/tendermint/apps/scheduler/shuffle.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/debug/byzantine/grpc.go
go/oasis-node/cmd/debug/byzantine/node.go
go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
go/registry/api/runtime.go
go/registry/api/status.go
go/registry/api/status_test.go
go/roothash/api/api.go
go/roothash/api/liveness.go
go/roothash/tests/tester.go
go/staking/api/slashing.go
runtime/src/consensus/registry.rs
runtime/src/consensus/roothash.rs
runtime/src/consensus/staking.rs

Add support for node suspension due to runtime liveness failures

---

.changelog/4478.feature.md
go/common/cbor/cbor.go
go/common/grpc/cbor.go

A non-breaking backport of #4478.

[BACKPORT/21.3.x] go/common/cbor: Bump decoding limits for RPC

---

.changelog/4491.bugfix.md
go/common/node/node.go
runtime/src/common/sgx/avr.rs

`SW_HARDENING_NEEDED` should be allowed since it only indicates that additional SW hardening might be needed for the platform.
Discovered this in the failing SGX E2E: due to INTEL-SA-00334 (which is overed by https://github.com/oasisprotocol/oasis-core/issues/2987)

runtime: allow SW_HARDENING_NEEDED IAS quote status

---

.changelog/4460.bugfix.md
go/registry/api/runtime_test.go
runtime/src/consensus/registry.rs
runtime/src/consensus/roothash.rs

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4460

runtime/registry: fix `staking_params_are_empty`

---

.changelog/4461.breaking.md
go/consensus/tendermint/apps/roothash/transactions_test.go
go/consensus/tendermint/apps/staking/state/gas.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/consensus/tendermint/apps/staking/transactions.go
go/consensus/tendermint/apps/staking/transactions_test.go
go/consensus/tendermint/beacon/beacon.go
go/genesis/genesis_test.go
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/min_transact_balance.go
go/staking/api/api.go
go/staking/tests/state.go

writing down some basic thoughts on the idea of a minimum balance (general balance only)
cross reference https://oasisprotocol.clickup.com/t/1zfn2hb
still a lot of problems with this

go/staking: add minimum balance

---

.github/workflows/ci-lint.yml

Default behavior is that in-progress runs are not canceled (e.g. when pushing new changes to a branch).

github/ci-lint: cancel concurrent in-progress workflows on same branch

---

.changelog/4538.bugfix.md
go/runtime/host/multi/multi.go

Identified on the Testnet, triggered on client nodes.

go/runtime/host/multi: Release lock before calling into runtime

---

.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.yml
.changelog/4531.internal.md
go/common/logging/logging.go
go/common/logging/zap.go
go/common/logging/zap_test.go
go/go.mod
go/go.sum

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4531
libp2p logs are now emitted through oasis-node logging system.
Example logs:
```
{"caller":"id.go:453","level":"debug","module":"libp2p:net/identify","msg":"/ipfs/id/1.0.0 received message from 12D3KooWCUm3BxCXj5UTfkhbRnxb7hicz3tTTZbphbKhGSz3vTdb /ip4/192.168.88.233/tcp/20020","ts":"2022-03-08T08:47:57.699910867Z"}
{"caller":"obsaddr.go:397","level":"debug","module":"libp2p:net/identify","msg":"added own observed listen addr","observed":"/ip4/192.168.88.233/tcp/20012","ts":"2022-03-08T08:47:57.700039654Z"}
{"caller":"id.go:649","level":"debug","module":"libp2p:net/identify","msg":"12D3KooWBPiJ4rzKgz4NRka2zRAMF5JDYXNf6r5xDMxuusWNZYaw received listen addrs for 12D3KooWCUm3BxCXj5UTfkhbRnxb7hicz3tTTZbphbKhGSz3vTdb: …
```

go/logging: libp2p log adapter

---

.changelog/4556.bugfix.md
go/genesis/genesis_test.go
go/registry/api/api.go
go/registry/api/api_test.go
go/registry/api/sanity_check.go

consensus/sanity-checks: skip suspended runtimes when computing stake claims

---

.changelog/4564.bugfix.md
go/oasis-net-runner/fixtures/default.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/4533

oasis-net-runner: Fix fixtures without a keymanager

---

.changelog/4565.internal.md
go/consensus/tendermint/abci/prune.go
go/consensus/tendermint/abci/prune_test.go
go/consensus/tendermint/abci/state.go
go/oasis-node/cmd/node/node.go
go/storage/mkvs/checkpoint/checkpointer.go
go/storage/mkvs/db/api/api.go
go/storage/mkvs/db/badger/badger.go
go/storage/mkvs/tree_test.go
go/worker/client/service.go
go/worker/storage/committee/node.go
go/worker/storage/worker.go

Previously the worker maintaned a separate store that kept information
about the progress of storage sync. Since it was a separate store this
could cause problems if it got out of sync (e.g. due to partial manual
copies). This should make the process more robust as there is only one
source of truth.

go/worker/storage: Remove separate storage sync status store

---

.changelog/4464.cfg.md
.changelog/4464.feature.md
go/oasis-node/cmd/common/common.go
go/oasis-node/cmd/common/flags/flags.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/ias/proxy.go
go/oasis-node/cmd/node/node.go
go/oasis-node/node_test.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/byzantine.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/ias.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/seed.go
go/oasis-test-runner/oasis/sentry.go
go/oasis-test-runner/oasis/validator.go

go/oasis-node/cmd/node: Do not allow running oasis-node as root

---

.changelog/4574.feature.md
go/worker/registration/worker.go

This is hard coded to 5%, and will not be enabled if the mock backend is
in use so that the tests hopefully do not need alterations.

go/worker/registration: Add a random re-registration delay

---

.changelog/4574.feature.md
go/worker/registration/worker.go

This is hard coded to 5%, and will not be enabled if the mock backend is
in use so that the tests hopefully do not need alterations.

[BACKPORT/22.0.x] go/worker/registration: Add a random re-registration delay

---

.changelog/4585.bugfix.md
go/consensus/tendermint/apps/registry/transactions_test.go
go/registry/api/api.go

[BACKPORT/22.0.x] go/registry: Fix invalid sanity check

---

.changelog/4588.feature.md
go/oasis-node/cmd/node/unsafe_reset.go
go/oasis-test-runner/oasis/cli/cli.go

cross reference: https://app.clickup.com/t/294pfzp
Preserving the mkvs database is becoming the more common workflow, so we're changing the default to be true.
Use `--preserve.mkvs_database=false` to wipe the mkvs database as the previous default did.

go/oasis-node/cmd: unsafe-reset preserve mkvs by default

---

.changelog/4591.feature.md
go/common/crypto/signature/signer.go
go/common/crypto/signature/signer_test.go

when allowing unregistered signature contexts, still apply options for contexts that are registered

go/signature: apply options on registered contexts 

---

.changelog/4591.feature.md
go/common/crypto/signature/signer.go
go/common/crypto/signature/signer_test.go

backport 21.3.x - go/signature: apply options on registered contexts

---

.changelog/4591.feature.md
go/common/crypto/signature/signer.go
go/common/crypto/signature/signer_test.go

backport 22.0.x - go/signature: apply options on registered contexts

---

.changelog/4416.feature.md
go/oasis-node/cmd/stake/account.go
go/oasis-node/cmd/stake/stake.go

Example querying state of account [oasis1qzc687uuywnel4eqtdn6x3t9hkdvf6sf2gtv4ye](https://www.oasisscan.com/accounts/detail/oasis1qzc687uuywnel4eqtdn6x3t9hkdvf6sf2gtv4ye9) at [height 6000000](https://www.oasisscan.com/blocks/6000000):
```
$ oasis-node stake account info --stake.account.address oasis1qzc687uuywnel4eqtdn6x3t9hkdvf6sf2gtv4ye9 --height 6000000
Account State for Height: 6000000
Balance:
Total: 2527971.764241348 ROSE
Available: 100.006066449 ROSE
Active Delegations from this Account:
Total: 2527871.758174899 ROSE
Delegations:
- To:     oasis1qzc687uuywnel4eqtdn6x3t9hkdvf6sf2gtv4ye9 (self)
Amount: 2527871.758174899 ROSE (2172175873635393 shares)
Active Delegations to this Account:
Total: 50855117.628644824 ROSE (43699313150121151 shares)
Delegations:
- From: …
```

go/oasis-node/cmd/stake: Allow querying historical account info

---

.changelog/4416.feature.md
go/oasis-node/cmd/stake/account.go
go/oasis-node/cmd/stake/stake.go

[BACKPORT/21.3.x] go/oasis-node/cmd/stake: Allow querying historical account info

---

.changelog/4607.breaking.md
go/common/version/version.go
go/consensus/tendermint/apps/governance/transactions.go
runtime/src/common/version.rs

The intent from the comments is to allow votes to be cast as long as the
entity has at least 1 validator in the active set.  This fixes entities
with nodes that are not currently registered having their votes rejected.
Fixes #4607

governance: Allow unregistered nodes in votes

---

.changelog/4382.bugfix.1.md
.changelog/4382.bugfix.2.md
go/common/identity/identity.go
go/common/identity/identity_test.go

Sentry client TLS certificate is always re-generated from the private key when the Oasis Node starts.
Previously, the re-generated sentry client TLS certificate was not saved to disk, which caused confusion since the on-disk certificate file (i.e. `sentry_client_tls_identity_cert.pem`) had incorrect/outdated expiry date.
Also, save re-generated node's persistent TLS certificate. If a node's TLS certificate is persistent, it is always re-generated from the private key when the Oasis Node starts.
Previously, the re-generated node's persistent TLS certificate was not saved to disk, which caused confusion since the on-disk certificate file (i.e. `tls_identity_cert.pem`) had incorrect/outdated expiry date.

go/common/identity: Save re-generated sentry client and node's persistent TLS certificate

---

.changelog/4622.bugfix.md
go/oasis-node/cmd/stake/account.go

[BACKPORT/21.3.x] oasis-node/cmd/stake: Print actual latest height when querying info

---

.changelog/4617.feature.md
go/oasis-node/cmd/common/grpc/grpc.go

Require server-side TLS for non unix-socket gRPC connections.

go/oasis-node/cmd: Allow using non local gRPC connections

---

.changelog/4623.breaking.md
go/consensus/tendermint/apps/scheduler/debug_force.go
go/consensus/tendermint/apps/scheduler/shuffle.go

As an artifact from over-engineering related to operator permissioned paratimes, the scheduler nodes-per-entity constraint was written primarily with the assumption that the max nodes per entity constraint will be greater than 1.
This leads to an entity that runs more nodes having an elevated probability that their node will get elected into the committee, even if the constraint is set.  This fixes the problem for the case where the limit is 1, by pruning off the entity list based on each node's VRF beta prior to doing the cryptographic sortition.
Note that while the issue still persists for the case where the limit is greater than 1, all currently deployed paratimes set the constraint to 1 if at all, and realistically the constraint is probably better as a boolean that chooses between …

scheduler: Improve "more nodes = more better" fairness problems

---

.changelog/4633.bugfix.md
go/worker/compute/executor/committee/batch.go
go/worker/compute/executor/committee/transactions.go

[BACKPORT/22.1.x] go/worker/compute: Always include resolved transactions

---

.changelog/4638.bugfix.md
go/runtime/txpool/txpool.go

[BACKPORT/22.1.x] go/runtime/txpool: Fix crash on early access

---

go/runtime/host/sgx/sgx.go

This is largely cosmetic since we wrap a nil err (so the failure happens as it should), but might as well fix it.

go/runtime/host/sgx: Don't trample over the actual error

---

.changelog/9740.feature.md
go/worker/storage/committee/node.go

extracted from go/worker/storage: Refactor metrics
eaf491f6cba89e1ecf94f2c2767d46c89dee58bf
it is said that this speeds up runtime storage sync

go/worker/storage: eliminate artificial wait for heartbeat

---

.changelog/4647.bugfix.md
go/runtime/host/sandbox/sandbox.go

Previously the `StoppedEvent` was only emitted in case the runtime was
previously running. In case multihost was performing a version switch
when a runtime was not yet started, this resulted in a deadlock.

go/runtime/host: Always emit StoppedEvent on stop

---

.changelog/4647.bugfix.md
go/runtime/host/sandbox/sandbox.go

[BACKPORT/22.1.x] go/runtime/host: Always emit StoppedEvent on stop

---

.changelog/4650.bugfix.md
go/oasis-node/cmd/debug/byzantine/p2p.go
go/oasis-node/cmd/node/node.go
go/worker/common/p2p/p2p.go

[BACKPORT/22.1.x] go/worker/common/p2p: Make sure P2P stops before service cleanup runs

---

.changelog/4650.bugfix.md
go/oasis-node/cmd/debug/byzantine/p2p.go
go/oasis-node/cmd/node/node.go
go/worker/common/p2p/p2p.go

Otherwise this may result in a crash during shutdown when P2P requests
are processed while database is already closed.

go/worker/common/p2p: Make sure P2P stops before service cleanup runs

---

.changelog/4652.feature.md
go/staking/api/grpc.go

Backwards compatible backport of: https://github.com/oasisprotocol/oasis-core/pull/4652

go/staking/grpc: rename misnamed GovernanceDeposits method

---

.changelog/4662.bugfix.md
go/oasis-node/cmd/common/genesis/staking.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/worker/registration/worker.go

Added the resuming on closed `stopRegCh`  to one place too many in https://github.com/oasisprotocol/oasis-core/commit/29dbfa840231db434911f19c47a732bb12eed9bc
TODO:

worker/registration: fix waiting for deregister event

---

go/runtime/bundle/bundle.go
go/runtime/bundle/bundle_test.go

go/runtime/bundle: Check the ELF image when validating

---

.changelog/4673.internal.md
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go

- fixes the runtime-upgrade sgx test
- reduces the number of nodes in the txsoruce-sgx to (hopefully) reduce the flakiness, since it appears the test was failing due to transactions timing out at times
There still might be some flakiness, but there should be no sgx test constantly failing now, as seen here: https://buildkite.com/oasisprotocol/oasis-core-ci/builds/8217

ci: E2E SGX tests fixes

---

.changelog/4669.feature.md
go/consensus/api/api.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/seed/seed.go
go/oasis-test-runner/scenario/e2e/consensus_state_sync.go
go/oasis-test-runner/scenario/e2e/early_query.go
go/oasis-test-runner/scenario/e2e/runtime/node_shutdown.go
go/oasis-test-runner/scenario/e2e/seed_api.go
go/worker/common/api/api.go
go/worker/common/committee/node.go

go/control/status: Add fields for quick overview of node status

---

.changelog/4683.bugfix.md
go/worker/compute/executor/committee/node.go

Otherwise this will cause additional downtime on upgrades due to
capability updates not being allowed.

go/worker/compute: Only advertise active version for TEE runtimes

---

.changelog/4687.bugfix.md
go/runtime/host/sandbox/process/seccomp_linux.go

We need to handle the clone3 syscall in a special manner as there are
several complications to its handling:
- Newer glibc versions will try clone3 first and if they see EPERM they
will instantly fail making the program unable to spawn threads.
- The clone3 syscall is much more complex than clone and so we can't
simply inspect its flags as above for clone.
Therefore we need to reject the syscall with ENOSYS, causing fallback to
clone.

go/runtime/host/sandbox: Properly handle clone3 in seccomp policy

---

.changelog/4683.bugfix.md
.changelog/4687.bugfix.md
go/runtime/host/sandbox/process/seccomp_linux.go
go/worker/compute/executor/committee/node.go

[BACKPORT/22.1.x] Multiple backports

---

.changelog/4707.internal.md
.github/workflows/release.yml

This makes sure that oasis-core-loader is more portable between
distributions.

ci: Build OpenSSL statically for Oasis Core releases

---

.buildkite/code.pipeline.yml
.changelog/4715.feature.md
go/worker/common/committee/keymanager.go
go/worker/common/committee/node.go
go/worker/common/committee/runtime_host.go
go/worker/compute/executor/committee/node.go

Since the runtime can go from having no key manager configured to having
one, the worker node should handle this correctly.

go/worker/common: Properly handle dynamic key manager configuration

---

.changelog/4729.bugfix.md
go/runtime/registry/host.go
keymanager-client/src/client.rs
tests/runtimes/simple-keymanager/src/api.rs

Since the runtime can change dynamically (due to version upgrades), we
need to make sure that we notify the new runtime as well.

go/runtime/registry: Refresh key manager policy on runtime changes

---

.changelog/4729.bugfix.md
go/runtime/registry/host.go
keymanager-client/src/client.rs
tests/runtimes/simple-keymanager/src/api.rs

[BACKPORT/22.1.x] go/runtime/registry: Refresh key manager policy on runtime changes

---

.changelog/4734.bugfix.md
go/runtime/registry/config.go

TODO:
This should fix the SGX provisioner check. Currently SGX provisioner needs to be set even for non-sgx runtimes, caused by: https://github.com/oasisprotocol/oasis-core/pull/4734

go/runtime/config: fix SGX provisioner check

---

.changelog/4734.bugfix.md
go/runtime/registry/config.go

Backport of: https://github.com/oasisprotocol/oasis-core/pull/4734

[BACKPORT:22.1.x]: go/runtime/config: fix SGX provisioner check

---

.changelog/4744.internal.md
go/common/node/address.go
go/common/node/node_test.go
go/consensus/tendermint/apps/registry/state/interop/interop.go
go/oasis-node/cmd/debug/byzantine/grpc.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/registry/tests/tester.go
go/worker/common/p2p/p2p.go
go/worker/common/p2p/peermgmt.go

Since `Address` is used in consensus state, it makes sense using an explicitly defined struct. The struct serialization is defined in a backwards compatible way.

go/common/node/address: use custom type instead of internal net.TCPAddr

---

.changelog/4713.feature.md
go/worker/common/p2p/init.go
go/worker/common/p2p/p2p.go
go/worker/common/p2p/peermgmt.go

This PR adds support for blocking p2p peers and for keeping persistent connections to peers.
The persistent peer functionality currently doesn't automatically connect to the given peers on startup, but will only keep the connection once it's already established.

go/worker/common/p2p: Add support for persistent and blocked peers

---

.changelog/4757.feature.md
client/src/enclave_rpc/client.rs
client/src/enclave_rpc/transport.rs
go/runtime/enclaverpc/api/api.go
go/runtime/host/protocol/types.go
go/runtime/keymanager/api/api.go
go/runtime/registry/host.go
go/worker/common/committee/keymanager.go
go/worker/common/committee/node.go
go/worker/keymanager/handler.go
go/worker/keymanager/worker.go
runtime/src/enclave_rpc/types.rs
runtime/src/types.rs

This makes EnclaveRPC more robust as the higher-level layer in the
runtime can trigger peer replacement on high level errors.
TODO

runtime: Add support for reporting EnclaveRPC peer feedback

---

.changelog/4759.trivial.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/apps/governance/transactions.go
go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/slashing.go
go/consensus/tendermint/apps/roothash/transactions.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/transactions.go

Closes https://github.com/oasisprotocol/oasis-core/issues/4196
For a manually selected subset of `Logger().Warn()` and `Logger().Error()` log statements, this PR downgrades them to `Debug()`.
I aimed to downgrade all those error logs that originate in a malformed transaction/message (= external to the node and network), and leave all those error logs that signal a problem with the node or the network itself.
In functions that deal with genesis/initstate, I erred on the side of not downgrading. This stuff doesn't get called often, and when it does, the stakes are higher.

consensus: Reduce log spam

---

.changelog/4769.internal.md
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/network.go

Adds support for configuring roothash max messages in network fixtures.

go/oasis-test-runner/fixture: support configuring runtime messages

---

.changelog/4539.feature.md
go/consensus/api/api.go
go/consensus/api/api_test.go
go/consensus/api/submission.go
go/consensus/api/transaction/transaction.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/common.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/full/light.go
go/consensus/tendermint/full/services.go
go/consensus/tendermint/seed/seed.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/runtime/archive_api.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/upgrade/upgrade.go

Closes https://github.com/oasisprotocol/oasis-core/issues/4539
TODO:

Add archive mode support

---

.changelog/4687.bugfix.md
go/runtime/host/sandbox/process/seccomp_linux.go

We need to handle the clone3 syscall in a special manner as there are
several complications to its handling:
- Newer glibc versions will try clone3 first and if they see EPERM they
will instantly fail making the program unable to spawn threads.
- The clone3 syscall is much more complex than clone and so we can't
simply inspect its flags as we do for clone.
Therefore we need to reject the syscall with ENOSYS, causing fallback to
clone.

[BACKPORT/21.3.x] go/runtime/host/sandbox: Properly handle clone3 in seccomp policy

---

.changelog/4790.bugfix.md
go/common/quantity/quantity.go

In theory this is non-breaking because we check errors and don't use the set value.

go/common/quantity: Avoid side-effects on errors

---

.changelog/4793.feature.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/full/full.go

This is equivalent to the cosmos `halt-height` option, to be used to
bring a node down gracefully at a specific height.  Hopefully this will
never need to be used.

go/consensus/tendermint: Add `consensus.tendermint.halt_height`

---

.changelog/4475.doc.md
docs/development-setup/prerequisites.md

Problem encountered when trying to build `cipher-paratime` with SGX support.
See https://github.com/oasisprotocol/cipher-paratime/issues/19 for more details.
I don't know what the equivalent is for Fedora systems. I'll add it once I find out.

Document missing dependency (gcc-multilib) for Ubuntu setup

---

.changelog/4809.trivial.md
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/common.go
go/consensus/tendermint/full/full.go

Previously there were two sets of "node started" indicators (introduced in #4571), one for the commonNode and the other one for the fullService/archiveService. Due to how things were initialized this could cause the full node to report that it is "started" too soon which would cause some queries to trigger a segmentation fault instead of blocking.
(Discovered in long-term tests.)

go/consensus/tendermint/full: Unify started indicators

---

.changelog/4808.bugfix.md
go/oasis-net-runner/fixtures/default.go

Do not add **any** key manager fixture entry, if no key manager is defined.

net-runner: Fix regression introduced in #4564

---

go/oasis-net-runner/fixtures/default.go

Use 0.1.0 instead of 1.0.0 for consistency with runtime tests and initial tutorial code.

net-runner: Use 0.1.0 for default fixture.default.runtime.version

---

.changelog/4813.feature.md
go/oasis-net-runner/fixtures/default.go

[BACKPORT/22.1.x] net-runner: Add --fixture.default.runtime.version

---

.changelog/4823.bugfix.md
go/consensus/tendermint/db/closer.go
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/common.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/full/light.go

Tendermint Core will close the block/state store DBs during Stop which
can make certain in-flight queries trigger a panic due to the database
being already closed.
This commit introduces a DB wrapper that enables us to defer closing
the DB until Cleanup is called (as at that point all of the services
have already been stopped).

go/consensus/tendermint: Make sure DBs are only closed during cleanup

---

.changelog/4821.feature.md
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/ias.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/oasis/oasis.go
go/worker/keymanager/init.go
go/worker/keymanager/worker.go

Private peers are libp2p peers which are added manually and are not advertised. The goal is to allow client nodes that the key manager likes to access km methods, which is used by the confidential evm paratime's signed queries.

go/oasis-node: allow km to have private peers

---

.changelog/4821.feature.md
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/worker/keymanager/init.go
go/worker/keymanager/worker.go

Backport of
* https://github.com/oasisprotocol/oasis-core/pull/4821

[BACKPORT/22.1.x] go/oasis-node: allow km private peers

---

.changelog/4843.feature.md
go/common/copy.go
go/oasis-net-runner/fixtures/default.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go

Adds support for setting runtime state root and initial runtime state.
Not needed by any existing tests, but useful for external tooling to initialize network with pre-existing runtime state.

go/oasis-test-runner: support setting runtime state root and state

---

.buildkite/go/nancy_audit.sh
.changelog/4843.feature.md
go/.nancy-ignore
go/common/copy.go
go/oasis-net-runner/fixtures/default.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go

Backport of https://github.com/oasisprotocol/oasis-core/pull/4843

[BACKPORT/22.1.x] go/oasis-test-runner: support setting runtime state root and state

---

.changelog/4861.bugfix.md
go/common/dynlib/cache.go
go/common/dynlib/cache_test.go
go/common/dynlib/hwcap_linux.go
go/common/dynlib/hwcap_other.go
go/runtime/host/sandbox/process/seccomp_linux.go

The seccomp filter generator needs to handle clone3 being missing at
least till RHEL8 and variants are burried for good.
Fixes #4861

go/runtime/host/sandbox/process: Handle missing clone3

---

.changelog/4861.bugfix.md
go/common/dynlib/cache.go
go/common/dynlib/cache_test.go
go/common/dynlib/hwcap_linux.go
go/common/dynlib/hwcap_other.go
go/runtime/host/sandbox/process/seccomp_linux.go

The seccomp filter generator needs to handle clone3 being missing at
least till RHEL8 and variants are burried for good.
Backport of #4862

[BACKPORT/22.1.x]: go/runtime/host/sandbox/process: Handle missing clone3

---

.changelog/4867.bugfix.md
go/runtime/host/sandbox/process/seccomp_linux.go

[BACKPORT/22.1.x]: go/runtime/host: correct clone3 version threshold

---

.changelog/4867.bugfix.md
go/runtime/host/sandbox/process/seccomp_linux.go

expressing the version octets in hexadecimal instead of octal
the effect of the bug was that the threshold was too low and older kernels were mistakenly asked to resolve 'clone3,' resulting in 
> {"caller":"sandbox.go:463","err":"failed to spawn sandbox: sandbox: error while generating seccomp policy: could not resolve name to syscall: "clone3"","level":"error","module":"runtime/host/sandbox","msg":"failed to start runtime","runtime_id":"000000000000000000000000000000000000000000000000e2eaa99fc008f87f","ts":"2022-07-27T06:22:04.5330855Z"}

go/runtime/host: correct clone3 version threshold

---

.buildkite/rust/common.sh
.buildkite/scripts/sgx_ias_tests.sh
.changelog/4878.internal.md
docs/development-setup/building.md
keymanager-client/src/client.rs
tests/runtimes/simple-keymanager/src/api.rs

keymanager-client: Skip policy when OASIS_UNSAFE_SKIP_KM_POLICY is set

---

.changelog/4883.feature.md
go/control/api/api.go
go/control/control.go
go/oasis-node/cmd/node/control.go
go/worker/keymanager/api/api.go
go/worker/keymanager/init.go
go/worker/keymanager/status.go
go/worker/keymanager/worker.go

**Task**
Currently the key manager worker does not report any status as part of the GetStatus node control gRPC API call. It should provide some useful information about the operation of the key manager node.
**Test**
Tested locally using default fixture, simple-keymanager and minimal-runtime:
- Key manager status is shown only for keymanager nodes and not for compute, client and validator nodes.
- Status changes to ready once consensus is synced and key manager is registered.
- Client runtimes and access list populates with a short delay.
- Private peers are shown if we set them using the worker.keymanager.private_peer_pub_keys flag.

go: Add key manager worker status to node status

---

.changelog/4891.doc.md
docs/SECURITY.md
docs/consensus/genesis.md
docs/consensus/services/scheduler.md
docs/development-setup/oasis-net-runner.md
docs/oasis-node/rpc.md

In light of the docs restructuring https://github.com/oasisprotocol/docs/pull/200 replace any `/oasis-sdk/*` or `/general/*` links with full github.com URL.
Redirection back to the documentation's URL should be done by docusaurus preprocessor.

docs: Replace /oasis-sdk and /general links with full github URLs

---

.changelog/4891.doc.md
docs/SECURITY.md
docs/consensus/genesis.md
docs/consensus/services/scheduler.md
docs/development-setup/oasis-net-runner.md
docs/oasis-node/rpc.md

[BACKPORT/22.1.x] docs: Replace /oasis-sdk and /general links with full github URLs

---

.changelog/4892.bugfix.md
go/oasis-node/cmd/genesis/genesis.go

When dumping genesis state the height argument is not parsed correctly.
Tested locally.
```
➜  oasis-core git:(peternose/fix/dump-genesis) ✗ oasis-node genesis dump --address unix:/.../internal.sock 
➜  oasis-core git:(peternose/fix/dump-genesis) ✗ grep height genesis.json                                                                                           
"height": 1752,
➜  oasis-core git:(peternose/fix/dump-genesis) ✗ oasis-node genesis dump --height=13 --address unix:/.../internal.sock     
➜  oasis-core git:(peternose/fix/dump-genesis) ✗ grep height genesis.json 
"height": 13,
➜  oasis-core git:(master) ✗ oasis-node genesis dump --height=13 --address unix:/.../internal.sock
➜  oasis-core git:(master) ✗ grep height genesis.json …
```

oasis-node/cmd/genesis: Fix reading height argument

---

.changelog/4893.internal.1.md
.changelog/4893.internal.2.md
keymanager-lib/src/keymanager.rs
runtime/src/consensus/tendermint/verifier.rs
runtime/src/consensus/verifier.rs
runtime/src/dispatcher.rs
tests/runtimes/simple-keyvalue/src/main.rs

* runtime: Add state_at to consensus Verifier trait
This allows fetching historic consensus layer state in addition to the
latest state.
* runtime: Refactor dispatcher initializer and expose consensus_verifier

runtime: Add state_at to consensus Verifier trait

---

.changelog/4832.feature.md
go/runtime/registry/config.go

This PR backports 8a220c68f, which will (hopefully) allow client nodes to run SGX runtimes.

[BACKPORT/22.1.x] go/runtime/registry: allow client nodes to run SGX

---

.buildkite/code.pipeline.yml
.changelog/4888.feature.md
Cargo.lock
go/oasis-test-runner/scenario/e2e/runtime/keymanager_key_generation.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/worker/keymanager/worker.go
keymanager-api-common/src/api.rs
keymanager-client/src/client.rs
keymanager-client/src/lib.rs
keymanager-client/src/mock.rs
keymanager-lib/Cargo.toml
keymanager-lib/src/kdf.rs
keymanager-lib/src/keymanager.rs
keymanager-lib/src/methods.rs
keymanager-lib/src/policy.rs
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/context.rs
tests/runtimes/simple-keyvalue/Cargo.toml
tests/runtimes/simple-keyvalue/src/main.rs
tests/runtimes/simple-keyvalue/src/methods.rs
tests/runtimes/simple-keyvalue/src/types.rs

Add API methods like the following:
- `get_ephemeral_key(epoch, key_pair_id)`
- `get_public_ephemeral_key(epoch, key_pair_id)`
Those would derive special ephemeral X25519 key pairs separate from the other runtime keys and where the epoch number is used as part of the derivation, but would only derive them if the epoch was not too far back in the past based on consensus layer state as seen by the key manager. Initially the epoch check may rely on untrusted consensus state provided by the key manager host node.

Add support for ephemeral keys in key manager

---

.changelog/4910.feature.md
keymanager-api-common/src/api.rs
keymanager-client/src/client.rs
keymanager-lib/src/kdf.rs
keymanager-lib/src/methods.rs
runtime/src/dispatcher.rs
tests/runtimes/simple-keyvalue/src/main.rs

The key manager protocol should add the latest known trust root (or just the height) to (private key) EnclaveRPC requests. This would allow the key manager to detect whether the runtimes querying it have a fresh enough state (e.g. within 50 blocks) and reject operations if not.
Obviously the bad view can be either on the key manager side (Byzantine key manager operator) or the runtime side (Byzantine runtime operator). In case the key manager node is Byzantine the runtime can just switch to a different one (this already happens automatically when key manager requests fail).
This should be supported in a backwards compatible manner by making the new field optional.
Happy path is already covered with e2e tests. Unhappy path was tested locally.
- If key manager client is not up to date, …

keymanager: Validate latest trust root height in key manager requests

---

.changelog/4916.feature.md
go/common/node/tee.go
go/consensus/tendermint/apps/registry/registry.go
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/registry/transactions_test.go
go/consensus/tendermint/tests/genesis/genesis.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/registry/api/api.go
go/registry/tests/tester.go
go/upgrade/migrations/consensus_tee_pcs.go

This is needed for `Client node TEE freshness verification` and should be implemented in the following manner.
We can add a (carefully parameter-gated) new transaction (e.g. `registry.ProveFreshness`) that accepts a fixed-size binary blob of 32 bytes and always succeeds without doing any processing or state changes. It should cost a reasonable amount of gas.
The enablement parameter should be part of the existing `tee_features` consensus parameter group and be a boolean called `freshness_proofs`. If it is set to true the new transaction is processed otherwise it is handled as a non-existing transaction (e.g. exactly as currently to avoid breaking consensus before the activation proposal passes).
The existing `consensus-tee-pcs` migration should be updated to enable the `freshness_proofs` …

registry: Add ProveFreshness consensus layer transaction

---

.buildkite/code.pipeline.yml
.buildkite/scripts/test_e2e.sh
.changelog/4903.feature.md
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/scenario/e2e/e2e.go
go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
go/oasis-test-runner/scenario/e2e/runtime/halt_restore_nonmock.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/trust_root.go
go/oasis-test-runner/scenario/e2e/runtime/trust_root_change.go
go/runtime/host/protocol/types.go
go/runtime/registry/host.go
runtime/src/consensus/tendermint/mod.rs
runtime/src/consensus/tendermint/verifier.rs
runtime/src/consensus/verifier.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

Tested locally. Without changes compute workers are stuck with error messages `Consensus verifier failed to initialize`.
```
{"err":"builder: I/O error\n\nCaused by:\n   0: rpc error\n   1: server error: module: consensus code: 3 message: consensus: version not found\n, ...}
```
With changes compute workers report error message `Not enough trust to accept new chain context` when there is not enough trust to do the transition
```
{"level":"info","log_event":"consensus/tendermint/verifier/chain_context/no_trust","module":"runtime/consensus/tendermint/verifier","msg":"Not enough trust to accept new chain context","runtime_id":"8000000000000000000000000000000000000000000000000000000000000000","runtime_name":"test-runtime","tally":"VotingPowerTally { total: 3, tallied: 2, trust_threshold: …
```

runtime/consensus/verifier: Support trust root consensus layer upgrades

---

.changelog/4925.feature.md
go/consensus/tendermint/apps/keymanager/state/interop/interop.go
go/storage/mkvs/interop/fixtures/consensus_mock.go
keymanager-api-common/src/api.rs
keymanager-api-common/src/lib.rs
keymanager-client/src/client.rs
keymanager-lib/src/policy.rs
runtime/src/common/crypto/signature.rs
runtime/src/consensus/keymanager.rs
runtime/src/consensus/mod.rs
runtime/src/consensus/state/beacon.rs
runtime/src/consensus/state/keymanager.rs
runtime/src/consensus/state/mod.rs
runtime/src/consensus/state/registry.rs
runtime/src/consensus/state/staking.rs

When the key manager policy is updated, the runtime should check whether this policy has actually been published in the consensus layer by using the light client verifier.
This will require adding the Rust implementation of the consensus state accessor for the key manager service. Then one can fetch the corresponding key manager Status and check that the correct policy has been published there.
Happy path is already tested in `trust-root/simple` scenario. Unhappy path tested locally, the key manager doesn't update policy and constantly throws the following error:
```{"caller":"worker.go:737","err":"worker/keymanager: failed to extract rpc response payload: rpc failure: 'policy hasn't been published'","level":"error","module":"worker/keymanager","msg":"failed to handle status …
```

keymanager: Verify that policy was published in the consensus layer

---

.changelog/4922.feature.md
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/api/submission.go
go/consensus/api/transaction/transaction.go
go/consensus/tendermint/full/common.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/seed/seed.go
go/runtime/host/protocol/types.go
go/runtime/host/sandbox/sandbox.go
go/runtime/registry/host.go
go/worker/common/committee/runtime_host.go
runtime/src/common/crypto/signature.rs
runtime/src/config.rs
runtime/src/consensus/mod.rs
runtime/src/consensus/tendermint/merkle.rs
runtime/src/consensus/tendermint/mod.rs
runtime/src/consensus/tendermint/verifier.rs
runtime/src/consensus/transaction.rs
runtime/src/consensus/verifier.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

Executor and key manager TEE nodes currently use node registration (which includes the randomly generated Runtime Attestation Key and nonce) in order to establish consensus layer view freshness.
But this approach doesn’t work for client nodes. Since client nodes do not currently register, there is no way for TEE runtimes running on them to verify consensus layer freshness. There is however a need for client nodes to be able to execute signed queries and requiring an up-to-date consensus layer view is crucial for verifying quotes and policies.
To do this the runtime just needs to generate a transaction containing a nonce and that transaction must be published in a block, with the host node providing the height at which the transaction was published, its index and Merkle proof of inclusion. …

runtime: Add client node TEE freshness verification

---

go/common/dynlib/cache.go

Devuan puts libc in a somewhat odd place, and doesn't have enough backward compatibility symlinks, so the fallback test fails.
Resolve this by adding a special case for where Devuan sticks shared libraries.  Note that most sensible systems will only ever exercise the fallback path when running unit tests.

go/common/dynlib: Handle Devuan in tests

---

.changelog/4929.trivial.md
CHANGELOG.md
CONTRIBUTING.md
README.md
go/common/version/version.go
go/oasis-test-runner/scenario/e2e/genesis_file.go

Replaces docs.oasis.dev references with docs.oasis.io

docs: Migrate docs.oasis.dev -> docs.oasis.io

---

.changelog/4911.internal.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/api/context.go
go/consensus/tendermint/apps/beacon/api.go
go/consensus/tendermint/apps/beacon/beacon.go
go/consensus/tendermint/apps/governance/api.go
go/consensus/tendermint/apps/governance/governance.go
go/consensus/tendermint/apps/keymanager/api.go
go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/registry/api.go
go/consensus/tendermint/apps/registry/registry.go
go/consensus/tendermint/apps/roothash/api.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/staking/api.go
go/consensus/tendermint/apps/staking/staking.go
go/consensus/tendermint/full/full.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go

This PR adds support for consensus transaction prioritization using the V1 tendermint mempool implementation.
Here are the base priorities for our consensus apps:
```
consensus/tendermint/apps/beacon/api.go:		AppPriority int64 = 100000
consensus/tendermint/apps/keymanager/api.go:		AppPriority int64 = 50000
consensus/tendermint/apps/registry/api.go:		AppPriority int64 = 50000
consensus/tendermint/apps/governance/api.go:		AppPriority int64 = 25000
consensus/tendermint/apps/roothash/api.go:		AppPriority int64 = 15000
consensus/tendermint/apps/staking/api.go:		AppPriority int64 = 1000
consensus/tendermint/apps/scheduler/api.go:		AppPriority int64 = 0
consensus/tendermint/apps/supplementarysanity/api.go:	AppPriority int64 = 0
```
The reason why the `scheduler` and `supplementarysanity` have a …

go: Add consensus transaction prioritization

---

.github/workflows/ci-lint.yml
.github/workflows/ci-reproducibility.yml
.github/workflows/release-dev.yml
.github/workflows/release.yml

When Go was bumped to 1.18 some of the CI workflows were not changed.

ci: Fix Go version used in workflows

---

go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/transactions.go
go/consensus/tendermint/apps/staking/transactions.go
go/registry/api/api.go

See #4196 for motivation.
#4759 already downgraded most extraneous error logs, but I found some more when syncing a node from scratch. This PR removes the logs that appeared with frequency of more than one per 100k blocks.

go/consensus, go/registry: Reduce amount of error logs (2nd iteration)

---

.changelog/4959.bugfix.md
go/runtime/txpool/txpool.go

After processing a new block locally, make sure that any transactions that are checked against that block are only propagated after waiting for the `newBlockPublishDelay` to increase probability that peers are up to date with the new block.
Obviously a better way would be to check the current round of each peer (e.g., via a p2p update protocol), but such filtering is unfortunately not possible to do with the current go-libp2p-pubsub implementation.

go/runtime/txpool: Add block propagation delay before tx publish

---

.changelog/4960.bugfix.md
go/runtime/host/sgx/sgx.go
go/runtime/registry/config.go

Previously there was an edge case when the SGX loader was configured and remapping to non-SGX was forced (e.g. on client nodes). This would result in an invalid SGX configuration that resulted in a strange error message about a missing SIGSTRUCT.
This has now been changed so that remapping happens independent of whether an SGX loader is configured or not.

go/runtime: Fix configuring the SGX-based provisioner

---

.changelog/4962.bugfix.md
go/worker/compute/executor/committee/node.go

Before, the `nudgeAvailabilityLocked` was constantly executed once keymanager client was initialized since the channel is closed.

go/worker/compute: Only process keymanager client initialization once

---

go/oasis-node/cmd/debug/txsource/workload/governance.go

Replace random changes to the consensus parameters with trivial changes that do not change parameters at all.
Locally it looks like `.buildkite/scripts/test_e2e.sh --e2e/runtime.epoch.interval=20 --scenario e2e/runtime/txsource-multi` doesn't produce errors anymore.

go/oasis-node: Fix flaky governance workload

---

.changelog/4973.internal.md
go/storage/mkvs/syncer/proof.go
go/storage/mkvs/syncer/proof_test.go
runtime/src/storage/mkvs/sync/proof.rs

Note that this does not impact verification correctness as only visited nodes are part of the proof computation and the verified tree returned by the verifier.
But in case future code may want to do something with raw entries of a verified proof this removes a possible footgun where unverified entries could be considered.

mkvs/proof: Make sure that all entries in the proof have been used

---

go/consensus/api/api.go
go/consensus/tendermint/full/full.go
go/control/api/api.go
go/oasis-node/cmd/node/node_control.go
go/oasis-node/cmd/node/seed_control.go
go/oasis-test-runner/scenario/e2e/runtime/archive_api.go
go/oasis-test-runner/scenario/e2e/runtime/sentry.go
go/p2p/api/api.go
go/p2p/nop.go
go/p2p/p2p.go

Move P2P related status information including node's P2P addresses under P2P section of the control status.
Note that the data is duplicated if the node is registered (e.g. validators, compute nodes, key managers, but not clients).
```
➜  validator-0 oasis-node control status
{
"consensus": {
"p2p": {
"pub_key": "8EBdmxYwjz9bLreogzNEFuoLPQfci5pRjvHbYHIC/1Q=",
"peer_id": "21bd3dc64c88cb14ee0d4d5bb8964adc3febdd1b",
"addresses": [
"8EBdmxYwjz9bLreogzNEFuoLPQfci5pRjvHbYHIC/1Q=@127.0.0.1:20001"
],
"peers": [
"78ec9c69741d2a05dd479096d3adcc7c20ab6832@127.0.0.1:20004",
"a42258a7ecdadfe1f917f737033de17aead2e19a@127.0.0.1:46008",
"0d57061f4a1b293a8a10f46435eb29055627ee4e@127.0.0.1:46020",
"ec41b7af0c5522114d5d2d406586e635ceb648a5@127.0.0.1:46036", …
```

go/control: Include node's P2P addresses in control status

---

.changelog/5000.feature.md
go/p2p/rpc/client.go
go/p2p/rpc/peermgmt.go
go/p2p/rpc/rpc.go
go/p2p/rpc/server.go
go/p2p/txsync/client.go
go/p2p/txsync/server.go
go/worker/keymanager/p2p/client.go
go/worker/keymanager/p2p/server.go
go/worker/storage/p2p/pub/client.go
go/worker/storage/p2p/pub/server.go
go/worker/storage/p2p/sync/client.go
go/worker/storage/p2p/sync/server.go

This will be needed for adding a consensus-wide light-blocks libp2p protocol.

go/p2p/rpc: add support for consensus-wide libp2p protocols

---

.changelog/5008.bugfix.md
go/common/workerpool/workerpool.go

When workerpool si stopped, the job channel might still contain jobs which haven't been processed. Therefore, the channel never closes and leaves one go routine hanging.
Tested with the following code. Before the code printed 1/101, afterwards 1/1.
```
package main
import (
"fmt"
"runtime"
"time"
"github.com/oasisprotocol/oasis-core/go/common/workerpool"
)
func main() {
fmt.Println(runtime.NumGoroutine())
for i := 0; i < 100; i++ {
leak()
}
time.Sleep(time.Minute)
fmt.Println(runtime.NumGoroutine())
}
func leak() {
pool := workerpool.New("p2p/rpc")
pool.Resize(10)
defer pool.Stop()
for i := 0; i < 100; i++ {
pool.Submit(func() {
time.Sleep(time.Millisecond)
})
}
}
```

go/common/workerpool: Fix memory leak when workerpool is stopped early

---

.changelog/5008.bugfix.md
go/common/workerpool/workerpool.go

Backport of https://github.com/oasisprotocol/oasis-core/pull/5008

[BACKPORT/22.2.x] go/common/workerpool: Fix memory leak when workerpool is stopped early

---

.changelog/5007.bugfix.1.md
.changelog/5007.bugfix.2.md
.changelog/5007.internal.md
go/p2p/rpc/client.go
go/p2p/rpc/client_test.go
go/p2p/rpc/nop.go
go/p2p/rpc/peermgmt.go
go/p2p/rpc/server.go
go/p2p/txsync/client.go
go/p2p/txsync/protocol.go
go/worker/keymanager/p2p/client.go
go/worker/keymanager/p2p/protocol.go
go/worker/storage/p2p/pub/client.go
go/worker/storage/p2p/pub/protocol.go
go/worker/storage/p2p/sync/client.go
go/worker/storage/p2p/sync/protocol.go

Peer selection is very tightly coupled with RPC client as peer manager is constructed inside client's constructor. We also miss simple RPC calls which contact exactly one peer.
Memory leak was check with the following code, which prints 1 and 101, meaning that 100 go routines leaked.
```
package main
import (
"fmt"
"runtime"
"time"
"github.com/eapache/channels"
)
func main() {
fmt.Println(runtime.NumGoroutine())
for i := 0; i < 100; i++ {
leak()
}
time.Sleep(time.Minute)
fmt.Println(runtime.NumGoroutine())
}
func leak() {
n := 10
var chs []channels.SimpleOutChannel
for i := 0; i < n; i++ {
ch := channels.NewNativeChannel(channels.BufferCap(1))
defer close(ch)
chs = append(chs, ch)
ch <- i
}
ch := channels.NewNativeChannel(channels.None)
channels.Multiplex(ch, chs...)
for v := range …
```

go/p2p/rpc: Refactor rpc calls

---

.changelog/5012.breaking.md
go/common/node/node.go
go/common/node/node_test.go
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
go/oasis-node/cmd/registry/node/node.go
go/oasis-test-runner/scenario/e2e/registry_cli.go
go/worker/registration/worker.go

This PR adds basic validation checks to the Software Version field in node descriptor. As this is a human-readable version field, only a reasonable max length is enforced at this time.
Fix genesis is also updated to remove (and warn about) any registry nodes failing the basic descriptor validity checks. On most recent mainnet state, all nodes pass the (updated) validation checks.

go/registry: validate SoftwareVersion field in node descriptor

---

.changelog/5011.feature.md
go/consensus/tendermint/apps/staking/state/state.go

the escrow address is the first part of the key so we can seek to it

go tendermint staking: reduce DelegationsTo scanning

---

docs/oasis-node/metrics.md
docs/oasis-node/metrics.md.tpl

At Tendermint Core they reorganized their docs, but forgot to put redirects for old links in place.

docs: Update Tendermint Core metrics link

---

.changelog/5016.feature.md
docs/consensus/services/staking.md
go/consensus/tendermint/apps/staking/state/state.go
go/consensus/tendermint/apps/staking/state/state_test.go
go/staking/api/api.go
go/staking/api/api_test.go
runtime/src/consensus/staking.rs

**Motivation / Before this PR:** `TakeEscrowEvent` reports the [amount](https://github.com/oasisprotocol/oasis-core/blob/531421a928dc3450abd721c832d376549626a473/go/staking/api/api.go#L284) that was slashed. However, this total amount is taken proportionally from two separate sharepools: the active escrow and the debonding escrow.
Example: an account has 300 ROSE in active escrow and 100 ROSE in debonding escrow, and gets slashed by 40 ROSE. 30 ROSE will be slashed from active escrow, and 10 ROSE from debonding.
The event is thus not self-contained in that the 30 and the 10 from the example above cannot be derived from the event data (= 40) without knowing the balances in active and debonding escrow at the time the event was generated. This is inconsistent with other events, and awkward …

go tendermint staking: specify slashed debonding amount in `TakeEscrowEvent`

---

.changelog/5022.feature.md
go/consensus/tendermint/apps/staking/state/state.go

`DebondingDelegationsFor` keys are ordered by `delegatorAddr`. Once past it, it doesn't need to scan further (analogous to `DelegationsTo` fixed in: https://github.com/oasisprotocol/oasis-core/pull/5011).
Seek query is already (correctly) prefixed with `delegatorAddr`.

go/staking: reduce DebondingDelegationsFor scanning

---

.changelog/5023.breaking.md
go/consensus/tendermint/apps/staking/state/state.go
runtime/src/consensus/state/beacon.rs
runtime/src/consensus/state/keymanager.rs
runtime/src/consensus/state/registry.rs
runtime/src/consensus/state/staking.rs

An efficient `DelegationsFor` query will be needed for implementing [ADR-0020](https://github.com/oasisprotocol/adrs/blob/main/0020-governance-delegator-votes.md). If desired, could do a similar change for `DebonidngDelegationsTo` to optimize the query for it. 
No fix-genesis updates needed, since on `InitChain` all the delegations are inserted via the updated `SetDelegation` function.

go/staking: efficient DelegationsFor query

---

.changelog/5032.trivial.md
docs/consensus/README.md

Fixes tendermint link to transaction format.
Followup on #5018.

docs: Fix broken tendermint link

---

.changelog/5024.internal.md
.changelog/5035.internal.md
Cargo.lock
go/.nancy-ignore
keymanager/Cargo.toml
runtime/Cargo.toml
tests/runtimes/simple-keyvalue/Cargo.toml

[BACKPORT/22.2.x] runtime: Bump oasis-cbor to 0.5.1

---

.changelog/5055.breaking.md
go/beacon/api/api.go
go/consensus/tendermint/apps/beacon/backend_vrf.go
go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/registry/registry.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/staking/staking.go
go/keymanager/api/api.go

Currently, some modules are returning non-specific errros on tx deserialization failures which results in them being assigned to module "unknown", code 1. It would be more correct to always return the corresponding ErrInvalidArgument error for all deserialization failures.

go: always return `ErrInvalidArgument` on tx deserialization failure

---

.changelog/5016.breaking.md

After discussing with @kostko on Slack, marking #5016 as breaking because some clients (notably, our go client) error on receiving an event with a new field, as pointed out in the description of #5016.

meta: Mark #5016 as breaking

---

.changelog/5050.breaking.1.md
.changelog/5050.breaking.2.md
go/consensus/tendermint/apps/governance/governance_test.go
go/consensus/tendermint/apps/scheduler/genesis.go
go/consensus/tendermint/apps/scheduler/query.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/consensus/tendermint/apps/scheduler/scheduler_test.go
go/consensus/tendermint/apps/scheduler/state/state.go
go/scheduler/api/api.go

#5034 will need an efficient way to obtain a list of active validator entities

go/scheduler: include entity IDs in consensus validators state

---

.changelog/5068.bugfix.md
go/.nancy-ignore
runtime/src/consensus/tendermint/verifier/mod.rs

Since the store may have an earlier (non-canonical, but valid) version of the block available, we need to only compare the actual header and not the commits/signatures.
This is because it can happen that during the immediate sync the light block does not yet contain all of the commits (but only just enough to be valid, e.g. 2/3+) and this gets stored in the light block store. Later on (e.g. during a query) the presented light block may have the full set of commits.

runtime/consensus/tendermint/verifier: Correctly compare headers

---

.changelog/5032.trivial.md
docs/consensus/README.md
docs/oasis-node/metrics.md
docs/oasis-node/metrics.md.tpl

[BACKPORT/22.2.x] docs: Fix Tendermint URLs

---

.changelog/5079.feature.md
go/worker/keymanager/api/api.go
go/worker/keymanager/status.go
go/worker/keymanager/worker.go

Before first init request:
```
> keymanager-0 oasis-node control status
{
"keymanager": {
"signed_policy": null,
"policy_checksum": null
}
}
```
After first init request:
```
> keymanager-0 oasis-node control status
{
"keymanager": {
"signed_policy": null,
"policy_checksum": ""
}
}
```
With (sample) policy:
```
> keymanager-0 oasis-node control status
{
"keymanager": {
"signed_policy": {
"policy": {
"serial": 1,
"id": "c000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff",
"enclaves": {
"yaWJhRsfNWJxd/1wN47XeBcPc3YR5N+/C20lvf9VtHR9MQZkeAkxrhA6swqQFxwgGvOFpydXu0aDV4/evemt9Q==": {
"may_query": {
"8000000000000000000000000000000000000000000000000000000000000000": [
"GCVveDwHFSG+LaBBzZNHtb21qO9Y+zRlhXGm4Uzx/LDkgEnR3g6zM1I5kWcabJO5fdZbzwknPVtr/oJi3JaOxw=="
]
},
"may_replicate": [ …
```

go/worker/keymanager: Show current key manager policy in the node status

---

.changelog/5080.feature.md
go/worker/keymanager/api/api.go
go/worker/keymanager/status.go
go/worker/keymanager/worker.go

Not sure if we need two polices, one from the registry and one from the enclave. If things go sideways, those two could differ.
```
➜  keymanager-0 oasis-node control status
{
"keymanager": {
"global": {
"id": "c000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff",
"is_initialized": true,
"is_secure": false,
"checksum": "Um8OfhUNj0qWPP4+Jrp5byV90xKkpFVK37myBmk5FcI=",
"nodes": [
"lw6q22vpk3KEG4n4tB/jUNBJhbyRYoxK9QRfRYJUXZQ=",
"46AhhHHegX40j/XSK2b5LEXOOisG2xgnjJohTG7BRTQ="
],
"policy": null
},
"worker": {
"status": "ready",
"may_generate": true,
"runtime_id": null,
"client_runtimes": [
"8000000000000000000000000000000000000000000000000000000000000000"
],
"access_list": [
{
"runtime_id": "c000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff",
"peers": [ …
```

go/worker/keymanager: Show global key manager status in node status

---

.changelog/5083.internal.md
go/p2p/rpc/nop.go
go/p2p/rpc/peermgmt.go
go/p2p/rpc/peermgmt_test.go

Adds `WatchUpdates` method to the `PeerManager` which allows subscribing to peer updates (peers being added or removed).
This will be required by an upcoming Pull Request (consensus light-blocks protocol via libp2p), where Tendermint light client providers backed by P2P peers are implemented. In short: each provider is backed by a single P2P peer, and the provider needs to detect if the peer is removed, so it can switch to a new peer.

go/p2p/PeerManager: support subscribing to peer updates

---

.changelog/5092.bugfix.md
go/runtime/registry/host.go

Backport of https://github.com/oasisprotocol/oasis-core/pull/5092 (bugfix commit).

[BACKPORT/22.2.x] go/runtime/registry: Fix watching policy updates

---

.changelog/5095.internal.md
go/go.mod
go/go.sum

Bumped as previous version 0.3.0 has a know vulnerability (see [GO-2022-1144](https://pkg.go.dev/vuln/GO-2022-1144)).

go/go.mod: Bump golang.org/x/net to 0.4.0

---

.changelog/5094.internal.md
runtime/src/protocol.rs

Before:
```
{"err":"unknown field","level":"error","module":"runtime/protocol","msg":"Failed to handle message","runtime_id":"c000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff","runtime_name":"test-runtime","ts":"2022-12-10T14:02:38.449464523Z"}
{"level":"info","module":"runtime/protocol","msg":"Protocol reader thread is terminating","runtime_id":"c000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff","runtime_name":"test-runtime","ts":"2022-12-10T14:02:38.449491013Z"}
```
After:
```
{"err":"unknown field","level":"warn","module":"runtime/protocol","msg":"Unable to decode message","runtime_id":"c000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff","runtime_name":"test-runtime","ts":"2022-12-10T13:59:20.76384491Z"}
{"bytes":"[163, 98, 105, 100, 2, 100, …
```

runtime/src/protocol: Deserialize unknown rhp messages as invalid

---

.changelog/5092.bugfix.md
.changelog/5092.feature.md
go/common/namespace.go
go/registry/api/runtime.go
go/runtime/host/multi/multi.go
go/runtime/host/protocol/types.go
go/runtime/registry/host.go
keymanager/src/api/errors.rs
keymanager/src/client/remote.rs
keymanager/src/crypto/kdf.rs
keymanager/src/policy/cached.rs
runtime/src/attestation.rs
runtime/src/common/sgx/ias.rs
runtime/src/common/sgx/mod.rs
runtime/src/common/sgx/pcs.rs
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/client.rs
runtime/src/enclave_rpc/demux.rs
runtime/src/enclave_rpc/dispatcher.rs
runtime/src/enclave_rpc/session.rs
runtime/src/lib.rs
runtime/src/policy.rs
runtime/src/protocol.rs
runtime/src/rak.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

Currently EnclaveRPC session establishment always uses the default quote verification policy to verify quotes. When the runtime is configured with a consensus layer trust root it could instead use the quote verification policy specified in the consensus layer for the key manager runtime.
How things work:
- RPC remote client starts with empty enclaves, without key manager quote policy and waits for them to be set and regularly updated via local rpc calls.
- Demux uses no enclaves (enclaves authorization is checked at the application level) and local RAK quote policy which might be empty until TEE attestation is finished. Note that compute runtimes use their own quote policy in the demux and not from the key manager, but that should be fine as they currently never use demux.

runtime/src/enclave_rpc: Verify RPC quotes with key manager quote policy

---

.changelog/5098.trivial.md
go/runtime/host/sgx/sgx.go

This changes the SGX device search order in the runtime host to prefer the latest mainline SGX driver.

go/runtime/host/sgx: Fix SGX device search order

---

keymanager/src/client/interface.rs
keymanager/src/client/mock.rs
keymanager/src/client/remote.rs
keymanager/src/crypto/kdf.rs
keymanager/src/runtime/methods.rs
tests/runtimes/simple-keyvalue/src/methods.rs

Unwrapping public key from key manager requests.

keymanager/src/runtime: Remove redundant public key options

---

.changelog/5104.feature.md
go/consensus/tendermint/apps/governance/transactions.go
go/consensus/tendermint/apps/keymanager/transactions.go
go/consensus/tendermint/apps/registry/transactions.go

I think we can exit early in some places when estimating gas (all other transactions do already have this check after gas accounting is done).

go/consensus: add missing 'IsSimulation' checks in some transactions

---

.changelog/5107.bugfix.md
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/full.go
go/oasis-node/cmd/debug/dumpdb/dumpdb.go

Previously one could accidentally copy state from one network but use a genesis document from a different one, causing state corruption during Tendermint block replay.
There is now a check to ensure we abort early.

go/consensus: Ensure state has the correct chain context

---

.changelog/5075.internal.md
go/runtime/enclaverpc/api/api.go
go/runtime/host/protocol/types.go
go/runtime/keymanager/api/api.go
go/runtime/registry/host.go
go/worker/common/committee/keymanager.go
go/worker/keymanager/p2p/protocol.go
go/worker/keymanager/p2p/server.go
go/worker/keymanager/worker.go
keymanager/src/client/remote.rs
keymanager/src/runtime/init.rs
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/client.rs
runtime/src/enclave_rpc/dispatcher.rs
runtime/src/enclave_rpc/transport.rs
runtime/src/enclave_rpc/types.rs
runtime/src/types.rs

Create a new simpler, session-less, RPC request/response protocol to be used when dealing with public keys.

runtime/src/enclave_rpc: Support insecure key manager RPC requests

---

.changelog/5111.bugfix.md
go/runtime/registry/host.go
keymanager/src/policy/cached.rs
runtime/src/attestation.rs
runtime/src/dispatcher.rs
runtime/src/policy.rs

- Key manager (quote) policy updates don't work as expected as the consensus verifier will reject policy updates as his view of the state is one block behind the host. This is Tendermint specific and we should retry the update if it fails.
- Runtime info was also not updated if the runtime upgraded to a new version. As a consequence the quote policy was never updated, even if the new version supported this feature.
Retries can be tested by running `.buildkite/scripts/test_e2e.sh -s=e2e.runtime.keymanager-upgrade` on an SGX instance.
Before:
```
// Status update (reason: policy change)
{... "msg":"got key manager policy update","policy":{"policy":{"serial":2,...}}"}
{... "msg":"key manager policy mismatch","published":"SignedPolicySGX { policy: PolicySGX { serial: …
```

go/runtime/registry: Fix key manager (quote) policy updates

---

.changelog/5112.breaking.md
go/consensus/tendermint/apps/registry/state/interop/interop.go
go/registry/api/runtime.go
go/registry/api/runtime_test.go
runtime/src/consensus/registry.rs
runtime/src/consensus/state/beacon.rs
runtime/src/consensus/state/keymanager.rs
runtime/src/consensus/state/registry.rs
runtime/src/consensus/state/staking.rs

Not used for anything at the moment, but can be used in future for verification of automatically distributed bundles.

go/registry: Add optional bundle checksum to runtime deployments

---

.changelog/5117.bugfix.md
go/consensus/tendermint/governance/governance.go
go/consensus/tendermint/registry/registry.go
go/consensus/tendermint/roothash/roothash.go
go/consensus/tendermint/staking/staking.go

Currently consensus events (e.g. in various GetEvents RPCs) are returned in the following order:
- BeginBlock
- EndBlock
- DeliverTx
This PR switches all GetEvents RPCs to the more natural order:
- BeginBlock
- DeliverTx
- EndBlock
The motivation comes from oasis-indexer, where processing events in the order they were returned before this PR can lead to violated assumptions (e.g. "no account can ever have negative balance").

tendermint: GetEvents: return events in order

---

.changelog/5114.breaking.md
go/consensus/tendermint/apps/registry/transactions.go
go/consensus/tendermint/apps/registry/transactions_test.go
go/oasis-node/cmd/debug/txsource/workload/registration.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go
go/oasis-test-runner/scenario/e2e/runtime/txsource.go
go/registry/api/api.go
go/registry/tests/tester.go

This existing code ensures that the new entity actually exists and has the required stake:
https://github.com/oasisprotocol/oasis-core/blob/2680a6e97f0ebf2ffa892c72cbaf7289e85f3938/go/consensus/tendermint/apps/registry/transactions.go#L749-L775
However, in the existing registry node tests `params.DebugBypassStake` is used, so this cannot really be tested there. That's why I added a separate unit test suite for register runtime (with is currently only testing the updating entity owner behavior).

go/registry: Support changing a runtime's owner

---

.changelog/5101.feature.md
go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/keymanager/state/interop/interop.go
go/keymanager/api/api.go
go/oasis-node/cmd/keymanager/keymanager.go
go/runtime/host/protocol/types.go
go/runtime/registry/host.go
keymanager/src/api/errors.rs
keymanager/src/api/requests.rs
keymanager/src/client/mock.rs
keymanager/src/client/remote.rs
keymanager/src/crypto/kdf.rs
keymanager/src/crypto/types.rs
keymanager/src/runtime/methods.rs
runtime/src/consensus/state/keymanager.rs
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/dispatcher.rs
runtime/src/policy.rs
runtime/src/protocol.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

Fetch and verify public long-term/ephemeral runtime keys through an insecure channel.
Key manager upgrade tested locally with e2e test. Upgrade works as we allow empty runtime signing keys. An alternative would be to be strict here, but then one key manager would not be included in the node list because of the `Runtime signing key mismatch for runtime` error. Not sure if this is a problem though, as the new manager will be added to the list as soon as the old one is deregistered.

keymanager/src/client: Fetch public keys using insecure RPC requests

---

.changelog/5123.bugfix.md
go/runtime/host/protocol/errors.go
go/worker/client/committee/node.go

When a query is requesting to be executed against the latest round and the runtime reports a consensus verifier error, use an earlier round instead as the latest round may not yet be verifiable by the light client as it needs to wait for the validator signatures.

go/worker/client: Better handle latest round queries with verification

---

.changelog/5120.internal.md
.changelog/5123.bugfix.md
Cargo.lock
go/runtime/host/protocol/errors.go
go/worker/client/committee/node.go
keymanager/Cargo.toml
runtime/Cargo.toml
tests/runtimes/simple-keyvalue/Cargo.toml

[BACKPORT/22.2.x] go/worker/client: Better handle latest round queries with verification

---

.changelog/5130.bugfix.md
.github/workflows/release-dev.yml
.github/workflows/release.yml

This was automatically changed when `ubuntu-latest` was switched to Ubuntu 22.04. We should use the same build environment for all of the patch releases (22.2.4 is an exception as we didn't see this earlier).

[STABLE/22.2.x] ci: Use Ubuntu 20.04 for release builds

---

.changelog/5131.internal.md
.github/workflows/release-dev.yml
.github/workflows/release.yml

This avoids the situation when ubuntu-latest gets changed to something else, possibly imposing a different set of dependencies.

ci: Explicitly use Ubuntu 22.04 for release builds

---

.changelog/5135.internal.md
runtime/src/common/version.rs
runtime/src/lib.rs
runtime/src/protocol.rs

Consensus version check was a sanity check which didn't allow dump-restore upgrades. The removal did no harm as the consensus version was never authenticated and light clients use the verifier to check state compatibility and authenticity.

runtime/src/protocol: Remove consensus version compatibility check

---

.changelog/5135.internal.md
runtime/src/common/version.rs
runtime/src/lib.rs
runtime/src/protocol.rs

Backport https://github.com/oasisprotocol/oasis-core/pull/5135.

[BACKPORT/22.2.x] runtime/src/protocol: Remove consensus version compatibility check

---

.changelog/5125.feature.md
go/common/node/node.go
go/common/node/node_test.go
go/common/node/sgx.go
go/common/node/sgx_test.go
go/consensus/tendermint/apps/registry/state/interop/interop.go
go/consensus/tendermint/apps/scheduler/scheduler.go
go/oasis-node/cmd/debug/byzantine/steps.go
go/roothash/api/commitment/txnscheduler.go
go/runtime/host/protocol/types.go
go/runtime/host/sgx/sgx.go
runtime/src/attestation.rs
runtime/src/consensus/registry.rs
runtime/src/consensus/state/registry.rs
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/session.rs
runtime/src/protocol.rs
runtime/src/rak.rs
runtime/src/types.rs

Used attestation signature to authenticate the REK. When computing the signature the new version hashes also REK.
Next (optional) step would be to:
- move `height` and `signature` to `CapabilitiesTEE`,
- define custom CBOR marshalling which would copy those two fields from the `SGXAttestation` v2, and 
- move signature verification to `CapabilitiesTEE`.
We would probably also need to introduce versioning for `CapabilitiesTEE`. As this step is more complicated and not needed,  I decided to skip it.

go/common/node: Add runtime encryption key (REK)

---

.changelog/5148.bugfix.md
runtime/src/consensus/tendermint/verifier/mod.rs

Thanks to @ptrus for flagging this.

runtime: Clear verification trace after block verification

---

.changelog/5156.feature.md
go/p2p/rpc/peermgmt.go
go/runtime/host/protocol/types.go
go/runtime/keymanager/api/api.go
go/runtime/registry/host.go
go/worker/common/committee/keymanager.go
go/worker/keymanager/p2p/client.go
go/worker/storage/p2p/sync/client.go
keymanager/src/client/remote.rs
keymanager/src/crypto/kdf.rs
runtime/src/enclave_rpc/client.rs
runtime/src/enclave_rpc/session.rs
runtime/src/enclave_rpc/transport.rs
runtime/src/types.rs
tests/runtimes/simple-keyvalue/src/main.rs

Currently the EnclaveRPC clients can only talk to a randomly chosen remote key manager as selected by the host. It should be possible for the client to ask the host to talk to a specific key manager instance identifier by its (node ID, RAK) pair and its identity would be verified by using RAK (in addition to the remote attestation checks). The enclave can obtain a trusted RAK of other instances from the consensus layer registry service.
This would allow for later implementation of secret sharing schemes where communication with particular instances is required.

runtime/src/enclave_rpc: Support calls to explicit key manager members

---

.changelog/5160.bugfix.md
go/worker/client/committee/node.go

Previously the transaction inclusion checks could attempt to inspect a block that the node has not yet synced, triggering an error.

go/worker/client: Ensure block round is synced to storage

---

.changelog/5159.bugfix.md
go/consensus/tendermint/apps/keymanager/keymanager.go
go/consensus/tendermint/apps/keymanager/keymanager_test.go
go/keymanager/api/api.go
go/keymanager/api/api_test.go

Previously, a node was added to the key manager committee if the node's first registered key manager runtime passed validation and matched the key manager status. From now on, all supported versions of the key manager runtime must pass this check.

go/consensus/tendermint/apps/keymanager: Fix committee construction

---

.changelog/5161.bugfix.md
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/p2p.go
go/worker/compute/executor/committee/proposals.go
go/worker/compute/executor/committee/state.go

Previously valid proposals could be dropped instead of being forwarded via the P2P gossip when the local node's consensus view was slightly behind even though the proposal was valid. With smaller committees and certain topologies this could result in some nodes not getting the proposals.

go/worker/compute: Do not drop valid proposals

---

.changelog/5166.breaking.md
go/consensus/tendermint/apps/keymanager/genesis.go
go/consensus/tendermint/apps/keymanager/messages.go
go/consensus/tendermint/apps/keymanager/messages_test.go
go/consensus/tendermint/apps/keymanager/state/state.go
go/consensus/tendermint/apps/keymanager/transactions.go
go/genesis/genesis_test.go
go/keymanager/api/api.go
go/keymanager/api/sanity_check.go
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
go/oasis-node/cmd/genesis/genesis.go
go/registry/api/api.go

Moving key manager gas costs from registry to key manager.

go/keymanager/api: Move key manager gas costs

---

.changelog/5168.internal.md
go/common/node/node.go
go/registry/api/api.go

Before, when upgrading from 22.2.x the supplementary-sanity checks would fail for validator nodes that did not yet re-register with added P2P address.
(Unrelated change) update `minNodeDescriptorVersion` to 3, because V2 descriptors are automatically migrated to V3 in deserialization, so no need to allow V2 descriptors.

go/consensus/supplementarysanity: Fix checks for legacy validators

---

go/common/sync/sync_test.go
go/consensus/tendermint/apps/governance/messages_test.go
go/consensus/tendermint/apps/keymanager/keymanager_test.go
go/consensus/tendermint/apps/keymanager/messages_test.go
go/consensus/tendermint/apps/registry/messages_test.go
go/consensus/tendermint/apps/registry/transactions_test.go
go/consensus/tendermint/apps/roothash/messages_test.go
go/consensus/tendermint/apps/scheduler/messages_test.go
go/consensus/tendermint/apps/staking/messages_test.go
go/p2p/backup/cstore_test.go
go/p2p/discovery/bootstrap/client_test.go
go/p2p/discovery/peerstore/peerstore_test.go
go/p2p/peermgmt/backup_test.go
go/p2p/peermgmt/connector_test.go
go/p2p/peermgmt/discovery_test.go
go/p2p/peermgmt/peermgr_test.go
go/p2p/protocol/protocol_test.go
go/p2p/rpc/client_test.go
go/storage/mkvs/overlay_test.go

Solves the following problem when test fails:
```
.../oasis-core/go/common/sync/testing.go:1343: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```

go: Minor test case fixes

---

docs/development-setup/prerequisites.md

Add missing clang dependency, update SGX tooling installation instructions (nightly no longer required to install tools).

docs: Fix development setup instructions

---

.changelog/5193.internal.md
go/oasis-net-runner/fixtures/default.go
go/oasis-test-runner/oasis/entity.go
go/oasis-test-runner/oasis/network.go

Adds support for disabling debug test entity, configuring epochtime interval and governance parameters to the `oasis-net-runner`.
These are useful/needed for implementing: `22.2.x` -> `master` E2E network upgrade tests.

[STABLE/22.2.x] oasis-net-runner: add some useful configuration options

---

go/consensus/tendermint/apps/keymanager/keymanager.go

Removing legacy code which assumed that key managers will be set in the genesis file before being initialized.

go/consensus/tendermint/apps/keymanager: Remove secure transition check

---

.changelog/5198.internal.md
keymanager/src/api/errors.rs
keymanager/src/api/requests.rs
keymanager/src/client/interface.rs
keymanager/src/client/mock.rs
keymanager/src/client/remote.rs
keymanager/src/crypto/kdf.rs
keymanager/src/crypto/mod.rs
keymanager/src/crypto/packing.rs
keymanager/src/runtime/methods.rs
runtime/src/common/namespace.rs
tests/runtimes/simple-keyvalue/src/methods.rs

Master secret rotation, 1st part:
- Refactor key manager's init method to be able to support multiple generations of the master secret.

keymanager: Add support for master secret generations

---

.changelog/5199.internal.md
go/consensus/tendermint/apps/keymanager/state/interop/interop.go
go/consensus/tendermint/apps/keymanager/state/state_test.go
go/consensus/tendermint/apps/keymanager/transactions.go
go/consensus/tendermint/apps/keymanager/transactions_test.go
go/keymanager/api/secret.go
go/keymanager/api/secret_test.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_ephemeral_keys.go
go/worker/keymanager/worker.go
keymanager/src/runtime/methods.rs
runtime/src/consensus/keymanager.rs
runtime/src/consensus/state/beacon.rs
runtime/src/consensus/state/keymanager.rs
runtime/src/consensus/state/registry.rs
runtime/src/consensus/state/staking.rs

Master secret rotation, 2nd part:
- Add signed encrypted master secret.

go/keymanager/api: Add signed encrypted master secret

---

.changelog/5204.feature.md
go/keymanager/api/api.go
go/runtime/host/protocol/types.go
go/worker/keymanager/worker.go
keymanager/src/api/errors.rs
keymanager/src/api/requests.rs
keymanager/src/policy/cached.rs
keymanager/src/runtime/methods.rs
runtime/src/consensus/state/keymanager.rs
runtime/src/types.rs
tests/runtimes/simple-keymanager/src/main.rs

The init request was never verified against the consensus layer state and, therefore, was not trustworthy. To make this request more informative and easily verifiable against consensus, it was extended to include all key manager status fields.

keymanager/src/runtime: Verify and modify init request

---

.changelog/5213.internal.md
Cargo.lock
runtime/Cargo.toml

Crate:     remove_dir_all
--
  | Version:   0.5.3
  | Title:     Race Condition Enabling Link Following and Time-of-check Time-of-use (TOCTOU)
  | Date:      2023-02-24
  | ID:        RUSTSEC-2023-0018
  | URL:       https://rustsec.org/advisories/RUSTSEC-2023-0018
  | Solution:  Upgrade to >=0.8.0

rust: Bump tempfile to 3.4.0

---

go/worker/keymanager/init.go
go/worker/keymanager/worker.go

Simplify the main for loop and organize the code by adding additional functions.

go/worker/keymanager: Refactor the main loop in the key manager worker

---

.changelog/5215.internal.md
go/oasis-node/cmd/keymanager/keymanager.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/worker/keymanager/watcher.go
go/worker/keymanager/worker.go
keymanager/src/client/remote.rs
keymanager/src/policy/cached.rs

The key manager settings configured in the policy can now be tested on non-SGX builds as well. This will simplify tests, as default values can be configured in the test fixtures (e.g. master secret rotation period).

keymanager: Support policies in unsafe builds

---

go/oasis-node/cmd/common/pprof/pprof.go
go/oasis-node/cmd/ias/proxy.go
go/oasis-node/cmd/node/init.go
go/oasis-test-runner/env/env.go
go/worker/storage/committee/node.go

This should speed up the runtime integration tests by more than half a minute (5s for every termination).

go/oasis-node: Fix graceful termination

---

.changelog/5239.bugfix.md
go/runtime/host/sgx/sgx.go

Fixes #5238 
This allows the node to continue working in case aesmd is upgraded while the node is running. In this case the Quoting Enclave identity can change and this requires the target info to be updated.

go/runtime/host/sgx: Update QE target info during re-attestation

---

go/config/config.go
go/oasis-node/cmd/common/metrics/config/config.go
go/oasis-node/cmd/common/metrics/metrics.go
go/oasis-node/cmd/config/migrate/migrate.go
go/oasis-node/cmd/config/migrate/migrate_test.go
go/oasis-node/cmd/debug/byzantine/byzantine.go
go/oasis-node/cmd/ias/proxy.go
go/oasis-node/cmd/node/flags.go
go/oasis-test-runner/cmd/cmp/cmp.go
go/oasis-test-runner/cmd/root.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/network.go

Config migration improvements

---

go/oasis-test-runner/cmd/cmp/cmp.go
go/oasis-test-runner/cmd/root.go

This fixes the following bug: https://github.com/oasisprotocol/oasis-core/pull/5244#discussion_r1167569898

go/oasis-test-runner: Fix viper bug in metrics options

---

.changelog/5248.bugfix.md
Cargo.lock
go/worker/client/committee/node.go

[BACKPORT/22.2.x] go/worker/client: Also treat literal latest round as latest

---

.buildkite/scripts/common.sh

The command `buildkite-agent artifact download` always re-downloads Buildkite artifacts, even if they are already present. With this PR it first checks its SHA-1 checksum (SHA-256 is not available for all artifacts). This should speed-up most E2E tests by ~1.5-3 minutes.

.buildkite: Download Buildkite artifact only if checksum changed

---

CONTRIBUTING.md
GOVERNANCE.md

[BACKPORT/22.2.x] Fix Discord links to use static custom URL

---

.buildkite/code.pipeline.yml

Because Intel will eventually roll-out SGX2, the new Buildkite agents with `/dev/sgx_enclave` execute jobs with `queue=sgx1`. The old Buildkite agents with `/dev/isgx` execute jobs with `queue=intel-sgx`. This PR switches SGX CI jobs to the new Buildkite agents and renames them.

.buildkite: Switch CI jobs to using /dev/sgx_enclave devices

---

.buildkite/code.pipeline.yml

[BACKPORT/22.2.x] .buildkite: Switch CI jobs to using /dev/sgx_enclave devices

---

go/oasis-test-runner/oasis/client.go
go/oasis-test-runner/oasis/keymanager.go
go/worker/keymanager/worker.go

Nil pointer error shows up if you try to run the latest stable test runtimes on a key manager node from the master branch.
Exploded bundles can be removed on cleanup on client, compute and key manager nodes.

go: Fix nil pointer error and remove exploded bundles 

---

.changelog/5260.bugfix.md
go/worker/compute/executor/committee/node.go

Previously a compute node could propose a new batch just before the epoch transition happened, resulting in computation that will be discarded anyway.

go/worker/compute/executor: Do not propose batch on epoch transition

---

.changelog/5264.feature.md
go/consensus/api/submission.go
go/consensus/tendermint/apps/roothash/roothash.go
go/consensus/tendermint/apps/roothash/transactions.go
go/consensus/tendermint/apps/roothash/transactions_test.go
go/consensus/tendermint/roothash/roothash.go
go/roothash/api/api.go
go/roothash/api/grpc.go
go/worker/compute/executor/committee/discrepancy.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/state.go

Backup compute workers now observe any gossiped commitments and pre-empt
consensus when it is obvious that there will be a discrepancy declared.

Optimize backup worker commit submission

---

.changelog/5272.internal.md
go/go.mod

The replace directive for github.com/whyrusleeping/timecache has been removed since the go-libp2p-pubsub library version 0.9.3 no longer utilizes it.
@kostko Was problem [#467](https://github.com/libp2p/go-libp2p-pubsub/issues/467) fixed in https://github.com/libp2p/go-libp2p-pubsub/tree/master/timecache?

go: Remove timecache replace directive in go.mod file

---

.changelog/5273.internal.md
go/go.mod

The replace directive for github.com/google/flatbuffers has been removed since the badger library version 3.2103.4 uses the same version 1.12.1.
See https://github.com/dgraph-io/badger/blob/v3.2103.4/go.mod#L14.

go: Remove flatbuffers replace directive in go.mod file

---

.buildkite/benchmarks.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/longtests.pipeline.yml
.buildkite/pipeline.sh
.buildkite/scripts/common.sh

Experimental attempt to reorganize and improve namespacing of CI caches and build artifacts. By introducing explicit levels at which local caches and artifacts can be shared (`global_cache`, `branch_cache`, `build_cache`), we should be able to support multiple Buildkite agents per node and increase their utilization.

.buildkite: Improve namespacing of CI caches and build artifacts

---

.buildkite/scripts/common.sh
.buildkite/scripts/download_e2e_test_artifacts.sh

It seems that running multiple Buildkite agents in parallel (after https://github.com/oasisprotocol/oasis-core/pull/5258) occasionally triggers a race condition if two Buildkite agents simultaneously attempt to write the same file to the local cache:
```
+mv -f /tmp/artifacts_tmp/oasis-node.test /tmp/artifacts/oasis-node.test
mv: cannot create regular file '/tmp/artifacts/oasis-node.test': File exists
```
This PR simplifies the Buildkite artifact downloading logic and prevents this race condition from causing a failed CI job.

.buildkite: Fix CI pipeline race condition

---

.changelog/5289.bugfix.md
go/oasis-node/cmd/ias/proxy.go

go/oasis-node/cmd/ias: Regenerate TLS certificate on startup

---

.changelog/5286.internal.md
go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go

Update the `fixgenesis` command to be in line with the v62 consensus migration.

Enable fixgenesis features

---

.changelog/5292.breaking.md
go/consensus/api/api.go
go/consensus/api/meta.go
go/consensus/tendermint/abci/mux.go
go/consensus/tendermint/abci/state.go
go/consensus/tendermint/abci/state/state.go
go/consensus/tendermint/abci/system.go
go/consensus/tendermint/abci/transaction.go
go/consensus/tendermint/api/block.go
go/consensus/tendermint/apps/beacon/backend_vrf.go
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/full.go
go/go.mod
go/go.sum
go/storage/mkvs/mkvs.go
go/storage/mkvs/overlay.go
go/storage/mkvs/overlay_test.go

go/consensus: Add block metadata to allow same-block state validation

---

.changelog/5301.feature.md
go/control/api/api.go
go/oasis-node/cmd/node/node_control.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
go/runtime/host/host.go
go/runtime/host/mock/mock.go
go/runtime/host/sandbox/sandbox.go
go/runtime/host/sgx/sgx.go

This PR adds the runtime provisioner type to the status output.

go/control: Add runtime provisioner type to host status output

---

go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go

This fixes a dumb bug I introduced to the e2e test for checking if the provisioner type works in the status output.

e2e: Fix test for provisioner type in status output

---

go/oasis-test-runner/scenario/e2e/runtime/gas_fees.go
go/oasis-test-runner/scenario/e2e/runtime/multiple_runtimes.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv_scenario.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_prune.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
tests/runtimes/simple-keyvalue/src/methods.rs
tests/runtimes/simple-keyvalue/src/types.rs

The runtime test client can now select which generation of the master secret should be used to insert, fetch, or delete a key/value pair from the simple key/value runtime. Until now, all encrypted transactions used master secret generation 0.
Needed for master secret generations cross-version/upgrade tests.

go/oasis-test-runner/scenario: Add master secret generation to txs

---

.changelog/5307.internal.md
go/oasis-test-runner/rust/builder.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv_scenario.go
go/oasis-test-runner/scenario/e2e/runtime/trust_root.go
go/oasis-test-runner/scenario/e2e/runtime/trust_root_change.go
runtime/src/consensus/tendermint/verifier/noop.rs
runtime/src/protocol.rs
tests/runtimes/simple-keymanager/src/main.rs

Build and test the key manager runtime with an embedded trust root.
Use secure operations when running trust root scenarios.

go/oasis-test-runner: Build key manager runtime with trust root 

---

.github/dependabot.yml

Fix the ignore clause to prevents PR's like: https://github.com/oasisprotocol/oasis-core/pull/5310
Try out the new [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) feature. For now, only group libp2p packages as a test. We could probably create a group that matches all packages other than select few (e.g. badger, cbor, libp2p) to reduce the number of PR's (and CI runs) opened by dependabot.

dependabot: rename tendermint->cometbft, try groups feature

---

.github/dependabot.yml

Otherwise it will keep trying to "update" the libp2p as in:
- https://github.com/oasisprotocol/oasis-core/pull/5312
- https://github.com/oasisprotocol/oasis-core/pull/5315

dependabot: remove libp2p group

---

.changelog/5319.bugfix.md
go/consensus/cometbft/apps/staking/state/state.go
go/consensus/cometbft/apps/staking/state/state_test.go

This PR fixes the scenario when the reward schedule hasn't completed yet, but the common pool has been exhausted.

staking: Fix reward distribution when common pool is exhausted

---

.changelog/5320.feature.md
go/worker/keymanager/api/api.go
go/worker/keymanager/status.go

The status of the key manager was updated to include a new attribute called `active_version`, which stores the version number of the currently deployed key manager runtime. If no deployment is active, the value is set to null.
Result:
```
➜  oasis-post-upgrade oasis-node control status -a keymanager-1-internal-205141582.sock
{
"keymanager": {
"worker": {
"active_version": {
"minor": 1
},
"runtime_id": "c000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff",
}
},
}
```

go/worker/keymanager/status: Show active version of the km runtime

---

.changelog/5321.bugfix.md
go/storage/mkvs/commit.go
go/storage/mkvs/tree_test.go

[BACKPORT/22.2.x] go/storage/mkvs: Fix commit of nil entries

---

.buildkite/code.pipeline.yml

Buildkite CI jobs run in separate Docker containers that have `/tmp` mounted as `tmpfs` (in memory). The Buildkite agent is running in another container, consequently it could not find these temporary E2E test artifacts (listed under `artifact_paths:`) and upload them to the S3 bucket.
Explicitly uploading artifacts as the last step of each CI job should solve this issue.

ci: Fix uploading of temporary E2E test artifacts

---

.changelog/5332.trivial.md
go/oasis-node/cmd/config/migrate/migrate.go
go/oasis-node/cmd/config/migrate/migrate_test.go

When running the `config migrate` command, an additional P2P runtime seed address is added when migrating seed nodes.

go/oasis-node/cmd/config/migrate: Add runtime P2P seed address too

---

.changelog/5334.breaking.md
go/consensus/cometbft/apps/roothash/liveness.go
go/consensus/cometbft/apps/roothash/liveness_test.go
go/consensus/cometbft/apps/roothash/roothash.go
go/consensus/cometbft/apps/roothash/transactions.go
go/registry/api/runtime.go
go/registry/api/runtime_test.go
go/roothash/api/liveness.go
go/roothash/tests/tester.go
go/scheduler/api/api.go
runtime/src/consensus/registry.rs

The roothash application now monitors the runtime proposer liveness, which runtimes can utilize to penalize proposers with insufficient commitments.

go/consensus/roothash: Track runtime proposer liveness

---

.changelog/5326.bugfix.md
go/worker/storage/committee/node.go

Before, after every processed result, the `triggerRoundFetches` was triggered. In the pathological case, where storage fetching always failed immediately, this caused the repeated calling of `triggerRoundFetches` completely hog the CPU - since there was no time spent blocking on i/o or anything.
The clickup issue suggested implementing back-off mechanism (implemented in: https://github.com/oasisprotocol/oasis-core/pull/5341), however it seems that simply not triggering `triggerRoundFetches` on failures fixes the pathological case as well, with not many downsides.
One (minor?) downside is that in case the whole batch of fetches within a `triggerRoundFetches` fails (e.g. due to unlucky selection of p2p nodes when fetching diffs), the next `triggerRoundFetches` will be triggered only after …

storage/sync: don't immediately trigger more round fetches on failures

---

.changelog/5347.doc.md
docs/consensus/README.md

Since we moved (and renamed folders) from tendermint to cometbft in the master branch, links in the stable branch docs to the source files are now broken. Fix the links by pointing to source files in the stable git branch.
Note: Auto-generated metrics.md doc still contains invalid link.

[22.2.x] Pin tendermint links to 22.2.x branch

---

.cargo/audit.toml

This vulnerability does not affect our current use of the library.

cargo: Ignore RUSTSEC-2022-0093 until we can update ed25519-dalek to v2

---

.changelog/5352.breaking.md
go/beacon/api/api.go
go/oasis-test-runner/scenario/e2e/change_reward_schedule.go
go/oasis-test-runner/scenario/e2e/consensus_parameter_upgrade.go
go/oasis-test-runner/scenario/e2e/helpers_consensus.go
go/oasis-test-runner/scenario/e2e/scenario.go
go/staking/api/api.go
go/staking/api/api_test.go
go/staking/api/sanity_check.go

This PR adds the ability to change the reward schedule in the staking consensus parameters through a governance vote.  An additional e2e test for the rewards was also added.

go/staking: Enable changing the reward schedule

---

go/oasis-net-runner/fixtures/default.go
runtime/src/common/crypto/x25519.rs
runtime/src/consensus/tendermint/verifier/mod.rs
runtime/src/consensus/tendermint/verifier/noop.rs

* runtime: Add conversion methods for common::crypto::x25519
* go/oasis-net-runner: Skip policy on non-TEE builds
* runtime: Always use same-block verification for latest state query

Multiple updates from SDK port to 23.0

---

.buildkite/scripts/daily_txsource.sh

In case of success daily artifacts are not interesting and can be removed, otherwise the script will error out before reaching the added line.

ci: Remove daily artifacts on successful test run

---

.changelog/5375.bugfix.md
go/oasis-node/cmd/ias/proxy.go

The fix in 720b88e437b8c49c6680d8cb6e681f3524358a2e (#5290) broke generation of new certificates when none existed.

go/oasis-node/cmd/ias: Fix TLS certificate generation

---

.changelog/5359.breaking.md
go/consensus/cometbft/apps/roothash/liveness_test.go
go/consensus/cometbft/apps/roothash/messages.go
go/consensus/cometbft/apps/roothash/messages_test.go
go/consensus/cometbft/apps/roothash/state/state.go
go/consensus/cometbft/apps/roothash/state/state_test.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-node/cmd/genesis/migrate.go
go/roothash/api/api.go
go/roothash/api/sanity_check.go

This adds the ability to store past N runtime state and I/O roots in consensus state.

roothash: Store past runtime state and I/O roots in consensus state

---

.buildkite/code.pipeline.yml
.buildkite/scripts/sgx_ias_tests.sh

E2E tests are missing artifacts if they fail or timeout. This is a bit cleaner alternative to https://github.com/oasisprotocol/oasis-core/pull/5382 that also handles timeouts. It adds a trap signal that executes the artifact upload command no matter the outcome (mimicking the behavior of `artifact_paths:`).

buildkite: Fix uploading artifacts when E2E test fails or timeouts

---

.changelog/5384.doc.md
docs/README.md
docs/consensus/services/registry.md
docs/development-setup/building.md
docs/development-setup/oasis-net-runner.md

See https://github.com/oasisprotocol/docs/pull/525

docs: Consistently use part/chapter/section terms

---

go/oasis-node/cmd/genesis/migrate.go
go/oasis-test-runner/scenario/e2e/runtime/helpers_runtime.go
go/worker/common/committee/node.go

* go/oasis-node: Reduce maximum consenus layer block size in migrate
* go/oasis-test-runner: Properly wait for runtime readiness

Various minor upgrade-related fixes

---

.changelog/5390.bugfix.md
go/ias/init.go
go/ias/proxy/client/client.go
go/oasis-node/cmd/node/node.go
go/runtime/host/sgx/epid.go
go/runtime/host/sgx/sgx.go
go/runtime/host/sgx/sgx_test.go
go/runtime/registry/config.go
go/runtime/registry/registry.go
go/worker/common/worker.go

Refactors the IAS proxy client to expose separate clients for each configured IAS proxy, instead of load-balancing internally between endpoints on a per-request basis.
This is required because the attestation procedure requires three calls to the IAS endpoint (`GetSPIDInfo`, `GetSigRL`, `VerifyEvidence`) and these should contact the same endpoint.
Retries other proxies on failure.

host/sgx/epid: ensure attestation API calls hit the same proxy

---

go/roothash/api/liveness.go
go/worker/common/api/api.go
go/worker/common/committee/node.go

```
oasis-node control status -a compute-2-internal-3562597129.sock
"liveness": {
"total_rounds": 15,
"live_rounds": 15,
"finalized_proposals": 7,
"missed_proposals": 0
},
```

go/worker/common: Display additional information in the liveness status

---

.changelog/5408.bugfix.md
go/consensus/cometbft/light/p2p/p2p.go
go/consensus/cometbft/light/service.go

Alternatively could also set it to something like `<uninitialized>` in the status instead of skipping.
TODO: backport

fix consensus light client status shows empty peer IDs

---

.changelog/5421.internal.md
.github/workflows/ci-lint.yml

Keep CI alive while we do not have Towncrier fork updated 
sample issue from other repo https://github.com/oasisprotocol/oasis-wallet-web/actions/runs/6692075152/job/18180527014?pr=1747

Install setuptools to make Towncrier fork work with Python 3.12

---

go/worker/keymanager/worker.go

**Description**
When a key manager node is the sole member of the committee, it generates master and ephemeral secrets immediately rather than at a random block within an epoch. In tests, this allows us to transition to the next epoch earlier, as soon as all required secrets are generated.
**Tests**
This change can be seen in the logs, when running a single key manager node:
```
{"caller":"worker.go:1136","epoch":1,"height":30,"level":"debug","module":"worker/keymanager","msg":"block height for generating secrets selected","ts":"2023-10-31T19:34:45.56695587Z"}
{"caller":"worker.go:635","epoch":2,"generation":0,"height":22,"level":"info","module":"worker/keymanager","msg":"generating master secret","ts":"2023-10-31T19:34:46.973834368Z"}
```
Observe that the secret was generated at height …

go/worker/keymanager: Speed up secret generation in tests

---

.changelog/5423.bugfix.md
go/consensus/cometbft/full/common.go

The `Commit` function can return both a nil error and a nil result in case the given block is not available yet.

go/consensus: Do not crash on nil result from Commit

---

.changelog/5427.feature.md
go/oasis-node/cmd/common/common.go
go/oasis-node/cmd/common/config/config.go
go/oasis-node/cmd/common/grpc/grpc.go
go/oasis-node/cmd/config/migrate/migrate.go
go/oasis-node/cmd/config/migrate/migrate_test.go
go/oasis-node/node_test.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/oasis/oasis.go

common/config: move internal UNIX socket path option to config file

---

.changelog/5427.feature.md
go/oasis-node/cmd/common/common.go
go/oasis-node/cmd/common/config/config.go
go/oasis-node/cmd/common/grpc/grpc.go
go/oasis-node/cmd/config/migrate/migrate.go
go/oasis-node/cmd/config/migrate/migrate_test.go
go/oasis-node/node_test.go
go/oasis-test-runner/oasis/args.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/oasis/oasis.go

[BACKPORT/23.0.x] 5427

---

.changelog/5426.bugfix.md
go/consensus/cometbft/apps/roothash/finalization.go
go/consensus/cometbft/apps/roothash/roothash.go
go/consensus/cometbft/apps/roothash/timeout.go
go/consensus/cometbft/apps/roothash/transactions.go
go/roothash/api/api.go
go/roothash/tests/tester.go
go/runtime/host/sgx/sgx.go
go/runtime/txpool/txpool.go
go/worker/client/committee/node.go
go/worker/common/committee/group.go
go/worker/common/committee/node.go
go/worker/common/committee/p2p.go
go/worker/compute/executor/committee/discrepancy.go
go/worker/compute/executor/committee/hooks.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/p2p.go
go/worker/storage/committee/node.go

[BACKPORT/23.0.x] 5426

---

.changelog/5433.bugfix.md
go/runtime/host/multi/multi.go

[BACKPORT/23.0.x] go/runtime/host/multi: Propagate consensus sync requests to next version

---

go/oasis-node/cmd/common/grpc/grpc.go

There's no reason to check for non-empty datadir here specifically. On node init it is already checked in: https://github.com/oasisprotocol/oasis-core/blob/12e86f1a77b9d9359d88297c01db26c659d0efee/go/oasis-node/cmd/node/node.go#L473

go/oais-node/grpc: remove unneeded datadir check

---

.changelog/5438.bugfix.2.md
.changelog/5438.bugfix.md
go/runtime/host/sandbox/sandbox.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/state.go
runtime/Cargo.toml
runtime/src/dispatcher.rs
runtime/src/protocol.rs

Similar to how this is handled in the multi runtime host, we need to release the lock before calling into the runtime as otherwise this could lead to a deadlock in certain situations.

go/runtime/host/sandbox: Release lock before calling into runtime

---

.changelog/5436.feature.md
.changelog/5438.bugfix.2.md
.changelog/5438.bugfix.md
go/consensus/cometbft/api/api.go
go/consensus/cometbft/apps/roothash/roothash.go
go/consensus/cometbft/apps/roothash/transactions.go
go/consensus/cometbft/roothash/roothash.go
go/oasis-node/cmd/common/grpc/grpc.go
go/roothash/api/api.go
go/roothash/api/grpc.go
go/runtime/host/multi/multi.go
go/runtime/host/sandbox/sandbox.go
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/state.go
runtime/Cargo.toml
runtime/src/dispatcher.rs
runtime/src/protocol.rs

Backports:
* #5430 
* #5436 
* #5438

[BACKPORT/23.0.x] Multiple backports

---

.changelog/5450.bugfix.md
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/client.rs

Previously if no RPC calls were initiated by the runtime, the client controller task was never spawned which caused quote policy update requests to pile up in the command queue, eventually blocking the entire runtime from processing requests.
Since the async runtime is now available early on during initialization, we can spawn the controller in the RpcClient constructor, avoiding these problems.

runtime: Create controller in RpcClient constructor

---

.changelog/5449.feature.2.md
.changelog/5449.feature.md
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/compute.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/scenario/e2e/runtime/helpers_runtime.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/runtime/config/config.go
go/runtime/registry/config.go

Updating the key manager upgrade test to cover scenario observed on the testnet:
- A new key manager registered with RSK.
- The old key manager couldn't re-register due to its inability to decode the key manager status (new unknown field).
- The old key manager was removed from the committee after its attestation expired (enclave initialization failed).
Next steps (upgrade test):
- Post-upgrade branch will be bumped to the latest master. This will cause the upgrade test to fail (testnet scenario).
- Pre-upgrade branch will be bumped to #5432. This will solve the problem and the upgrade test will not fail anymore (mainnet scenario).

go/oasis-test-runner: Verify enclave initialization after km upgrade 

---

.buildkite/code.pipeline.yml
.buildkite/scripts/test_km_upgrade.sh
.cargo/audit.toml
.changelog/5421.internal.md
.changelog/5432.trivial.md
.github/workflows/ci-lint.yml
go/.nancy-ignore
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
runtime/src/consensus/state/keymanager.rs

Oasis Core 23.0.x introduced support for master secret rotations, adding three new fields to the key manager status. Although these fields are omitted when empty, they can still cause issues. When one of the new key managers registers, the consensus sets the runtime signing key, causing problems for the old key managers. As a result, the old key managers are not able to re-register anymore because enclave re-initialization will fail to verify whether the new policy was published in the consensus layer, due to the inability to decode the key manager status. In contrast, generation and rotation epoch do not create such problems since master secret generations are not enabled by default.
Added also generation and rotation epoch, even though these fields do not cause problems.
Backports: …

runtime/keymanager: Support new key manager status fields

---

.buildkite/code.pipeline.yml

The upgrade-test should now pass, as #5432 was merged.

buildkite: Download artifacts after runtimes are built

---

go/oasis-test-runner/scenario/e2e/runtime/keymanager_rotation_failure.go

In the key manager rotation failure test, start key managers after they deregister to ensure that both are added to the committee simultaneously. If key managers are started randomly, there is a risk that only one will be added to the committee, as the other may register in another epoch.

go/oasis-test-runner: Fix flaky key manager rotation failure test

---

.changelog/5457.feature.md
go/consensus/cometbft/apps/beacon/state/interop/interop.go
go/consensus/cometbft/apps/roothash/state/interop/interop.go
go/consensus/cometbft/apps/roothash/state/state.go
go/roothash/api/api_test.go
go/storage/mkvs/interop/fixtures/consensus_mock.go
runtime/src/common/key_format.rs
runtime/src/consensus/roothash/mod.rs
runtime/src/consensus/state/beacon.rs
runtime/src/consensus/state/keymanager.rs
runtime/src/consensus/state/registry.rs
runtime/src/consensus/state/roothash.rs
runtime/src/consensus/state/staking.rs

runtime: Add roothash round roots rust state wrappers

---

.changelog/5457.feature.md
go/consensus/cometbft/apps/beacon/state/interop/interop.go
go/consensus/cometbft/apps/roothash/state/interop/interop.go
go/consensus/cometbft/apps/roothash/state/state.go
go/roothash/api/api_test.go
go/storage/mkvs/interop/fixtures/consensus_mock.go
runtime/src/common/key_format.rs
runtime/src/consensus/roothash/mod.rs
runtime/src/consensus/state/beacon.rs
runtime/src/consensus/state/keymanager.rs
runtime/src/consensus/state/registry.rs
runtime/src/consensus/state/roothash.rs
runtime/src/consensus/state/staking.rs

https://github.com/oasisprotocol/oasis-core/pull/5457

[BACKPORT/23.0.x] 5457

---

.changelog/5456.bugfix.2.md
.changelog/5456.bugfix.md
go/p2p/discovery/bootstrap/client.go
go/p2p/host.go
go/p2p/rpc/client.go
go/p2p/rpc/nop.go

Some nodes cannot bootstrap because the seed node has too many open connections.
```
{"attempted":1,"caller":"scope.go:584","current":77,"direction":"Inbound","edge":"system","error":"system: cannot reserve inbound connection: resource limit exceeded","level":"debug","limit":77,"module":"libp2p:rcmgr","msg":"blocked connection from constraining edge","scope":"conn-9516","stat":{"NumStreamsInbound":0,"NumStreamsOutbound":0,"NumConnsInbound":77,"NumConnsOutbound":0,"NumFD":77,"Memory":0},"ts":"2023-11-16T21:09:27.902582862Z","usefd":true}
{"caller":"listener.go:99","error":"conn-9516: system: cannot reserve inbound connection: resource limit exceeded","level":"debug","module":"libp2p:upgrader","msg":"resource manager blocked accept of new connection","ts":"2023-11-16T21:09:27.902778381Z"} …
```

go/p2p: Improve seed node performance

---

.changelog/5465.internal.md
go/common/sgx/pcs/http.go
go/common/sgx/pcs/pcs.go
go/common/sgx/pcs/quote.go
go/common/sgx/pcs/tcb.go
go/ias/http/http.go
go/runtime/host/sgx/ecdsa.go

As part of work on supporting PPID PCS attestation the `GetPCKCertificateChain` http client was implemented and some minor fixes were done to the existing code.
Although the PPID PCS attestation remains unsupported (due to aesmd api limitations) it makes sense getting this in for potential future implementation.

go/sgx/pcs: GetPCKCertificateChain client and minor fixes

---

.changelog/5469.bugfix.md
go/p2p/peermgmt/backup.go

If the peer address of a seed node was added to the libp2p address book before peer manager restored backup peer addresses, its permanent TTL was replaced with the TTL for recently connected peers.
When running tests locally, the bootstrap client is created before peers are restored. So this bug was probably the reason why we observed the following error in our logs:
```
{"caller":"client.go:463","err":"failed to open stream: failed to dial: no addresses","level":"debug","method":"advertise","module":"p2p/rpc/client","msg":"failed to call method","peer_id":"12D3KooWBpWUqSb8u8AQewueVMmfK2E81pA76xd8srHyK5cLo18A","protocol":"/oasis/bootstrap/1.0.0","ts":"2023-11-23T11:17:33.064203232Z"}
```

go/p2p/peermgmt/backup: Prevent overwriting TTL when restoring peers

---

.changelog/5467.feature.md
go/consensus/cometbft/apps/roothash/query.go
go/consensus/cometbft/roothash/roothash.go
go/oasis-node/cmd/debug/txsource/workload/governance.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/oasis-test-runner/oasis/network.go
go/roothash/api/api.go
go/roothash/api/grpc.go

Also adds roothash to the txsource queries workload e2e test.

go/roothash: expose PastRoundRoots in roothash client

---

.changelog/5473.bugfix.md
go/oasis-node/cmd/config/migrate/migrate.go
go/oasis-node/cmd/config/migrate/migrate_test.go

[BACKPORT/23.0.x] go/oasis-node: Remove obsolete db section during config migration

---

.changelog/5476.bugfix.md
go/p2p/discovery/bootstrap/client.go
go/p2p/rpc/client.go
go/p2p/rpc/nop.go

[BACKPORT/23.0.x] go/p2p/discovery: Close only idle connections to seed node

---

.changelog/5480.bugfix.md
go/p2p/peermgmt/peermgr.go

Should fix the following error that occurs when discovery is started and stopped immediately if there are enough peers.
```
Nov 27 22:04:11 opf-sgx-a oasis-node[461305]: {"caller":"client.go:466","err":"failed to open stream: failed to dial: context canceled","level":"debug","method":"discover","module":"p2p/rpc/client","msg":"failed to call method","peer_id":"12D3KooWBpWUqSb8u8AQewueVMmfK2E81pA76xd8srHyK5cLo18A","protocol":"/oasis/bootstrap/1.0.0","ts":"2023-11-27T22:04:11.485476292Z"}
```

go/p2p/peermgmt: Find peers and connect only when needed

---

.changelog/5479.bugfix.md
go/consensus/cometbft/apps/governance/governance.go
go/oasis-test-runner/scenario/e2e/genesis_file.go

Non breaking since this is just an early stop in loop to avoid a no-op - adding and subtracting shares for the same vote.

governance: fix delegator-validator vote match check

---

.changelog/5481.bugfix.md
go/consensus/cometbft/light/service.go
go/oasis-test-runner/scenario/e2e/genesis_file.go

[BACKPORT/23.0.x] go/consensus/cometbft/light: Only fetch from light store for now

---

.changelog/5488.bugfix.md
go/runtime/host/protocol/connection.go

Runtime errors that are successfully decoded shouldn't have the "failed to read response" errors (these were successfully read but failed):
e.g. evm runtime error
```
failed to read response: reverted: EQs2VRAjRWeJq83vECNFZ4mrze8QI0VniavN7xAjRWeJq83v
```

rhp: don't prepend 'failed to read response' to module errors

---

.changelog/5270.internal.md
common.mk
go/Makefile

Merge after `github.com/btcsuite/btcd/chaincfg/chainhash: ambiguous import` error is resolved.

makefile: Exit with an error if go mod tidy fails

---

go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/cometbft/full/common.go
go/worker/client/committee/node.go
runtime/src/types.rs

Should be merged after Oasis Core 23.0.x with same-block consensus validation is released.
See also https://github.com/oasisprotocol/oasis-core/pull/5300.

go/worker/client/committee/node: Cleanup method Query

---

.changelog/5503.feature.md
runtime/src/common/sgx/pcs.rs

Make some of the PCS attestation helper functions public so that these can be reused (e.g. in the [attestation-tool](https://github.com/oasisprotocol/tools/tree/main/attestation-tool)). Most of the structs are already public.

runtime/sgx/pcs: Make useful attestation verification methods public

---

.changelog/5205.internal.md
go/keymanager/api/api.go
go/worker/keymanager/worker.go
runtime/src/types.rs
tests/runtimes/simple-keymanager/src/main.rs

Should be updated and merged after Oasis Core 23.0.x is released and all key managers support master secret rotation.
See also #5204.

 keymanager/src/runtime: Remove legacy version of init request

---

.changelog/5458.bugfix.md
keymanager/src/crypto/kdf.rs
keymanager/src/policy/cached.rs
runtime/src/common/sgx/seal.rs
runtime/src/consensus/tendermint/verifier/mod.rs
runtime/src/consensus/tendermint/verifier/store/state.rs

Previously, if the CPU changed between runs of the Oasis node, the error
reported was a cryptic "ciphertext is corrupted" (because the sealed SGX
secrets were invalidated).
Now we add a bit more context to make it easier for the end-user.

runtime: Improve error reporting if DeoxysII unsealing fails

---

.changelog/5515.doc.md
docs/consensus/services/registry.md
docs/consensus/transactions.md

Docusaurus 3.x broken link checker also includes checking anchors. This PR fixes those.

docs: Fix broken anchors

---

.changelog/5520.bugfix.md
go/runtime/transaction/transaction.go
go/runtime/transaction/transaction_test.go

Based on #5521 
Previously accessing the transaction artifacts tree would always use the slower read syncer interface meant for communicating with untrusted db instances. This is now short-circuited in case a local db is available.

go/runtime/transaction: Use node database directly when possible

---

.changelog/5514.feature.md
go/storage/mkvs/syncer_test.go
runtime/src/consensus/state/mod.rs
runtime/src/storage/mkvs/mod.rs
runtime/src/storage/mkvs/sync/proof.rs
runtime/src/storage/mkvs/tree/lookup.rs
runtime/src/storage/mkvs/tree/marshal.rs
runtime/src/storage/mkvs/tree/mod.rs
runtime/src/storage/mkvs/tree/overlay.rs

A bit simplified from the go version, for the use case in oasis-sdk (proofs for values in state/io mkvs).

runtime: add storage proof builder

---

.changelog/5533.internal.md
Cargo.lock

https://rustsec.org/advisories/RUSTSEC-2024-0006

rust: bump shlex to v 1.3.0

---

.changelog/5534.feature.md
go/oasis-net-runner/cmd/root.go
go/oasis-test-runner/oasis/network.go

Previously, every node started by the net runner had the default
log level of debug, while now it's possible to set it to other
levels.  The log format can also be changed.

go/oasis-net-runner: Add ability to set node log level and format

---

.changelog/5403.bugfix.md
go/worker/client/committee/node.go

Backport of #5403.
Useful mini fix for archive nodes.

[BACKPORT/22.2.x] 5403

---

.changelog/5542.bugfix.md
go/runtime/txpool/txpool.go
go/worker/compute/executor/committee/node.go

In case a transaction is rejected because it fails a re-check pass, it should also be removed from the seen cache as it may be resubmitted later when it could become valid.

go/runtime/txpool: Remove rechecked transactions from seen cache

---

go/oasis-test-runner/scenario/e2e/runtime/helpers_runtime.go
go/runtime/host/protocol/connection.go
go/runtime/registry/host.go
go/worker/common/committee/node.go
go/worker/keymanager/api/api.go
go/worker/keymanager/init.go
go/worker/keymanager/secrets.go
go/worker/keymanager/status.go
go/worker/keymanager/worker.go

Moved secrets away from the main key manager worker. Major changes:
- Registration (see `handleRuntimeHostEvent`):
- The key manager worker is responsible for updating capabilities and version on every start and update.
- The secrets worker is responsible for updating extra info on restarts (RAK changes) and when checksum changes. 
- Key manager status was changed. 
- The idea is to capture global values (e.g. `runtime_id`, `access_list`) at the top, and move secrets specific values under section `secrets` which will be latter accompanied by section `churp`.
- Status state can be found in the key manager worker status and in the secrets status (can be also changed).
- The key manager is initialized when all sub-workers are initialized (currently we have only one worker for secrets).

go/worker/keymanager: Decouple secrets from key manager worker

---

.changelog/5539.feature.md
go/keymanager/api/api.go
go/worker/keymanager/api/api.go
go/worker/keymanager/init.go
go/worker/keymanager/secrets.go
go/worker/keymanager/worker.go

Also fixed two minor bugs:
- method `Methods` should not return local methods,
- method `CallEnclave` should verify if the hosted runtime is available.

go/worker/keymanager: Authorize noise session connect calls

---

.changelog/5545.bugfix.md
go/oasis-node/cmd/node/node.go
go/worker/client/worker.go
go/worker/common/committee/registration.go
go/worker/compute/executor/committee/node.go
go/worker/registration/worker.go

Previously a node configured as an observer node would forget to register for all of its configured runtimes, causing the registration to fail.

go/worker/client: Fix observer node registration

---

.changelog/5546.feature.md
.changelog/5546.internal.1.md
.changelog/5546.internal.2.md
go/p2p/rpc/client.go
go/p2p/rpc/peermgmt.go
go/runtime/host/mock/mock.go
go/runtime/host/protocol/types.go
go/worker/keymanager/p2p/client.go
go/worker/keymanager/p2p/protocol.go
go/worker/keymanager/worker.go
keymanager/src/client/remote.rs
runtime/src/config.rs
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/client.rs
runtime/src/enclave_rpc/demux.rs
runtime/src/enclave_rpc/session.rs
runtime/src/enclave_rpc/types.rs
runtime/src/types.rs
tests/runtimes/simple-keymanager/src/main.rs
tests/runtimes/simple-keyvalue/src/main.rs

Since retry and peer selection is now handled in the runtimes having it also done outside is detrimental to latency. The runtime knows better when to actually retry and which peers to select.

go/worker/keymanager/p2p: Remove retries and sticky peers

---

.changelog/5553.internal.md
go/worker/compute/executor/committee/node.go
go/worker/compute/executor/committee/state.go

This also avoids an intermediate committed IO root which complicates the required database layout.

go/worker/compute: Simplify I/O root commit

---

.changelog/5554.internal.md
keymanager/src/runtime/methods.rs
runtime/src/dispatcher.rs
runtime/src/enclave_rpc/context.rs
runtime/src/enclave_rpc/dispatcher.rs

Removing support for outdated key manager clients, which fetched public key via noise sessions.

keymanager/runtime: Use insecure RPC requests for ephemeral public keys

---

.buildkite/code.pipeline.yml
.changelog/5558.internal.md
docker/oasis-core-ci/Dockerfile

Also remove the `soft_fail` in CI, since this seems to be stable now. I briefly checked CI history and didn't notice any failed coverage runs. At the time `soft_fail` was enabled (version 0.8) the job failed almost always.

docker: Bump cargo-tarpaulin to 0.27.3

---

.changelog/5531.feature.md
go/storage/mkvs/checkpoint/chunk.go
go/storage/mkvs/checkpoint/file.go
go/storage/mkvs/iterator.go
go/storage/mkvs/lookup.go
go/storage/mkvs/node/node.go
go/storage/mkvs/node/node_test.go
go/storage/mkvs/prefetch.go
go/storage/mkvs/syncer/proof.go
go/storage/mkvs/syncer/proof_test.go
go/storage/mkvs/syncer/syncer.go
go/storage/mkvs/syncer_test.go
runtime/src/storage/mkvs/sync/proof.rs
runtime/src/storage/mkvs/tree/lookup.rs
runtime/src/storage/mkvs/tree/marshal.rs

Internal MKVS nodes always implicitly contained the full leaf node in the proof. Instead it should be added as a regular child node in the proof. That way an unneded large value (e.g. value in a leaf node of an internal node on the path to the actual node we're proving) won't inflate the proofs size.
Change is backwards compatible, existing proofs are unmarshaled as V0.
TODO:

mkvs/proofs: Remove implicit internal leaf nodes from proofs

---

.changelog/5561.internal.md
keymanager/src/crypto/kdf.rs
runtime/src/storage/mod.rs

The untrusted in-memory key/value storage is now accessible to all tests.

runtime/src/storage: Move untrusted in-memory key/value storage

---

.changelog/5566.bugfix.md
go/governance/api/api.go

Previously, when creating a governance proposal, the writer would output unchanged parameters and show them as nil value.

governance: Remove unchanged proposal parameters

---

.changelog/5577.bugfix.md
go/runtime/host/protocol/connection.go

This is especially noticable after #5569 which added an early node identity query.

go/runtime/host: Wait for readiness instead of failing immediately

---

.changelog/5588.feature.md
go/go.mod
go/go.sum
go/oasis-test-runner/scenario/e2e/upgrade.go
go/upgrade/migrations/consensus_240.go

This is needed as DCAP quotes are larger and nodes running multiple confidential runtimes may otherwise exceed the max transaction size.

go/upgrade: Adjust MaxTxSize and MaxBlockSize in consensus240 handler

---

.changelog/5595.feature.md
go/worker/storage/committee/node.go
go/worker/storage/worker.go

This should speed up storage sync in case of nodes that have multiple runtimes configured.

go/worker/storage: Make fetch pool per-runtime

---

.changelog/5622.bugfix.md
go/consensus/cometbft/full/archive.go
go/oasis-test-runner/scenario/e2e/runtime/archive_api.go
go/runtime/history/history.go

TODO: Also backport to 22.2.x
Fix runtime queries on archive nodes. Also adds a runtime query to the archive_api E2E test.
Runtime queries are failing on archive due to the `CurrentBlock` not being set in the common node.

go/archive: fix runtime queries on archive nodes

---

.changelog/5622.bugfix.md
go/consensus/tendermint/full/archive.go
go/oasis-node/cmd/storage/storage.go
go/oasis-test-runner/scenario/e2e/runtime/archive_api.go
go/runtime/history/history.go
go/runtime/history/history_test.go
go/runtime/registry/registry.go

Backports https://github.com/oasisprotocol/oasis-core/pull/5622
@vitrvvivs also confirmed this fixes the issue on the archive node.
Note:
- would probably need some backports for CI to pass, not sure if worth it since 22.2.x version only remains relevant for archive nodes
Local archive test run:
> level=info ts=2024-04-05T11:58:04.55323219Z caller=root.go:464 module=test-runner msg="passed scenario" scenario=e2e/runtime/archive-api run_id=0

[BACKPORT/22.2.x] go/archive: fix runtime queries on archive node

---

runtime/src/consensus/registry.rs

This can be useful when only checking the endorsement itself is important as the content will be verified separately.

runtime: Add EndorsedCapabilityTEE::verify_endorsement

---

.buildkite/benchmarks.pipeline.yml
.buildkite/code.pipeline.yml
.buildkite/go/test_and_coverage.sh
.buildkite/longtests.pipeline.yml
.buildkite/rust/build_generic.sh
.buildkite/rust/build_runtime.sh
.buildkite/rust/test_generic.sh
.buildkite/scripts/download_e2e_test_artifacts.sh
.buildkite/scripts/test_e2e.sh
.buildkite/scripts/test_upgrade.sh
.changelog/5641.internal.md
Makefile
docs/development-setup/deploying-a-runtime.md
docs/development-setup/oasis-net-runner.md
go/oasis-test-runner/rust/builder.go

Running SGX tests with binaries built in debug mode can be extremely slow, so build everything in release mode. This should also speed up E2E tests.

Build runtime binaries in release mode

---

.changelog/5648.feature.md
go/consensus/cometbft/staking/staking.go
go/oasis-node/cmd/stake/stake.go
go/staking/api/api.go
go/staking/api/grpc.go

This unifies handling of the two remaining attributes so everything is consistently read from state, in a backwards compatible manner.

go/staking: Read token information from state when available

---

.changelog/5630.bugfix.md
Cargo.lock
go/runtime/txpool/txpool.go
go/worker/common/committee/node.go
tests/runtimes/simple-rofl/Cargo.toml

If the node hasn't finished syncing, `checkTxBatch` previously caused the runtime to be aborted, even though it wasn't the runtime's fault.
Now the checks are retried after the node is finished syncing.

go/runtime/txpool: Don't abort runtime if node is not synced yet

---

go/oasis-node/cmd/debug/byzantine/byzantine.go

This fixes a bug where the Byzantine node crashes during E2E tests due to consensus divergence.

go/oasis-node/cmd/debug/byzantine: Correctly configure PCS

---

.changelog/5654.internal.md
.github/dependabot.yml

Let's see how this works.  It should look something like this: https://github.com/fortanix/rust-sgx/pull/581

.github/dependabot: group rust dependency updates

---

.github/dependabot.yml

Wanted to keep empty `exclude-patterns` and `ignore` in the config, so that one can clearly see where these should be added if needed (e.g. for dependencies that will be harder to update/will require more changes and should be updated in separate PRs).
But:
> The property '#/updates/2/groups/rust/exclude-patterns' did not contain a minimum number of items 1

.github/dependabot: fix empty excludes

---

go/consensus/cometbft/apps/keymanager/secrets/txs.go

Removing changes made to `secrets/txs.go` in https://github.com/oasisprotocol/oasis-core/pull/5628/commits/7d649f96dea8604403915995d15c1416e46e010e.

go/consensus/cometbft/apps/keymanager/secrets: Undo fix gas charge

---

.changelog/5686.bugfix.md
keymanager/src/runtime/secrets.rs

This avoids an issue where a key manager node that is slightly behind would return an error during an epoch transition.

keymanager: Allow one epoch in the future during validation

---

.changelog/5703.bugfix.md
keymanager/src/runtime/secrets.rs

This avoids issues where key managers get out of sync during operation and start rejecting otherwise valid requests. It should still be safe as especially since all new runtimes now perform freshness checks.

keymanager: Increase MAX_FRESH_HEIGHT_AGE

---

.changelog/5699.feature.md
keymanager/src/churp/kdf.rs
keymanager/src/churp/mod.rs

```rust
let shared_secret; // x-coordinate of a point on a curve
let salt; // runtime ID || churp ID || key ID
let state_key = Kdf::state_key(shared_secret, salt);
```

keymanager/src/churp: Implement key derivation function

---

.changelog/5708.bugfix.md
go/registry/api/api.go

The body of the ProveFreshness tx [seems to be outdated](https://github.com/oasisprotocol/oasis-core/blob/master/go/consensus/cometbft/apps/registry/registry.go#L138), this PR switches the type to the [32]byte blob. 
Nexus currently uses a [workaround](https://github.com/oasisprotocol/nexus/blob/main/analyzer/consensus/convert_tx.go#L104) that deserializes the tx body into a custom type.

registry: update proveFreshness tx body

---

.changelog/5707.feature.md
go/runtime/bundle/bundle.go
go/runtime/bundle/bundle_test.go
go/runtime/bundle/component/component.go
go/runtime/bundle/manifest.go
go/runtime/host/composite/composite.go
go/runtime/host/host.go
go/runtime/host/multi/multi.go
go/runtime/host/sandbox/sandbox.go
go/runtime/host/sgx/sgx.go
go/runtime/registry/config.go
go/runtime/registry/host.go
go/runtime/registry/host_rofl.go
runtime/src/attestation.rs
runtime/src/dispatcher.rs

Previously each bundle that contained one or more ROFL components also needed to contain the exact version of the RONL component it was attaching to.
This is somewhat awkward to use so this adds support for detached ROFL components where the bundle only contains the ROFL and oasis-node then automatically gets the appropriate RONL component from another bundle.

Support detached ROFL components

---

.changelog/5725.bugfix.md
go/common/node/node.go
go/worker/registration/worker.go
go/worker/storage/worker.go

Since the storage node is always coupled with another role, make sure to not add any particular role as otherwise this could cause observer nodes to also register as compute nodes and then misbehave.

go/worker/storage: Do not add any particular roles

---

.changelog/5760.internal.md
go/consensus/cometbft/features/features.go
go/consensus/genesis/genesis.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/network.go

Useful for enabling new consensus-breaking features with upcoming releases. A feature is enabled if the latest consensus-breaking software version is not lower than the version in which the feature is to be enabled.
Example of usage:
```go
if consParams.SoftwareVersion != nil && consParams.SoftwareVersion.ToU64() >= version.MustFromString("24.2").ToU64() {
// Enable feature.
} else {
// Disable feature and behave like version 24.1.
}
```

go/consensus: Add the latest consensus-breaking software version

---

.changelog/5772.internal.md
docker/oasis-core-dev/Dockerfile

Forgot to bump the toolchain version in the Docker image in #5770.

docker: Bump Rust toolchain to 2024-07-09

---

.changelog/5785.bugfix.md
.changelog/5785.feature.md
go/runtime/bundle/bundle.go
go/runtime/config/config_test.go
go/runtime/registry/config.go

* go/runtime: Automatically enable all configured detached components
* go/runtime/bundle: Use manifest hash at bundle load time

Fix handling of detached bundles

---

.changelog/5784.trivial.md
go/keymanager/churp/rpc.go
go/worker/keymanager/churp.go
keymanager/src/churp/handler.rs
keymanager/src/churp/methods.rs
keymanager/src/churp/state.rs
keymanager/src/churp/storage.rs

Also refactored code to:
- better handle different churp instances (added new trait `Handler`),
- load shares and polynomials only on startup (and not on every request if the share/polynomial is missing),
- verify loaded dealer before returning a response with bivariate share.

keymanager/src/churp: Serve key shares to lagging clients

---

go/runtime/host/protocol/types.go

Merge after #5305 is deployed.

go/runtime: Remove same block consensus validation feature

---

go/runtime/host/protocol/types.go

Merge after https://github.com/oasisprotocol/oasis-core/pull/5205 and https://github.com/oasisprotocol/keymanager-paratime/pull/15 are deployed.

go/runtime: Remove km master secret rotation feature

---

.changelog/5800.internal.md
Cargo.lock
go/common/crypto/signature/signer.go
keymanager/src/churp/storage.rs
secret-sharing/Cargo.toml
secret-sharing/src/churp/dealer.rs
secret-sharing/src/churp/shareholder.rs
secret-sharing/src/churp/switch.rs
secret-sharing/src/kdc/mod.rs
secret-sharing/src/poly/bivariate.rs
secret-sharing/src/poly/lagrange/naive.rs
secret-sharing/src/poly/lagrange/optimized.rs
secret-sharing/src/poly/scalar.rs
secret-sharing/src/poly/univariate.rs
secret-sharing/src/shamir/dealer.rs
secret-sharing/src/shamir/player.rs
secret-sharing/src/vss/matrix.rs
secret-sharing/src/vss/vector.rs

Methods and functions in `churp` and `shamir` schemes are constant time only when dealing with sensitive data, as other operations (e.g. validation of input parameters) cannot reveal sensitive content.

secret-sharing: Make sensitive functions constant time

---

.buildkite/code.pipeline.yml
.changelog/5836.internal.md

Tested `debug_assert` in https://buildkite.com/oasisprotocol/oasis-core-ci/builds/14000.

buildkite: Enable debug assertions in runtimes

---

secret-sharing/Cargo.toml

The default features, such as ecdh, ecdsa, pem, and others, are not needed.

secret-sharing: Exclude default subtle and p384 features

---

.changelog/5790.trivial.md
go/consensus/cometbft/apps/keymanager/churp/ext.go
go/consensus/cometbft/apps/keymanager/churp/genesis.go
go/consensus/cometbft/apps/keymanager/churp/genesis_test.go
go/consensus/cometbft/apps/keymanager/churp/query.go
go/consensus/cometbft/apps/keymanager/churp/state/state.go
go/consensus/cometbft/apps/keymanager/churp/state/state_test.go
go/consensus/cometbft/apps/keymanager/common/genesis.go
go/consensus/cometbft/apps/keymanager/secrets/genesis.go
go/consensus/cometbft/apps/keymanager/secrets/query.go
go/consensus/cometbft/keymanager/churp/client.go
go/consensus/cometbft/keymanager/keymanager.go
go/genesis/genesis_test.go
go/keymanager/api/api.go
go/keymanager/churp/backend.go
go/keymanager/secrets/api.go
go/oasis-node/cmd/debug/dumpdb/dumpdb.go
go/oasis-node/cmd/genesis/genesis.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_churp.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_churp_many.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_churp_txs.go
go/oasis-test-runner/scenario/e2e/upgrade.go
go/registry/api/api.go
go/upgrade/migrations/consensus_240.go

go/registry: Deprecate enable key manager CHURP flag

---

.changelog/5838.feature.md
go/runtime/bundle/manifest.go
go/runtime/registry/config.go

go/runtime: Support bundle components without ELF binary

---

keymanager/src/churp/handler.rs
secret-sharing/Cargo.toml
secret-sharing/src/churp/handoff.rs
secret-sharing/src/churp/switch.rs

Trying to simply the code by removing `if` conditions for handoff kind in `Handoff` methods.

secret-sharing/src/churp: Separate handoff kinds

---

.changelog/5852.internal.md
keymanager/src/policy/signers.rs

Useful after #5851 to allow configuring the set of mock trusted signers used by net runner.

keymanager: Add mock trusted signers for debug mock SGX builds

---

.changelog/5865.internal.md
keymanager/src/client/interface.rs
keymanager/src/client/mock.rs
keymanager/src/client/remote.rs

keymanager: Expose runtime ID and RSK in the key manager client

---

.changelog/5863.internal.md
keymanager/src/churp/handler.rs
keymanager/src/client/interface.rs
keymanager/src/client/mock.rs
keymanager/src/client/remote.rs
keymanager/src/runtime/secrets.rs
keymanager/src/secrets/provider.rs
runtime/src/enclave_rpc/client.rs
tests/runtimes/simple-keyvalue/src/main.rs

Peer feedback, which should not work anymore when fetching key shares, will be fixed in another PR.

keymanager/src/client: Fetch churp key shares concurrently

---

.changelog/5867.internal.md
go/runtime/host/protocol/types.go
go/worker/keymanager/worker.go
runtime/src/types.rs

I think that this can be removed.

runtime: Remove obsolete feature rpc_peer_id

---

.changelog/5872.feature.md
go/common/cache/lru/lru.go
go/common/cache/lru/lru_test.go
go/consensus/cometbft/beacon/beacon.go
go/p2p/rpc/client.go
go/runtime/host/protocol/types.go
go/runtime/keymanager/api/api.go
go/runtime/registry/host.go
go/runtime/txpool/txpool.go
go/worker/common/committee/keymanager.go
go/worker/common/committee/node.go
runtime/src/enclave_rpc/client.rs
runtime/src/enclave_rpc/transport.rs
runtime/src/types.rs

Example logs:
```json
// First client.
{"caller":"keymanager.go:242","level":"debug","module":"worker/keymanager","msg":"received peer feedback from runtime","peer_feedback":"failure","request_id":11876174929579737116,"ts":"2024-09-30T11:13:55.971535462Z","valid":true}
{"caller":"keymanager.go:242","level":"debug","module":"worker/keymanager","msg":"received peer feedback from runtime","peer_feedback":"success","request_id":11876174929579737117,"ts":"2024-09-30T11:13:55.972354408Z","valid":true}
// No peers found error, so peer feedback is never stored.
{"caller":"keymanager.go:242","level":"debug","module":"worker/keymanager","msg":"received peer feedback from runtime","peer_feedback":"failure","request_id":11876174929579737118,"ts":"2024-09-30T11:13:55.972777804Z","valid":false}
// …
```

runtime/src/enclave_rpc: Support peer feedback for concurrent requests

---

.changelog/5878.feature.md
go/common/grpc/grpc.go
go/common/grpc/grpc_test.go
go/oasis-node/cmd/common/grpc/grpc.go

This usecase came up in https://github.com/oasisprotocol/oasis-web3-gateway/pull/626 where we want to expose the node from docker via a port (since this works better cross-platform than exposing the socket via a volume).
It was requested that both `oasis-node` and `oasis-cli` work with the exposed endpoint, for better developer experience.
--- 
The added `CfgInsecureLoopback` might be a bit over the top, I'm not sure if we should keep it or not. We could always drop TLS for loopback address. But this could break any existing setup if someone did setup proper TLS with trusted certs on his local setup, so that's why I added it.
The `IsLocalAddress` is made public so that it can be reused in `oasis-sdk` and we won't need to duplicate the not most intuitive gRPC address parsing logic …

go/common/grpc: allow non-tls connections to loopback addresses

---

.changelog/5876.cfg.md
.changelog/5876.feature.md
go/oasis-test-runner/oasis/oasis.go
go/storage/database/database.go
go/storage/database/database_test.go
go/worker/storage/config/config.go

Fixes #5875 
The new default storage backend is "auto" which attempts to detect the storage backend that should be used based on existing data directories. When none exist, "pathbadger" is used. When multiple exist, the most recently modified one is used.
This should make newly deployed nodes default to pathbadger.

go/storage: Add automatic storage backend detection

---

.changelog/5917.bugfix.md
runtime/src/enclave_rpc/client.rs

The graceful shutdown of active sessions was removed, as they should not be closed when the RPC client is dropped. Instead, we should explicitly invoke the appropriate functions.
Reasons:
- Blocking is not acceptable because drops should be fast, and sessions should be closed asynchronously.
- Spawning a new task is also not acceptable since drops should (mostly) be deterministic. There could be issues if the code following an implicit drop call relies on sessions being closed (not a problem yet).
- If the Tokio runtime stops and the async tasks spawned during the drop haven't completed, they will be destroyed without being executed.

runtime/src/enclave_rpc/client: Fix panic on drop in async context

---

.changelog/5931.feature.md
go/runtime/bundle/bundle.go
go/runtime/bundle/bundle_test.go
go/runtime/bundle/manifest.go

go/runtime/bundle: Add expected enclave identity to manifest

---

Cargo.lock
go/common/badger/helpers.go
go/common/persistent/persistent.go
go/config/config.go
go/consensus/cometbft/db/badger/badger.go
go/consensus/cometbft/full/full.go
go/oasis-node/cmd/node/node.go
go/oasis-node/cmd/storage/storage.go
go/oasis-test-runner/oasis/oasis.go
go/p2p/peermgmt/registry.go
go/registry/api/runtime.go
go/runtime/bundle/bundle.go
go/runtime/bundle/bundle_test.go
go/runtime/config/config.go
go/runtime/history/db.go
go/runtime/history/history.go
go/runtime/history/history_test.go
go/runtime/history/prune.go
go/runtime/host/composite/composite.go
go/runtime/host/sandbox/sandbox_test.go
go/runtime/host/sgx/sgx_test.go
go/runtime/localstorage/localstorage.go
go/runtime/registry/config.go
go/runtime/registry/registry.go
go/storage/mkvs/db/badger/badger.go
go/storage/mkvs/db/pathbadger/pathbadger.go
go/worker/common/worker.go
go/worker/registration/worker.go
tests/runtimes/simple-rofl/Cargo.toml

Laying grounds for the main part of the hot-reloading issue and adding minor changes to the code that were found along the way.

go: Refactor and cleanup code

---

Cargo.lock
go/worker/keymanager/worker.go
tests/runtimes/simple-rofl-tdx/Cargo.lock

Forcing `url` upgrade to 2.5.4 and waiting for new releases of `tendermint-rpc` and `tendermint-config`.
```
Crate:     idna
ID:        RUSTSEC-2024-0421
idna 0.5.0
└── url 2.5.2
├── tendermint-rpc 0.39.1
└── tendermint-config 0.39.1
```
Forcing also `hashbrown` upgrade to 0.15.1 and waiting for new version of `lru`.
```
cargo update -p url
cargo update -p hashbrown@0.15.2
```

go/worker/keymanager: Generate secrets immediately with mock beacon

---

go/consensus/api/submission.go

In tests, some key managers occasionally register later than expected. This occurs because the VRFProve transaction check increments the nonce in the cache but fails as the node cannot be found in the registry. Subsequently, the RegisterNode transaction also fails due to an invalid nonce, as VRFProve transaction did not incremented the nonce in the consensus. Although the nonce is reset afterwards, this dance can persist indefinitely. 
An alternative would be to somehow distinguish check-only failures from normal failures.
The impact of these changes on performance has not been tested.

go/consensus/api/submission: Always clear nonce on error

---

.buildkite/code.pipeline.yml
.changelog/5975.cfg.md
.changelog/5975.internal.md
common.mk
go/oasis-test-runner/oasis/network.go
go/runtime/bundle/component.go
go/runtime/bundle/registry.go
go/runtime/config/config.go
go/runtime/host/composite/composite.go
go/runtime/host/sgx/sgx.go
go/runtime/host/tdx/qemu.go
go/runtime/registry/config.go
go/runtime/registry/registry.go
go/worker/keymanager/secrets.go

Trying to remove the bundle registry dependency from the `createProvisioner` function, as nodes should generally not have any bundles stored locally upon their initial startup.
These changes also decouple the creation of provisioners from TEE selection. Previously, only client nodes could choose the TEE in which a component would run. Now, node operators can specify the TEE for each component, provided the component supports the chosen TEE. If no TEE is specified, it is automatically selected, with TDX and SGX taking precedence over ELF.
How to configure nonSGX client:
```yaml
runtime:
paths: # Can be replaced with bundle repository url.
- {{ runtime_orc_path }} 
runtimes:
- id: {{ runtime_id }}
components:
- id: ronl
tee: none # Do not run in SGX or TDX!
```
How to configure SGX client: …

go/runtime/registry: Simplify creation of provisioners

---

.changelog/5962.cfg.md
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
go/runtime/bundle/discovery.go
go/runtime/config/config.go

Renaming also repository to registry, as the URL doesn't necessary point to a repository.

go/runtime/config: Add default bundle registry

---

.changelog/5995.internal.md
go/runtime/bundle/component.go

Currently not used anywhere yet, but will be used later on. Adding it in early so that the runtime build side (e.g. Oasis CLI) can use it.

go/runtime/bundle: Add some more metadata to manifest

---

.changelog/6005.feature.md
go/oasis-test-runner/oasis/runtime.go
go/oasis-test-runner/scenario/e2e/runtime/rofl.go
go/runtime/bundle/bundle_test.go
go/runtime/bundle/component.go
go/runtime/bundle/component_test.go
go/runtime/bundle/registry_test.go
go/runtime/host/tdx/qemu.go
go/runtime/registry/config.go
go/runtime/registry/registry.go

go/runtime/host/tdx: Add support for persistent image overlay

---

go/oasis-node/cmd/node/node_control.go
go/runtime/bundle/bundle.go
go/runtime/bundle/manifest.go
go/runtime/bundle/manifest_test.go

The current solution for handling legacy manifest version updated the RONL component version after the bundle was opened. This was not the best solution as that changed the manifest hash. Furthermore, if the manager read the manifest directly from the exploded data directory, the RONL component version did't not change, causing problems if the node was restarted with cached bundles.

go/runtime/bundle/manifest: Fix legacy manifest version

---

.changelog/5737.feature.md
go/common/version/version.go
go/common/version/version_test.go
go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
go/runtime/bundle/manager.go
go/runtime/bundle/manager_test.go
go/runtime/bundle/manifest.go
go/runtime/bundle/registry.go
go/runtime/bundle/registry_test.go
go/runtime/registry/registry.go

* #5737 
* ~Furthermore, we fix the current bug (`master`) of not being able to remove runtime from the configuration (see https://github.com/oasisprotocol/oasis-core/pull/5976#issuecomment-2587690157)~ -> done as part of https://github.com/oasisprotocol/oasis-core/pull/6003
Save on disk usage/ease the maintenance.
1. ~Regular and detached exploded bundles no longer present in the config, are removed during discovery startup. This way we are not blocking initialization~ -> Done here https://github.com/oasisprotocol/oasis-core/pull/6003
2. Regular bundles with version lower then active are removed by watching new epochs and checking if bundle registry has bundles lower than the active version for the current epoch.
```bash
.buildkite/scripts/test_e2e.sh --scenario …
```

Periodically clean up cached bundles directory 

---

go/runtime/bundle/bundle.go
go/runtime/bundle/bundle_test.go
go/runtime/bundle/manager.go
go/runtime/host/sandbox/provisioner_test.go
go/runtime/host/sgx/provisioner_test.go

Maybe this will be useful in the future. I’m not sure yet and don’t want to throw away the changes.

go/runtime/bundle: Explode bundle into an arbitrary directory

---

.changelog/6038.trivial.md
go/go.mod
go/go.sum
go/runtime/host/sgx/common/common.go

go/runtime/host/sgx: Retry re-attestation faster on failure

---

go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
go/runtime/registry/registry.go

go/runtime: Disable hot-loading of runtime bundles for key managers

---

go/runtime/bundle/manager.go

When upgrading from earlier versions the exploded bundle directory may contain non-bundle subdirectories which should not cause the loader to fail.

go/runtime/bundle: Don't abort when some manifests cannot be loaded

---

.changelog/6040.bugfix.md
go/beacon/tests/tester.go
go/consensus/cometbft/abci/state.go
go/consensus/cometbft/api/state.go
go/consensus/cometbft/apps/staking/slashing.go

go/consensus/cometbft: Fail ImmutableState creation if version is missing

---

.changelog/6058.bugfix.md
runtime/src/transaction/dispatcher.rs

Fixing `Box::<NoopDispatcher>::default().is_supported()` which returned `true` for ROFL apps.

runtime/src/transaction: Fix is_supported call to wrapped dispatcher

---

.changelog/6060.bugfix.md
go/oasis-test-runner/oasis/validator.go
go/runtime/host/sandbox/process/bwrap.go
go/runtime/registry/config.go
go/worker/keymanager/worker.go

Ensures validator nodes without configured runtimes and with the default runtime provisioner set to sandbox do not fail to start if bubblewrap is not installed.

go/runtime/host/sandbox: Verify sandbox binary when needed

---

.changelog/6066.bugfix.md
go/runtime/host/sandbox/process/naked.go

go/runtime/host: Ensure processes get cleaned up on node termination

---

.changelog/4539.feature.md
go/consensus/api/api.go
go/consensus/api/api_test.go
go/consensus/api/submission.go
go/consensus/api/transaction/transaction.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/common.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/full/light.go
go/consensus/tendermint/full/services.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/args.go
go/upgrade/upgrade.go
go/worker/storage/worker.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/5978
Manual backport of: https://github.com/oasisprotocol/oasis-core/pull/4571
It doesn't ensure runtime works as well, since we do not need runtime archive support for that network (there were no runtimes).
Testing:

[BACKPORT/20.10.x] Add consensus archive mode support

---

.changelog/4539.feature.md
go/consensus/api/api.go
go/consensus/api/api_test.go
go/consensus/api/submission.go
go/consensus/api/transaction/transaction.go
go/consensus/tendermint/api/api.go
go/consensus/tendermint/full/archive.go
go/consensus/tendermint/full/common.go
go/consensus/tendermint/full/full.go
go/consensus/tendermint/full/light.go
go/consensus/tendermint/full/services.go
go/consensus/tendermint/tendermint.go
go/oasis-node/cmd/node/node.go
go/oasis-test-runner/oasis/args.go
go/upgrade/upgrade.go
go/worker/storage/worker.go

Fixes: https://github.com/oasisprotocol/oasis-core/issues/5978
Manual backport of: https://github.com/oasisprotocol/oasis-core/pull/4571
It doesn't ensure runtime archive works as well, since we do not need runtime archive support for that network.
Testing:

[BACKPORT/20.12.x] Add consensus archive mode support

---

go/oasis-node/cmd/node/node.go
go/oasis-node/cmd/node/node_control.go
go/runtime/host/provisioner/provisioner.go
go/runtime/registry/config.go
go/runtime/registry/handler.go
go/runtime/registry/host.go
go/runtime/registry/registry.go
go/worker/common/committee/node.go
go/worker/common/committee/runtime_host.go
go/worker/common/worker.go
go/worker/keymanager/handler.go
go/worker/keymanager/init.go
go/worker/keymanager/worker.go

Refactored committee node:
- Removed `RuntimeHostHandlerFactory` as it is more cleaner to pass parameters to the constructor instead of passing a factory.
- Removed handler and notifier from the committee node, so that we can easier stop/start the notifier.
- Removed host provisioner (which is now generalized to provision any runtime) from the runtime registry, as it doesn't belong there.
- It is now globally avaliable to common worker which provisions runtimes and to the key manager worker which provisions key manager runtime (maybe we need to move up also handler and notifier).
Related to:
- #6014

go/runtime/registry: Remove runtime host handler factory

---

.changelog/6077.bugfix.md
go/runtime/host/tdx/qemu.go

go/runtime/host/tdx: Resize overlay image if needed

---

go/consensus/cometbft/roothash/roothash.go

Replaying the latest block with a hook was not ideal because if the broker still had blocks in the queue while adding a new subscription, it could result in an unexpected block order and potentially cause the last block to be replayed twice. 
Solution with monotonically increasing order solved this problem, but there is a simpler one where we use broker's option to publish the last block on subscription.

go/consensus/cometbft/roothash: Publish the last block on subscribe 

---

.changelog/6069.feature.md
go/consensus/cometbft/roothash/roothash.go
go/roothash/api/history.go
go/runtime/history/db.go
go/runtime/history/history.go
go/runtime/history/history_test.go

Closes #6069 
During history reindex, we now batch `1000` writes at the same time.
As from the [benchmarks](https://docs.google.com/document/d/1Lq-Qe6jrrLUSKIkLLsIGOrfb31Ivi-hZKP0wAC50V1E/edit?tab=t.0#heading=h.rg3qm3z5hci9), this already gives 2-3x performance gain for the single threaded program.
Given its simplicity and the fact, that it will be required by all possible solutions, this is a natural start.

go/roothash: Batch history reindex writes 

---

go/roothash/api/api.go
go/roothash/api/history.go
go/runtime/history/history.go

The latest round and the invalid round now have unique values, allowing us to distinguish between the two.

go/roothash/api: Change invalid round value

---

go/consensus/cometbft/roothash/roothash.go
go/roothash/api/history.go
go/runtime/history/db.go
go/runtime/history/history.go
go/runtime/history/history_test.go
go/runtime/history/prune.go
go/worker/compute/executor/committee/prune.go

`RoundResults` are now on-chain so there is no need to reindex them anymore. See [thread](https://oasisprotocol.slack.com/archives/C075WCGDNJ0/p1741098222045169) for more context.
Related to #5738, I have confirmed this increases our history reindex ~30%, which is in line with what [existing benchmarks](https://docs.google.com/document/d/1Lq-Qe6jrrLUSKIkLLsIGOrfb31Ivi-hZKP0wAC50V1E/edit?tab=t.0#heading=h.2fkeolp01q4u) predict.

 go/roothash: Remove RoundResults from history reindex

---

.cargo/audit.toml
.changelog/6104.internal.md
Cargo.lock

```
Crate:     protobuf
Version:   2.28.0
Title:     Crash due to uncontrolled recursion in protobuf crate
Date:      2024-12-12
ID:        RUSTSEC-2024-0437
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0437
Solution:  No fixed upgrade is available!
Dependency tree:
protobuf 2.28.0
├── protoc-rust 2.28.0
│   └── aesm-client 0.6.0
│       └── oasis-core-runtime-loader 0.0.0
├── protobuf-codegen 2.28.0
│   └── protoc-rust 2.28.0
└── aesm-client 0.6.0
```
```
Crate:     ring
Version:   0.17.8
Title:     Some AES functions may panic when overflow checking is enabled.
Date:      2025-03-06
ID:        RUSTSEC-2025-0009
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0009
Solution:  Upgrade to >=0.17.12
Dependency tree:
ring 0.17.8
└── rustls-webpki 0.102.8
├── …
```

rust: Bump ring to 0.17.13

---

.buildkite/rust/build_runtime.sh
.buildkite/rust/common.sh
docs/development-setup/building.md
docs/development-setup/prerequisites.md

I was going through the development environment setup instructions again when setting up my new workstation and noticed that we use unnecessary quotes when setting up the Oasis environment variables (`export OASIS_...="1"`) -- there is no need to use quotes there, since we're setting the variable to a single word.

docs: Fix environment variable quoting

---

go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/cometbft/api/api.go
go/consensus/cometbft/beacon/beacon.go
go/consensus/cometbft/full/common.go
go/consensus/cometbft/full/full.go
go/consensus/cometbft/full/services.go
go/consensus/cometbft/light/service.go
go/consensus/cometbft/roothash/roothash.go
go/oasis-node/cmd/common/background/service_manager.go
go/oasis-node/cmd/storage/storage.go
go/oasis-test-runner/scenario/e2e/runtime/storage_early_state_sync.go
go/roothash/api/history.go
go/runtime/history/db.go
go/runtime/history/history.go
go/runtime/history/history_test.go
go/runtime/history/indexer.go
go/runtime/registry/registry.go
go/worker/client/committee/node.go
go/worker/common/committee/node.go
go/worker/common/worker.go
go/worker/storage/committee/node.go

The runtime history should be built on top of the roothash service, using observed blocks for block reindexing and round syncing. The roothash service should broadcast blocks as soon as they are finalized in consensus, whereas the block history should broadcast blocks only after they have been reindexed or synced.
Now, we have 3 ways to observe runtime blocks:
1. Method `consensus.RootHash().WatchBlocks` returns blocks immediately once they are finalized in the consensus.
2. Method `rt.History().WatchCommittedBlocks` returns blocks immediately once they are committed to local storage.
3. Method `rt.History().WatchBlocks` returns blocks immediately once they are committed and synced to local storage.
Comparing methods to previous solution:
- Previous 1 == Current 2

 go/consensus/cometbft/roothash: Remove history from roothash service

---

.changelog/6115.cfg.md
go/consensus/api/api.go
go/consensus/cometbft/config/config.go
go/consensus/cometbft/full/common.go
go/consensus/cometbft/full/full.go
go/consensus/cometbft/light/service.go
go/consensus/p2p/light/server.go
go/oasis-test-runner/oasis/fixture.go
go/oasis-test-runner/oasis/keymanager.go
go/oasis-test-runner/oasis/network.go
go/oasis-test-runner/oasis/oasis.go
go/oasis-test-runner/scenario/e2e/consensus_state_sync.go
go/oasis-test-runner/scenario/e2e/runtime/storage_early_state_sync.go
go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go

The consensus light client is currently used only for consensus state synchronization. However, in the future, stateless clients will also rely on it. Therefore, we have moved the trust root configuration to a dedicated section.

go/consensus/cometbft/config: Move light client config

---

.changelog/5998.feature.md
go/control/api/api.go
go/oasis-node/cmd/node/node_control.go
go/runtime/history/indexer.go
go/runtime/registry/registry.go

Show block history indexer status, also closes #5998.
Rendexing:
```bash
"indexer": {
"status": "reindexing",
"last_round": 3951368,
"reindex_status": {
"batch_size": 1000,
"last_height": 18764680,
"start_height": 18705681,
"end_height": 25804727,
"eta": "2025-03-28T19:30:00+01:00"
}
},
```
Indexing"
``` bash
"indexer": {
"status": "indexing",
"last_round": xxxxxxx,
},
```

go/control: Show runtime block history indexer status

---

go/oasis-test-runner/scenario/e2e/runtime/history_reindex.go

History reindex e2e test is flaky: https://buildkite.com/oasisprotocol/oasis-core-ci/builds/15043#0195ef94-e784-49d4-aebc-187f01a818c1.
Even though compute node is producing blocks, its indexer may still be behind the client...

Fix flaky history reindex test

---

go/storage/mkvs/node/key.go
go/storage/mkvs/node/key_test.go

`SetBit` method was clearing all remaining bits instead of zeroing the chosen one. We could also remove since currently not used.

go/storage/mkvs/node: Fix SetBit method of the Key

---

go/consensus/api/api.go
go/consensus/cometbft/abci/state/state.go
go/consensus/cometbft/api/api.go
go/consensus/cometbft/api/state.go
go/consensus/cometbft/apps/beacon/query.go
go/consensus/cometbft/apps/beacon/state/state.go
go/consensus/cometbft/apps/beacon/state/state_vrf.go
go/consensus/cometbft/apps/governance/query.go
go/consensus/cometbft/apps/governance/state/state.go
go/consensus/cometbft/apps/keymanager/churp/state/state.go
go/consensus/cometbft/apps/keymanager/query.go
go/consensus/cometbft/apps/keymanager/secrets/state/state.go
go/consensus/cometbft/apps/registry/query.go
go/consensus/cometbft/apps/registry/state/state.go
go/consensus/cometbft/apps/roothash/query.go
go/consensus/cometbft/apps/roothash/state/state.go
go/consensus/cometbft/apps/scheduler/query.go
go/consensus/cometbft/apps/scheduler/state/state.go
go/consensus/cometbft/apps/staking/auth.go
go/consensus/cometbft/apps/staking/query.go
go/consensus/cometbft/apps/staking/state/state.go
go/consensus/cometbft/apps/vault/query.go
go/consensus/cometbft/apps/vault/state/state.go
go/consensus/cometbft/full/common.go
go/consensus/cometbft/governance/governance.go
go/consensus/cometbft/registry/registry.go
go/consensus/cometbft/roothash/roothash.go
go/consensus/cometbft/staking/staking.go
go/consensus/cometbft/vault/vault.go
go/oasis-node/cmd/debug/dumpdb/dumpdb.go

These changes unify constructors for immutable and mutable state and allow us to query the state by using a remote tree.

go/consensus/cometbft/api/state: Organize immutable state

---

go/consensus/cometbft/api/api.go
go/consensus/cometbft/api/api_test.go
go/consensus/cometbft/beacon/beacon.go
go/consensus/cometbft/full/archive.go
go/consensus/cometbft/full/full.go
go/consensus/cometbft/full/services.go
go/consensus/cometbft/roothash/roothash.go

This will remove `DeliverCommand` from consensus `ServiceClient`, making the API more clean and limited only to two methods `DeliverBlock` and `DeliverEvents`. As a result, anyone with access to blocks and events can now run the client.

go/consensus/cometbft/api: Simplify consensus service client

---

go/consensus/cometbft/abci/messages.go
go/consensus/cometbft/abci/messages_test.go
go/consensus/cometbft/abci/mux.go
go/consensus/cometbft/api/api.go
go/consensus/cometbft/api/app.go
go/consensus/cometbft/apps/beacon/beacon.go
go/consensus/cometbft/apps/beacon/query.go
go/consensus/cometbft/apps/governance/governance.go
go/consensus/cometbft/apps/governance/query.go
go/consensus/cometbft/apps/keymanager/churp/ext.go
go/consensus/cometbft/apps/keymanager/keymanager.go
go/consensus/cometbft/apps/keymanager/query.go
go/consensus/cometbft/apps/keymanager/secrets/ext.go
go/consensus/cometbft/apps/registry/query.go
go/consensus/cometbft/apps/registry/registry.go
go/consensus/cometbft/apps/roothash/query.go
go/consensus/cometbft/apps/roothash/roothash.go
go/consensus/cometbft/apps/scheduler/query.go
go/consensus/cometbft/apps/scheduler/scheduler.go
go/consensus/cometbft/apps/staking/query.go
go/consensus/cometbft/apps/staking/staking.go
go/consensus/cometbft/apps/supplementarysanity/supplementarysanity.go
go/consensus/cometbft/apps/vault/query.go
go/consensus/cometbft/apps/vault/vault.go
go/consensus/cometbft/full/common.go
go/consensus/cometbft/registry/registry.go
go/consensus/cometbft/roothash/roothash.go

These changes reduce the CometBFT consensus backend interface to a minimal set of methods, all of which can be implemented by a light client backend.

go/consensus/cometbft/api: Simplify consensus backend

---

go/beacon/api/api.go
go/beacon/tests/tester.go
go/consensus/cometbft/apps/beacon/api.go
go/consensus/cometbft/apps/beacon/backend_insecure.go
go/consensus/cometbft/apps/beacon/backend_vrf.go
go/consensus/cometbft/apps/beacon/beacon.go
go/consensus/cometbft/beacon/beacon.go
go/control/api/api.go
go/governance/tests/tester.go
go/oasis-node/cmd/node/node_debug.go
go/oasis-node/node_test.go
go/oasis-test-runner/scenario/e2e/min_transact_balance.go
go/registry/tests/tester.go
go/roothash/tests/tester.go
go/scheduler/tests/tester.go
go/staking/tests/tester.go
go/worker/compute/executor/tests/tester.go

Removing `SetableBackend` interface, as transaction submission does not belong in the beacon backend implementation. This change also removes the dependency between the beacon backend and the consensus backend/transaction submission manager.

go/beacon/api: Remove SetableBackend interface

---

go/common/grpc/testing/ping.go
go/common/pubsub/pubsub.go
go/common/pubsub/pubsub_test.go
go/consensus/cometbft/apps/roothash/genesis.go
go/consensus/cometbft/apps/roothash/state/state.go
go/consensus/cometbft/apps/supplementarysanity/checks.go
go/consensus/cometbft/beacon/beacon.go
go/consensus/cometbft/full/common.go
go/consensus/cometbft/full/full.go
go/consensus/cometbft/governance/governance.go
go/consensus/cometbft/keymanager/churp/client.go
go/consensus/cometbft/keymanager/keymanager.go
go/consensus/cometbft/keymanager/secrets/client.go
go/consensus/cometbft/registry/registry.go
go/consensus/cometbft/roothash/roothash.go
go/consensus/cometbft/scheduler/scheduler.go
go/consensus/cometbft/staking/staking.go
go/consensus/cometbft/vault/vault.go
go/p2p/rpc/peermgmt.go
go/runtime/history/history.go
go/runtime/host/mock/host.go
go/runtime/host/multi/multi.go
go/runtime/host/sandbox/host.go
go/storage/mkvs/checkpoint/checkpointer.go

These changes achieve two things:
- Remove `ctx` from the constructors.
- Use the correct `ctx` when calling on subscribe hooks.

go/consensus/cometbft: Remove context from backend constructors

---

go/common/crypto/drbg/hmac_drbg.go

In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.

refactor: use the built-in max/min to simplify the code

---

go/consensus/api/api.go
go/consensus/cometbft/abci/mux.go
go/consensus/cometbft/api/api.go
go/consensus/cometbft/full/common.go
go/consensus/cometbft/full/full.go
go/oasis-node/cmd/node/node.go

Halt hooks are only used by full nodes and can be specific to the backend implementation. To simplify the service backend interface, halt hooks were moved to full node. They can be moved back later if needed.

go/consensus/api: Remove services backend

---

go/consensus/cometbft/abci/prune.go
go/consensus/cometbft/abci/prune_test.go

Tested on a client with an empty data dir. 
Before (prune starts with 0):
```json
{"caller":"prune.go:174","latest_version":26455298,"level":"debug","log_event":"cometbft/abci/prune","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":0,"ts":"2025-05-06T10:38:45.508387156Z"}
```
After (prune starts with 26456114) :
```json
{"caller":"prune.go:170","latest_version":26456114,"level":"debug","log_event":"cometbft/abci/prune","module":"abci-mux/pruner","msg":"Prune: Delete","pruned_version":26451681,"ts":"2025-05-06T10:34:34.592106051Z"}
```

go/consensus/cometbft/abci/prune: Lazy read earliest version

---

.changelog/6180.feature.md
go/consensus/api/api.go
go/consensus/api/grpc.go
go/consensus/cometbft/api/api.go
go/consensus/cometbft/beacon/beacon.go
go/consensus/cometbft/full/archive.go
go/consensus/cometbft/full/common.go
go/consensus/cometbft/full/full.go
go/consensus/cometbft/full/services.go
go/consensus/cometbft/governance/events.go
go/consensus/cometbft/governance/governance.go
go/consensus/cometbft/registry/events.go
go/consensus/cometbft/registry/registry.go
go/consensus/cometbft/roothash/events.go
go/consensus/cometbft/roothash/roothash.go
go/consensus/cometbft/scheduler/scheduler.go
go/consensus/cometbft/staking/events.go
go/consensus/cometbft/staking/staking.go
go/consensus/cometbft/vault/events.go
go/consensus/cometbft/vault/vault.go
go/consensus/tests/tester.go
go/governance/api/api.go
go/oasis-node/cmd/debug/txsource/workload/queries.go
go/registry/api/api.go
go/roothash/api/api.go
go/scheduler/api/api.go
go/staking/api/api.go
go/vault/api/api.go

Method `GetBlockResults` is needed by the light client node to serve events.
If performance degrades due to unmarshalling block results metadata in every `GetEvents` call, we can retain the backend interface and use `GetCometBFTBlockResults` if implemented, falling back to `GetBlockResults` otherwise.

go/consensus/api: Add method GetBlockResults

---

.github/workflows/ci-reproducibility.yml

```
*** Creating release for version 25.3...
• building binaries
• building                                       binary=dist/oasis-remote-signer_linux_amd64_v1/oasis-remote-signer
• building                                       binary=dist/oasis-node_linux_amd64_v1/oasis-node
• building                                       binary=dist/oasis-net-runner_linux_amd64_v1/oasis-net-runner
```

ci: Fix goreleaser path

---

go/consensus/cometbft/api/api.go
go/consensus/cometbft/api/api_test.go
go/consensus/cometbft/beacon/beacon.go
go/consensus/cometbft/governance/governance.go
go/consensus/cometbft/keymanager/keymanager.go
go/consensus/cometbft/registry/registry.go
go/consensus/cometbft/roothash/roothash.go
go/consensus/cometbft/scheduler/scheduler.go
go/consensus/cometbft/staking/staking.go
go/consensus/cometbft/vault/vault.go

Makes sure that service descriptor is created only once and that queries are pushed to the channel immediately.

go/consensus/cometbft: Refactor service descriptor

---

go/consensus/cometbft/full/statesync.go
go/consensus/cometbft/light/client.go

CometBFT's light client is not safe for concurrent use by multiple goroutines, so we need to verify only one header/block at a time.

go/consensus/cometbft/light/client: Refactor light client

---

.changelog/6231.bugfix.md
go/runtime/localstorage/localstorage.go

go/runtime/localstorage: Fix nil dereference after close

---

.changelog/6239.bugfix.md
go/storage/mkvs/db/api/api.go
go/storage/mkvs/db/pathbadger/metadata.go
go/worker/storage/committee/node.go

go/worker/storage/committee: Fix Stuck Storage Finalization

---

go/storage/mkvs/iterator.go

Whilst working on #6165 (still WIP) I found iterator code quite hard to follow/debug. I tried to simplify it a bit but am still not 100% convinced by the changes ([see comment](https://github.com/oasisprotocol/oasis-core/pull/6176#discussion_r2072365166)).

go/storagek/mkvs: Simplify Iterator's doNext function

---

.changelog/6244.internal.md
keymanager/src/crypto/kdf.rs
keymanager/src/crypto/types.rs

I don't think this checksum is ever used, or is it? If not, it might be best to remove it, since it's unrelated to the keys derived from ephemeral secrets.

keymanager/src/crypto: Deprecate checksum in key pair

---

.buildkite/code.pipeline.yml

SGX full tests are failing due to timeout. See:
- https://buildkite.com/oasisprotocol/oasis-core-ci/builds/15719
- https://buildkite.com/oasisprotocol/oasis-core-ci/builds/15720

buildkite: Increase parallelism for sgx full tests

---

go/storage/mkvs/checkpoint/chunk.go

fix inconsistent struct comment

chore: fix inconsistent struct comment

---

.changelog/5751.feature.md
go/oasis-node/cmd/debug/byzantine/node.go
go/p2p/rpc/client.go
go/worker/common/p2p/txsync/client.go
go/worker/common/p2p/txsync/protocol.go
go/worker/keymanager/p2p/client.go
go/worker/keymanager/p2p/protocol.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/checkpoint_sync_test.go
go/worker/storage/committee/node.go
go/worker/storage/p2p/checkpointsync/client.go
go/worker/storage/p2p/checkpointsync/protocol.go
go/worker/storage/p2p/checkpointsync/server.go
go/worker/storage/p2p/diffsync/client.go
go/worker/storage/p2p/diffsync/protocol.go
go/worker/storage/p2p/diffsync/server.go
go/worker/storage/p2p/pub/client.go
go/worker/storage/p2p/pub/protocol.go
go/worker/storage/p2p/synclegacy/client.go
go/worker/storage/p2p/synclegacy/protocol.go
go/worker/storage/p2p/synclegacy/server.go

As discussed in #6262 it might be simpler to manually handle fallback to the legacy protocol.
Closes #5751.
Regarding the style, I would prefer to keep it consistent with other p2p packages even if not optimal: https://github.com/oasisprotocol/oasis-core/pull/6262#discussion_r2220496029

Split storage sync P2P protocol (manual fallback)

---

go/consensus/cometbft/abci/state.go
go/oasis-node/cmd/node/node_control.go
go/oasis-test-runner/oasis/log.go
go/storage/mkvs/checkpoint/checkpointer.go
go/storage/mkvs/checkpoint/checkpointer_test.go
go/worker/storage/committee/checkpoint_sync.go
go/worker/storage/committee/metrics.go
go/worker/storage/committee/prune.go
go/worker/storage/committee/worker.go
go/worker/storage/service_internal.go
go/worker/storage/worker.go

**What was done:**
1. **Pass context explicitly.**
2. Fix:
* Panicking.
* Deadlocking on the clean-up.
* Triggering genesis checkpoint to early.
3. Minor refactors.
**Follow-up**:
I propose factoring out _checkpointer_ and _availability nudger_ (https://github.com/oasisprotocol/oasis-core/pull/6308) into separate workers. Could be one PR for each.
This will make _diff sync part_ easier to reason about and thus optimize.

go/worker/storage: Refactor state sync worker pt1

---

.changelog/6327.bugfix.md
runtime/src/protocol.rs

Fixes https://github.com/oasisprotocol/oasis-core/issues/6327
Example client side response with the update:
```go
addrss, err := rt.Accounts.Addresses(context.Background(), uint64(height), types.NativeDenomination)
if err != nil {
println("Failed to fetch addresses:", err.Error())
}
// prints: Failed to fetch addresses: Failed to write response: message too large
```
while before the query would just appear to be stuck on the client.

runtime/protocol: Propagate write failures

---

.buildkite/code.pipeline.yml
.buildkite/go/nancy_audit.sh

Implementing authentication for our Nancy audit Buildkite step, as Sonatype OSS Index now requires authentication.

buildkite: Require Sonatype OSS Index auth for nancy audit

---

.changelog/6339.feature.md
go/consensus/cometbft/abci/state.go
go/storage/mkvs/db/badger/helpers.go
go/storage/mkvs/db/pathbadger/config.go
go/worker/storage/config/config.go

As from the experiments, increasing block cache size significantly increases the pruning speed of the runtime state ([see](https://github.com/oasisprotocol/oasis-core/issues/6334#issuecomment-3347762369)).
Looking at the badgerDB [documentation](https://github.com/hypermodeinc/badger/blob/64b2f3736e24c16219b0e74f826d46c7187d6f46/options.go#L685), it is recommended to use cache if using compression. The current default value is `256 MB`, thus bumping to it from existing `64 MB`.
Finally, given that we are highly data intensive application we may set it to even more, e.g. `1 GB`.
Might be also a good idea to bump cometbft managed databases (i.e. blockstore, state, evidence) albeit feels wasteful for the evidence, and currently there is no granularity. Given we don't have performance …

go: Bump default block cache size of NodeDB badger instances to 256 MiB
